### ISSUE TITLE
Pixelated video in Frigate card but not in AlexxIT card

### ISSUE THREAD

**Issue by kyvaith** [dermotduffy/frigate-hass-card#1028]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v4.0.0
**Last working release (if known):**
n/a
**Browser and Operating System:**
Chrome 111 on Windows 11

**Description of problem:**
The video is pixelated in frigate card. In AlexxIT  is only pixelated  when scrolling - after stopping scrolling video get antialiased nicely.

I was trying to workaround this issue by adding display: contents; overflow: unset; to ha-card element and it helped for a moment the suddenly stopped.

I suspect it could be related somehow with the number of nestings of divs and shadow-roots where the actual video element is placed.

**Javascript errors shown in the web inspector (if applicable):**

_none_

![Zrzut ekranu 2023-03-27 231528](https://user-images.githubusercontent.com/107579/228208968-c93db7d6-9133-429d-815b-b0d19ca83895.png)

**Comment by dermotduffy** [comment]
Can you try setting:

```
live:
  show_image_during_load: false
```

My ~random guess is that this will result in no video being shown at all, which further suggests that the pixelated video is actually just the Home Assistant image snapshot of the camera that is shown during the load of the "real" video. If yes, this is caused by the most recent version of the AlexxIT card -- and this is already fixed in the (not yet released) `v4.1.0` branch of this card. If I'm right, and if you're feeling adventurous, you could either build your own or re-use build artifacts from a recent commit, e.g.: https://github.com/dermotduffy/frigate-hass-card/suites/11822125580/artifacts/617371415 and see if that performs any better.

PS: Another way to tell is by using the developer tools element selector on the card and selecting the 'video'. If it's actually an `img` tag, it's the above issue.

**Comment by kyvaith** [comment]
I've spend lot of time to properly configure RTSP stream so I'm sure this is not a JSMpeg element ;) And I saw the aforementioned issue before (have it too).  Also JSMpeg goes to oher direction - it's too blurry not pixelated ;-)

This is probably related to the Angle d3d11 implementation in Chrome on Windows. It works well on my Android phone in example.

**Comment by felipecrs** [comment]
But have you tried disabling `show_image_during_load` as @dermotduffy suggested?

**Comment by kyvaith** [comment]
But RTSP don't work with this setting on... I have it constantly disabled constantly. Enabling it shows JSMpeg.

**Comment by felipecrs** [comment]
Not true. Enabling it shows still images, not JSMPEG. :)

It means your stream isn't being loaded at all.

**Comment by kyvaith** [comment]
????? This is a 1920x1080x30fps stream... Should I take a fullscreen screenshot for you?

**Comment by felipecrs** [comment]
No, sorry. Maybe I'm misunderstanding. I'll let @dermotduffy continue here.

**Comment by NickM-27** [comment]
It's not clear which stream provider is being used here, that would make things more understood.

**Comment by kyvaith** [comment]
I's  not clear to me what you're asking for. I'm using WebRTC RTSP stream proxied through Frigate (using restream). As the client I'm using both Frigate Card and AlexxIT card configured identically. On the Frigate card the Angle d3d11 antialiasing (or any other mechanism used in chrome with GPU to nicely scale down 1920x1080 video stream to 300x200 DIV in lovelence) don't work at all. And on AlexxIT  card works pretty well. This is not a bug per se in Frigate Card, but probably number of resources used by card, the footprint in GPU memory or something else. Angle d3d11 simply skipping re-rendering video because of the lack of resources. I'm using last-year standard business Core i5 laptop. On my Xiaomi Mi11 problem don't occur at all.

**Comment by NickM-27** [comment]
I'm asking what your frigate card configuration is

**Comment by kyvaith** [comment]
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.front
    webrtc_card:
      url: rtsp://127.0.0.1:8554/front?video&audio
    title: Podwórko
    icon: mdi:home
    live_provider: auto
live:
  preload: true
  draggable: false
  lazy_load: false
  show_image_during_load: false
  auto_play: all
  webrtc_card:
    style: >-
      .mode, .fullscreen {display: none;} ha-card {display: contents; overflow:
      unset;} .player {background-color: unset; height: unset;} video
      {border-radius: 10px;}
    muted: true
    mode: mse
    ui: true
  lazy_unload: never
  auto_pause: never
  layout: {}
view:
  default: live
  camera_select: live
  update_force: false
  scan:
    show_trigger_status: false
    untrigger_reset: false
menu:
  position: top
  alignment: right
media_viewer:
  auto_play: all
  auto_pause: never
  controls:
    title: {}
dimensions:
  aspect_ratio: '16:9'
  aspect_ratio_mode: static
event_gallery:
  controls:
    thumbnails:
      size: 75
      show_details: false
      show_favorite_control: false
      show_timeline_control: false
```

**Comment by NickM-27** [comment]
I'd suggest setting live_provider to webRTC card and see if it behaves differently

**Comment by kyvaith** [comment]
After setting provider to WebRTC I see shuttering and lags, but the pixelated video behavior don't change.

**Comment by dermotduffy** [comment]
@kyvaith When you use the `webrtc_card` provider it is _literally_ embedding the very same element as when you just manually make a WebRTC card. It must be something really special if you are seeing visual differences between the two, unless it is some browser rendering artifact ...

Suggestions:

* Try a different browser, does it still happen?
* As recommended earlier, try using [the latest build artifact](https://github.com/dermotduffy/frigate-hass-card/suites/11931576698/artifacts/625119625) in case there is some other incompatibility between the 'older' card you are using, and the newer WebRTC.
* Try the smallest possible configuration, and see if you still experience this. Add back bits of config until you can narrow it down. I think the config I'd start with is:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.front
    live_provider: 'webrtc_card'
    webrtc_card:
      url: rtsp://127.0.0.1:8554/front?video&audio
live:
  show_image_during_load: false
```

**Comment by kyvaith** [comment]
![image](https://user-images.githubusercontent.com/107579/230122689-c719b476-e86f-49cc-a5aa-28269c465adf.png)

![image](https://user-images.githubusercontent.com/107579/230122871-c21f224c-2ab9-4576-81e2-7bb2229608b9.png)

On Edge, Opera, Vivaldi, Brave same behavior. On Firefox no anti-aliasing at all even in AlexxIT card.

I've updated js's form your link. Same behaviour.

**Comment by dermotduffy** [comment]
I continue to not be able to reproduce this on any of Chrome, Firefox or Safari on either Linux or iOS. I can certainly see some aliasing, but it's always identical between the Frigate card and the native WebRTC card.

The configs I'm using for the Frigate card:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room
    live_provider: webrtc-card
```

And the WebRTC card:

```yaml
type: custom:webrtc-camera
entity: camera.living_room
```

As of right now, this issue is not actionable / I'm not sure what to do next. I'm hoping someone else can chime in with a matching experience with some new clue...
