### ISSUE TITLE
Fullscreen mode tap +/- popup

### ISSUE THREAD

**Issue by kyuzumaki** [dermotduffy/frigate-hass-card#1030]
Firstly thankyou for your work on this the integration works great already. Hopefully you will consider this suggestion.

**Describe the solution you'd like**
I would like an option to just tap or double tap the middle of the camera view to make it go fullscreen and the same to shrink it. Essentially a big invisible fullscreen button in the centre of the video feed.

**Describe alternatives you've considered**
I've set the menu to a persistent overlay so it stays in the corner and is easier to get to.

**Comment by dermotduffy** [comment]
Try this:

```yaml
live:
  actions:
    double_tap_action:
      action: custom:frigate-card-action
      frigate_card_action: fullscreen
```
