### ISSUE TITLE
Lovelace card not showing full camera in latest release

### ISSUE THREAD

**Issue by peetipablo** [dermotduffy/frigate-hass-card#104]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
1.0.1

**Last working release (if known):**
N/A

**Browser and Operating System:**
Manjaro - Firefox 93.0 (also HomeAssistant IOS app)

**Description of problem:**
The card is not showing the entire camera with default dimension settings, and manual dimension settings are not honored.  Full screen appears normal.

file:///home/peetipablo/Downloads/lovelace_screenshot.jpg

file:///home/peetipablo/Downloads/fullscreen_screenshot.jpg

```
type: custom:frigate-card
camera_entity: camera.doorbell
controls:
  nextprev: chevrons
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '9:16'
webrtc: {}
menu_mode: below
```

**Additional information:**
