### ISSUE TITLE
Suggested UX improvements for mini-timeline in `live` view

### ISSUE THREAD

**Issue by bagobones** [dermotduffy/frigate-hass-card#1055]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
5 beta 1
**Last working release (if known):**
N/A
**Browser and Operating System:**
windows/chrome, iOS/Safari

**Description of problem:**
In the release notes mini timeline is shown with a vertical line showing current time and scrolling updating playback. I am not seeing this happen under live view. Also taping on events highlights them but it does not start playing them.

If I tap on the text for the HOUR it appears it is trying to load but the mini timeline disappears and the video window just goes blank.

My general expectation would be:
- dragging backward would skip to clip
- tapping on a event box would play the clip
- tapping on an hour or blank space would play recordings 

**Additional information:**
YAML config, using go2rtc as the live provider, however I did try removing that at setting it to a HA camera entities and didn't see any change.
```
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: birdseye
  - frigate:
      camera_name: doorbell
    live_provider: go2rtc
  - frigate:
      camera_name: main_hall
    live_provider: go2rtc
  - frigate:
      camera_name: garage_front
    live_provider: go2rtc
  - frigate:
      camera_name: backyard
    live_provider: go2rtc
  - frigate:
      camera_name: living_room
    live_provider: go2rtc
  - frigate:
      camera_name: kitchen
    live_provider: go2rtc
  - frigate:
      camera_name: basement
    live_provider: go2rtc
  - frigate:
      camera_name: basement_hall
    live_provider: go2rtc
timeline:
  media: clips
media_gallery:
  controls:
    thumbnails:
      show_details: true
dimensions:
  aspect_ratio_mode: unconstrained
live:
  draggable: false
  controls:
    next_previous:
      style: none
    title:
      mode: popup-top-left
    timeline:
      mode: below
      media: clips
  transition_effect: none
  show_image_during_load: false
  preload: false
  control s:
    timeline:
      clustering_threshold: 2
menu: {}
```
