### ISSUE TITLE
Overlay popups when switching cameras.

### ISSUE THREAD

**Issue by bagobones** [dermotduffy/frigate-hass-card#1069]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
v5 beta 1
**Last working release (if known):**
v4 ?
**Browser and Operating System:**
ios/safari, chome/

**Description of problem:**

I am using the native go2rtc provider and I have noticed that the loading / switching is a little slow clunky vs v4 with the webrtc config.

With I switch cameras 3 things seem to happen every time.
- The video player displays with a loading spinner
- The camera name popup fires
- THEN for some reason the play back bar and overlays (desktop) or the paush icon overlay (iOS) appears THEN I can finally see the camera.

This seems to settle down a bit after the first one or two cameras have loaded then the pausing / seems to no longer happen?

in v4 webrtc config I would see a little loading text in the top right then it would start playing

Td;Dr when jumping to the card the first time there are too many over lays / popups delaying how fast you can see the video.

I might also add that I LIKE knowing which camera I am viewing but the "Popup" appear to be the only option, would be nice to have a static option, maybe include the camera name in the button / navbar as an option?

**Additional information:**

Full card config

```
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: birdseye
      labels:
        - Person
  - frigate:
      camera_name: doorbell
      labels:
        - person
    live_provider: go2rtc
  - frigate:
      camera_name: main_hall
    live_provider: go2rtc
  - frigate:
      camera_name: garage_front
    live_provider: go2rtc
  - frigate:
      camera_name: backyard
    live_provider: go2rtc
  - frigate:
      camera_name: living_room
    live_provider: go2rtc
  - frigate:
      camera_name: kitchen
    live_provider: go2rtc
  - frigate:
      camera_name: basement
    live_provider: go2rtc
  - frigate:
      camera_name: basement_hall
    live_provider: go2rtc
timeline:
  media: clips
media_gallery:
  controls:
    thumbnails:
      show_details: true
dimensions: {}
live:
  draggable: false
  controls:
    next_previous:
      style: none
    title:
      mode: popup-top-right
    timeline:
      media: clips
      mode: below
      show_recordings: false
    thumbnails:
      mode: below
      media: clips
  transition_effect: none
  show_image_during_load: false
  preload: false
  control s:
    timeline:
      clustering_threshold: 2
  lazy_load: true
menu:
  style: outside
  position: bottom
media_viewer:
  controls:
    thumbnails:
      mode: below
    next_previous:
      style: none
    timeline:
      mode: below

```
