### ISSUE TITLE
Displaying multiple cameras at once in a grid

### ISSUE THREAD

**Issue by jbms** [dermotduffy/frigate-hass-card#1075]
It would be great to be able to display multiple cameras at once, e.g. tiled in some automatic way, with a way to toggle between the tiled camera view and a single camera filling the entire card.

For the live view, this would perhaps not add much over just having separate frigate cards for each camera, but when viewing past recordings, this feature could allow displaying multiple cameras at once with the times synchronized.

**Comment by felipecrs** [comment]
> this feature could allow displaying multiple cameras at once with the times synchronized.

That's interesting!

**Comment by dermotduffy** [comment]
Thanks for the feature request. This is probably a non-trivial amount of work, so would love to see people indicate their support for it by adding to the "thumbs up" of the original poster, or chiming in with their usecases for it. Thanks for the idea @jbms !

**Comment by dermotduffy** [comment]
I'll give a small update here: Due to the amount of interest in this feature -- as seen by the votes on the top post -- I have started to experiment with this a little. There's a long way to go, but I have a proof of concept "multi-camera" viewer and the ability to change between single and grid mode. Rendering multiple video feeds at once is fairly processor intensive, so I doubt this will be usable on something like a raspberry pi -- but perhaps with the `image` live provider. I definitely need to do further experimentation to decide whether to scrap or keep the proof of concept -- stay tuned.

PS: @operator207 I am assuming you already know about the [Frigate birdseye view](https://docs.frigate.video/configuration/birdseye/), which you can already load in the card, that will show you multiple live cameras rendered into a single video feed.

**Comment by operator207** [comment]
> PS: @operator207 I am assuming you already know about the [Frigate birdseye view](https://docs.frigate.video/configuration/birdseye/), which you can already load in the card, that will show you multiple live cameras rendered into a single video feed.

I do. Though it seems to only populate based on motion or detection. I'm more interested in a 'window' to look through and see live feeds I select as important.
Maybe my birdseye isn't configured correctly? I'll take a look at the documents link you provided. Thanks!

**Comment by dermotduffy** [comment]
> I do. Though it seems to only populate based on motion or detection. I'm more interested in a 'window' to look through and see live feeds I select as important.

Try the `continuous` birdseye mode. If you configured the card with the birdseye camera, and with each camera individually, maybe you can get a little close to what you want right now. Good luck!

**Comment by dermotduffy** [comment]
**Update on this**: Whilst I have very limited development time, I am making progress and this feature has my undivided attention within that time. I have extended the "grid" support to live view as well as media -- it really looks pretty cool and has given me a whole bunch of new ideas for further features, so I'm considering this experimentation phase complete and working on getting the experimental code into something that is complete enough and tested enough to be PR-ready. Stay tuned!

**Comment by dermotduffy** [comment]
OK -- this initial change is submitted. It's a monster change, so whilst I've squished all the bugs I could find -- I'm sure there are more that will emerge in testing. But this is "done enough" for me to close this issue, and we can deal with any latent bugs in separate issues as I / people find them.

This will be in the next release (v6).

**Comment by liorfranko** [comment]
Hi

Thank you, @dermotduffy, for working on it!
I'm testing the grid view from the dev branch, and it's working great so far.
I wanted to check if it's possible to make the idle camera work on 1 second refresh interval or something like low performance.

**Comment by JakeTheRabbit** [comment]
Testing the grid view as well. Took me a long time to get working didnt realise I needed to use the dev version as the [documentation](https://dermotduffy.github.io/frigate-hass-card/#/README?id=multi-camera-grid-configuration) has the grid view grid option but doesn't say use dev version. 
Once I installed the [dev version](https://github.com/dermotduffy/frigate-hass-card/actions/runs/8517597704) using this [brilliant tutorial](https://github.com/dermotduffy/frigate-hass-card/blob/main/README.md#advanced-users-installing-unreleased-ver) I couldn't get it to work until I cleared my browser cache then it worked! 6 hours later... 
Thanks for this feature it is reallllllly good this is a game changer for me. I learned a lot about the card and far out what a feature set. 
It doesn't seem to want to work with the Panel (1 Card) type view but worked with Masonry etc fine. 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/123831499/19353480-1229-4b65-b139-d37c3b267443)

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_door_2
  - camera_entity: camera.garage_side
  - camera_entity: camera.driveway
  - camera_entity: camera.back_nw_side
  - camera_entity: camera.back_yard_2
  - camera_entity: camera.kitchen_side_house
view:
  default: live
  camera_select: clips
  dark_mode: 'on'
  interaction_seconds: 30
live:
  display:
    mode: grid
  preload: false
  lazy_load: true
  draggable: true
  zoomable: true
  transition_effect: slide
  controls:
    builtin: true
    next_previous:
      style: chevrons
      size: 48
    thumbnails:
      media: clips
      size: 100
      show_details: false
      show_download_control: true
      show_favorite_control: true
      show_timeline_control: true
      mode: none
    timeline:
      style: ribbon
      mode: none
      clustering_threshold: 3
      media: all
      show_recordings: true
      window_seconds: 3600
    title:
      mode: popup-bottom-right
      duration_seconds: 2
  layout:
    fit: contain
    position:
      x: 50
      'y': 50
dimensions:
  aspect_ratio_mode: dynamic
```
