### ISSUE TITLE
View clips/recordings in birdseye view?

### ISSUE THREAD

**Issue by kylepyke** [dermotduffy/frigate-hass-card#1080]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

I'd like a way to navigate to the clips view from a birdseye stream. Currently, selecting a `camera_entity` shows the clips button in the menu (if enabled) for that camera, but no such button is exists for birdseye. Ideally the clips button would still be there, but would filter recordings from the `dependencies` array, sorted by most recent. 

Similarly, it would be great to be able to navigate to the timeline view from birdseye.

**Describe alternatives you've considered**

Showing the clips button on a birdseye stream does not appear to be overridable.

**Additional context**

**Comment by dermotduffy** [comment]
Hmm. You appear to be asking for exactly how the card already behaves, unless I am missing something, e.g.:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.sitting_room
  - camera_entity: camera.front_door
  - camera_entity: camera.birdseye
    dependencies:
      all_cameras: true
  - camera_entity: camera.landing
```

This will show events from all other cameras when the birdseye camera is shown.

Am I missing something?

**Comment by kylepyke** [comment]
I'm not sure I understand. Your config snippet doesn't have a birdseye view as far as I can tell?

Here is the first part of my YAML code for the card:

```
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: birdseye
    id: Birdseye
    live_provider: jsmpeg
    dependedcies:
      cameras:
        all_cameras: true
  - camera_entity: camera.hearth_frgt
    live_provider: go2rtc
    id: Hearth
    go2rtc:
      modes:
        - webrtc
        - mse
        - mp4
      stream: hearth
  - camera_entity: camera.living_frgt
    live_provider: go2rtc
    id: Living Room
    go2rtc:
      modes:
        - webrtc
        - mse
        - mp4
      stream: living
  - camera_entity: camera.basement_frgt
    live_provider: go2rtc
    id: Basement
    go2rtc:
      modes:
        - webrtc
        - mse
        - mp4
      stream: basement
```

Which shows this:

<img width="517" alt="2" src="https://user-images.githubusercontent.com/107963487/231036905-8c81dc4b-8293-42a3-a03f-576694a6f9a6.png">

...but if I choose a camera, I see added menu buttons:

<img width="511" alt="3" src="https://user-images.githubusercontent.com/107963487/231036955-4c77c506-30f8-4b7a-9dc1-cef0db3e6f8d.png">

Shouldn't the `dependencies` bit group the cameras together for birdseye?

**Comment by dermotduffy** [comment]
```
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: birdseye
    id: Birdseye
    live_provider: jsmpeg
    dependedcies:  <--------- TYPO
```
