### ISSUE TITLE
Card does not respect frigate 0.12.0 live stream configuration (webrtc)

### ISSUE THREAD

**Issue by david-collett** [dermotduffy/frigate-hass-card#1083]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
4.0.0

**Last working release (if known):**

**Browser and Operating System:**

Firefox 111 on Ubuntu 22.10

**Description of problem:**

I have updated to Frigate 0.12.0 and configured my cameras to use the go2rtc restream mechanism which is working well.
However, when I set the default live view for my camera to a non-default stream (e.g. the lower-res detect stream) as instructed here https://docs.frigate.video/configuration/live#setting-stream-for-live-ui.

e.g.
```
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: front_sub
```

This changes the live view in frigates own UI, but is not reflected in the frigate hass card, which continues to re-stream the full res ('record' role) stream from frigate. Is this expected behavior? IIRC, the previous version correctly chose the now deprecated 'rtsp' role stream, if configured.

My frigate-card configuration is:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front
    live_provider: ha
dimensions:
  aspect_ratio_mode: dynamic
menu:
  style: outside
  position: top
view:
  default: clips
```

**Additional information:**

I have installed the hass RTSPtoWebRTC integration and pointed it to frigates go2rtc api port, and can confirm (using `about:webrtc` in firefox), that the frigate card is displaying a webrtc stream, just not the expected 'live' one.
