### ISSUE TITLE
How to setup go2rtc for my card?

### ISSUE THREAD

**Issue by clowncracker** [dermotduffy/frigate-hass-card#1085]
I've upgraded frigate to v12 and I am using the beta for the hass card, but I am unsure on how to set go2rtc for the camera feed.  If I select the camera entity that is setup to use go2rtc in frigate will it automatically use go2rtc for the feed?

**Comment by dermotduffy** [comment]
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.sitting_room
    live_provider: go2rtc
```
[Relevant docs](https://github.com/dermotduffy/frigate-hass-card/tree/release-5.0.0#live-provider-camera-go2rtc-configuration)
