### ISSUE TITLE
default live_provider for all cameras

### ISSUE THREAD

**Issue by si458** [dermotduffy/frigate-hass-card#1090]
**Is your feature request related to a problem? Please describe.**
i currently have to set every camera entity i add to a single card to `live_provider: go2rtc`

**Describe the solution you'd like**
to be able to set a default `live_provider` for a single card to apply to all cameras

**Describe alternatives you've considered**
entering `live_provider` to every camera manually

**Additional context**
my config below showing its madness, and im also using the latest beta version `v5.0.0-beta.1`
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.ai_cam1
    live_provider: go2rtc
  - camera_entity: camera.ai_cam2
    live_provider: go2rtc
  - camera_entity: camera.ai_cam3
    live_provider: go2rtc
  - camera_entity: camera.ai_cam4
    live_provider: go2rtc
  - camera_entity: camera.ai_cam5
    live_provider: go2rtc
  - camera_entity: camera.ai_cam6
    live_provider: go2rtc
  - camera_entity: camera.ai_cam7
    live_provider: go2rtc
  - camera_entity: camera.ai_cam8
    live_provider: go2rtc
  - camera_entity: camera.ai_cam9
    live_provider: go2rtc
  - camera_entity: camera.ai_cam10
    live_provider: go2rtc
  - camera_entity: camera.ai_cam11
    live_provider: go2rtc
  - camera_entity: camera.ai_cam12
    live_provider: go2rtc
  - camera_entity: camera.ai_cam13
    live_provider: go2rtc
  - camera_entity: camera.ai_cam14
    live_provider: go2rtc
  - camera_entity: camera.ai_cam15
    live_provider: go2rtc
  - camera_entity: camera.ai_cam16
    live_provider: go2rtc
  - camera_entity: camera.ai_cam17
    live_provider: go2rtc
  - camera_entity: camera.ai_cam18
    live_provider: go2rtc
menu:
  style: outside
live:
  controls:
    thumbnails:
      mode: none
```
