### ISSUE TITLE
Rename `service_data` to `data` in action calls to match HA change

### ISSUE THREAD

**Issue by miguelangel-nubla** [dermotduffy/frigate-hass-card#1103]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v5.0.0-beta.2

**Description of problem:**
I was following the documentation to set up a new menu item (custom:frigate-card-menu-icon) and the documentation makes reference to:
"[Home Assistant action configuration](https://www.home-assistant.io/lovelace/actions) including the extended functionality described under [actions](https://github.com/dermotduffy/frigate-hass-card#actions)."

But using the `data` variable as indicated in said documentation for `tap_action`, is not working.

```
  tap_action:
    action: call-service
    service: input_button.press
    data:
      entity_id: <entity.id>
```

Instead, using `service_data` works:
```
  tap_action:
    action: call-service
    service: input_button.press
    service_data:
      entity_id: <entity.id>
```

I don't know if this a bug or a documentation issue, in HA or the card.
