### ISSUE TITLE
Cannot get new V5 features available

### ISSUE THREAD

**Issue by Remko76** [dermotduffy/frigate-hass-card#1114]
I have Frigate running fine with multiple cameras, using go2rtc for restreaming with following config (example for one camera):

```
go2rtc:
  streams:
    werkstatt:
      - rtsp://USER:PASS@192.168.76.65:554/h264Preview_01_main
      - ffmpeg:werkstatt#audio=opus
    werkstatt_sub:
      - rtsp://USER:PASS@192.168.76.65:554/h264Preview_01_sub
      - ffmpeg:werkstatt_sub#audio=opus
  webrtc:
    candidates:
    - 192.168.76.6:8555
    - stun:8555



##########################################################
  werkstatt:
    ffmpeg:
      inputs:
        #High Res
        - path: rtsp://127.0.0.1:8554/werkstatt
          roles:
            - record
        #Low Res    
        - path: rtsp://127.0.0.1:8554/werkstatt_sub
          roles:
            - detect
#    live:
#      stream_name: werkstatt_sub
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 15
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 10    
    objects:
      track:
        - person
        - cat
        - car
        - mouse
        - motorcycle
```

All working fine with the official Frigate integration in Homeassistant. I have updated to the latest Frigate V5 Lovelace card, but doe not seem to have any of the nice new features which was listed. Things like:
- Substream selection
- The timeline browser with live view
- The filtering in the snapshot category.

This is the config from my card:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.werkstatt
performance:
  profile: high
live:
  preload: false
menu:
  style: outside
```

Is there anything I am missing here....? Any help is greatly appreciated.
