### ISSUE TITLE
Allow specifying specific substream for fullscreen view 

### ISSUE THREAD

**Issue by rbray89** [dermotduffy/frigate-hass-card#1120]
It would be nice to save on bandwidth to use camera substreams for the in-card live view, but swap to the full resolution camera once entered in to fullscreen mode.

I'm unaware of any way to accomplish this currently.

**Comment by dermotduffy** [comment]
You can (kind of) do something like that with configuration overrides, but it's a bit hacky. You'd just override the cameras configuration to reverse the order of the cameras, i.e. like this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    dependencies:
      cameras:
        - camera.office_hd
  - camera_entity: camera.office_hd
    hide: true
overrides:
  - conditions:
      fullscreen: true
    overrides:
      cameras:
        - camera_entity: camera.office_hd
          dependencies:
            cameras:
              - camera.office
        - camera_entity: camera.office
          hide: true
```

I think the real fix is some sort of new primative like `automations` can run commands when conditions change.
