### ISSUE TITLE
Birdseye not working anymore

### ISSUE THREAD

**Issue by netsoft-ruidias** [dermotduffy/frigate-hass-card#1121]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v5.0.0

**Last working release (if known):**
v4.x.x

**Browser and Operating System:**
Chrome and Companion App

**Description of problem:**
After updating to the new version 5 of the card, the Birdseye camera stopped working, now it only shows the spinning icon.

This is my setup for the Birdseye:

```yaml
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: birdseye
    live_provider: jsmpeg
(...)
```

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Additional information:**
