### ISSUE TITLE
substeam and update_cycle_camera not working 

### ISSUE THREAD

**Issue by jemershaw** [dermotduffy/frigate-hass-card#1122]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
N/A

**Browser and Operating System:**
Chrome + Linux

The problem is when you have multiple cameras with substream and you toggle both streams to the main(hd stream) then when it cycles through the cameras it will reset to the original stream and not the toggled(hd) version.

Here is an example of what the card looks like:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.camera1
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
        - webrtc
      stream: camera1.sub
    dependencies:
      cameras:
        - camera.camera1
    id: camera1.sub
    hide: false
  - webrtc_card: {}
    live_provider: go2rtc
    camera_entity: camera.camera1
    go2rtc:
      modes:
        - mse
        - webrtc
    hide: true
    title: Camera1 HD
  - camera_entity: camera.camera2
    live_provider: go2rtc
    webrtc_card: {}
    go2rtc:
      modes:
        - mse
        - webrtc
      stream: camera2.sub
    id: camera2.sub
    dependencies:
      cameras:
        - camera.camera2
  - camera_entity: camera.camera2
    live_provider: go2rtc
    title: Camera2 HD
    go2rtc:
      modes:
        - mse
        - webrtc
    dependencies:
      cameras: []
    hide: true
timeline:
  media: clips
  controls:
    thumbnails:
      mode: above
view:
  default: live
  update_cycle_camera: true
  update_seconds: 5
  timeout_seconds: 10
menu:
  buttons:
    live:
      enabled: true
    substreams:
      priority: 100
      alignment: opposing
      icon: mdi:high-definition
    media_player:
      priority: 50
      alignment: matching
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    timeline:
      enabled: false
  style: hidden
live:
  draggable: true
  controls:
    next_previous:
      style: none
    title:
      mode: none
    thumbnails:
      mode: none
  provider: webrtc
  show_image_during_load: true
cameras_global:
  webrtc_card:
    background: false
    mse: true
```

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
