### ISSUE TITLE
Recording did not stop after threshold for stationary object

### ISSUE THREAD

**Issue by oleks85** [dermotduffy/frigate-hass-card#1123]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
0.12.0-da3e197

**Last working release (if known):**

**Browser and Operating System:**
Safari. Frigate installed in docker container with preset-vaapi

**Description of problem:**

My camera is looking on back yard where I have my car parked. In configuration I have settings for stationary object like this:

```
stationary:
        interval: 0
        threshold: 50
```

My assumption was that as car is still frigate will stop recording if there is no motions around. But it showing "In progress" title on event infinitely. I waited more than hour then remove car from detector to stop consuming disc space.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
My config file:

```
mqtt:
  enabled: False

objects:
  track:
    - person
    - dog
    - cat

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  camera1: # <------ Name the camera
    ffmpeg:
      inputs:
 #       - path: rtsp://admin:20685Kononenk!@192.168.0.129:554/media/video2
 #         roles:
 #           - detect
        - path: rtsp://admin:20685Kononenk!@192.168.0.129:554/media/video1 # <----- >
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: True # <---- disable detection until you have a working camera >
#      width: 720 # <---- update for your camera's resolution
#      height: 576 # <---- update for your camera's resolution
      width: 2560
      height: 1440
      stationary:
        interval: 0
        threshold: 50

    record:
      enabled: True
    motion:
      mask:
#        - 85,93,205,0,0,0,0,430,0,576,142,576,108,333
#        - 720,129,720,0,340,0,285,67
        - 724,0,295,243,486,1440,0,1440,0,313,0,0
        - 2560,340,2560,0,1201,0,1028,168
```
