### ISSUE TITLE
`webrtc-card` provider incorrectly requires `cameraEntity` for engine detection

### ISSUE THREAD

**Issue by Bobbik1** [dermotduffy/frigate-hass-card#1124]
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
4.x

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```
Could not determine suitable engine for camera. Check troubleshooting.
{
  "hide": false,
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  },
  "engine": "auto",
  "frigate": {
    "client_id": "frigate"
  },
  "motioneye": {
    "images": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    },
    "movies": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    }
  },
  "live_provider": "webrtc-card",
  "image": {
    "refresh_seconds": 1
  },
  "icon": "mdi:balcony",
  "title": "Taras",
  "id": "1",
  "webrtc_card": {
    "entity": "camera.taras_hd"
  }
}

```

**Additional information:**

**Comment by Bobbik1** [comment]
```
type: custom:frigate-card
cameras:
  - webrtc_card:
      entity: camera.taras_hd
    title: Taras
    icon: mdi:balcony
    live_provider: webrtc-card
    id: '1'
  - webrtc_card:
      entity: camera.tapo_camera_8431_hd
    title: Wejście
    live_provider: webrtc-card
    id: '2'
  - webrtc_card:
      entity: camera.tapo_camera_d888_hd
    title: Trawnik
    id: '3'
menu:
  position: top
  alignment: right
  buttons:
    cameras:
      enabled: false
    snapshots:
      enabled: false
    live:
      enabled: false
    download:
      enabled: false
view:
  default: live
  dark_mode: 'off'
live:
  controls:
    next_previous:
      style: chevrons
      size: 20
    title:
      mode: popup-top-right
      duration_seconds: 2
elements:
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - '2'
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: automation.discord_snapshot
        icon: mdi:motion-sensor
        tap_action:
          action: toggle
      - type: custom:frigate-card-menu-icon
        icon: mdi:content-save
        tap_action:
          action: call-service
          service: script.delete_last_tapo1
      - type: custom:frigate-card-menu-icon
        icon: mdi:home-floor-1
        tap_action:
          action: call-service
          service: script.setcam_first
      - type: custom:frigate-card-menu-icon
        icon: mdi:home-floor-2
        tap_action:
          action: call-service
          service: script.setcam_last
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          transform: none
          left: 20px
          bottom: 20px
        service: button.press
        data_left:
          entity_id: button.tapo_camera_8431_move_left
        data_right:
          entity_id: button.tapo_camera_8431_move_right
        data_up:
          entity_id: button.tapo_camera_8431_move_up
        data_down:
          entity_id: button.tapo_camera_8431_move_down
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - '1'
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: automation.taras_discord_snapshot
        icon: mdi:motion-sensor
        tap_action:
          action: toggle
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - '3'
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: automation.discord_snapshot_trawnik
        icon: mdi:motion-sensor
        tap_action:
          action: toggle
dimensions:
  aspect_ratio_mode: unconstrained
media_viewer:
  layout:
    fit: fill
```

**Comment by dermotduffy** [comment]
I think this is a real bug. Does this work:

```yaml
cameras:
  - webrtc_card:
      entity: camera.taras_hd
    camera_entity: camera.taras_hd  // <--------------------- added
    title: Taras
    icon: mdi:balcony
    live_provider: webrtc-card
    id: '1'
  - webrtc_card:
      entity: camera.tapo_camera_8431_hd
    camera_entity: camera.tapo_camera_8431_hd  // <--------------------- added
    title: Wejście
    live_provider: webrtc-card
    id: '2'
  - webrtc_card:
      entity: camera.tapo_camera_d888_hd
    camera_entity: camera.tapo_camera_d888_hd  // <--------------------- added
    title: Trawnik
    id: '3'
```

This should not be necessary, but from reading the code may workaround your issue. 

If you confirm it helped, I'll do a proper fix.

**Comment by Bobbik1** [comment]
Kind of works now (cam no 2 doesn't - dunno why yet) Thanks for answer and whole excelent job !

**Comment by Bobbik1** [comment]
However it's little sketchy, sometimes it takes very long untill WebRTC view is loaded, (it is in "gullwing" mode until then ;) ) sometimes it doesn't load at all, (error screen) 
```
Camera unavailable
{
  "hide": false,
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  },
  "engine": "auto",
  "frigate": {
    "client_id": "frigate"
  },
  "motioneye": {
    "images": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    },
    "movies": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    }
  },
  "live_provider": "auto",
  "image": {
    "refresh_seconds": 1
  },
  "camera_entity": "camera.tapo_camera_8431_hd",
  "title": "Drzwi",
  "id": "2",
  "webrtc_card": {
    "entity": "camera.tapo_camera_8431_hd"
  }
}
```
Webrtc Card at the same time shows live view just fine.

**Comment by dermotduffy** [comment]
> edit: It looks like everything works just fine without live_provider: webrtc-card
> Webrtc Card at the same time shows live view just fine.

You may have multiple problems mixed together. If your goal is to use the `webrtc-card` provider, I would recommend explicitly adding that (rather than removing it as you suggest). Once you do that, I would expect the loading times for the Frigate card and the webrtc-card to be near to identical.

**Comment by Bobbik1** [comment]
Added the ```live_provider: webrtc-card``` , I'm not sure if loading time is better or not, but one of my cameras randomly doesn't load at all (gullwing mode) . I have no idea why, since it has the same config as rest of mycameras: 
```
  - webrtc_card:
      entity: camera.tapo_camera_8431_hd
    camera_entity: camera.tapo_camera_8431_hd
    id: '2'
    title: Drzwi
    live_provider: webrtc-card
```
