### ISSUE TITLE
Allow the card to be configured to allow connecting the microphone on card load

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1128]
I'm playing with the new two-way audio support and it's quite nice. However, I feel it will be a little complicated for my parents to understand how it works:

1. Have to hold the mic button to connect once
2. Have to hold the mic button while talking after it connects

I have an automation that automatically loads the Frigate card in expand mode when someone rings the doorbell. It would be nice if I could also pass some kind of `frigate-card-action:connect_microphone` in the URL as well, so that when it loads, it's already ready to talk.

**Comment by felipecrs** [comment]
Or, an alternative would be to have an option like:

_Always start stream with microphone connected_

So that I could enable this option and this extra query parameter would not be required.

**Comment by dermotduffy** [comment]
I had 2 feature ideas I considered implementing but figured I'd wait until someone asked for them -- you asked for them both in <24 hours ;-)

Since the microphone stream is "universal" and not tied to any one video feed, I think the choice is effectively:

 * Create the microphone stream the instant the card is loaded.
 * Create the microphone stream the first time the user attempts to unmute [default].

**Comment by felipecrs** [comment]
There is just one catch... if you implement like this, and I switch to this mode (_have the microphone connected the instant the card is loaded_), then I think the `microphone_connected` condition (#1130) would not be as helpful.

How about the URL query option?

**Comment by dermotduffy** [comment]
> There is just one catch... if you implement like this, and I switch to this mode (have the microphone connected the instant the card is loaded), then I think the microphone_connected condition (https://github.com/dermotduffy/frigate-hass-card/issues/1130) would not be as helpful.

I think that's correct, but isn't that kind of what you want? i.e. if you want the microphone permanently connected, then you can just configure the card how you want without the condition being necessary (i.e. set the icon to the icon you want).

Am I missing something?

**Comment by felipecrs** [comment]
Yes, but I don't want the audio to be permanently unmuted either. If I set the audio to be unmuted on microphone_connected, and microphone is always connected, then audio will be always playing as well.

In fact, I only want the microphone to be connected when someone rings my doorbell, and in that case, I also want the audio to be unmuted. This I can trigger through a Fully Kiosk load URL action with the proper parameters, like to expand the card.

When viewing the dashboard regularly, I don't want audio to be unmuted just because microphone would be always connected either.

Anyway... maybe I can still set some overrides for only when `expand: true`. Like have the microphone connect automatically only if `expand: true`.

**Comment by dermotduffy** [comment]
Ah, ok. This is getting into the territory where the out of box answer probably won't do what you want, since it's more complex. I think something like this would do it since you could trigger it directly off the doorbell (only would work if your doorbell was an entity).

```yaml
automations:
  condition:
    - state:
      - entity: binary_sensor.doorbell
        state: 'on'
  actions:
      - action: custom:frigate-card-action
        frigate_card_action: expand
      - action: custom:frigate-card-action
        frigate_card_action: unmute
```

Or even something like this if we made connecting the microphone a command:

```yaml
automations:
  condition:
    - expand: true
  actions:
      - action: custom:frigate-card-action
        frigate_card_action: microphone_connect
      - action: custom:frigate-card-action
        frigate_card_action: unmute
```
