### ISSUE TITLE
Add some mechanism to automatically unmute inbound audio when using the microphone

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1130]
I keep the audio of my cameras muted by default in the card. However, it would be nice to have an option like:

_Automatically unmute when microphone connects_

So that I don't need to press 2 buttons in order to have a proper conversation.

**Comment by felipecrs** [comment]
Maybe a new `microphone_connected` card condition?

**Comment by felipecrs** [comment]
I have even another use case for such a condition:

- When `microphone_connected` is off, I'd like to set the microphone icon to something else like:

![image](https://user-images.githubusercontent.com/29582865/235369130-40536d34-31cb-48e9-8220-669f597ed78f.png)

**Comment by dermotduffy** [comment]
> Automatically unmute when microphone connects

I think you mean unmute the inbound audio, not unmute the microphone? 

> Maybe a new microphone_connected card condition?

Does "connected" here mean the microphone is attached the stream (regardless of whether the microphone is muted/unmuted) or does it mean when the microphone is unmuted? I think the former...

**Comment by dermotduffy** [comment]
I've been thinking about adding a new `automations` section that would run card comments when card conditions are met. If we added a new `microphone_connected` condition, and we had this, you could:

 - Use `overrides` to change the menu icon.
 - User `automations` to automatically send an unmute command to the feed.

Something like this:

```
overrides:
  condition:
    microphone_connected: true // <----------- Does not exist
  menu:
    buttons:
      microphone:
        icon: mdi:phone-in-talk-outline
automations: // <------------ Does not exist
  condition:
    microphone_connected: true // <----------- Does not exist
  actions:
      - action: custom:frigate-card-action
        frigate_card_action: unmute // <------------ Does not exist
  condition:
    microphone_connected: false // <----------- Does not exist
  actions:
      - action: custom:frigate-card-action
        frigate_card_action: mute // <------------ Does not exist
```

Is this the kind of thing you mean? The other approach would be to add a new value for `live.auto_unmute` which is `microphone` and perhaps something similar for `live.auto_mute` to do the opposite.

**Comment by dermotduffy** [comment]
> Is this the kind of thing you mean? The other approach would be to add a new value for live.auto_unmute which is microphone and perhaps something similar for live.auto_mute to do the opposite.

Maybe something like this is more sensible in this case, unmuting your inbound audio stream when you use a microphone seems obvious, and it'd be weird to have to add 11 lines of config (as extensible as it is) just to get that to happen.

**Comment by felipecrs** [comment]
> > Automatically unmute when microphone connects
> 
> I think you mean unmute the inbound audio, not unmute the microphone? 
> 
> > Maybe a new microphone_connected card condition?
> 
> Does "connected" here mean the microphone is attached the stream (regardless of whether the microphone is muted/unmuted) or does it mean when the microphone is unmuted? I think the former...


Correct for your two assumptions

**Comment by felipecrs** [comment]
> Use overrides to change the menu icon.

But I thought I could also use overrides to change the unmute:

```yaml
overrides:
  condition:
    microphone_connected: true // <----------- Does not exist
  menu:
    buttons:
      microphone:
        icon: mdi:phone-in-talk-outline
  live:                     // <- unmute incoming audio
    auto_unmute: all        // <- unmute incoming audio 
```

No?
