### ISSUE TITLE
Add option to disable zoom in `live`, `media_viewer` and `image`

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#1140]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to disable the zoom option. 

**Describe the solution you'd like**
A simple option in the config menu to disable zoom

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dermotduffy** [comment]
> It would be nice to be able to disable the zoom option.

May I ask why -- does it get in the way, or no use?

I think you mean something like this in the config:

```yaml
live:
  draggable: false    // <- Already exists
  zoomable: false     // <- You're asking for something like this?
```
