### ISSUE TITLE
Aspect ratio setting not working as expected

### ISSUE THREAD

**Issue by pravardhanreddy** [dermotduffy/frigate-hass-card#1160]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v5.0.0

**Last working release (if known):**
None

**Browser and Operating System:**
Chrome, Ubuntu 22.04

**Description of problem:**
The card provides option for setting the aspect ratio of the card. However, when set to static aspect ratio, the card just created white space around the video instead of fitting the video to the provided aspect ratio.
![image](https://github.com/dermotduffy/frigate-hass-card/assets/30177846/5a06f9f3-200e-4890-93cf-d026a9f90eb2)

The stream is from a CP Plus security camera. FFmpeg says the stream is 960x1080. The config for go2rtc and frigate is as follows:
```yaml
go2rtc:
  streams:
    first_floor: rtsp://192.168.29.129/cam/realmonitor?channel=3\&subtype=0

cameras:
first_floor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/first_floor
          input_args: preset-rtsp-restream
          roles:
            - record
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Can you include the card config you're using?

If the goal is just to have the card exactly match the video with no white space around it, you should not need any additional aspect ratio parameters.

**Comment by pravardhanreddy** [comment]
My card config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.first_floor
```
This gives me 
![image](https://github.com/dermotduffy/frigate-hass-card/assets/30177846/76e8d036-f2a0-4015-9059-693140735409)

As you can see, the image is stretched out. I don't think the problem is with the card matching the aspect ratio. I just wanted to display it at 16:9 so that the image looks normal. I thought that's what the static aspect ratio option did. Using that option gives me
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.first_floor
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```
![image](https://github.com/dermotduffy/frigate-hass-card/assets/30177846/935bbf41-c401-41ee-a6e3-dbf5708aa45d)

If that's not the behavior maybe there should be an option to choose to fill the card?

**Comment by dermotduffy** [comment]
> As you can see, the image is stretched out. 

I don't see that ;-) I took your screenshot, measured the width/height of the video frame and divide one by the other I get `0.888...`. If I divide `960 / 1080` (the values returned by ffmpeg) I get `0.888`, i.e. the card is (as per these screenshots) already showing you the aspect ratio that matches what ffmpeg itself detects.

That is *definitely* not a `16:9` video feed, so setting the aspect ratio can only result in the white bars on the side.

Put another way, the aspect ratio you see in the default (in default configuration) should match the aspect ratio you see in the Frigate UI itself. If you're not happy with _that_ aspect ratio, you have an issue with your Frigate config, not your card config.

> If that's not the behavior maybe there should be an option to choose to fill the card?

Your first screenshot shows the video filling the card already, so perhaps I still don't understand what behavior you want.

**Comment by dermotduffy** [comment]
@pravardhanreddy OK, I think I get it now, you want to ignore the actual aspect ratio of the video and have the card show an effective different aspect ratio.

Suggest experimenting with a combination of a static aspect ratio (this is the dimensions of the _card_ not the video) and the `layout` options. Example: I have 1 camera with a vertical portrait video feed (9:16), and I can use the following to have the card only show a landscape "slice" of that feed (in 16:9 -- reversed from 9:16). In the below example the y value (`34`) is the vertical position of that slice to show. This obviously results in a (significant) portion of the frame not being displayed in the card, but maybe is the kind of thing you're looking for. Note that in a "tall" video feed like yours (and my example), the `x` setting won't do anything since all of the width of the frame will be displayed. The `y` setting will select which "height slice" to show. 

Kind of hard to explain, but play around with the options and see if it does similar to what you want:

```
live:
  layout:
    fit: cover
    position:
      y: 34
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```

* [More examples](https://github.com/dermotduffy/frigate-hass-card#changing-the-media-layout)
* [Screenshot of what these parameters can do](https://github.com/dermotduffy/frigate-hass-card#media-layout-1), in this case it shows changing 16:9 to 9:16 -- you'd be doing similar to the reverse.

The visual editor might be useful to play around with these values:

![layout](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/073fe394-5133-4b14-8235-f6423dc98a19)

**Comment by pravardhanreddy** [comment]
Omg that did it
![image](https://github.com/dermotduffy/frigate-hass-card/assets/30177846/9fb3488d-dead-4372-a2bd-41036cbe757b)

Config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.first_floor
live:
  layout:
    fit: fill
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```
Thank you so much. It might be nice to combine the settings in the same place, as they both control how the card is displayed.
