### ISSUE TITLE
Transparently call Frigate PTZ via integration

### ISSUE THREAD

**Issue by kirsch33** [dermotduffy/frigate-hass-card#1163]
it appears from the latest dev builds that frigate 0.13 will support PTZ natively via ONVIF. it would be nice to be able to configure this only within Frigate itself and have this functionality inherited by the frigate-hass-card instead of needing to add webrtc card into the mix. 

it seems as though PTZ functionality has been available in frigate-hass-card since before the PR for ptz control in the frigate repo.

(please correct me if my understanding is incorrect)

**Comment by dermotduffy** [comment]
You are correct, the Frigate card already supports PTZ via Home Assistant service calls.

Myself and @NickM-27 discussed this briefly before, having had a similar idea. If the Frigate API exposed calls to move the camera around, we could proxy calls from the card through the integration to the backend, and the card could just support this out of the box for Frigate cameras...

**Comment by dermotduffy** [comment]
> we could proxy calls from the card 

Actually, I think a better idea is to implement service calls in HA that call the backend. This would mean that the standard HA "interface" (service-calls) would support Frigate PTZ, so other non-Frigate card uses could benefit. It would also mean very little would need to change on the card, beyond populating some defaults for Frigate cameras.

**Comment by dermotduffy** [comment]
Update: Nick is working on 2 in https://github.com/blakeblackshear/frigate-hass-integration/pull/510 .

**Comment by TimelessNL** [comment]
> You are correct, the Frigate card already supports PTZ via Home Assistant service calls.

I've tried to call the new Frigate service, but so far unsuccessful 😢 
Basically I copied the `tap_action` section from a working `entity-button` card
```
elements:
  - type: custom:frigate-card-ptz
    orientation: vertical
    style:
      transform: none
      right: 5%
      top: 50%
    actions_left:
      tap_action:
        action: call-service
        service: frigate.ptz
        target:
          entity_id: camera.backdoor
        data:
          action: move
          argument: left
```
Which results in the following error (_partly Dutch, but the exact error is in English_)
![afbeelding](https://github.com/dermotduffy/frigate-hass-card/assets/10838968/ccd9e930-2b65-4e7a-b954-8d88da39c1cf)

**Comment by dermotduffy** [comment]
I think this might be related to #1103 , which I plan to fix in the next major release as it's a breaking change. HA renamed the `data` parameter for service calls from `service_data` to `data`, but the original name is still used in this card. So try this:

```yaml
elements:
  - type: custom:frigate-card-ptz
    orientation: vertical
    style:
      transform: none
      right: 5%
      top: 50%
    actions_left:
      tap_action:
        action: call-service
        service: frigate.ptz
        target:
          entity_id: camera.backdoor
        service_data:    // <--------------- This is changed
          action: move
          argument: left
```

As I understand it with the new Frigate PTZ endpoint you need to both move **and** stop the camera, or it'll just keep going. You should be able to use the `start_tap_action` (instead of `tap_action`) for the `move` call, and a new `stop_tap_action` to also call stop when the tap is stopped. So it'll start to move when you press the button, and stop when you let it go.

Note that I have not tested calling the new Frigate PTZ endpoints as I'm describing, but it should work. I plan to make this work more "out of the box" for Frigate (without needing so much YAML) in future (that's what this issue is for) -- but hopefully you have enough clues to get this working with the above for now. Good luck.
