### ISSUE TITLE
Unable to use card , have error Failed to receive response from Home Assistant for request.

### ISSUE THREAD

**Issue by denveronly** [dermotduffy/frigate-hass-card#1187]
**Checklist:**

- [yes ] I updated to the latest version available
- [yes ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

Chrome and safari on osx

Trying to make a simple card

- type: custom:frigate-card
        cameras:
          - camera_entity: camera.garage

<img width="523" alt="Screenshot 2023-05-30 at 00 04 05" src="https://github.com/dermotduffy/frigate-hass-card/assets/66441516/45e55db0-4df5-4408-8723-b288d8393071">

and i get an error
Have HA OS on one PC, Frigate is running on Unraid. Connected to HA, have all cameras visible in integration
Integration version 4.0.0
HA - latest core

Frigate is working fine

Frigate info
```
{
  "ha_version": "2023.5.4",
  "card_version": "5.1.1",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15",
  "date": "2023-05-29T21:04:39.551Z",
  "frigate_version": {
    "04188c6992ea410a5f9d2724f5ee6f5e": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en",
  "timezone": "Europe/Kiev",
  "git": {
    "build_version": "5.1.1-HEAD+g2d977be",
    "build_date": "Sat, 20 May 2023 20:35:29 GMT",
    "commit_date": "Sat, 20 May 2023 13:32:32 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.garage"
      }
```

**Comment by dermotduffy** [comment]
What is the value of this variable in your Frigate config:

```yaml
mqtt:
  client_id: <value here>
```

Whatever value you set there, you should also set in the camera configuration in the card as:

```yaml
cameras:
  frigate:
    client_id: <value here>
```

If you're not setting any value at all in your Frigate config, there's probably something broken with your installation.

**Comment by denveronly** [comment]
> ```yaml
> frigate:
>       client_id: <value here>
> ```

Thank you mate, it worked!
it was all about **client_id: <value here>** in the lovelace section

**Comment by denveronly** [comment]
Can i ask about another thing that i encounter problem, i want to make like a cameracard in HA that shows frigate birdseye view
i found on HA community forum a config but have error in any way i try to implement at my instance
what am i doing wrong
error is **Cannot read properties of null( reading mode)**

```
type: custom:frigate-card
view:
  default: live
  camera_select: live
menu:
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    image:
      enabled: false
    timeline:
      enabled: false
    frigate_ui:
      enabled: false
  style: outside
  position: bottom
live:
  preload: true
  controls:
    thumbnails:
      mode: none
    next_previous:
      style: none
    title:
      mode: none
  lazy_load: true
  draggable: true
  lazy_unload: all
cameras:
  - live_provider: frigate-jsmpeg
    frigate:
      camera_name: birdseye
    dependencies:
      all_cameras: true
```

**Comment by dermotduffy** [comment]
> Thank you mate, it worked!

Great! Will close this issue.

> error is Cannot read properties of null( reading mode)

The config you quote is outdated (the visual editor should give you an option to automatically updated it), but a very simple example is the following, and you can expand from here:

```yaml
type: custom:frigate-card
cameras:
  - live_provider: jsmpeg
    frigate:
      camera_name: birdseye
```

You can also [restream your birdseye view](https://docs.frigate.video/configuration/restream) and it'll just show up as a normal camera entity in HA, then you'd just do the even simpler:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.birdseye // <-- You'd fill in your birdseye camera entity here.
```
