### ISSUE TITLE
Thumbnail carousel for specific camera showing clips for multiple cameras

### ISSUE THREAD

**Issue by whodat** [dermotduffy/frigate-hass-card#1195]
After upgrading to the latest version of frigate and frigate-hass-card, the gallery on any camera for my 5 cameras shows the recordings for all cameras. Would like a camera's gallery to only list recordings for only that camera. In the attachment, the gallery being shown for that specific camera are actually recordings for the camera to the far right.

Thanks for any help!

![Capture](https://github.com/dermotduffy/frigate-hass-card/assets/1149466/9edfc297-8352-426f-bead-24815296c8a9)

**Comment by dermotduffy** [comment]
Can you include your card configs?

**Comment by whodat** [comment]
cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.bluefence_cam1
        view:
          default: live
        menu:
          style: outside
          position: top
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.bluefence_cam2
        view:
          default: live
        menu:
          style: outside
          position: top
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.luckylodge_cam5_2
        view:
          default: live
        menu:
          style: outside
          position: top
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.luckylodge_cam6_2
        view:
          default: live
        menu:
          style: outside
          position: top
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.luckylodge_cam7_2
        view:
          default: live
        menu:
          style: outside
          position: top

**Comment by dermotduffy** [comment]
Hmm. So the card for `camera.bluefence_cam2` is showing clips for a totally different camera? Given that each card only has one camera configured, this is very unusual, and I'm not yet convinced it's a card issue ...

If you view the camera in the HA media browser (not related to the card at all), do you see the correct clips for that camera?

What happens if you manually set the frigate camera_name like this:

```yaml
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.bluefence_cam2
        frigate:
          camera_name: [PUT_FRIGATE_CAMERA_NAME_HERE]
    view:
      default: live
    menu:
      style: outside
      position: top
```

... does that work as expected?

**Comment by dermotduffy** [comment]
Also: If you view the events for this camera in the Frigate UI itself, do you get any mixing?

**Comment by whodat** [comment]
No mixing when using Frigate UI itself, everything is good there.  Changed Cam6 to the following, and restarted HA. That camera still showed recordings for every camera.

      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.luckylodge_cam6_2
            frigate:
              camera_name: LuckyLodge_Cam6
        view:
          default: live
        menu:
          style: outside
          position: top

**Comment by whodat** [comment]
And here is my directory structure...

![image](https://github.com/dermotduffy/frigate-hass-card/assets/1149466/43cc940b-a2a6-47a7-9fa2-0977be3a8e63)

**Comment by dermotduffy** [comment]
> No mixing when using Frigate UI itself, everything is good there. Changed Cam6 to the following, and restarted HA. That camera still showed recordings for every camera.

This is very strange! I'm struggling to see how this is possible, since the card only has a single camera configured. Can you try making a new dashboard, with just a single card, and just this config:

```yaml
  - type: custom:frigate-card
    cameras:
      - frigate:
          camera_name: LuckyLodge_Cam6
    view:
      default: live
    menu:
      style: outside
      position: top
```

... and grab me a screenshot of the problem if it persists?
