### ISSUE TITLE
Timeline view has no media around the scrub bar

### ISSUE THREAD

**Issue by XBigTK13X** [dermotduffy/frigate-hass-card#1197]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
5.1.1

**Last working release (if known):**
Never worked for me

**Browser and Operating System:**
Firefox/Windows
Chrome/Windows
Home Assisstant/Android

**Description of problem:**

The timeline view for my cameras never displays any media around the scrub bar. There is no visual feedback to determine if the point in the timeline has the footage I am trying to find. Instead, it always appears like this screenshot. I've tried changing all the settings I can find for the card, nothing ever impacts the timeline preview. Note that my debug info below is an older card release, but this issue exists for me on 5.1.1.

![Screenshot 2023-06-11 061425](https://github.com/dermotduffy/frigate-hass-card/assets/439577/855c53c1-aef1-44ca-847e-fda99e7909c2)

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.6.1",
  "card_version": "5.0.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0",
  "date": "2023-06-11T11:22:11.079Z",
  "frigate_version": {
    "fbd21801935293b1eb4da59bc53456ad": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en",
  "timezone": "America/Chicago",
  "git": {
    "build_version": "5.0.0-HEAD+gd7b150a",
    "build_date": "Sat, 22 Apr 2023 17:18:25 GMT",
    "commit_date": "Sat, 22 Apr 2023 10:10:23 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.yellow_room"
      }
    ],
    "timeline": {
      "media": "all",
      "style": "ribbon",
      "controls": {
        "thumbnails": {
          "mode": "above",
          "size": 75
        }
      }
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```
ReferenceError: t is not defined 25b80e56-e397-46de-b1f8-f6ebbfd2bcb3:1:100
    e blob:http://ha.9914.us:8123/25b80e56-e397-46de-b1f8-f6ebbfd2bcb3:1
    <anonymous> blob:http://ha.9914.us:8123/25b80e56-e397-46de-b1f8-f6ebbfd2bcb3:1

```

**Comment by dermotduffy** [comment]
I don't understand the issue as described: the timeline view is not supposed to show media, it's just a timeline.

If you are intending to display the mini-timeline under the live media, you can enable that with something like this:

```yaml
live:
  controls:
    timeline:
      mode: below
```

This will show the timeline under the live media, which is perhaps what you are expecting?

**Comment by XBigTK13X** [comment]
Thank you for taking the time to correct my misunderstanding of the docs.

That does make a timeline appear below the live feed, but doesn't seem to allow scrubbing. When I click and drag it immediately loads a recording/clip on mousedown instead of letting me move the timeline around. 

Here's a my new config after applying the changes you suggested.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.green_room
    live_provider: go2rtc
view:
  default: image
image:
  mode: camera
  refresh_seconds: 3
menu:
  buttons:
    cameras:
      enabled: false
    substreams:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
    download:
      enabled: false
live:
  controls:
    timeline:
      mode: below
      style: ribbon
      media: all
```

**Comment by dermotduffy** [comment]
Turn it on for both live and the media-viewer and I think it will be closer to what you want?

```yaml
live:
  controls:
    timeline:
      mode: below
media_viewer:
  controls:
    timeline:
      mode: below
```
