### ISSUE TITLE
Pre-release 1.2: New picture elements support feature

### ISSUE THREAD

**Issue by alexdelprete** [dermotduffy/frigate-hass-card#121]
I tried this in latest pre-release, 1.2, as pr #111 description:

```
    elements:
      - type: custom:frigate-card-menu-icon
        entity: switch.switch_pedonale
      - type: custom:frigate-card-menu-icon
        entity: switch.switch_carrabile
```

And it gives me this error: `Invalid configuration: elements[0] -> type`

Then I tried:

```
elements:
  - type: custom:frigate-card-menu-state-icon
    entity: switch.switch_pedonale
    entity: switch.switch_carrabile
```

And it worked, no errors, but behaviour is like before: if I click on the two switches, it doesn't toggle them, but it opens the properties/state of the switch.
