### ISSUE TITLE
go2rtc live_provider missing

### ISSUE THREAD

**Issue by jameseck** [dermotduffy/frigate-hass-card#1218]
I have just upgraded to Frigate 0.12 - installed as HA addon.
Also upgraded the Frigate integration to 4.0.0 and this hass card to 5.2.0.

I'm trying to modify my dashboard to use go2rtc instead of jsmpeg for the Frigate cameras.

Previously (and still) working:
```
- type: custom:frigate-card
  cameras:
    - camera_entity: camera.front
      live_provider: frigate-jsmpeg
```

Not working:
```
- type: custom:frigate-card
  cameras:
    - camera_entity: camera.front
      live_provider: go2rtc
```
Error that shows is: ``` card custom:frigate-card Error: Invalid configuration: [ "cameras[0] -> live_provider"] ```

Additionally, if I try to configure the card via the gui, I cannot even select "go2rtc" from the dropdown list of live_providers.
I'm sure I'm missing something obvious but can't figure it out.

Thanks in advance
