### ISSUE TITLE
webrtc-card provider incorrectly requires cameraEntity for engine detection

### ISSUE THREAD

**Issue by stplatt** [dermotduffy/frigate-hass-card#1222]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.2.0

**Last working release (if known):**
Never? Supposedly fixed in https://github.com/dermotduffy/frigate-hass-card/issues/1124

**Browser and Operating System:**
Chrome, Windows 10
Android webview, Android 13
Home Assistant OS

**Description of problem:**

From: https://github.com/dermotduffy/frigate-hass-card/issues/1124
> I have now fixed the problem that was causing you to need to include the `camera_entity`, it will be in the next build. This does not resolve your camera that mysteriously does not load, obviously.

It seems like camera_entity is still required for webrtc-card? 

This works:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.octoprint
    live_provider: webrtc-card
    webrtc_card:
      url: camera.octoprint
      ui: true
      background: false
menu:
  buttons:
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    expand:
      enabled: true
    timeline:
      enabled: false
    fullscreen:
      alignment: opposing
  style: overlay
  position: bottom
  button_size: 35
elements:
  - type: state-icon
    tap_action:
      action: toggle
    entity: switch.basement_workbench_light
    style:
      top: 20px
      left: 20px
live:
  draggable: false
  zoomable: true
```

But this doesn't:
```
type: custom:frigate-card
cameras:
  - live_provider: webrtc-card
    webrtc_card:
      url: camera.octoprint
      ui: true
      background: false
menu:
  buttons:
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    expand:
      enabled: true
    timeline:
      enabled: false
    fullscreen:
      alignment: opposing
  style: overlay
  position: bottom
  button_size: 35
elements:
  - type: state-icon
    tap_action:
      action: toggle
    entity: switch.basement_workbench_light
    style:
      top: 20px
      left: 20px
live:
  draggable: false
  zoomable: true
```

**Comment by dermotduffy** [comment]
In your "doesn't work example", you're not providing an entity you're providing a URL, which is likely the source of the issue, i.e. this should work:

```
type: custom:frigate-card
cameras:
  - webrtc_card:
      entity: camera.landing
 ```

**Comment by stplatt** [comment]
So in WebRTC camera you can provide just the URL (as a URL or as gortc camera name) for streaming, it doesn't need a home assistant entity. I take it there's no way to do the same in this Frigate card?

Example webrtc config:

```
type: 'custom:webrtc-camera'
url: 'rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0'
```

**Comment by dermotduffy** [comment]
> So in WebRTC camera you can provide just the URL (as a URL or as gortc camera name) for streaming, it doesn't need a home assistant entity. I take it there's no way to do the same in this Frigate card?

Well, you can pass whatever arguments you want to the WebRTC card. The issue here is that we need to autodetect the card engine somehow, and right now using the `url` field is not one of the things the card does. Allowing  an entity to be passed  to the `url` field is a strange design choice  in my mind, but that's none of my business since that's on the WebRTC side -- this card should always flawlessly support WebRTC card.

I take it you cannot use `entity` instead of `url` in this case for some reason? If you can, why not just do that?

**Comment by stplatt** [comment]
> Allowing an entity to be passed to the `url` field is a strange design choice in my mind

It's not really an entity, it's just the name of my camera in gortc. Probably confusing because I used similar naming scheme to home assistant with the camera.xxx format



> I take it you cannot use `entity` instead of `url` in this case for some reason? If you can, why not just do that?

That is what I'm doing, but it requires me to have a home assistant entity that I don't really need. I can create a camera in go2rtc config and just stream it in WebRTC card, but I can't use the frigate card without creating a camera entity in home assistant.

**Comment by dermotduffy** [comment]
> That is what I'm doing, but it requires me to have a home assistant entity that I don't really need. I can create a camera in go2rtc config and just stream it in WebRTC card, but I can't use the frigate card without creating a camera entity in home assistant.

The card doesn't actually require the entity, so you shouldn't need to create it for the card's sake. It just needs to somehow get the Frigate camera name, i.e. like this:

```yaml
type: custom:frigate-card
cameras:
  - live_provider: webrtc-card
    frigate:
      camera_name: <frigate_name> <-----------------
    webrtc_card:
       // whatever you want
```

**Comment by stplatt** [comment]
> The card doesn't actually require the entity, so you shouldn't need to create it for the card's sake. It just needs to somehow get the Frigate camera name, i.e. like this:

I'm not using frigate though, I'm just using go2rtc.

**Comment by dermotduffy** [comment]
> I'm not using frigate though, I'm just using go2rtc.

Aha. OK -- maybe I'm finally getting the issue :-)

The workaround would simply be to manually specify the engine, something like this:

```yaml
cameras:
  - live_provider: webrtc-card
    engine: generic            // <--------------------- Added this
    webrtc_card:
      url: camera.octoprint
      ui: true
      background: false
```

This would probably work without any entity needing to exist.

Real fix would be: If the user is relying on engine autodetection, but does configure a webrtc_card URL, we should auto-detect the engine as `generic` vs (no engine) unless we have a reason to believe it's something else (e.g. `frigate`).

**Comment by stplatt** [comment]
> The workaround would simply be to manually specify the engine, something like this:
> 
> ```yaml
> cameras:
>   - live_provider: webrtc-card
>     engine: generic            // <--------------------- Added this
>     webrtc_card:
>       url: camera.octoprint
>       ui: true
>       background: false
> ```

Yes, perfect, the engine is what I was missing. I also needed to add an ID for it to work, but that's easy enough. Thanks!

```
type: custom:frigate-card
cameras:
  - live_provider: webrtc-card
    engine: generic
    webrtc_card:
      url: camera.octoprint
      ui: true
      background: false
    id: Octoprint
```

**Comment by dermotduffy** [comment]
A fix for this is now merged on the `dev` branch and will be in the next release. Here's a demo config, note the absence of an `id` or `engine` parameter, it just works as you probably expected it to in the first place!

```yaml
type: custom:frigate-card
cameras:
  - live_provider: webrtc-card
    webrtc_card:
      url: camera.office
```
