### ISSUE TITLE
Card installation/setup problems - "Could not determine suitable engine for camera."

### ISSUE THREAD

**Issue by occasionallyword** [dermotduffy/frigate-hass-card#1227]
**Checklist:**

- [Yes] I updated to the latest version available
- [Yes] I cleared the cache of my browser

**Release with the issue:**
core-2023.7.2

**Last working release (if known):**
N/A - fresh installation

**Browser and Operating System:**
Firefox on Linux

**Description of problem:**
I have HA and Frigate installed under Docker.  I've added HACS, and installed the Frigate Integration afterwards.  I can get HA notifications of Frigate object detections, so that's at least partially working.  I installed this card through HACS, and I had to manually add the path to the Resource UI manager.  

When I go to add this hass card to my, "Overview" page, I see the following on the card itself:

```
Could not determine suitable engine for camera.[ Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).

{
  "hide": false,
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  },
  "engine": "auto",
  "frigate": {
    "client_id": "frigate"
  },
  "motioneye": {
    "images": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    },
    "movies": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    }
  },
  "live_provider": "auto",
  "image": {
    "refresh_seconds": 1
  }
}
```
There's some similar output in my F12 browser debug menu:

```
Error: Could not determine suitable engine for camera
    vu card-555679fd.js:75
    Wg card-555679fd.js:75
    _getEnginesForCameras card-555679fd.js:75
    initializeCameras card-555679fd.js:75
    _initializeCameras card-555679fd.js:507
    _initializeMandatory card-555679fd.js:507
    initializeIfNecessary card-555679fd.js:507
    _initializeMandatory card-555679fd.js:507
    promise callback*_initializeMandatory card-555679fd.js:507
    shouldUpdate card-555679fd.js:507
    performUpdate card-555679fd.js:11
    scheduleUpdate card-555679fd.js:11
    _$Ej card-555679fd.js:11
    requestUpdate card-555679fd.js:11
    u card-555679fd.js:11
    j card-555679fd.js:11
    ge card-555679fd.js:23
    kb card-555679fd.js:507
    C scoped-custom-element-registry.js:385
    t scoped-custom-element-registry.js:236
    r create-element-base.ts:93
    h create-element-base.ts:111
    h create-element-base.ts:215
    c create-element-base.ts:172
    k create-card-element.ts:101
    value hui-card-preview.ts:88
    value hui-card-preview.ts:56
    performUpdate reactive-element.ts:1331
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
    requestUpdate reactive-element.ts:1210
    u reactive-element.ts:948
    _ reactive-element.ts:931
    i hui-card-preview.ts:22
    C scoped-custom-element-registry.js:385
    t scoped-custom-element-registry.js:236
    u lit-html.ts:1124
    g lit-html.ts:1535
    _$AI lit-html.ts:1379
    z lit-html.ts:2175
    update lit-element.ts:165
    performUpdate reactive-element.ts:1331
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
    requestUpdate reactive-element.ts:1210
    set reactive-element.ts:726
    value hui-dialog-edit-card.ts:81
    c make-dialog-manager.ts:130
    h make-dialog-manager.ts:163
    o fire_event.ts:76
    a show-edit-card-dialog.ts:17
    value hui-view.ts:248
    o fire_event.ts:76
    value hui-card-options.ts:251
    handleEvent lit-html.ts:2010
    _$AI lit-html.ts:1999
    v lit-html.ts:1187
 
Object { hide: false, dependencies: {…}, triggers: {…}, engine: "auto", frigate: {…}, motioneye: {…}, live_provider: "auto", image: {…} }
card-555679fd.js:75:163734

```
I don't see any further details which I can provide.

I would assume the card would function as a normal behavior.

**Frigate card diagnostic information**

Not sure what this could be referring to.  

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
You're not actually specifying any camera details whatsoever, so the card cannot figure out what to display. See the [basic camera examples](https://github.com/dermotduffy/frigate-hass-card#basic-cameras-configuration).

If you think I'm missing something, please provide a copy of your full card config.

Thanks and good luck.

**Comment by occasionallyword** [comment]
No combination of changes with the card configuration makes a difference.  Here's the current config:

```
type: custom:frigate-card
cameras:
  - frigate:
      url: *frigate_ip:5000*
      client_id: *frigate_mqtt_client_id*
  - camera_entity: camera.denlsu
  - camera_entity: camera.livingroom
```

**Comment by dermotduffy** [comment]
```yaml
type: custom:frigate-card
cameras:
  - frigate:
      url: *frigate_ip:5000*
      client_id: *frigate_mqtt_client_id*
```

This is not specifying any camera and is likely the source of your problem. If you just intend to include the 2 camera entities below, just remove this `frigate` section from the config entirely, i.e. this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.denlsu
  - camera_entity: camera.livingroom
```

**Comment by occasionallyword** [comment]
Those entries were added through the use of the GUI config (aka, not typed line by line manually), and removing them doesn't solve my issue as previously mentioned.  I am using a custom frigate client ID as I plan to use more than one instance of frigate, and per the instructions, I should specify frigate server and client ID information when using more than one instance.  I don't understand how following the instructions for the configuration would ever cause failures in the first place.  

After removing the frigate section and restarting everything, I am however met with a new error which I wasn't seeing before:

```
Failed to receive response from Home Assistant for request.[ Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).

{
  "request": {
    "type": "frigate/events/get",
    "instance_id": "frigate",
    "cameras": [
      "DenLSU"
    ],
    "limit": 50,
    "id": 43
  },
  "response": {
    "code": "not_found",
    "message": "Unable to find Frigate instance with ID: frigate"
  }
}
```

It seems to me that I *do* need to specify the frigate client ID, no?  Trying to add it manually outside of the `camera:` block results in an identical error, so I don't think it's functional there.

**Comment by dermotduffy** [comment]
Quick answer: If you are using a custom client_id, you do need to set it -- your config was creating a new camera entry but **only** specifying the client_id, and had two cameras that didn't specify the client id at all. Try this:

```yaml
type: custom:frigate-card
cameras_global:
  frigate:
    url: *frigate_ip:5000*
    client_id: *frigate_mqtt_client_id*
cameras:
  - camera_entity: camera.denlsu
  - camera_entity: camera.livingroom
```

... or more expressively...

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.denlsu
    frigate:
      url: *frigate_ip:5000*
      client_id: *frigate_mqtt_client_id*
  - camera_entity: camera.livingroom
    frigate:
      url: *frigate_ip:5000*
      client_id: *frigate_mqtt_client_id*
```
