### ISSUE TITLE
2-way audio doesn't work with docker hosted Frigate

### ISSUE THREAD

**Issue by gregtakacs** [dermotduffy/frigate-hass-card#1230]
So I've been trying to get the 2-way audio working with my Reolink Doorbell.

Basic setup:
- HA is running as HAOS on an intel celeron NUC
- Frigate is running in a docker container on a intel celeron NAS (ASUSTOR)
- The same NAS also hosts my traefik revese proxy that I use to provide https for HA and make HA accessible from the outside world on port 443
- I am using go2rtc 1.5.0 that I loaded into the frigate docker container's config directory

My frigate config looks like this:
```
mqtt:
  enabled: true
  host: {MQTT_HOST_IP}
  port: 1883
  user: mqtt
  password: {MQTT_PASSWD}
  
go2rtc:
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=20dB\""
  streams:
    doorbell-2way:
    - rtsp://{CAM_USER}:{CAM_PASS}@{CAM_IP}:554/h264Preview_01_sub
    - ffmpeg:rtsp://{CAM_USER}:{CAM_PASS}@{CAM_IP}:554/h264Preview_01_sub#audio=pcm#audio=volume
    doorbell:
      - http://{CAM_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={CAM_USER}&password={CAM_PASS}
      - "ffmpeg:doorbell#audio=opus"
    doorbell-sub:
      - http://{CAM_IP}/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={CAM_USER}&password={CAM_PASS}
  log:
    level: info # default level
    api: trace
    exec: debug
    ngrok: info
    rtsp: debug
    stream: debug
    webrtc: debug

live:
  height: 480

ffmpeg:
  # hwaccel_args: preset-vaapi
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - qsv
  output_args:
    record: preset-record-generic-audio-aac
    
detect:
  enabled: True
  width: 896
  height: 672
  fps: 5

objects:
  track:
    - person
    - car
    - dog
    - cat

cameras:
  doorbell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell-sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: True
    live:
      stream_name: doorbell-2way
    snapshots:
      enabled: True
```

If I go to the go2rtc panel and click on the webrtc link I get a fully working 2-way stream, mic and speaker working (I enabled in chrome to allow my docker's IP to access the microphone without TLS)

```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://{CAM_IP}/Preview_01_sub/",
      "remote_addr": "{CAM_IP}:554",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=83568, senders=1"
      ],
      "senders": [
        "8 PCMA/8000, bytes=26080, receivers=1"
      ],
      "recv": 84584,
      "send": 26000
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/37dd9ac6cac9de58b7c4ee36f9698eb1",
      "remote_addr": "127.0.0.1:51426",
      "user_agent": "ffmpeg/go2rtc",
      "medias": [
        "audio, recvonly, L16/8000"
      ],
      "receivers": [
        "96 L16/8000, bytes=53216, senders=1"
      ],
      "recv": 53868
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host {MY_COMPUTER_IP}:52155",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
      ],
      "receivers": [
        "8 PCMA/8000, bytes=26080, senders=1"
      ],
      "senders": [
        "102 H264, bytes=83568, receivers=1",
        "8 PCMA/8000, bytes=53216, receivers=1"
      ],
      "recv": 29340,
      "send": 111829
    }
  ]
}
```

My HA card is configured as such. It's basically using the frigate camera but instructs the card to use the 2-way stream:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: doorbell-2way
menu:
  buttons:
    microphone:
      enabled: true
      alignment: opposing
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
      alignment: opposing
    camera_ui:
      enabled: false
  style: overlay
  position: left
  button_size: 80
live:
  controls:
    thumbnails:
      mode: none
  auto_mute: all
  preload: false
  microphone:
    always_connected: true
    disconnect_seconds: 0
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
```

But if I go to HA and look at the card I don't get the 2-way audio, only hear sound, can't send back voice, while the mic button does show up it just shows a half microphone and half speech bubble not a full mic and pushing it does nothing.

<img width="232" alt="image" src="https://github.com/dermotduffy/frigate-hass-card/assets/20398441/5fc4b3ad-8b9c-4a3e-8d3d-309c90ccf482">

Also the stream use on go2trc shows no audio stream is set up to be sent to the camera:
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://{CAM_IP}/Preview_01_sub/",
      "remote_addr": "{CAM_IP}:554",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=1472867, senders=1"
      ],
      "recv": 1488887
    },
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/37dd9ac6cac9de58b7c4ee36f9698eb1",
      "remote_addr": "127.0.0.1:51460",
      "user_agent": "ffmpeg/go2rtc",
      "medias": [
        "audio, recvonly, L16/8000"
      ],
      "receivers": [
        "96 L16/8000, bytes=733152, senders=1"
      ],
      "recv": 742024
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
      ],
      "senders": [
        "102 H264, bytes=226420, receivers=1",
        "8 PCMA/8000, bytes=108544, receivers=1"
      ],
      "send": 284774
    }
  ]
}
```

I have tried to move the docker container from bridged to host to macvlan, the result was the same. When I tried to access HA from my phone while on the same wifi I did get asked if I Wanted to share my microphone with the page (I said yes) only to see the same microphone icon in the corner.

So I have confirmed that everything works in the frigate hosted go2rtc but things break down within the frigate-card inside HA. Any help is appreciated.
