### ISSUE TITLE
Alternative way to cast camera streams

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1231]
**Is your feature request related to a problem? Please describe.**
Casting camera streams from the Frigate Card is very easy, but the casted stream has a big problem: extremely high latency because it uses HLS format.

This makes it unusable for certain situations, like for example automatically showing some events in TVs as they happen or displaying the doorbell on the Nest Hub when someone rings.

**Describe the solution you'd like**
I figured there is a way to improve this, by a lot:

1. Create a new, hidden, 1-panel layout dashboard. Call it Frigate Card:
![image](https://github.com/dermotduffy/frigate-hass-card/assets/29582865/84a761d3-12c6-48a2-a0be-0730b15a5d59)

2. Add a Frigate Card to this new dashboard. Mine looks like:

```yaml
type: custom:frigate-card
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - webrtc
cameras:
  - camera_entity: camera.video_porteiro
    id: video_porteiro
    go2rtc:
      stream: video_porteiro_hd
performance:
  profile: low
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
menu:
  style: none
live:
  auto_unmute: all
  controls:
    builtin: false
  zoomable: false
  lazy_unload: all
view:
  default: live
```

You can add as many camera entities you want, but make sure to hide the buttons if you intend to display it in a TV, for example. In my example, I'm also using the HD substream of my video_porteiro camera (doorbell).

3. Then, you can cast this card with:

```yaml
service: cast.show_lovelace_view
data:
  view_path: 0?frigate-card-action:camera_select=video_porteiro
  entity_id: media_player.tv_da_sala
  dashboard_path: frigate-card
```

Where from `view_path` you can select any camera you want through the query parameter.

The result? A quick and very low latency stream, with audio.

My point with this feature suggestion is:

It would be awesome if this process of casting the camera could be automated directly from the _Send to media player_ button in the Frigate Card, so that I would not need to call this service manually each time.

Maybe something like:

```yaml
type: custom:frigate-card
menu:
  buttons:
    media_player:
      enabled: true
      # Alters from current method to this new method
      method: cast_card
      # Expects that the user has a Frigate Card dashboard created already and configured as below
      cast_card:
        view_path: 0
        dashboard_path: frigate-card
cameras:
  - camera_entity: camera.video_porteiro
    # Optional, by default uses the same id as from the current card
    cast_card:
      id: video_porteiro
```

**Describe alternatives you've considered**
The alternative is to call the service manually. I can probably add some buttons in my dashboard to trigger this service more easily, but it would never be as easy and as integrated as from within the Frigate Card itself.

**Additional context**
N/A

**Comment by Neonox31** [comment]
Hi @felipecrs,

Nice idea, I upvoted :+1: 

By any chance, did you managed to get this working on a Google nest hub ?
On my side the google nest hub default image of home assistant cast is displayed in place of the camera but it works well on my chromecast ultra, maybe a decoding issue of the stream I presume.

**Comment by dermotduffy** [comment]
Quick question on the intention @felipecrs :

```yaml
    # Optional, by default uses the same id as from the current card
    cast_card:
      id: video_porteiro
```

Trying to figure out what is intended by the `id` parameter here. I think maybe there's a typo in the comment, and it should mean the **_camera_** to cast? I'm not sure why you'd ever want casting camera A, to cast a different camera, so maybe I'm not getting it!

**Comment by felipecrs** [comment]
That's the card id, in case there are multiple cards in the same page.

**Comment by Neonox31** [comment]
@felipecrs Are you sure that `cast.show_lovelace_view` service accepts query parameters in `view_path` ?
On my side it doesn't seem to be working, but maybe I'm missing something ?

**Comment by felipecrs** [comment]
Damn, it doesn't work indeed. In my case, I thought it was working because I was always testing with the first camera in the card.

Ok, so to make it work currently you have to actually create a dashboard for each camera then.

**Comment by felipecrs** [comment]
I have reported as a bug to Hass: https://github.com/home-assistant/core/issues/98316

**Comment by felipecrs** [comment]
Here is one quick demo on a Nest Hub to cast my brother's doorbell:

https://github.com/dermotduffy/frigate-hass-card/assets/29582865/e0e77aea-e555-4978-8e7b-20a745034e1a

Next I want to check if 2-way audio works, but his house doesn't yet have a 2-way audio go2rtc capable camera yet.

If it works, it's gonna be awesome to answer the doorbell directly from the Nest Hub.

**Comment by Neonox31** [comment]
@felipecrs FYI I submitted https://github.com/dermotduffy/frigate-hass-card/issues/1244 because generic cameras are not correctly selected using query params, and after I think I will go with your solution to cast my cameras on my Google devices 👍

**Comment by dermotduffy** [comment]
I'm thinking the dashboard and method should perhaps be a property of the camera, not least because of https://github.com/home-assistant/core/issues/98316 which would require a dashboard per camera, vs a property of the button:

That would look like:

```yaml
type: custom:frigate-card

menu:
  buttons:
    media_player:
      enabled: true

cameras:
  - camera_entity: camera.video_porteiro
    cast:
      method: 'standard' | 'dashboard'
      dashboard:
        dashboard_path: frigate-card-dashboard
        view_path: mytab
        view_card_id: foo <--- defaults to this card's card-id
        view_camera_id: bar <--- defaults to this camera's id
        // This effectively resolves to this path: /frigate-card-dashboard/mytab?frigate-card-action.foo.camera_select=bar

// To use the same method / path for all cameras
cameras_global:
  cast:
  // Supports all the arguments shown above
```

@felipecrs Does this look right to you?
