### ISSUE TITLE
Allow to trigger card automations on microphone unmuted

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1241]
**Is your feature request related to a problem? Please describe.**
For my doorbell, I need to run a Home Assistant service to let it know someone answered it. This also makes it stop ringing on other devices.

I would like to be able to send such command to my doorbell as soon as I unmute microphone in the Frigate Card, to signal that I answered it.

**Describe the solution you'd like**

Something like this:

```yaml
automations:
  - conditions:
      microphone_unmuted: true
      camera: doorbell
    actions:
      - action: call-service
        service: script.answer_doorbell
```

**Describe alternatives you've considered**

@pergolafabio's idea was to create his own microphone button so that he can call the service before unmuting the card. That's actually not bad at all.

**Additional context**
N/A

**Comment by dermotduffy** [comment]
Or perhaps:

```yaml
automations:
  - conditions:
      microphone: unmuted <-------- or muted
      camera: doorbell
    actions:
      - action: call-service
        service: script.answer_doorbell
```

One issue that comes to mind is that when the card starts (or the config is edited/reloaded) it will immediately match this criteria, and thus call your service. This is probably not what you want? May need to add something like:

```yaml
automations:
  - conditions:
      on_config_load: false <----------------
      microphone: unmuted <-------- or muted
      camera: doorbell
    actions:
      - action: call-service
        service: script.answer_doorbell
```
