### ISSUE TITLE
Expand callable card actions to allow navigating to specific event records 

### ISSUE THREAD

**Issue by kirsch33** [dermotduffy/frigate-hass-card#1246]
**Describe the solution you'd like**
I use Home Assistant/Frigate for notifications when specific objects enter specific zones. With this notification I currently pass a link to the URL on my domain, which gets opened and played in Safari. I also have configured an action to load the triggered cameras live view based on currently available card actions:
```yaml

script:
  send_dynamic_notification:
    sequence:
      - service: notify.mobile_app_austins_iphone
        data:
          message: "{{ message }}"
          data:
            tag: "{{ notifTag }}"
            group: "{{ group }}"
            image: "{{ null }}"
            video: "{{ null }}"
            attachment:
              url: "{{ image }}"
            push:
              interruption-level: active
            actions:
              - action: URI
                title: "View Clip In Browser"
                uri: "{{ video }}"
                destructive: false
              - action: URI
                title: "View Live"
                uri: "/lovelace/frigate?frigate-card-action:camera_select={{ camera }}&frigate-card-action:live"
                destructive: false
    mode: single
```
The "View Live" is launched directly in the Home Assistant app which is great. I would like to use a card action for the "View Clip" action as well so that it also launches directly to the HA app. Ideally I could pass a camera and event ID parameter to navigate directly to the specific recording created by the event in the media viewer. 

It could also be interesting to launch the card's live view but with the mini timeline adjusted to the event start time, which is how I typically like to view recent activity.
