### ISSUE TITLE
Filtering of Clips

### ISSUE THREAD

**Issue by asteriqz** [dermotduffy/frigate-hass-card#1256]
Hi,

I'm hoping to setup the card to quickly show me the clips for both my cameras, I've selected both camera's as entities although the default is to display the first one only, I've added my second camera into the filter (backyard) although this change isn't persistent after a refresh. Is there anyway to set up the card similar to below although have it persistent after reboot/refresh etc.

![image](https://github.com/dermotduffy/frigate-hass-card/assets/20625187/8b96efcb-efb7-45da-bdec-81f156284950)

Thank you!

**Comment by dermotduffy** [comment]
Right now there's no way to make a persistent "filter query", but you can probably do something very similar by just having one camera depend on the other. In the following example, when media for `camera.landing` is shown, the card will also show media for `camera.living_room`. Then if you list `camera.landing` as the first default card, and the clips gallery as the default view, you may get what you want ...

```yaml
  - camera_entity: camera.landing
    dependencies:
      cameras:
        - camera.living_room
```

**Comment by asteriqz** [comment]
Hi,

I've updated it to:

type: custom:frigate-card
cameras:
  - camera_entity: camera.backyard
    dependencies:
      cameras:
        - camera.driveway

Although it still only looks to only show camera.backyard.

**Comment by dermotduffy** [comment]
Sorry, my example was incomplete. You need to not only tell it that `camera.backyard` depends on `camera.driveway`, but you also need to actually define `camera.driveway` also, i.e. like this:

```yaml
  - camera_entity: camera.backyard
    dependencies:
      cameras:
        - camera.driveway
  - camera_entity: camera.driveway
```
