### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by RudySixOw** [dermotduffy/frigate-hass-card#1257]
Hi, first sorry for my bad english.

I try to make menu list with  name of camera and if i choose a camera the frigate card show it. 

I try with 

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: {{ states('input_select.list_cam') }}
    live_provider: go2rtc
    go2rtc:
      modes:
        - mjpeg
      stream: {{ states('input_select.list_cam') }}
```

But it's don't work.

Thanks in advance.

**Comment by dermotduffy** [comment]
The card does not support this today -- cameras must be explicitly listed. If you wanted them all to use go2rtc and mjpeg, you could do something like this:

```yaml
type: custom:frigate-card
cameras:
  - camera.kitchen
  - camera.sitting_room
  - camera.landing
  - <------------- List all the cameras you care about here ------------>
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - mjpeg
```

... but you still need to list them all manually. The card will automatically create a menu with the cameras you list.
