### ISSUE TITLE
Change number of cameras based on HA state does not work

### ISSUE THREAD

**Issue by brpeterso** [dermotduffy/frigate-hass-card#1263]
I have several indoor cameras that I have turned off by a switch when we're home. Currently, these cameras take up space in the card that you have to scroll through. I see there is a hide camera from UI...could there be an option that allows you to hide/unhide it based on a sensor/switch?

**Comment by dermotduffy** [comment]
This **should** be possible with something like this, but I can't quite get it to work to change the number of cameras, so I'm going to leave this issue open to investigate further:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.back_yard
  - camera_entity: camera.sitting_room
overrides:
  - conditions:
      state:
        - entity: switch.whatever
          state: 'off'
    overrides:
      cameras:
        - camera_entity: camera.sitting_room
```
