### ISSUE TITLE
Enabling 2 way audio restarts the stream. Sometimes makes the app hang.

### ISSUE THREAD

**Issue by teymur1988** [dermotduffy/frigate-hass-card#1268]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
4.0.0/0.12.1-367d724
**Last working release (if known):**

**Browser and Operating System:**
windows 11/ios. google chrome/mozilla firefox/HA app, safari browser

**Description of problem:**
Enabling 2 way audio on a camera restarts the stream and sometimes makes the app hang.

**Explain what the issue is, and how things should look/behave. If possible provide a screenshot with a description.**
I've installed Frigate as HA addon. I added all my cameras to the config. My cameras are Amcrest 1041B. Live provider is set to go2rtc. All cameras are hardwired. HA is also hardwired. Enabling 2 way audio on the card makes the stream restart and sometimes causes the HA ios app hang. And sometimes the stream restart and comes back and it works. See the attached videos please.

This is when it hangs.

https://github.com/dermotduffy/frigate-hass-card/assets/57329345/f3499a0f-01cc-4c85-9dba-b19ad973ab30

This is when it works.

https://github.com/dermotduffy/frigate-hass-card/assets/57329345/d200fdfe-cb51-4ba4-bca8-0836673b388c

My frigate config is as per below:
```yaml
go2rtc:
  streams:
    doorbell:
      - rtsp://admin:password@doorbellcamera.asus/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:doorbell#audio=opus
    doorbell_sub:
      - rtsp://admin:password@doorbellcamera.asus/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:doorbell_sub#audio=opus

  webrtc:
    listen: ":8555" # address of your local server (TCP)
    candidates:
      - my_ip_address:8555 # if you have dynamic public IP-address
  ffmpeg:
    output: "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
  api:
    origin: "*"
  rtsp:
    listen: ":8554"
  log:
    level: info # default level
    api: trace
    exec: debug
    ngrok: info
    rtsp: trace
    streams: error
    webrtc: fatal

####FRIGATE CONFIG BELOW####

mqtt:
  host: 10.10.10.29
  user: homeassistant
  password: password
#
database:
  path: /config/frigate.db
#
detectors:
  detector_name:
    type: cpu
#
snapshots:
  enabled: true
#
record:
  enabled: True
  retain:
    days: 360
    mode: motion
  events:
    retain:
      default: 720
      mode: active_objects
#
birdseye:
  enabled: True
  mode: motion
#
cameras:
  frigate_doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://scrypted.asus:41253/f049b7e96f5937d5 #1080p
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://scrypted.asus:41253/69d7283c289d5e6d #muted stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
```
-->

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.9.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
  "date": "2023-09-13T14:01:12.512Z",
  "frigate_version": {
    "f57bdffd5dcac46242e82851a9ae9b09": "4.0.0/0.12.1-367d724"
  },
  "lang": "en",
  "timezone": "Asia/Baku",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "dimensions": {
      "aspect_ratio_mode": "dynamic",
      "aspect_ratio": "16:9"
    },
    "cameras": [
      {
        "camera_entity": "camera.frigate_doorbell",
        "live_provider": "go2rtc",
        "webrtc_card": {},
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "doorbell"
        }
      }
    ],
    "menu": {
      "buttons": {
        "frigate": {
          "alignment": "matching",
          "enabled": true
        },
        "microphone": {
          "enabled": true,
          "type": "toggle",
          "alignment": "opposing"
        },
        "cameras": {
          "enabled": false
        },
        "fullscreen": {
          "enabled": false
        },
        "mute": {
          "enabled": true,
          "alignment": "opposing"
        },
        "download": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        }
      },
      "position": "bottom",
      "alignment": "left",
      "style": "outside"
    },
    "live": {
      "layout": {
        "fit": "fill"
      },
      "controls": {
        "next_previous": {},
        "thumbnails": {}
      },
      "transition_effect": "slide",
      "preload": true,
      "auto_mute": "all",
      "draggable": false,
      "lazy_load": false
    },
    "timeline": {
      "media": "clips",
      "controls": {
        "thumbnails": {
          "mode": "above"
        }
      }
    },
    "media_viewer": {
      "auto_unmute": "all",
      "transition_effect": "slide"
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
