### ISSUE TITLE
Possible to see all event recordings (from all cameras) in one view?

### ISSUE THREAD

**Issue by zaneclaes** [dermotduffy/frigate-hass-card#1270]
**Is your feature request related to a problem? Please describe.**
I have many cameras, and the thing I'm most interested in seeing is a list of event recordings for me to view.

**Describe the solution you'd like**
An "all cameras" option for the recording tabs would probably be easiest.

**Describe alternatives you've considered**
There's an opportunity here to make a really nice UI for this use-case... we use our security cameras mostly as wildlife cameras, and we get nice recordings of various animals (deer, bears, mountain lions, etc.) fairly regularly. Waking up to a nice feed of wildlife in home assistant would be nice :)

**Comment by dermotduffy** [comment]
This might do what you want (or similar at least). It creates a bunch of cameras, and tells the card that the first camera depends on all the others, which will group their event media together.

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room
    dependencies:
      all_cameras: true
  - camera_entity: camera.landing
  - camera_entity: camera.office <--- List as many cameras as you want here
view:
  default: clips
```
