### ISSUE TITLE
Birdseye and multiple frigate servers

### ISSUE THREAD

**Issue by andrewhack** [dermotduffy/frigate-hass-card#1271]
HI,

I don't know if this is even possible but any suggestions are warm welcomed.
This is what I have as configuration at the moment. client_id is acceptable because I can see the birdseye from frigatenvr1.
I can't add the other servers in similar way because the camera name is always  birdseye

Any suggestions?

``` 
- type: custom:frigate-card
    cameras:
      - frigate:
          camera_name: birdseye
          client_id: frigatenvr1
        dependencies:
          all_cameras: true

**Comment by andrewhack** [comment]
Adding a separate card for every frigate servers is not helping - the first birdseye is visible, only

```
- type: custom:frigate-card
    cameras:
      - frigate:
          camera_name: birdseye
          client_id: frigatenvr1
  - type: custom:frigate-card
    cameras:
      - frigate:
          camera_name: birdseye
          client_id: frigatenvr2
  - type: custom:frigate-card
    cameras:
      - frigate:
          camera_name: birdseye
          client_id: frigatenvr3

**Comment by dermotduffy** [comment]
> I can't add the other servers in similar way because the camera name is always birdseye

What's the error you are shown exactly? Why does this not work?

If it's simply that the id of the cameras are clashing in the card since the camera names are the same, something like this might help (have not tested):

```yaml
- type: custom:frigate-card
  cameras:
    - id: birdseye1
      frigate:
        camera_name: birdseye
        client_id: frigatenvr1
    - id: birdseye2
      frigate:
        camera_name: birdseye
        client_id: frigatenvr2
```
