### ISSUE TITLE
Frigate card query args not working when used with Bubble Card

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#1276]
I am using the [bubble card](https://github.com/Clooos/Bubble-Card) to have a popup using the navigate action. This is basically a card that is in the dashboard but hidden and when the navigation is called with the hash `#cameras` a popup will show with the card inside. 

Running frigate card 5.2.0

Here is the yaml for the view that is calling this:

```yaml
type: custom:mushroom-chips-card
chips:
  - type: template
    entity: sensor.frigate_status
    content: |-
      {% if (states("binary_sensor.back_deck_cam_person_occupancy") == 'on')  %}
        Person @ Back Deck
      {% elif states('binary_sensor.back_deck_cam_dog_occupancy') == 'on' %}
        Dog @ Back Deck
      {% else %}
        Back Deck
      {% endif %}
    icon: |-
      {% if (states("binary_sensor.back_deck_cam_person_occupancy") == 'on')  %}
        mdi:account-alert-outline
      {% elif states('binary_sensor.back_deck_cam_dog_occupancy') == 'on' %}
        mdi:dog-service
      {% else %}
        mdi:cctv
      {% endif %}
    icon_color: |-
      {% if (states("binary_sensor.back_deck_cam_person_occupancy") == 'on')  %}
        red
      {% elif states('binary_sensor.back_deck_cam_dog_occupancy') == 'on' %}
        red
      {% else %}
        white
      {% endif %}
    tap_action:
      action: navigate
      navigation_path: '#cameras?frigate-card-action:camera_select=back_deck_cam'
alignment: center

```

I have also tried

`navigation_path: '#cameras?frigate-card-action:popup:camera_select=back_deck_cam'`
`navigation_path: '#cameras?frigate-card-action:camera_select=camera.back_deck_cam'`

but they also do not seem to work.

Here is the yaml for the frigate card in a popup

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#cameras'
    name: Cameras
    icon: mdi:cctv
    margin_top_mobile: 0px
    margin_top_desktop: 28px
    width_desktop: 90%
  - type: custom:vertical-stack-in-card
    cards:
      - type: custom:frigate-card
        card_id: popup
        cameras:
          - camera_entity: camera.front_cam
            live_provider: go2rtc
            go2rtc:
              modes:
                - webrtc
            frigate:
              labels:
                - person
                - dog
                - cat
            id: front_cam
          - camera_entity: camera.back_gate_cam
            live_provider: go2rtc
            go2rtc:
              modes:
                - webrtc
            frigate:
              labels:
                - person
            id: back_gate_cam
          - camera_entity: camera.back_deck_cam
            live_provider: go2rtc
            go2rtc:
              modes:
                - webrtc
            frigate:
              labels:
                - person
            id: back_deck_cam
          - camera_entity: camera.garage_cam
            live_provider: go2rtc
            go2rtc:
              modes:
                - webrtc
            frigate:
              labels:
                - person
          - camera_entity: camera.front_doorbell_cam
            live_provider: go2rtc
            go2rtc:
              modes:
                - webrtc
            frigate:
              labels:
                - person
          - camera_entity: camera.office_cam
            live_provider: go2rtc
            go2rtc:
              modes:
                - webrtc
            frigate:
              labels:
                - dog
        live:
          lazy_unload: all
          auto_play: all
          auto_mute: all
          auto_unmute: never
          controls:
            title:
              mode: none
            thumbnails:
              mode: below
              media: snapshots
              show_details: false
            next_previous:
              style: none
          zoomable: false
          auto_pause: all
        media_viewer:
          controls:
            title:
              mode: none
            next_previous:
              style: none
        menu:
          style: outside
          position: bottom
          buttons:
            frigate:
              enabled: false
            snapshots:
              enabled: false
            download:
              enabled: false
            camera_ui:
              enabled: false
            fullscreen:
              enabled: false
            media_player:
              enabled: false
            microphone:
              enabled: true
            timeline:
              enabled: false
        performance:
          profile: high
        timeline: {}
```

I can see the url properly showing the query args, and the card opens but it always opens to front_cam

example: `http://HA_IP:8123/dashboard-draft/default-view#cameras?frigate-card-action:camera_select=back_deck_cam`

**Comment by kirsch33** [comment]
i could be wrong, but it could be related to this. while the issue is closed, per my latest comment and @dermotduffy response, it is still being addressed

https://github.com/dermotduffy/frigate-hass-card/issues/1259

**Comment by kirsch33** [comment]
also see this for context 

https://github.com/dermotduffy/frigate-hass-card/issues/1253#issuecomment-1699148995

**Comment by NickM-27** [comment]
To be clear I'm testing this on web so not sure what the specific issue is, but sounds like this is being refactored so sounds good to me

**Comment by dermotduffy** [comment]
> To be clear I'm testing this on web so not sure what the specific issue is, but sounds like this is being refactored so sounds good to me

That's right -- this is what I'm currently working on in my development time. I will specifically test the examples in this bug as I'm doing so. It's part of a much larger refactor of the main `card.ts` file which has grown beyond maintainability.

**Comment by dermotduffy** [comment]
@NickM-27 Since it seems you tried out the refactored PR, did the querystring work as you expected now?

This should be the correct format to select a camera: `?frigate-card-action:camera_select=camera.front_door`

**Comment by NickM-27** [comment]
![Screen Shot 2023-10-04 at 05 49 54 AM](https://github.com/dermotduffy/frigate-hass-card/assets/14866235/9b52fffa-8b3d-43b0-864e-28e11d20be0f)

Haven't tried the new version yet, but it has just been sitting on this regardless of what I do

**Comment by NickM-27** [comment]
when I load the editor the card works fine but then I save and it just shows the above

**Comment by NickM-27** [comment]
it appears the issue is the card does not like being inside `vertical-stack-in-card`

however, once I removed that, it still does not seem to be working with the query args, the first camera is always opened

**Comment by dermotduffy** [comment]
Looks like more than 1 issue here. Mind sharing the non-vertical-stack config, with that I think the only issue is the query string doesn't work, right? 

And with the vertical stack (config as shown earlier in this issue?), it gets stuck at the ha reconnection?

**Comment by NickM-27** [comment]
> Looks like more than 1 issue here. Mind sharing the non-vertical-stack config (whatever the smallest config you have that shows the problem), with that I think the only issue is the query string doesn't work, right?

right, just that the query args don't seem to work AND when using query args the camera selector popup doesn't seem to work.

example: `http://192.168.50.106:8123/dashboard-draft/default-view#cameras?frigate-card-action:camera_select=camera.front_cam`

```yaml
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.front_cam
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc
        frigate:
          labels:
            - person
            - dog
            - cat
        id: front_cam
      - camera_entity: camera.back_gate_cam
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc
        frigate:
          labels:
            - person
        id: back_gate_cam
      - camera_entity: camera.back_deck_cam
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc
        frigate:
          labels:
            - person
        id: back_deck_cam
      - camera_entity: camera.garage_cam
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc
        frigate:
          labels:
            - person
      - camera_entity: camera.front_doorbell_cam
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc
        frigate:
          labels:
            - person
      - camera_entity: camera.office_cam
        live_provider: go2rtc
        go2rtc:
          modes:
            - webrtc
        frigate:
          labels:
            - dog
    live:
      lazy_unload: all
      auto_play: all
      auto_mute: all
      auto_unmute: never
      controls:
        title:
          mode: none
        thumbnails:
          mode: below
          media: snapshots
          show_details: false
        next_previous:
          style: none
      zoomable: false
      auto_pause: all
      transition_effect: none
    media_viewer:
      controls:
        title:
          mode: none
        next_previous:
          style: none
    menu:
      style: outside
      position: bottom
      buttons:
        frigate:
          enabled: false
        snapshots:
          enabled: false
        download:
          enabled: false
        camera_ui:
          enabled: false
        fullscreen:
          enabled: false
        media_player:
          enabled: false
        microphone:
          enabled: true
        timeline:
          enabled: false
    performance:
      profile: high

```

> And with the vertical stack (config as shown earlier in this issue?), it gets stuck at the ha reconnection?

I believe so, or at least that's what the card text implies. To be clear, this is with the `custom:vertical-stack-in-card` and not the built in stack

**Comment by dermotduffy** [comment]
> example: http://192.168.50.106:8123/dashboard-draft/default-view#cameras?frigate-card-action:camera_select=camera.front_cam

In this example, your card doesn't have a camera with an id "camera.front_cam", as you've explicitly set the id to `front_cam`, i.e. I would expect this to work:

`http://192.168.50.106:8123/dashboard-draft/default-view#cameras?frigate-card-action:camera_select=front_cam`

Don't suppose that could be the issue?

**Comment by NickM-27** [comment]
I'll try it again but that was actually how it was before but I changed it. I'll give it another go

**Comment by dermotduffy** [comment]
On the vertical stack issue, I install [this](https://github.com/ofekashery/vertical-stack-in-card) which I think is what you're referring to, and used your same config at the start of the issue. It seems to work fine. But when I add the bubble card, it behaves erratically, sometimes renders nothing at all, sometimes (rarely though) shows the reconnection message you had. If I change `custom:bubble-card` to `xxxcustom:bubble-card` it seems to go back to normal (except the bubble bit has the expected error message). Can't tell if the issue is in the bubble card or Frigate card...

**Comment by dermotduffy** [comment]
> On the vertical stack issue

OK, think I figured the vertical stack/bubble issue out somewhat. One of the bubble card, or more likely the vertical stack card, is passing in an `undefined` HA state object to the Frigate card, which should not happen. This is causing the Frigate card to think the connection is lost, and it is incorrectly detecting the "reconnection". Working on a fix. I see other issues with using the Frigate card in the bubble card though, but one thing at a time...

**Comment by NickM-27** [comment]
unfortunately this still doesn't seem to be working for me. If I have a button with navigate action and `navigation_path: '#cameras?frigate-card-action:camera_select=back_deck_cam'` it is still opening with the front_cam (which is the first cam in the list) selected

**Comment by dermotduffy** [comment]
> If I have a button

Aha. OK. You're not just going to the URL in the browser (bet that works), you're using a navigate action. I have reproduced the navigate action case not working -- phew.

**Comment by dermotduffy** [comment]
@NickM-27 OK, with those two merged changes on the `dev` branch I think this will be better for you. Note that the other issue I found is addressed with this non-merged PR:

https://github.com/ofekashery/vertical-stack-in-card/pull/126

Vertical stack card will cut off the camera selector menu if you position it at the bottom, since it uses `overflow: hidden`.

**Comment by NickM-27** [comment]
not sure if I am doing something wrong but it still doesn't work for me. I also copied the full address and tried to open it directly in the browser and it still opens to the front camera.

**Comment by dermotduffy** [comment]
> not sure if I am doing something wrong but it still doesn't work for me.

Oh dear, sorry this is consuming your time.

* Would you mind checking your Javascript console (F12 in Chrome) while you're loading the page with the query string and see if anything interesting is happening.
* I found and fixed a [different bug](https://github.com/dermotduffy/frigate-hass-card/issues/1286) impacting the carousel not scrolling correctly in certain cases. It's possible this was what you were seeing, although I suspect unlikely.

For full transparency, here is how I am testing. Please let me know if I'm not testing the right thing:

## Test Case 1: Simple navigation actions

![test-case-1](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/417057bb-4289-4f2d-9825-0f96b5f786cc)

Picture elements config:

```yaml
type: picture-elements
image: https://demo.home-assistant.io/stub_config/floorplan.png
elements:
  - type: icon
    icon: mdi:cctv
    style:
      top: 22%
      left: 30%
    tap_action:
      action: navigate
      navigation_path: /lovelace-test/map?frigate-card-action:camera_select=camera.living_room
  - type: icon
    icon: mdi:cctv
    style:
      top: 71%
      left: 42%
    tap_action:
      action: navigate
      navigation_path: /lovelace-test/map?frigate-card-action:camera_select=camera.landing
```

Card config:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room
  - camera_entity: camera.landing
```

## Test Case 2: Bubble + Vertical Stack

![test-case-2](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/7340de2b-6c96-4dc4-a3ec-f026779813d5)

Button:

```yaml
type: button
show_name: true
show_icon: true
tap_action:
  action: navigate
  navigation_path: >-
    /lovelace-test/vsic?frigate-card-action:camera_select=camera.living_room#cameras
show_state: false
icon: mdi:cctv
```

Stack/Card:
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#cameras'
    name: Cameras
    icon: mdi:cctv
    margin_top_mobile: 0px
    margin_top_desktop: 28px
    width_desktop: 90%
  - type: custom:vertical-stack-in-card
    cards:
      - type: custom:frigate-card
        card_id: popup
        cameras:
          - camera_entity: camera.landing
          - camera_entity: camera.living_room
```

**Comment by NickM-27** [comment]
okay so it appears the `#cameras` must come after the query args, not before. When it comes after things work as expected

**Comment by NickM-27** [comment]
by the way I am noticing the (what seems new) grid media gallery with live camera views, is there a way to default to this view?

**Comment by dermotduffy** [comment]
> okay so it appears the #cameras must come after the query args, not before. When it comes after things work as expected

Great, phew. Yes: the frigate card is using true query string parameters. Looks like bubble card is using anchor references like `#whatever`, this must come after a query string in a URL. This makes some sense, since anchor references are typically used to move particular content on a long page into view, which is (kind of?) what is happening with the popup: the content is already rendered, just not visible until it's "popped" into view.

> by the way I am noticing the (what seems new) grid media gallery with live camera views, is there a way to default to this view?

You mean the multi-camera grid? Yes, you can enable it by default for either (or both) of the live view or media view like the below. There's also a menu button to switch back and forth dynamically.

```yaml
[...]
live:
  display:
    mode: grid
media_viewer:
  display:
    mode: grid
```
