### ISSUE TITLE
CONFIG SUPPORT: Audio and 2 way audio not working

### ISSUE THREAD

**Issue by cooltings** [dermotduffy/frigate-hass-card#1285]
Hi I can't seem to get 2-way audio or one way audio 2 work in the card.
I have a reolink video doorbell (wifi)
Audio works in the go2rtc interface.
Here is my frigate config:
```
mqtt:
  host: core-mosquitto
  user: mqtt-user
  password:xxxxx
  
detectors:
  cpu:
    type: cpu
    num_threads: 2
  
go2rtc:
  ffmpeg:
      bin: ffmpeg
      volume: "-af \"volume=30dB\""
  streams:

    reolink: 
    
     - http://192.168.0.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx
     - "ffmpeg:reolink#audio=aac"
    reolink_sub: 
      - rtsp://admin:xxxx@192.168.0.33:554/h264Preview_01_sub
      - "ffmpeg:reolink_sub#audio=aac"

cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:        
          - 0,0,0,225,0,384,48,385,113,393,240,414,337,407,353,380,625,395,647,392,637,347,724,358,769,390,1280,720,1280,0
    objects:
        filters:
          person:
            mask:         
              - 0,0,0,225,0,384,48,385,113,393,240,414,337,407,353,380,625,395,647,392,637,347,724,358,769,390,1280,720,1280,0
    record:
      enabled: True      
      retain:
        days: 7
        mode: all  
    snapshots: # <----- Enable snapshots
      enabled: True 
```
I am using the reolink_sub stream in the card.
Thanks, any help would be much appreciated

**Comment by dermotduffy** [comment]
Can you include your Frigate card config? Have you read [here in the doc](https://github.com/dermotduffy/frigate-hass-card#using-2-way-audio) which includes limitations/requirements?

**Comment by cooltings** [comment]
here it is
```
type: custom:frigate-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: reolink_sub
    triggers:
      motion: true
    title: Doorbell
    id: doorbell
    webrtc_card:
      url: front
    frigate:
      camera_name: doorbell
live:
  microphone:
    always_connected: true
    disconnect_seconds: 30
  auto_unmute: selected
  lazy_load: true
  preload: true
  auto_play: all
  show_image_during_load: true
  auto_mute: unselected
  transition_effect: slide
  auto_pause: hidden
menu:
  buttons:
    microphone:
      enabled: true
      priority: 100
      type: momentary
      alignment: opposing
    download:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    expand:
      enabled: false
    frigate:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
  style: overlay
  position: left
  alignment: right
  button_size: 50
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '4:3'
image:
  refresh_seconds: 0
media_gallery:
  controls:
    thumbnails:
      size: 157
```
