### ISSUE TITLE
CONFIG SUPPORT: Live audio not working

### ISSUE THREAD

**Issue by madjetey** [dermotduffy/frigate-hass-card#1303]
Had it working once.  Messed around and now my Dahua live camera is mute.  Go2RTC stream has audio (2-way stream doesn't).
Generic camera integration kept timing out when adding go2rtc stream.  Tried to use Scrypted stream as alternative.

Card config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.gatecam1
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: GateCam1Lo
    webrtc_card:
      entity: camera.scrypt_gategam1_lo
    frigate:
      url: http://127.0.0.1:5000
      camera_name: GateCam1Lo
    triggers:
      occupancy: true
menu:
  alignment: right
  button_size: 50
  buttons:
    substreams:
      enabled: false
    live:
      enabled: true
    snapshots:
      enabled: false
    clips:
      enabled: true
    image:
      enabled: false
    fullscreen:
      enabled: false
    frigate:
      enabled: false
    cameras:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    media_player:
      enabled: true
    microphone:
      enabled: true
      alignment: opposing
    mute:
      enabled: true
      alignment: opposing
      type: toggle
  style: outside
  position: right
timeline:
  style: stack
  controls:
    thumbnails:
      mode: none
  show_recordings: false
  media: clips
live:
  preload: true
  layout:
    fit: fill
  controls:
    builtin: false
    timeline:
      mode: none
  microphone:
    always_connected: false
  auto_mute: hidden
  auto_unmute: all
  auto_play: all
view:
  default: live
  camera_select: snapshot
  dark_mode: auto
  update_cycle_camera: true
  update_force: false
  scan:
    enabled: true
    show_trigger_status: true
    untrigger_reset: true
    untrigger_seconds: 0
media_gallery:
  controls:
    thumbnails:
      show_favorite_control: false
      show_timeline_control: true
    filter:
      mode: left
media_viewer:
  transition_effect: none
  layout:
    fit: cover
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:11'
performance:
  features:
    animated_progress_indicator: false
  style:
    border_radius: false
    box_shadow: false

```

Relevant section of Frigate config:

```
go2rtc:
  streams:
#    HouseCamTest:  # Wyze restreaming from docker wyze bridge.  Disabled.
#      - rtsp://_address_:8554/housecam1
#    HouseCamTest_lo:
#      - rtmp://_address_:1935/housecam1
    GateCam1:
      - rtsp://_address_:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:rtsp_cam#audio=opus"
    GateCam1Lo:
      - rtsp://_address_:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:rtsp_cam#audio=opus"
    GateCamHTTP: # <- for other streams
      - rtsp://_address_:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <- stream which supports video & aac audio
      - "ffmpeg:http_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)


cameras:
  HouseCam1:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
      # High resolution
        - path: rtsp://192.168.1.108:8554/housecam1
          roles:
            - record
      # Low resolution
        - path: rtsp://192.168.1.108:8554/housecam1-sub
          roles:
            - detect
      output_args:
        #detect: -dn -an -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        #rtmp: -c copy -f flv
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    record:
     enabled: True
     events:
       objects:
         - person
         - dog
    zones:
      DownstairsInterior1:
        coordinates: 0,0,0,360,454,360,567,0
  GateCam1:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
       # High resolution
        - path: rtsp://127.0.0.1:8554/GateCam1
          roles:
            - record
      # Low resolution
        - path: rtsp://127.0.0.1:8554/GateCam1Lo
          roles:
            - detect
            - rtmp
      output_args:
        rtmp: preset-rtmp-generic
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 740 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    record:
     enabled: True
     events:
       objects:
         - person
         - car
         - dog
         - motorcycle
         - bicycle
    zones:
      Driveway1:
       coordinates: 289,292,302,480,740,480,740,0,567,0

```
