### ISSUE TITLE
Add support for Home Assistant users in Frigate card conditions

### ISSUE THREAD

**Issue by joaopedros2** [dermotduffy/frigate-hass-card#1305]
I need some help with the Frigate card.

I want to conditionally display some buttons only in fullscreen mode, and right now, I'm having issues with the "media_player" button.

```
elements:
  - type: custom:frigate-card-conditional
    conditions:
      media_loaded: true
	  fullscreen: true
      view:
        - live
    elements:
      - type: custom:frigate-card-menu-icon
        icon:  mdi:cast
        title: Screen Cast
        tap_action:
          action: custom:frigate-card-action
          frigate_card_action: media_player
```

**Comment by dermotduffy** [comment]
I think you're just missing the required arguments to the media player action, is this what you're looking for:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room
elements:
  - type: custom:frigate-card-conditional
    conditions:
      media_loaded: true
      fullscreen: true
      view:
        - live
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:cast
        title: Screen Cast
        tap_action:
          action: custom:frigate-card-action
          frigate_card_action: media_player
          media_player_action: play               <--------------ADDED
          media_player: media_player.dining_room  <--------------ADDED
```

I'm not sure what you're trying to do exactly, but since the card already comes with a "native" (non-element) cast button, you could also just conditionally override whether that native button shows up.

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room
menu:
  buttons:
    media_player:
      enabled: false
overrides:
  - conditions:
      media_loaded: true
      fullscreen: true
      view:
        - live
    overrides:
      menu:
        buttons:
          media_player:
            enabled: true
```
