### ISSUE TITLE
Messed up & missing recorded media

### ISSUE THREAD

**Issue by madjetey** [dermotduffy/frigate-hass-card#1314]
**Checklist:**

- [*] I updated to the latest version available
- [*] I cleared the cache of my browser

**Last working release (if known):5.2.0

**Browser and Operating System:**
iOS HA App & HASS.Agent via Edge on Windows 10

**Description of problem:**

**Frigate card diagnostic information**

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.gatecam1
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: GateCam1Lo
    webrtc_card:
      entity: camera.scrypt_gategam1_lo
    frigate:
      url: http://127.0.0.1:5000
      camera_name: GateCam1Lo
    triggers:
      occupancy: true
menu:
  style: overlay
  position: bottom
  buttons:
    substreams:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    clips:
      enabled: true
    mute:
      enabled: true
    microphone:
      alignment: opposing
      enabled: true
      type: momentary
  alignment: left
view:
  default: live
  dark_mode: auto
  camera_select: live
media_gallery:
  controls:
    filter:
      mode: left
live:
  microphone:
    always_connected: false
  preload: true
  auto_mute: all
  auto_unmute: selected
  controls:
    title:
      mode: popup-top-left
    thumbnails:
      mode: none
      show_favorite_control: false
      show_timeline_control: false
      show_details: false
      show_download_control: false
    builtin: false
timeline:
  style: stack
  media: all
```

**Comment by dermotduffy** [comment]
It would help if you could describe the issue -- i.e. what does "messed up" mean? Do the recordings play? Do  regular clips play?

Just to rule in/out whether the issue is the card: Do the recordings work okay in the HA Media browser? ("Media" tab in the Home Assistant sidebar).

**Comment by madjetey** [comment]
To be clear the message in the card's media gallery is "No media to display". This is the same for clips, snapshots & recordings.  It's the same across all browsers & apps however the HA media browser loads and plays fine.

I should also mention that when I use the configuration below the issue resolves but leaves me struggling with smooth playback (local & remote) and two-way audio

```

type: custom:frigate-card
cameras:
  - camera_entity: camera.gatecam1
menu:
  style: overlay
  position: bottom
  buttons:
    substreams:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    clips:
      enabled: true
    mute:
      enabled: true
    microphone:
      alignment: opposing
      enabled: true
      type: momentary
      icon: mdi:phone
  alignment: left
view:
  default: live
  dark_mode: auto
  camera_select: live
media_gallery:
  controls:
    filter:
      mode: left
live:
  microphone:
    always_connected: false
  preload: true
  auto_mute: all
  auto_unmute: selected
  controls:
    title:
      mode: popup-top-left
    thumbnails:
      mode: none
      show_favorite_control: false
      show_timeline_control: false
      show_details: false
      show_download_control: false
    builtin: false
timeline:
  style: stack
  media: all

```

I also forgot to mention: _camera.gatecam1_ is a frigate entity.
