### ISSUE TITLE
[QUESTION] Just the video live image without any buttons/icons

### ISSUE THREAD

**Issue by moostmartijn** [dermotduffy/frigate-hass-card#1316]
Hi, please delete if this is not allowed, but I'm working on a new mobile dashboard with square cards. The frigate-hass-card seems to be the only card which can convert my 16:9 ratio camera to a 4:3 camera. 

I would like to have just the live video stream of a camera without any icons, buttons, names or any other functionality. Is that possible with this card?

There's always a small pop-up with the name, and always a pause, mute, full-screen button. Is is possible to have a completely clear live video stream without all these bells and whistles? 
<img width="248" alt="Schermafbeelding 2023-11-02 om 22 25 01" src="https://github.com/dermotduffy/frigate-hass-card/assets/31592734/dd6fa90a-1416-48c6-bca3-7faa8c55bcbe">

This is the config I'm using now:

```
            - type: custom:frigate-card
              style: |
                ha-card {
                  height: 242px;
                  max-height: 242px; /* Set a maximum height for the card */

                  @media (max-width: 767px) {
                  height: 210px !important; /* Adjusted height for mobile */
                  max-height: 210px !important; /* Set a maximum height for the card */
                  } 
                }
              view_layout:
                grid-area: left2
              cameras:
                - camera_entity: camera.g4_doorbell_high
              dimensions:
                aspect_ratio: "4:4"
                aspect_ratio_mode: static
              menu:
                style: none
                buttons:
                  fullscreen:
                    enabled: false
              live:
                layout:
                  fit: cover
                controls:
                  next_previous:
                    style: none
                  thumbnails:
                    mode: none
                  builtin: false
                zoomable: false
                lazy_unload: all
              media_viewer:
                controls:
                  builtin: false
                title:
                  mode: none
              performance:
                style:
                  border_radius: true
              view:
                default: live
```

Oh, and by the way; 
I would like to have more rounded corners, but this seems impossible, is that true? 

Thanks for your reply!

**Comment by dermotduffy** [comment]
The card has a full visual editor, so you should be able to just play around with all the options. All bells and whistles can be disables. Looks like the config you're using should be  pretty close, here's a quick config that just shows live and nothing else:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    live_provider: go2rtc
menu:
  style: none
live:
  controls:
    builtin: false
    thumbnails:
      mode: none
    timeline:
      mode: none
    title:
      mode: none
```

What's left showing up if you use this config?

> I would like to have more rounded corners, but this seems impossible, is that true?

If your  HA theme uses rounded corners, the card should automatically respect that.
