### ISSUE TITLE
Expnd button not showing

### ISSUE THREAD

**Issue by therustyalex** [dermotduffy/frigate-hass-card#1318]
Running: HACS Frigate Card v4.0.0

When I experiment with adding / removing buttons under the menu section, I am not able to add the expand button, but all other buttons work.
```yaml
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.arlo_3
                live_provider: ha
            frigate:
              url: xxxx
            view:
              default: live
            menu:
              style: outside
              buttons:
                expand:
                  enabled: true
                frigate:
                  enabled: false
```
