### ISSUE TITLE
Two way audio only works off Wifi (Reolink POE Doorbell)

### ISSUE THREAD

**Issue by Pickman711** [dermotduffy/frigate-hass-card#1326]
I have been struggling to get my two way audio to work on my new doorbell. I have frigate configured with a minimal setup to get started.

Frigate is installed on docker in my unraid machine and HA is on my dell mini pc. Frigate has no errors and seems to be working fine.

I can get the two way audio to work when my phone is off wifi and doesn't work when connected. It was to my surprise since I figured I would have the opposite issue of it not working away from home.

The frigate card has what I think is a broken microphone symbol on wifi and goes red and works off of wifi.
![card](https://github.com/blakeblackshear/frigate-hass-integration/assets/102765544/381f9f65-3278-48e6-b460-6836cce189e0)

Here is my frigate yaml and card configuration. I'd appreciate any insight, thanks in advance.
```
mqtt:
  enabled: true
  host: 10.10.0.50
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: password
  stats_interval: 60

go2rtc:
  streams:
    doorbell:
      - rtsp://admin:password@10.10.30.13:554/h264Preview_01_main
      - ffmpeg:doorbell#audio=opus#audio=volume#audio=aac
    doorbell_sub:
      - rtsp://admin:password@10.10.30.13:554/h264Preview_01_sub
      - ffmpeg:doorbell_sub#audio=opus#audio=volume
  webrtc:
    candidates:
      - 10.10.0.100:8555
      - stun:8555
      
  ## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: doorbell_sub
      
    detect: 
      enabled: false
      width: 640
      height: 480
      fps: 5
    record:
      enabled: false
      retain: 
        days: 2 
        #mode: active_objects 
      events:
        retain:
          default: 5 
          mode: motion 
        pre_capture: 3 
        post_capture: 10
```
```
type: custom:frigate-card
cameras:
  - live_provider: go2rtc
    frigate: {}
    go2rtc:
      modes:
        - webrtc
    camera_entity: camera.doorbell
menu:
  style: overlay
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      type: toggle
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: true
    mute:
      enabled: true
live:
  microphone:
    always_connected: false
```
