### ISSUE TITLE
Enable mute / unmute mic button for live_provider: webrtc-card

### ISSUE THREAD

**Issue by eporsche** [dermotduffy/frigate-hass-card#1327]
I am not seeing the microphone unmute / mute button even when its enabled and two way audio works.
I am using this config:
```
...
live_provider: webrtc-card
    webrtc_card:
          url: webrtc_stream
          mode: webrtc
          media: microphone,audio,video
..
buttons:
        microphone:
          enabled: true
```
**Describe the solution you'd like**
I would like to see the microphone mute / unmute buttons

**Describe alternatives you've considered**
Using the webrtc card
