### ISSUE TITLE
Use webrtc-card with 3rd party webrtc server

### ISSUE THREAD

**Issue by t0ny-peng** [dermotduffy/frigate-hass-card#1330]
Love the work of Frigate card. Please forgive me if my question is not clear.

Basically, I'm running `Scrypted` on the same server of Frigate to stream cameras to HomeKit(the Homekit camera integration of HA has an annoying doorbell bug). Since `Scrypted` already provides a WebRTC server, I disabled the `go2rtc` server shipped with Frigate, and plan to stream from `Scrypted` WebRTC server directly to the browser.

Something that may help to understand:
- I am not using the [AlexxIT WebRTC](https://github.com/AlexxIT/WebRTC) integration, as it requires a `go2rtc` server
- I can open the `rtsp` stream provided by `Scrypted` WebRTC in VLC

My configuration is: (with unrelated part removed)
```yaml
type: custom:frigate-card
...
cameras:
  - camera_entity: camera.front_door
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://10.0.0.2:39735/1cb7b361dabc465f # This stream is working in VLC
    title: Front Door
    icon: mdi:door
    triggers:
      occupancy: true
```

The browser console reported this error, which is understandable since webrtc integration is not enabled.

```
https://<my domain>/webrtc/webrtc-camera.js?v2.3.1
```

**Describe the solution you'd like**

I wonder if it's possible to hose this json file somewhere else, and let Frigate card load it, then shows the RTSP stream provided by Scrypted rebroadcasting. Thanks!

**Describe alternatives you've considered**

The only alternative is to run `go2rtc` in Frigate, and use the `go2rtc` live provider.

**Additional context**

N/A
