### ISSUE TITLE
Remote acess whith go2rtc

### ISSUE THREAD

**Issue by joaopedros2** [dermotduffy/frigate-hass-card#1336]
I'm using the following configuration on the card to use the microphone, but unfortunately, when I access it outside my LAN network, the card doesn't work, I have no sound.
```
cameras:
  - camera_entity: camera.front_door
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
```

It only works if I have my VPN to my HA server active.

Is there anything I can do to work around this issue?

**Comment by felipecrs** [comment]
https://docs.frigate.video/configuration/live#webrtc-extra-configuration

_For external access, over the internet, setup your router to forward port 8555 to port 8555 on the Frigate device, for both TCP and UDP._

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!

**Comment by felipecrs** [comment]
Do you use cloudflare because your network is CGNAT? If so, opening ports won't do anything. :(

**Comment by joaopedros2** [comment]
> Do you use cloudflare because your network is CGNAT? If so, opening ports won't do anything. :(

I don't know if I am using CGNAT or not, but I am using Cloudflare to access my Home Assistant externally...

**Comment by felipecrs** [comment]
Access this website, what is the result?

https://tomchen.github.io/symmetric-nat-test/

![image](https://github.com/user-attachments/assets/ec9edfe3-c00e-451c-b52e-e31a393ab770)

If you are behind Symmetric NAT, your best bet is to use NGROK:

https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-ngrok

**Comment by joaopedros2** [comment]
I was testing my home network and found an issue with incorrect port configuration on the wrong router. I had to enable bridge mode on the ISP's router and open port 8555 for WebRTC on the TP-Link Deco router. I also tested for CGNAT, and it returned "Normal NAT".

Unfortunately, I don't have audio from the streaming, and I can't communicate via the microphone to the camera. From what I've read, 2-way audio only works through an 'https' link, but it's not working.
I'm using the TP-Link Tapo C210 cameras with firmware version 1.3.11.

![image](https://github.com/user-attachments/assets/0bc31ecf-c87d-485d-ac6e-05864fe1ff79)
![image](https://github.com/user-attachments/assets/fede4385-cc78-451a-aa4b-3ca3dd460aa9)

___
Here is how I have the Frigate card configured.
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam_fg_quarto_lourenco
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
live:
  auto_unmute:
    - visible
    - selected
    - microphone
  auto_play:
    - selected
    - visible
  controls:
    builtin: false
    thumbnails:
      mode: none
    ptz:
      hide_zoom: true
      hide_home: true
      hide_pan_tilt: true
  preload: true
  lazy_unload:
    - unselected
    - hidden
  draggable: false
  zoomable: true
status_bar:
  style: none
menu:
  style: hover-card
  position: top
  alignment: top
  buttons:
    mute:
      enabled: true
      alignment: opposing
      priority: 4
    microphone:
      enabled: true
      alignment: opposing
      priority: 3
      type: toggle
    media_player:
      alignment: opposing
      priority: 2
    fullscreen:
      alignment: opposing
      priority: 1
    cameras:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    timeline:
      enabled: false
    frigate:
      enabled: false
    live:
      enabled: false
performance:
  style:
    box_shadow: false
```

Here is how I have the Frigate camera configuration.
```
# Restream configuration
go2rtc:
  webrtc:
    candidates:
      - localhost:8555
      - stun:8555
  streams:
    cam_fg_quarto_lourenco:
      - ffmpeg:rtsp://user:pw@192.168.X.XXX:554/stream1#video=copy#audio=aac
      - tapo://admin:PW-SHA-256@192.168.X.XXX
```
