### ISSUE TITLE
Add support for condition to detect companion app

### ISSUE THREAD

**Issue by PovilasID** [dermotduffy/frigate-hass-card#1339]
**Is your feature request related to a problem? Please describe.**
When you get a notification and want to do a quick check on mobile app switching over to SD stream is a little annoying and takes a bit of time.

**Describe the solution you'd like**
Ability to set a sub stream to be default for companion app and for web browser.

**Describe alternatives you've considered**
Two different dashboards. One with HD stream and other one has low resolution stream as default that is default for mobile app  two different almost identical dashboards looks a little redundant.

**Additional context**
Mobile app's small screen does not need to display a full resolution image and if it is on mobile connection sometimes can not do that without lag that prevents from being able to evaluate the situation. While on desktop there is almost no need to look at low resolution image, hence separate default's makes sense

**Comment by dermotduffy** [comment]
You can (kind of) do this already by using the screen resolution. Below example uses the new `v6` beta releases:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    dependencies:
      cameras:
        - camera.hall
  - camera_entity: camera.hall
    title: Office HD
    capabilities:
      disable_except:
        - substream
overrides:
  - conditions:
      - condition: screen
        media_query: '(max-width: 500px)'
    set:
      cameras:
        - camera_entity: camera.hall
          id: camera.office
```

In this silly example, if the resolution of the device is less than `500px` across, the camera is substituted for a different one.  

However, it might be nicer to have a condition that indicates whether or not the card is rendered in the companion app, or perhaps which browser, etc. Will repurpose this issue for that.
