### ISSUE TITLE
Card stream uses Detect (low quality) substream.

### ISSUE THREAD

**Issue by joshwillcock** [dermotduffy/frigate-hass-card#1341]
**Checklist:**

- [Y ] I updated to the latest version available
- [Y ] I cleared the cache of my browser

**Release with the issue:**
V5.20

**Last working release (if known):**

**Browser and Operating System:**
Chrome/Safari Mac/Windows

**Description of problem:**

Having setup a main stream (101) and substream (102) in Frigate with 101 for RTMP & Record and 101 for Detect, the Detect feed is the only one which appears within the Frigate-hass-card.

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.10.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "date": "2024-01-07T22:07:34.095Z",
  "frigate_version": {
    "11e11d2f72a65f47a5134d59cceb098d": "4.0.1/0.12.1-367d724"
  },
  "lang": "en_GB",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.driveway_camera",
        "live_provider": "auto",
        "title": "Driveway Cam"
      }
    ],
    "performance": {
      "style": {
        "border_radius": true,
        "box_shadow": false
      },
      "features": {
        "animated_progress_indicator": true
      },
      "profile": "high"
    },
    "timeline": {
      "style": "stack",
      "media": "all"
    },
    "image": {},
    "live": {
      "preload": true,
      "zoomable": true,
      "show_image_during_load": false
    },
    "view": {
      "default": "live",
      "camera_select": "live",
      "dark_mode": "auto"
    },
    "menu": {
      "style": "overlay",
      "button_size": 44,
      "position": "bottom",
      "alignment": "bottom",
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "live": {
          "enabled": true
        },
        "camera_ui": {
          "enabled": false
        },
        "expand": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "recordings": {
          "enabled": false
        },
        "download": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        }
      }
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
Frigate Config Extract:
```
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/porchcam_substream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_stream
          roles:
            - rtmp
            - record
```
