### ISSUE TITLE
2-way audio issue (Requested device not found)

### ISSUE THREAD

**Issue by hohaha045** [dermotduffy/frigate-hass-card#1342]
I've been getting the 2-way audio to work for a while but still can't really figure it out.
My frigate (13 beta 6)is installed in DSM7, and HA on a thin client, same network.

the frigate config:

```
mqtt:
  enabled: True
  host: 192.168.1.29
  port: 1883
  user: mqtt
  password: mqttpassword

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    Guardian:
      - rtsp://password@192.168.1.10:554/stream1
      - "ffmpeg:Guardian#audio=opus"


cameras:
  Guardian: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://password@192.168.1.10:554/stream2 # <----- The stream you want to use for detection
          roles:
            - detect
            - audio
        - path: rtsp://password@192.168.1.10:554/stream1 # <----- The stream you want to use for record
          roles:
            - record
      #hwaccel_args: preset-vaapi
      output_args:
        #record: preset-record-generic-audio-copy
        record: preset-record-generic-audio-aac
        - cat
        - purr
        - meow
        - hiss
    record:
      enabled: True
    snapshots:
       enabled: True
```

The issue I am facing is the microphone icon became 
![Screenshot 2024-01-13 at 12 12 03 PM](https://github.com/dermotduffy/frigate-hass-card/assets/53906339/ecb39f35-7f5d-4247-92e8-492e043ee7d5)

when I press it. 

So I found this post: https://github.com/dermotduffy/frigate-hass-card/issues/1230#issuecomment-1644920156
"Aha! I think your Home Assistant URL is forbidden from accessing your microphone (I only used that icon for exactly this case!)."

and looking at the Chrome console and see:

```

DOMExcetpion: Requested device not found

Nf	@	card-555679fd.js:75
connect @ card-555679fd.js:507
await in connect (async)
_initializeMicrophone @ card-555679fd.js:507 
_cardActionHandler @ card-555679fd.js:507 
_cardActionEventHandler @ card-555679fd.js:507 
l @ card-555679fd.js:1 
h @ card-555679fd.js:1 
fm @ card-555679fd.js:75 
pm @ card-555679fd.js:75 
_actionHandler @ card-555679fd.js:194 
(anonymous) @ card-555679fd.js:212 
handleEvent @ card-555679fd.js:17 
l @ card-555679fd.js:1 
n @ card-555679fd.js:75

```

![Screenshot 2024-01-13 at 12 31 16 PM](https://github.com/dermotduffy/frigate-hass-card/assets/53906339/677e15af-7b85-4aa1-9c70-0cb624ef51b6)

I've checked the chrome permission and tried using the HA apps but still not working.

![Screenshot 2024-01-13 at 12 19 43 PM](https://github.com/dermotduffy/frigate-hass-card/assets/53906339/447843b6-d05d-447c-950c-06985fa86fcd)

Any advice or something else I could try to get it work?
Thank you
