### ISSUE TITLE
Video Scrubbing not seemingly functional

### ISSUE THREAD

**Issue by bcamp929** [dermotduffy/frigate-hass-card#1348]
A feature added in v5.0.0 was video scrubbing. I have not seen anything that indicates the feature has been removed. I also have not seen any information as to how to get this setup properly. Somewhere along the line of my searching, i found that i needed to add:

features:
   - scrubbing: true
   
...to my camera config, which i did. Scrubbing is not working. Is there any documentation regarding this, or can assistance be given to getting this working? I realize this may be a stretch as to being an "issue", but I am not sure where else to turn for support with this. So, I apologize in advance. I guess the issue is that this either doesn't work, or it does work and there is no obvious way to get it working.

**Comment by dermotduffy** [comment]
Please provide your configuration and I'll take a look.

**Comment by bcamp929** [comment]
Here is my current config. Thank you!

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.familyroom
    live_provider: go2rtc
    title: Family Room
    frigate: {}
    image: {}
    triggers:
      motion: false
      occupancy: true
media_viewer:
  controls:
    timeline:
      clustering_threshold: 2
      media: clips
      show_recordings: false
  auto_unmute: all
  auto_play: all
  auto_pause: never
live:
  preload: true
  auto_play: all
  auto_unmute: all
  transition_effect: slide
  controls:
    timeline:
      style: ribbon
      mode: below
      media: clips
      show_recordings: false
    next_previous: {}
    builtin: true
  layout:
    fit: fill
  microphone:
    always_connected: false
view:
  default: live
  camera_select: live
  scan:
    enabled: false
  timeout_seconds: 15
dimensions:
  aspect_ratio_mode: unconstrained
  aspect_ratio: '16:9'
timeline:
  style: ribbon
  media: clips
  show_recordings: false
menu:
  buttons:
    mute:
      enabled: true
    play:
      enabled: true
    microphone:
      enabled: true
    cameras:
      enabled: false
    substreams:
      enabled: false
    snapshots:
      enabled: false
    expand:
      enabled: true
    clips:
      enabled: false
    screenshot:
      enabled: true
  style: hidden
  position: top
performance: {}
features:
  scrubbing: true

```

**Comment by dermotduffy** [comment]
You need to enable the timeline in the media viewer when you're viewing media you want to scrub, like this:

```
media_viewer:
  controls:
    timeline:
      mode: below
```

PS: This does nothing:

```
features:
  scrubbing: true
```
