### ISSUE TITLE
Setting live builtin controls to none does not hide playback controls when using card in custom:layout-card grid

### ISSUE THREAD

**Issue by skykingjwc** [dermotduffy/frigate-hass-card#1350]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
Unknown.  This i a new install.
**Browser and Operating System:**
Chrome (latest), Windows 10 and Android

**Description of problem:**
When using card in a custom view, the option to hide the playback controls does not seem to work.  I set the configuration using the GUI, then cut and pasted the code from the GUI code editor into my config file.  The card itself works, and most of the styles options work (such as letterbox mode) however no matter what I try the playback controls always show.

```
type: custom:layout-card
layout_type: grid #custom:grid-layout

layout:
  grid-template-columns: "55px repeat(9, 85px) 55px"
  grid-template-rows: "170px 38px repeat(5, 70px) 38px 80px 90px"

cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.seccam1
    view:
      default: live
    menu:
      buttons:
        frigate:
          enabled: false
        live:
          enabled: false
        cameras:
          enabled: false
      style: none
    performance:
      style:
        box_shadow: false
        border_radius: false
    timeline:
      show_recordings: false
    live:
      layout:
        fit: contain
      controls:
        title:
          mode: none
        timeline:
          mode: none
          show_recordings: false
        builtin: false     # <----  this should hide the playback controls
      show_image_during_load: false
      zoomable: false
      draggable: false
      transition_effect: none
      preload: true
    image: {}
    media_viewer:
      controls:
        builtin: false
    media_gallery:
      controls:
        filter:
          mode: none
    view_layout:
      grid-column: 2 / span 9
      grid-row: 2 / span 8
```

**Frigate card diagnostic information**
```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.12.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "date": "2024-01-27T19:33:25.373Z",
  "frigate_version": {
    "4eff6429f813f0f9380546aa7787b162": "4.0.1/0.12.1-367d724"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.seccam1"
      }
    ],
    "view": {
      "default": "live"
    },
    "menu": {
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "live": {
          "enabled": false
        },
        "cameras": {
          "enabled": false
        }
      },
      "style": "overlay"
    },
    "performance": {
      "style": {
        "box_shadow": false,
        "border_radius": false
      }
    },
    "timeline": {
      "show_recordings": false
    },
    "live": {
      "layout": {
        "fit": "contain"
      },
      "controls": {
        "title": {
          "mode": "none"
        },
        "timeline": {
          "mode": "none",
          "show_recordings": false
        },
        "builtin": false
      },
      "show_image_during_load": false,
      "zoomable": false,
      "draggable": false,
      "transition_effect": "none",
      "preload": true
    },
    "image": {},
    "media_viewer": {
      "controls": {
        "builtin": false
      }
    },
    "media_gallery": {
      "controls": {
        "filter": {
          "mode": "none"
        }
      }
    },
    "view_layout": {
      "grid-column": "2 / span 9",
      "grid-row": "2 / span 8"
    },
    "card_mod": {
      "style": "ha-card {\n  background-color: black;\n  border-radius: 0px;\n}\n"
    }
  }
}
Your dashboard was updated. Refresh to see changes?
Your dashboard was updated. Refresh to see changes?
```

**Javascript errors shown in the web inspector (if applicable):**
No errors found in debug console

**Additional information:**
