### ISSUE TITLE
Add support for a `delay` action

### ISSUE THREAD

**Issue by pergolafabio** [dermotduffy/frigate-hass-card#1355]
**Is your feature request related to a problem? Please describe.**
Hi, we are using the card for door intercom purposes, on a real incoming call, we need to send a service to the intercom, to make the speaker idle, afterwards we can start the two way audio, but between the 2 services, we need a delay function... 

Here is an example what we do with the card:

```
              icon: mdi:phone
              tap_action:
                - action: call-service
                  service: button.press
                  data:
                    entity_id: xxx
                - action: call-service
                  service: button.press
                  data:
                    entity_id: xxxx
```
What i want to archive is this:

```
              icon: mdi:phone
              tap_action:
                - action: call-service
                  service: button.press
                  data:
                    entity_id: xxx
                - action: call-service
                  delay: 1
                - action: call-service
                  service: button.press
                  data:
                    entity_id: xxxx
```

Is this somehow possible with this card? i couldnt find the right syntax...

An alternative way is to call a script instead, but it would be nicer if we could to it in the card

Thnx for the feedback!
