### ISSUE TITLE
2-way audio does not work with certain Hikvision cameras

### ISSUE THREAD

**Issue by pergolafabio** [dermotduffy/frigate-hass-card#1356]
**Checklist:**
- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** 
Specific PR release: https://github.com/dermotduffy/frigate-hass-card/pull/1291
But it also happens with 5.2.0 and Frigate addon 

**Last working release (if known):** Unknown
**Browser and Operating System:**
This happens on all browsers mac/chrome/companion app

**Description of problem:**

Using the config below, two way audio works, toggling the MIC button on/off again, always stops/starts the two way audio...
But the camera is also a doorbell, when a call is received, we need to first mute the call, by sending a service to it, to make the ringing sound stop, afterwards we press the mic button to start talking... so far so good.. Then i press the mic button to stop the audio, this also works... Next on the second call, we do the same thing, we send the service to the doorbell to stop the ringing, but the when we press the MIC button, the two way audio isnt initiated... this is my issue
What we need todo, is to refresh the page where the frigate card is located, after the refresh, when we then press again the MIC button, it seems to work....

I dont know why, or whats the cause, or why i need to refresh the page?

frigate card config:

```
        - type: custom:frigate-card
          cameras:
            - camera_entity: camera.deurbel
              live_provider: go2rtc
              go2rtc:
                url: https://user:pass@go2rtc.mydomai:8123
                stream: deurbel
                modes:
                  - webrtc
                  ......
```

go2rtc config:

```
streams:
  deurbel:
    - rtsp://user:xxx@192.168.0.14:554/Sms=24.unicast
    - isapi://user:xxx@192.168.0.70:80/
```

I also checked the go2rtc addon logs, no isses there... so not sure if its go2rtc or frigate card related, difficult to tell..
What is happening on a refresh of the view? whats different between a refresh of the view and toggling the mic button?

What i also see, when you do a refresh of the page, the mic button is not immediately visible, it takes a second, and then its there... Is there maybe a way to force that refresh? That could maybe solve my issue, alltough still dont know the root cause...

Edit:

My guess, go2rtc is using ISAPI to use two way audio on hikvision camera's, I think the audio session is not closed when pressing the mute button? When refreshing the page it starts a new two way audio session? The audio session is always open, regardless the mic button is muted or not??
That way, on an incoming call the audio session is closed, bur frigate thinks it's still open?

**Comment by Daz42** [comment]
Just to add to the above (I've been working with @pergolafabio, I have a Hikvision Doorbell and Internal Intercom. I am using the Frigate add-on, Frigate Integration and Hass card to use the camera, speaker and microphone from the Hikvision Doorbell. When using this all through the Frigate Hass card, it all initially works well and I get 2 way audio.

However, when I take the following steps things go wrong:

1. Checked that 2 way audio working
2. Press doorbell button
3. Pressed the HA entity indoor button for answer call (Hikvision Doorbell Entity)
4. Pressed the HA entity indoor button for hangup call (Hikvision Doorbell Entity)
5. 2 way audio not working anymore
6. Restarted Frigate / reload Hass card
7. 2 way audio back again

I'm happy to do any testing.

**Comment by pergolafabio** [comment]
a quick update, i tested the WebRTC card to rule out go2rtc, and that card works reliable
everytime i click the mute/unmute icon to switch streams, it works

is it maybe possible to compare the mic button from frigate to  behave also like the webrtc card?


![image](https://github.com/dermotduffy/frigate-hass-card/assets/43251136/45e77e22-2fb2-4a52-b22f-8cdfd0d23d17)

**Comment by dermotduffy** [comment]
> My guess, go2rtc is using ISAPI to use two way audio on hikvision camera's, I think the audio session is not closed when pressing the mute button?

Correct.

> When refreshing the page it starts a new two way audio session? The audio session is always open, regardless the mic button is muted or not??

Unless you use the `always_connected` option, the stream will be converted to a 2-way session the first time the microphone is unmuted. It will automatically disconnect (convert back to without 2-way audio) after `disconnect_seconds` have elapsed.

> Next on the second call, we do the same thing, we send the service to the doorbell to stop the ringing, but the when we press the MIC button, the two way audio isnt initiated... this is my issue

So it all works fine, until to call an unrelated service and then the microphone unmute doesn't work anymore? How are you calling the unrelated service? Can you provide your full card config? 

Thank you!

**Comment by pergolafabio** [comment]
Hey , thnx for feedback already, appreciate it! Below full config
As you can see, im using the dev card version, where i can point to camera without frigate addon/integration

As you can see, i have extra 2 buttons ( see also screenshot) a phone / hangup button
That phone buttons calls a script, so that when someone is actually pressing the doorbell button, i need to stop the ringing and afterwards inittiate the two way audio

But i also see this new PF :  https://github.com/dermotduffy/frigate-hass-card/pull/1359
That means i can combine the answer + mic button into one, thnx already for that, will test that out later!

But anyway, back to issue, you are talking about always_connected ,  i tried it with true/false, but ddint make any difference... But i wasnt aware of the disconnect_seconds!! I was always testing making calls after each other, within the 60 seconds

What is the best approach for this? probably setting this back to "false" , so that means, on incoming call, if i wait longer then 60 seconds for next call , it should work? What happens if the stream is active? I mean if the lovelave card is active? Does it trigger the 60 sec disconnected? Or does it only disconnect if i browse away from the page?

That being said, maybe that new PR could be helpfull with the automation? Can i define for example, if press the hangup button or if i toggle again the mic button, that i force the disconnect?


But whats still strange, i dont know if the disonnect_seconds will solve it... When the issue occured, i could toggle the mic button as many times if i want, it never worked again sending two way audio, untill i did a refresh of the lovelace card... 
Shouldnt toggling the mic button , disconnect any open audio sessions anway?

```
        - type: custom:frigate-card
          cameras:
            - camera_entity: camera.deurbel
              live_provider: go2rtc
              go2rtc:
                url: https://user:pass@go2rtc.mydomain:8123
                stream: deurbel
          menu:
            style: outside
            position: bottom
            buttons:
              microphone:
                enabled: true
                type: toggle
              screenshot:
                enabled: false
              download:
                enabled: false
              fullscreen:
                enabled: false
              snapshots:
                enabled: false
              timeline:
                enabled: false
              media_player:
                enabled: false
              clips:
                enabled: false
              live:
                enabled: false
              cameras:
                enabled: false
              frigate:
                enabled: false
              camera_ui:
                enabled: false
          live:
            microphone:
              always_connected: true
            auto_mute: []
            auto_unmute: []
            controls:
              builtin: true
              title:
                mode: none
            layout:
              fit: fill
          elements:
            - type: custom:frigate-card-menu-icon
              icon: mdi:volume-high
              tap_action:
                - action: custom:frigate-card-action
                  frigate_card_action: unmute
            - type: custom:frigate-card-menu-icon
              icon: mdi:volume-off
              tap_action:
                - action: custom:frigate-card-action
                  frigate_card_action: mute
            - type: custom:frigate-card-menu-icon
              icon: mdi:phone
              tap_action:
                - action: call-service
                  service: script.answer_call
                - action: custom:frigate-card-action
                  frigate_card_action: unmute
                - action: custom:frigate-card-action
                  frigate_card_action: microphone_unmute
            - type: custom:frigate-card-menu-icon
              icon: mdi:phone-hangup
              tap_action:
                - action: custom:frigate-card-action
                  frigate_card_action: microphone_mute
            - type: custom:frigate-card-menu-icon
              icon: mdi:door-open
              hold_action:
                - action: call-service
                  service: switch.turn_on
                  data:
                    entity_id: switch.ds_kd8003_door_relay_0
          dimensions:
            aspect_ratio_mode: static
            aspect_ratio: '16:9'
```

![image](https://github.com/dermotduffy/frigate-hass-card/assets/43251136/69087cf1-d3c1-4736-b4c7-c726532e108e)

**Comment by pergolafabio** [comment]
For quick testing, i changed my card to this setting:

```
          live:
            microphone:
              always_connected: false
              disconnect_seconds: 15
```

Indeed after 15 sec, the mic is disconnected, i can turn on mic and speak again, so that setting is working

However , my issue is still present, if i have a real call coming in, i drop the doorbell sound, but then i enable mic, but i cant speak... if i then wait 15 sec, the mic is off, i turn it on again, i still cant speak

The only solution, is to browse away from the lovelace card or a a refresh of the page, then i can speak again

There must be something different in refreshing the page and the disconnect feature, i think the dsconnect feature doesnt disconnect enough? Whats the difference between your disconnect feature and refreshing the page?
