### ISSUE TITLE
FR:  Option for Most Recent Snapshot/Clip to include *all* cameras selected rather than first in the list

### ISSUE THREAD

**Issue by Codelica** [dermotduffy/frigate-hass-card#1357]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to quickly see the latest events/snapshots for all of my "outdoor perimeter" cameras -- which are a subset of all the cameras I have installed.

**Describe the solution you'd like**
Basically I'd like a view using the "Most Recent Snapshots" option that includes *all the cameras* selected,  rather than showing them individually by camera and requiring manual selection.

**Describe alternatives you've considered**
One card for each outdoor perimeter camera.

**Additional context**
Sorry if this isn't clear or there is a way to configure it currently, but I just have a card with all the camera I'm interested in selected and there doesn't seem to be a way for that view to just include all the snapshots in the view, rather than it just starting with that first camera.

**Comment by dermotduffy** [comment]
> I'd like to be able to quickly see the latest events/snapshots for all of my "outdoor perimeter" cameras -- which are a subset of all the cameras I have installed.

This is pretty much the exact usecase for camera dependencies. Try something like this:

```
[...]
cameras:
  - camera_entity: camera.outdoor1
    dependencies:
      cameras:
        - camera.outdoor2
        - camera.outdoor3
  - camera_entity: camera.outdoor2
  - camera_entity: camera.outdoor3
[...]
```

When you view the events for `camera.outdoor1`, it should include the events for the other named cameras also.
