### ISSUE TITLE
First clip doesn't load

### ISSUE THREAD

**Issue by woempiej** [dermotduffy/frigate-hass-card#1368]
Hi,

I'm using the Frigate Lovelace card. Since the latest update the Lovelace card doesn't show the 1st (latest) video anymore.
I'm using the card in the "most recent clip" view.

![afbeelding](https://github.com/dermotduffy/frigate-hass-card/assets/62903344/0f12c1a6-d636-4918-acf5-d861f104a9d7)

I need to
Android HA app:
Swipe to the previous video and then swipe back to the newest video to be able to watch the newest video.
Firefox browser:
Navigate to another dashboard tab and go back to my "security" tab to be able to watch the newest video.
or
Choose to edit the HA dashboard > Then it showes the video correctly
Chrome browser:
Navigate to another dashboard tab and go back to my "security" tab to be able to watch the newest video.
or
Choose to edit the HA dashboard > Then it showes the video correctly

I did think about the browser cache and history wipe.

No error(s) logs in the HA log
No error(s) in the Frigate log

Yesterday I rebuild all of the Frigate installation:
Deleted HA add-on
Deleted HA integration > Wich the Lovelace card is comming from
Deleted all Frigate related files via the file editor
Deleted all Media
Media > Frigate (Integration folder)
Media > My Media > frigate (Add-On folder)

Deleted the Lovelace card and builded it back up via the GUI

```yaml
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.frigate_cam1
      - camera_entity: camera.frigate_cam2
      - camera_entity: camera.frigate_cam3
    view:
      default: clip
      update_force: true
      scan:
        show_trigger_status: true
    menu:
      style: outside
      buttons:
        media_player:
          enabled: false
        timeline:
          enabled: false
        live:
          enabled: false
        snapshots:
          enabled: false
    media_viewer:
      controls:
        title:
          mode: none
        thumbnails:
          mode: none
        timeline:
          mode: below
          window_seconds: 28800
    media_gallery:
      controls:
        thumbnails:
          show_favorite_control: false
          show_timeline_control: false
          show_download_control: false
        filter:
          mode: none
```
