### ISSUE TITLE
Intersection option in go2rtc/webrtc camera is not respected

### ISSUE THREAD

**Issue by widewing** [dermotduffy/frigate-hass-card#1376]
When I use webrtc camera card alone, the video stream will stop when the card is outside of screen. 
In Webrtc Camera card there is an option
```
intersection: 0.75  # auto stop stream when less than 75% of video element is in the screen, 50% by default
```
But when using this card with go2rtc live stream, it will always stream even out of screen. This is particularly annoying when have a lot camera and using mobile app or page.

**Comment by dermotduffy** [comment]
Can you include your config?

**Comment by widewing** [comment]
The setting is pretty simply frigate-card with live_provider=webrtc-card, and 10 cards in one page.
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_door
    live_provider: webrtc-card
    webrtc_card:
      type: custom:webrtc-camera
      url: front_door
      server: http://localhost/go2rtc/
      muted: true
      digital_ptz:
        persist: false
```
I realize when the page load all the feeds will load, but when I scroll up/down the hided cards will pause and when they become visible they will reload.
