### ISSUE TITLE
Question: Hide Side-Drawer Gallery Button

### ISSUE THREAD

**Issue by ncodee** [dermotduffy/frigate-hass-card#1377]
Hi, I've gone through the card settings but can't find anything related to toggling off the side-drawer that popups as an fixed overlay on the frigate card. I already have a dedicated button to access the gallery, so it makes it rather redundant.

How do I go about turning this off? Thanks

![Frigate Hass Thumbnails](https://github.com/dermotduffy/frigate-hass-card/assets/52791179/84ece7c8-c960-4cd6-897f-e610b1077d28)

**Comment by dermotduffy** [comment]
I think you mean you want to hide the thumbnail carousel in the live view and possibly the media viewer:

```yaml
[...]
live:
  controls:
    thumbnails:
      mode: none
media_viewer:
  controls:
    thumbnails:
      mode: none
```
