### ISSUE TITLE
Microphone button not showing

### ISSUE THREAD

**Issue by lorenzomartini1** [dermotduffy/frigate-hass-card#1380]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v5.2.0

**Last working release (if known):**
na

**Browser and Operating System:**
Google Chrome on Windows 10

**Description of problem:**
![image](https://github.com/dermotduffy/frigate-hass-card/assets/35630216/6e848d3b-94fe-4c55-9dac-f9481d287e27)

Sometimes the microphone icon is not showing, and sometimes it show up after 10/15 seconds.

**Frigate card diagnostic information**

```json
{
  "ha_version": "2024.2.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "date": "2024-02-26T13:54:48.223Z",
  "frigate_version": {
    "1b22592cf8c1b00bdb246e8c93d2f54b": "4.0.1/0.13.0-7c629c1"
  },
  "lang": "it",
  "timezone": "Europe/Rome",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.cam_gatto",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ]
        }
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true,
          "alignment": "opposing"
        },
        "timeline": {
          "enabled": false
        },
        "cameras": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        },
        "download": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        },
        "mute": {
          "enabled": true,
          "alignment": "opposing"
        },
        "camera_ui": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "clips": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        }
      },
      "style": "outside",
      "position": "top",
      "alignment": "top"
    },
    "live": {
      "controls": {
        "thumbnails": {
          "mode": "none"
        }
      },
      "auto_mute": "all",
      "preload": true,
      "microphone": {
        "always_connected": true
      }
    },
    "dimensions": {},
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "size": 140,
          "show_favorite_control": false,
          "show_timeline_control": false,
          "show_download_control": false
        },
        "filter": {
          "mode": "none"
        }
      }
    },
    "elements": [
      {
        "type": "custom:frigate-card-ptz",
        "style": {
          "right": "0%",
          "top": "82%"
        },
        "service": "button.press",
        "data_left": {
          "entity_id": "button.camera_di_lore_move_left"
        },
        "data_right": {
          "entity_id": "button.camera_di_lore_move_right"
        },
        "data_up": {
          "entity_id": "button.camera_di_lore_move_up"
        },
        "data_down": {
          "entity_id": "button.camera_di_lore_move_down"
        }
      }
    ]
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```
```
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://ha.smarthome.mrtsolutions.it/config/www/community/lovelace-card-mod/card-mod.js
```
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-select" has already been used with this registry
```
```
logging-mixin.ts:57 Failure writing uncaught error to system log: Error: Cannot parse given Error object
    at Object.parse (error-stack-parser.js:35:23)
    at stacktrace.js:106:62
    at new Promise (<anonymous>)
    at fromError (stacktrace.js:105:20)
    at t (log-message.ts:37:31)
    at logging-mixin.ts:45:33
```

**Additional information:**

**Comment by dermotduffy** [comment]
Your WebRTC stream probably isn't loading correctly. If the video feed looks like it's updating at about 1 FPS, this is because the card is showing you stills while it waits for the stream to load. The button will appear when the stream is loaded. This is usually a networking or configuration issue.

Example comparison issue: https://github.com/dermotduffy/frigate-hass-card/issues/1375#issuecomment-1952594207

**Comment by lorenzomartini1** [comment]
> Your WebRTC stream probably isn't loading correctly. If the video feed looks like it's updating at about 1 FPS, this is because the card is showing you stills while it waits for the stream to load. The button will appear when the stream is loaded. This is usually a networking or configuration issue.
> 
> Example comparison issue: [#1375 (comment)](https://github.com/dermotduffy/frigate-hass-card/issues/1375#issuecomment-1952594207)

ok thank you for the response... but why on Tapo app it is always working? What does it depends on?

My Frigate config:
```
go2rtc:
  streams:
    cam_gatto:
      - rtsp://<localuser>:<localpw>@<ip>:554/stream1
      - tapo://admin:<cloud sha256 pw>@<ip>
  candidates:
      - <frigate lan ip 192.168.x.x>:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
```
and
```
cameras:
  cam_gatto:
    record:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_gatto?video=copy&audio=aac
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    onvif:
      host: <camip>
      port: 2020
      user: xxxxx
      password: xxxx
      
    birdseye:
      enabled: False
```

should I change something? I have other 3 Reolink IP Camera in Frigate and they work correctly
