### ISSUE TITLE
API error whilst retrieving events for camera

### ISSUE THREAD

**Issue by btrudgill** [dermotduffy/frigate-hass-card#1382]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.2.0
**Last working release (if known):**

**Browser and Operating System:**
Firefox, home assistant mobile app (ios and android).

**Description of problem:**

Probably 50% of the time when I check my cameras, the events do not load (the side tab thing does not show up) and after a few seconds I get the error message shown below.

Frigate version: 0.13.2-6476f8a

**Frigate card diagnostic information**
This is the error I am getting on the card when the events fail to load:
```json
{
  "request": {
    "type": "frigate/events/get",
    "instance_id": "frigate",
    "cameras": [
      "doorbell"
    ],
    "limit": 50,
    "id": 48
  },
  "response": {
    "code": "frigate_error",
    "message": "API error whilst retrieving events for cameras ['doorbell'] for Frigate instance frigate"
  }
}
```

```json
{
  "ha_version": "2024.2.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0",
  "date": "2024-02-27T09:19:49.056Z",
  "frigate_version": {
    "47ac916ca5d1661b5fe5f01f9e5360dd": "5.0.1/0.13.2-6476f8a"
  },
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "doorbell_main"
        },
        "camera_entity": "camera.doorbell"
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true,
          "priority": 100,
          "type": "toggle"
        },
        "download": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        },
        "mute": {
          "enabled": true,
          "priority": 85
        },
        "media_player": {
          "enabled": false
        },
        "fullscreen": {
          "priority": 34
        }
      },
      "style": "hidden"
    },
    "live": {
      "controls": {
        "builtin": false
      }
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Frigate config included in case it is useful.
```
mqtt:
  host: 192.168.1.239
  port: 1883
  user: user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 31
    mode: all
  events:
    retain:
      default: 31
      mode: active_objects

snapshots:
  enabled: True

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: false

go2rtc:
  streams:
    doorbell_main:
      - "ffmpeg:http://192.168.1.132/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#video=copy#audio=copy#audio=opus"
      - rtsp://user:pass@192.168.1.132:554/h264Preview_01_main
    doorbell_sub:
      - "ffmpeg:http://192.168.1.132/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass"
    rear_main:
      - rtsp://user:pass@192.168.1.210:554/h264Preview_01_main
    rear_sub:
      - rtsp://user:pass@192.168.1.210:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.1.61:8555
      - stun:8555
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 896
      height: 672
      fps: 5
      enabled: true
    objects:
      track:
      - person
      - dog
      - cat
    motion:
      mask: 
        - 896,0,896,169,896,267,660,296,547,233,470,255,377,244,237,230,97,230,0,253,0,0
        - 0,672,425,672,425,630,0,631

  rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_main?video=copy&audio=opus
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true
    objects:
      track:
      - person
      - dog
      - cat
    motion:
      mask: 
        - 0,360,225,360,224,334,129,338,140,206,124,125,255,0,0,0
        - 296,360,640,360,640,0,367,0,490,67,513,315
```
