### ISSUE TITLE
The parameter timeout_seconds is not being respected all the time

### ISSUE THREAD

**Issue by Daniel-dev22** [dermotduffy/frigate-hass-card#1386]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
5.2.0
**Last working release (if known):**
N/A
**Browser and Operating System:**
Android companion app android 14 Samsung Galaxy S24 ultra.

**Description of problem:**

Sometimes frigate card switches from the focused camera back to the first camera in the list which I learned is the default view. I added `timeout_seconds` in the hopes that would stop it and it definitely seems to have helped but sometimes I notice it go back to default view within less than 1 minute.

```
view:
  timeout_seconds: 0
```
**Frigate card diagnostic information**

```json
{
  "ha_version": "2024.2.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Linux; Android 14; SM-S928U1 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36 Home Assistant/2024.1.5-12102 (Android 14; SM-S928U1)",
  "date": "2024-02-24T20:21:47.500Z",
  "frigate_version": {
    "121894675fc2447d4c58c7cbe23d8009": "5.0.1/0.14.0-74a8fee"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.garage"
      }
    ]
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
 Card yaml

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#cameras'
    name: Cameras
    icon: mdi:cctv
    margin_top_mobile: 0px
    margin_top_desktop: 28px
    width_desktop: 75%
  - type: custom:frigate-card
    card_id: popup
    cameras_global:
      live_provider: go2rtc
      go2rtc:
        modes:
          - mse
      frigate:
        labels:
          - person
    cameras:
      - camera_entity: camera.doorbell
      - camera_entity: camera.outdoor_1
      - camera_entity: camera.outdoor_2
      - camera_entity: camera.outdoor_3
      - camera_entity: camera.outdoor_4
      - camera_entity: camera.outdoor_5
      - camera_entity: camera.outdoor_6
      - camera_entity: camera.outdoor_7
      - camera_entity: camera.outdoor_8
      - camera_entity: camera.outdoor_9
      - camera_entity: camera.garage
      - camera_entity: camera.front_door_area
      - camera_entity: camera.dining_room_area
      - camera_entity: camera.laundry_room
      - camera_entity: camera.lower_level_walkway
    live:
      lazy_unload: hidden
      auto_play: all
      auto_mute: all
      auto_unmute: never
      controls:
        title:
          mode: none
        thumbnails:
          mode: below
          media: snapshots
          show_details: false
        builtin: false
        next_previous:
          style: none
      zoomable: true
      draggable: false
      auto_pause: all
      transition_effect: none
      display:
        mode: grid
    media_viewer:
      snapshot_click_plays_clip: true
      auto_unmute: selected
      controls:
        builtin: false
        title:
          mode: none
        thumbnails:
          mode: none
        next_previous:
          style: none
    view:
      timeout_seconds: 0
    menu:
      style: outside
      position: bottom
      button_size: 45
      buttons:
        frigate:
          enabled: false
        snapshots:
          enabled: false
        download:
          enabled: false
        camera_ui:
          enabled: false
        fullscreen:
          enabled: true
        media_player:
          enabled: false
        microphone:
          enabled: true
        timeline:
          enabled: false
        cast:
          enabled: false
        play:
          enabled: true
        mute:
          enabled: true
    performance:
      profile: high
    overrides:
      - conditions:
          media_query: '(max-width: 300px)'
        overrides:
          menu:
            style: none
          media_viewer:
            controls:
              mode: none
              timeline:
                mode: none
          media_gallery:
            controls:
              mode: none
          live:
            zoomable: false
            controls:
              next_previous:
                style: none
              thumbnails:
                mode: none
```

I load the pop-up with cards like this 

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.outdoor_1
    live_provider: image
view:
  default: image
  actions:
    tap_action:
      - action: navigate
        navigation_path: >-
          ?frigate-card-action:popup:camera_select=camera.outdoor_1&frigate-card-action:popup:live#cameras
image:
  mode: camera
  refresh_seconds: 5
  layout:
    fit: fill
menu:
  style: none
dimensions:
  min_height: 75px
```

And I noticed that whenever this happens it's always the first camera in the `cameras` list which is the doorbell.
