### ISSUE TITLE
Audio in but no Microphone Audio out

### ISSUE THREAD

**Issue by nosar77** [dermotduffy/frigate-hass-card#1400]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
5.2.0*

**Browser and Operating System:**
Brave on desktop
HA app on android 14

**Description of problem:**

For some reason I have everything set up properly but I cannot get any sound to come out of the reolink video doorbell when pressing the microphone button in HA. 

**Frigate card diagnostic information**

```json
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.3.0",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "date": "2024-03-13T06:26:29.599Z",
  "frigate_version": {
    "f49dd756fdb385f63641c50c0792cf49": "5.0.1/0.13.2-6476f8a"
  },
  "lang": "en",
  "timezone": "America/Los_Angeles",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front_door_bell",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ]
        }
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true,
          "alignment": "opposing",
          "type": "momentary"
        },
        "timeline": {
          "enabled": false
        },
        "cameras": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        },
        "download": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        },
        "mute": {
          "enabled": true,
          "alignment": "opposing"
        },
        "camera_ui": {
          "enabled": false
        }
      },
      "style": "overlay",
      "position": "left",
      "button_size": 80
    },
    "live": {
      "controls": {
        "thumbnails": {
          "mode": "none"
        }
      },
      "auto_mute": "all",
      "preload": false
    },
    "dimensions": {},
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "size": 140,
          "show_favorite_control": false,
          "show_timeline_control": false,
          "show_download_control": false
        },
        "filter": {
          "mode": "none"
        }
      }
    }
  }
}
```

**Frigate Config File:**

```
mqtt:
  host: IP         # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate               # YOUR MQTT USERNAME
  password: "password"        # YOUT MQTT PASSWORD
  stats_interval: 60



detectors:
  cpu1:
    type: cpu
    num_threads: 3


go2rtc:
  streams:
    front_door_bell:
      - rtsp://username:password@IP:554/h264Preview_01_sub
      - "ffmpeg:rtsp://username:password@IP:554/h264Preview_01_sub#audio=pcm#audio=volume"

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
    hwaccel_args: preset-vaapi



# Camera configuration
cameras:
  front_door_bell:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@IP:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy

#Global camera Ccnfigs
objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000

snapshots :
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

record:
  enabled: true
  events:
    retain:
      default: 7

```

**Additional information:**
