### ISSUE TITLE
Card no longer loads in some Android devices after #1390

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1407]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** #1390 onwards (tested up to #1399)

**Last working release (if known):** #1390 downwards (last working is #1366)

**Browser and Operating System:** Android 10, Webview 122. Also happened in my brother's wife with Android 14, Webview 122. Problem reproduces within or outside the companion app.

**Description of problem:**

The card does not load on a few devices. **Note it is working normally in some other devices.**

![image](https://github.com/dermotduffy/frigate-hass-card/assets/29582865/29ade534-1370-44e7-b424-6f3f0af717a3)
![image](https://github.com/dermotduffy/frigate-hass-card/assets/29582865/cd7fa31e-edbe-4dec-bbd9-766600cb2169)

**Frigate card diagnostic information**

Can't access this button.

**Javascript errors shown in the web inspector (if applicable):**

None, unfortunately.

**Additional information:**

After some investigation with the help of @dermotduffy, this is where the initialization logic seems to stop:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/29582865/b3fb661a-a438-4eae-b875-9c42b6074d23)

**Comment by felipecrs** [comment]
@dermotduffy I just opened this issue to keep track of it. I was able to reproduce it again when trying to update to latest revision. Don't worry, I'm not expecting you to investigate it since you can't reproduce it.

Maybe more people will experience the same.

**Comment by miguelangel-nubla** [comment]
Do you have a workaround for now?

**Comment by felipecrs** [comment]
None that I know, for now I downgraded.

**Comment by felipecrs** [comment]
I have news about this. After updating to latest dev (38d3fa3), the card loads in such Android device, however it shows the following:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/29582865/15fe2236-5872-4685-adc9-baedfbb0f336)

Note the same dashboard is working normally on all other devices. This issue is only happening on the same device that was presenting the original issue reported here, therefore I believe it's connected.

**Comment by felipecrs** [comment]
Unfortunately, nothing shows up in the console logs.

Not sure if I'm doing something wrong, but not even:

```yaml
debug:
  logging: true
```

Produced any output in the console logs.

PS: Webview 125.0.6422.165

**Comment by felipecrs** [comment]
Solution for now is to keep at 305a2db.

**Comment by tv4you2016** [comment]
hello,
I have the same problem, is there any solution?

**Comment by dermotduffy** [comment]
@felipecrs There is definitely nothing relevant in the JS console, even with the console set to "All levels" and logging turned on in the card:

```` 
debug:
  logging: true
```

**Comment by felipecrs** [comment]
@dermotduffy, there's this one:

```console
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.12.1 
android-tv-card.min.js?hacstag=654393646770:5  ANDROID-TV-CARD v3.9.3
layout-card.js?hacstag=156434866245:228 LAYOUT-CARD 2.4.5 IS INSTALLED
card-0f1adfa8.js:489  FRIGATE-HASS-CARD  Version 5.2.0 
card-0f1adfa8.js:75 ex: No cameras support this view
    at nx.getViewByParameters (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:93:10052)
    at ax._setViewGeneric (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:102:1342)
    at ax.setViewByParameters (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:102:565)
    at hb.execute (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:85:2831)
    at bb.execute (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:88:365)
    at Mb.executeActions (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:88:1601)
    at https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:88:4136
    at Sb.execute (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:88:4191)
    at _listeners (https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:88:19134)
    at https://home.felipecrs.com/local/custom/frigate-hass-card/card-0f1adfa8.js:88:22035 Object
Lp @ card-0f1adfa8.js:75
```

**Comment by felipecrs** [comment]
This is the config:

<details>

<summary>Click here to show</summary>

```yaml
type: custom:frigate-card
card_id: video_porteiro
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - webrtc
  image:
    refresh_seconds: 1
  dimensions:
    layout:
      fit: cover
      position:
        x: 0
        'y': 0
automations:
  - conditions:
      - condition: fullscreen
        fullscreen: false
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: live_substream_off
  - conditions:
      - condition: fullscreen
        fullscreen: true
      - condition: screen
        media_query: '(min-width: 1500px)'
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: live_substream_on
overrides:
  - conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.rua
      - condition: media_loaded
        media_loaded: true
    merge:
      live:
        controls:
          ptz:
            hide_zoom: true
  - conditions:
      - condition: fullscreen
        fullscreen: true
    merge:
      menu:
        style: overlay
        buttons:
          substreams:
            enabled: true
      live: {}
      cameras_global:
        dimensions:
          layout:
            fit: contain
            position:
              x: 50
              'y': 50
elements:
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.portao
      - condition: media_loaded
        media_loaded: true
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_do_portao_visao_noturna
        alignment: opposing
        priority: 52
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.morro
      - condition: media_loaded
        media_loaded: true
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_do_morro_visao_noturna
        alignment: opposing
        priority: 52
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.rua
      - condition: media_loaded
        media_loaded: true
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_da_rua_visao_noturna
        alignment: opposing
        priority: 52
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
menu:
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    image:
      enabled: false
    cameras:
      alignment: opposing
    timeline:
      enabled: false
    media_player:
      enabled: true
    clips:
      enabled: true
    camera_ui:
      enabled: true
    substreams:
      enabled: false
      alignment: opposing
      priority: 51
      icon: mdi:high-definition
    expand:
      enabled: false
    microphone:
      enabled: false
    play:
      enabled: false
    mute:
      enabled: true
    display_mode:
      enabled: false
  style: outside
  position: top
  alignment: left
live:
  preload: false
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: none
    builtin: false
  lazy_load: true
  show_image_during_load: true
  microphone:
    disconnect_seconds: 60
  lazy_unload:
    - unselected
    - hidden
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
cameras:
  - camera_entity: camera.video_porteiro
    dependencies:
      cameras:
        - video_porteiro_hd
    go2rtc:
      modes:
        - webrtc
    cast:
      method: dashboard
      dashboard:
        dashboard_path: frigate-card
        view_path: '0'
  - camera_entity: camera.rua
    dependencies:
      cameras:
        - rua_hd
  - camera_entity: camera.morro
    dependencies:
      cameras:
        - morro_hd
  - camera_entity: camera.portao
    dependencies:
      cameras:
        - portao_hd
  - camera_entity: camera.video_porteiro
    title: Vídeo Porteiro (HD)
    id: video_porteiro_hd
    go2rtc:
      stream: video_porteiro_hd
    capabilities:
      disable_except:
        - substream
  - camera_entity: camera.rua
    title: Rua (HD)
    id: rua_hd
    go2rtc:
      stream: rua_hd
    capabilities:
      disable_except:
        - substream
  - camera_entity: camera.morro
    title: Morro (HD)
    id: morro_hd
    go2rtc:
      stream: morro_hd
    capabilities:
      disable_except:
        - substream
  - camera_entity: camera.portao
    title: Portão (HD)
    id: portao_hd
    go2rtc:
      stream: portao_hd
    capabilities:
      disable_except:
        - substream
image:
  mode: camera
performance: {}
media_viewer:
  auto_unmute:
    - selected
    - visible
debug:
  logging: true
profiles:
  - low-performance
status_bar:
  style: none
```

</details>
