### ISSUE TITLE
How to add a duration to frigate.ptz service

### ISSUE THREAD

**Issue by mhoogenbosch** [dermotduffy/frigate-hass-card#1420]
Not really an issue, but can't find the answer anywhere.

I got my card configured, previously with the IMOU service. But since IMOU is going to charge for cloud api calls (or in fact; already is). I'm moving to PTZ from native Frigate. The controls work within frigate. So connection is great. But calling the service doesn't stop moving. 

My config:

```
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          right: 85%
          top: 75%
          transform: scale(3, 3)
        actions_left:
          action: call-service
          service: frigate.ptz
          data:
            action: move
            argument: left
          target:
            entity_id: camera.fynncam
        actions_right:
          action: call-service
          service: frigate.ptz
          data:
            action: move
            argument: right
          target:
            entity_id: camera.fynncam
```

I tried adding duration, also looked into some other configs and tried adding ptztimeout, but none seem to make the camera stop moving.
