### ISSUE TITLE
Dev version doens't work on Fully Kiosk on Android 12

### ISSUE THREAD

**Issue by mhoogenbosch** [dermotduffy/frigate-hass-card#1426]
Because of my PTZ requirement (see also: https://github.com/dermotduffy/frigate-hass-card/issues/1420) I have installed the DEV version of this card.

Now I know there is no support for the DEV version and that's fine. But on my Android tablet (wallboard) i'm getting the following issue:

No cameras support this view. Check troubleshooting
```
{
  "view": "live",
  "cameras_capabilities": {}
}
```

On my other devices (Windows 11, iPhone), but also on the same device but with Chrome, it does work.

I'm using Version 1.55.1-play version of Fully Kiosk.
The HA companion doesn't work either btw, of that i'm running 2024.1.5-full

The issue is there with the most minimalist card config:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.deurbel
```

The card does work with the lastest official release.

**Comment by dermotduffy** [comment]
> Now I know there is no support for the DEV version

For the record, bug reports for the `dev` branch are very welcome since it's the only way I'll get it ready for prime time. Thank you!

> The HA companion doesn't work either btw, of that i'm running 2024.1.5-full

So, for the same config, it does work in:
   * Windows 11
   * iPhone

But does not work in:
   * Fully kiosk 
   * HA Companion app

Is that right?

> 
> ```json
> {
>   "view": "live",
>   "cameras_capabilities": {}
> }
> ```

... this should never happen, and suggests somehow the camera is not being initialized correctly. It's odd that it works on some devices but not others, and sounds like it could conceivably be the same as #1407. Guess: Some sort of initialization race condition that is only being triggered on some devices...

**Comment by mhoogenbosch** [comment]
In Windows 11 it works fine indeed. But there is no Companion and Fully kiosk.
In iPhone it works on both the app and the browser
In Android 12 tablet device, it works on Chrome browser, but doesn't on companion app and fully kiosk

Now I found an Android 12 phone too laying around. With that device it works on both the Chrome and Companion app. Didn't have fully kiosk installed.

While typing this it doesn't make sense for me, so tomorrow i'll confirm these tests. But if I have confirmed this, only the screensize could have something to do with it, right? As both the companion app and fully kiosk take over the device.

**Comment by dermotduffy** [comment]
> But if I have confirmed this, only the screensize could have something to do with it, right? 

That's certainly one difference, but I fear/suspect this is the kind of subtle issue where device speed / latency could cause one `async` operation to complete before another changing the result subtly between devices / reloads. The other bug I linked to had something similar -- worked on one device, but not another despite identical configuration.

**Comment by mhoogenbosch** [comment]
Confirmed. On my phone based on Android 12 it just works. 

So the tablet doesn't work. But only in Companion app and Fully Kiosk. On chrome it does work.

**Comment by dermotduffy** [comment]
FYI: I found an initialization related issue that I fixed as a side-effect in #1448 . I wasn't trying to fix _this_ issue, but there's a chance I did ... if someone could take a look to confirm/deny that would be great!

**Comment by mhoogenbosch** [comment]
Just tested it and unfortunately it doesn't work. Same behavior.

**Comment by felipecrs** [comment]
That's weird. I tried upgrading today and I have the exact same issue:

```json
{
  "view": "live",
  "cameras_capabilities": {}
}
```

But in my case, it happens on all devices.

If you wonder, here's my config. All camera entities are Frigate-based, latest integration + latest Frigate 0.14.

```
type: custom:frigate-card
card_id: video_porteiro
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - webrtc
  image:
    refresh_seconds: 1
  dimensions:
    layout:
      fit: cover
      position:
        x: 0
        'y': 0
automations:
  - conditions:
      - condition: fullscreen
        fullscreen: false
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: live_substream_off
  - conditions:
      - condition: fullscreen
        fullscreen: true
      - condition: screen
        media_query: '(min-width: 1500px)'
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: live_substream_on
overrides:
  - conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.rua
      - condition: media_loaded
        media_loaded: true
    merge:
      live:
        controls:
          ptz:
            hide_zoom: true
  - conditions:
      - condition: fullscreen
        fullscreen: true
    merge:
      menu:
        style: overlay
        buttons:
          substreams:
            enabled: true
      live: {}
      cameras_global:
        dimensions:
          layout:
            fit: contain
            position:
              x: 50
              'y': 50
elements:
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.portao
      - condition: media_loaded
        media_loaded: true
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_do_portao_visao_noturna
        alignment: opposing
        priority: 52
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.morro
      - condition: media_loaded
        media_loaded: true
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_do_morro_visao_noturna
        alignment: opposing
        priority: 52
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
      - condition: camera
        cameras:
          - camera.rua
      - condition: media_loaded
        media_loaded: true
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.camera_da_rua_visao_noturna
        alignment: opposing
        priority: 52
        options:
          '0':
            icon: mdi:theme-light-dark
          '1':
            icon: mdi:weather-sunny
          '2':
            icon: mdi:weather-night
menu:
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    image:
      enabled: false
    cameras:
      alignment: opposing
    timeline:
      enabled: false
    media_player:
      enabled: true
    clips:
      enabled: true
    camera_ui:
      enabled: true
    substreams:
      enabled: false
      alignment: opposing
      priority: 51
      icon: mdi:high-definition
    expand:
      enabled: false
    microphone:
      enabled: false
    play:
      enabled: false
    mute:
      enabled: true
    display_mode:
      enabled: false
  style: outside
  position: top
  alignment: left
live:
  preload: false
  controls:
    next_previous:
      style: none
    title:
      mode: none
    thumbnails:
      mode: none
    builtin: false
  lazy_load: true
  show_image_during_load: true
  microphone:
    disconnect_seconds: 60
  lazy_unload:
    - unselected
    - hidden
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
cameras:
  - camera_entity: camera.video_porteiro
    dependencies:
      cameras:
        - video_porteiro_hd
    go2rtc:
      modes:
        - webrtc
    cast:
      method: dashboard
      dashboard:
        dashboard_path: frigate-card
        view_path: '0'
  - camera_entity: camera.rua
    dependencies:
      cameras:
        - rua_hd
  - camera_entity: camera.morro
    dependencies:
      cameras:
        - morro_hd
  - camera_entity: camera.portao
    dependencies:
      cameras:
        - portao_hd
  - camera_entity: camera.video_porteiro
    title: Vídeo Porteiro (HD)
    id: video_porteiro_hd
    go2rtc:
      stream: video_porteiro_hd
    capabilities:
      disable_except:
        - substream
  - camera_entity: camera.rua
    title: Rua (HD)
    id: rua_hd
    go2rtc:
      stream: rua_hd
    capabilities:
      disable_except:
        - substream
  - camera_entity: camera.morro
    title: Morro (HD)
    id: morro_hd
    go2rtc:
      stream: morro_hd
    capabilities:
      disable_except:
        - substream
  - camera_entity: camera.portao
    title: Portão (HD)
    id: portao_hd
    go2rtc:
      stream: portao_hd
    capabilities:
      disable_except:
        - substream
image:
  mode: camera
performance: {}
media_viewer:
  auto_unmute:
    - selected
    - visible
profiles:
  - low-performance
```
