### ISSUE TITLE
Can't get triggers to work

### ISSUE THREAD

**Issue by onetoomany** [dermotduffy/frigate-hass-card#1429]
v5.2.0 on HA 2024.4.0

This is most likely user error, not a bug ...

I'm wanting to have a default camera view (in this case, it is a non frigate camera), which switches to a specific frigate camera based on certain conditions.
I've done the simplest test, which is to try to trigger a camera based on the state of my light switch. However, the camera view does not change from "pictures" to "footpath".

Another challenge is that I want to remove the menu with the full screen button, and instead go to full screen when the image is clicked on - is this possible?

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.pictures
  - camera_entity: camera.footpath
    triggers:
      entities:
        - switch.study_light
  - camera_entity: camera.pond
  - camera_entity: camera.parking
  - camera_entity: camera.front_garden
live:
  auto_play: all
  controls:
    next_previous:
      style: none
view:
  default: live
  camera_select: live
  timeout_seconds: 20
menu:
  buttons:
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    media_player:
      enabled: false
    camera_ui:
      enabled: false
    download:
      enabled: false
    snapshots:
      enabled: false
  style: outside
  position: top
  alignment: left

```

**Comment by dermotduffy** [comment]
You need to enable scan mode for your simple test, try adding:

```yaml
...
view:
  default: live
  camera_select: live
  timeout_seconds: 20
  scan:              # <------- Added
    enabled: true    # <------- Added
...
```

> Another challenge is that I want to remove the menu with the full screen button, and instead go to full screen when the image is clicked on - is this possible?

There are two parts to this:
   * Removing the menu.
   * Adding a card wide action to go to fullscreen mode when the image is clicked on.

The first is certainly possible now with the right by setting the menu style to `none`, but sadly the second has a bug at the moment being tracked here: https://github.com/dermotduffy/frigate-hass-card/issues/1402 .
