### ISSUE TITLE
Help Request - Clip View with Thumbnail Carousel

### ISSUE THREAD

**Issue by nwithan8** [dermotduffy/frigate-hass-card#1437]
I'm trying to make exactly this as documented in the [README](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#clip-viewing-with-thumbnail-carousel), but for the life of me I can't make heads or tails of this complex YAML. If anyone knows, that would be appreciated.

**Comment by dermotduffy** [comment]
Example that shows thumbnails underneath both live and media viewer views, with the details turned off on each thumbnail:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
live:
  controls:
    thumbnails:
      mode: below
      show_details: false
media_viewer:
  controls:
    thumbnails:
      mode: below
      show_details: false
```
