### ISSUE TITLE
Help needed - Hide right hand side drawer

### ISSUE THREAD

**Issue by unxplained** [dermotduffy/frigate-hass-card#1454]
Sorry, not sure where I could find some help.

Was wondering if there was anyway to hide this drawer, on the right hand side of the card.

![SCR-20240510-klab](https://github.com/dermotduffy/frigate-hass-card/assets/8056914/69383b37-f2e5-4959-bc80-189a7acd96d1)

Thank you

**Comment by dermotduffy** [comment]
Try:

```yaml
live:
  controls:
    thumbnails:
      mode: none
```
