### ISSUE TITLE
Make a Filter permanent, for example, only shows persons on a media library card on Homeassisntant

### ISSUE THREAD

**Issue by victordariovera** [dermotduffy/frigate-hass-card#1455]
Hi! It's not possible at all to fix a filter configuration, for example, to show a frigate card showing *only* persons.

**Describe the solution you'd like**
A yaml card configuration to set up a permanent filter, for example show only persons

**Describe alternatives you've considered**
An option on GUI to adjust the permanent filter

**Additional context**
I'd tried in multiple ways to fix a filter configuration in the card by labels.

**Comment by patienttruth** [comment]
This is not exactly what you're asking for, but perhaps is satisfactory solution. I searched for filter on the docs page and found:
https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#camera-frigate-configuration

It looks like you can set a limit to what the card shows in the YAML.

```yaml
cameras:
  - camera_entity: camera.frigate_lorex_01_gate
    dependencies:
      cameras:
        - camera.frigate_lorex_02_turnaround
    frigate:
      labels:
        - person
  - camera_entity: camera.frigate_lorex_02_turnaround
```

incidentally, the "dependency" entry is one that I learned when looking for a similar solution to my use case of preserving the camera filter which shows two cameras. I ended up making one card for each side of the house which lists a primary camera, and a secondary camera as a dependency. The default view is clips. It shows the clip thumbnails for the two cameras mixed together and sorted by time.

**Comment by bob454522** [comment]
im having this same issue -  For example if I set the frigate card to only show the snapshots media gallery, and then add in 4x cameras,  every-time the card is reloaded, the media filter settings go back to the default (ie of the 1st camera you added , so the other 3x are ignored).  (even making a brand new frigate card,  it keeps going back to just the 1x camera)

if you click the media filter drawer button on the right,  make your settings ,  then the gallery is updated.  but as soon as the page is reloaded it goes back to the default filter settings of just 1x camera.

I think an image can better show what im referring to - i want the snapshots gallery to show all cameras i have setup in the frigate card's settings:
any idea how to fix this (or to force the "Media Gallery" -> "Media Filter" settings in YAML ?) 

thanks
![image](https://github.com/user-attachments/assets/414f35fd-bb73-410e-b35c-18f038c36f3f)

**Comment by patienttruth** [comment]
@bob454522 did you try the YAML with the `dependencies` line like in my example above? 

I'm pretty sure that makes it show extra cameras upon loading the page. In my use case I have a card that automatically loads 2 cameras into the filter which I believe is what you're looking for.

**Comment by ivanjx** [comment]
@patienttruth how about including all zones from all cameras?

**Comment by dermotduffy** [comment]
[Issues cleanup] As @patienttruth mentions above, this should just work if there are dependencies set up between the cameras. To depend on all cameras, we'd use:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.hall_ondu
    dependencies:
      all_cameras: true
```

If this doesn't do what you are seeking, let me know what is missing? Thanks and good luck!
