### ISSUE TITLE
Using frigate-hass-card with Frigate on different host.

### ISSUE THREAD

**Issue by hapklaar** [dermotduffy/frigate-hass-card#1461]
I can't for the life of me get the frigate card to work with a Frigate install on a separate Linux host on my network. I only get either a black screen or the default screen.

How should this be configured if at all possible?

As I don't have a camera entity for the Frigate camera, I just chose a random camera and then configured the Frigate URL as follows:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.various_temp
    frigate:
      camera_name: Voor
      url: http://192.168.111.102:5000/
    live_provider: auto
view:
  default: clips
  camera_select: clips
```

I do have the Frigate proxy working in HASS and don't have the Frigate integration installed as it runs on another host.

help?
