### ISSUE TITLE
Automatic config upgrade issue from 305a2db to 38d3fa3

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1473]
From 305a2db573d16bb7a91da65e7792b116b12a33b8 to 38d3fa358a4ded1edd3db60c46f8c0515ad25612.

<details>
  <summary>Previous config</summary>

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: go2rtc
    image:
      refresh_seconds: 1
    go2rtc:
      stream: video_porteiro_mic
      modes:
        - webrtc
elements:
  - type: custom:frigate-card-conditional
    conditions:
      microphone:
        connected: false
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:phone
        alignment: opposing
        style:
          color: green
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: microphone_unmute
  - type: custom:frigate-card-conditional
    conditions:
      state:
        - entity: input_boolean.video_porteiro_chamando
          state: 'on'
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:phone-hangup
        alignment: opposing
        style:
          color: red
        tap_action:
          - action: call-service
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.video_porteiro_chamando
  - type: custom:frigate-card-conditional
    conditions:
      microphone:
        connected: true
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:phone-hangup
        alignment: opposing
        style:
          color: red
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: microphone_mute
          - action: call-service
            service: fully_kiosk.load_url
            data:
              url: https://home.felipecrs.com/lovelace/default_view
              device_id: b5005de440d90c862538e61299d8d9f1
automations:
  - conditions:
      microphone:
        connected: true
    actions:
      - action: call-service
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.video_porteiro_chamando
live:
  controls:
    builtin: false
    title:
      mode: none
    thumbnails:
      mode: none
    next_previous:
      style: none
  zoomable: true
  show_image_during_load: true
  draggable: false
  lazy_unload:
    - unselected
    - hidden
  microphone:
    disconnect_seconds: 180
  auto_unmute:
    - microphone
    - visible
    - selected
menu:
  buttons:
    cameras:
      enabled: false
    frigate:
      enabled: false
    fullscreen:
      enabled: false
      alignment: opposing
    media_player:
      enabled: false
    play:
      enabled: false
    microphone:
      enabled: true
      type: toggle
    live:
      enabled: false
    mute:
      enabled: true
    snapshots:
      enabled: false
    clips:
      enabled: false
    download:
      enabled: false
    timeline:
      enabled: false
    expand:
      enabled: false
      alignment: opposing
    display_mode:
      enabled: false
  style: outside
  position: top
  button_size: 85
  alignment: right
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```

</details>

<details>
  <summary>Upgraded config</summary>

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: go2rtc
    image:
      refresh_seconds: 1
    go2rtc:
      stream: video_porteiro_mic
      modes:
        - webrtc
elements:
  - type: custom:frigate-card-conditional
    conditions:
      microphone:
        connected: false
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:phone
        alignment: opposing
        style:
          color: green
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: microphone_unmute
  - type: custom:frigate-card-conditional
    conditions:
      - condition: state
        state: 'on'
        entity: input_boolean.video_porteiro_chamando
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:phone-hangup
        alignment: opposing
        style:
          color: red
        tap_action:
          - action: call-service
            service: input_boolean.turn_off
            data:
              entity_id: input_boolean.video_porteiro_chamando
  - type: custom:frigate-card-conditional
    conditions:
      microphone:
        connected: true
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:phone-hangup
        alignment: opposing
        style:
          color: red
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: microphone_mute
          - action: call-service
            service: fully_kiosk.load_url
            data:
              url: https://home.felipecrs.com/lovelace/default_view
              device_id: b5005de440d90c862538e61299d8d9f1
automations:
  - conditions:
      microphone:
        connected: true
    actions:
      - action: call-service
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.video_porteiro_chamando
live:
  controls:
    builtin: false
    title:
      mode: none
    thumbnails:
      mode: none
    next_previous:
      style: none
  zoomable: true
  show_image_during_load: true
  draggable: false
  lazy_unload:
    - unselected
    - hidden
  microphone:
    disconnect_seconds: 180
  auto_unmute:
    - microphone
    - visible
    - selected
menu:
  buttons:
    cameras:
      enabled: false
    frigate:
      enabled: false
    fullscreen:
      enabled: false
      alignment: opposing
    media_player:
      enabled: false
    play:
      enabled: false
    microphone:
      enabled: true
      type: toggle
    live:
      enabled: false
    mute:
      enabled: true
    snapshots:
      enabled: false
    clips:
      enabled: false
    download:
      enabled: false
    timeline:
      enabled: false
    expand:
      enabled: false
      alignment: opposing
    display_mode:
      enabled: false
  style: outside
  position: top
  button_size: 85
  alignment: right
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
```
  
</details>

Error message:

```
Invalid configuration: [ "elements[0] -> type", "elements[0] -> conditions", "elements[0] -> icon", "elements[0] -> entity", "elements[0] -> items", "elements[0] -> title", "elements[0] -> service", "elements[2] -> type", "elements[2] -> conditions", "elements[2] -> icon", "elements[2] -> entity", "elements[2] -> items", "elements[2] -> title", "elements[2] -> service", "automations[0] -> conditions" ]
```

Workaround:

```diff
    conditions:
-     microphone:
-       connected: true
+     - condition: microphone
+       connected: true
```
