### ISSUE TITLE
[Config Support] Reolink Doorbell 2-way Audio - Microphone button missing?

### ISSUE THREAD

**Issue by ReticentRobot** [dermotduffy/frigate-hass-card#1477]
I don't think is a bug or a feature request, so using the blank issue - I hope that is right, please let me know if not.

I am trying to get 2-way audio working on my Reolink Doorbell WiFi.  I've looked at the configs I can find here and on the main Frigate GitHub, the recommended Reolink config, etc. - but I haven't been able to cobble anything together from those that enables the two-way audio for me.  I'm accessing via Nabu Casa, if that makes any difference.  I'm sure I'm just missing something but I don't know what.  

Here is my config.yml
```mqtt:
  enabled: true
  host: 192.168.1.102
  user: mqtt-client
  password: mypass
detectors:
  coral_usb:
    type: edgetpu
    device: usb
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    front_doorbell:
      - ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=mypass#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.30/Preview_01_sub
    front_doorbell_sub:
      - ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=mypass
cameras:
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 632,92,487,254,486,368,793,485,896,390,896,209,821,0
    zones:
      zone_0:
        coordinates: 43,672,338,388,337,224,457,254,464,395,535,672
version: 0.14
```

and my lovelace yaml:
```type: custom:frigate-card
cameras:
  - camera_entity: camera.front_doorbell
menu:
  style: overlay
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      type: toggle
    recordings:
      enabled: false
    frigate:
      enabled: false
    cameras:
      enabled: false
    snapshots:
      enabled: false
    mute:
      enabled: true
live:
  microphone:
    always_connected: false
```

Can anyone point me in the right direction?

**Comment by TechnoGangsta** [comment]
Port forward port 8555 to your frigate host IP. That should get it going for you.

**Comment by bagobones** [comment]
Reolink Doorbell 2-way Audio is broken in several versions of the cameras firmware same with RTSP.

Both RTSP and the 2-way audio work in the most recent firmware for the black WiFi doorbell.

Here are my working settings

Doorbell:

Firmware Version: v3.0.0.3308_2407315182

Stream settings:

Note that I-frame interval impacts how smooth and fast restreaming is.

```
Clear:
Resolution: 2560*1920
Frame Rate (FPS): 20
Max Bitrate (Kbps): 4096
I-frame Interval: 1x

Fluent:
Resolution: 640*480
Frame Rate (FPS): 10
Max Bitrate (Kbps): 512
I-frame Interval: 1x
```


Important Frigate / Go to RTC settings:
You may need webrtc working and exposed externally for fast viewing on iPhones and browsers that don't use mse mode.

```
go2rtc:
  webrtc:
    candidates:
      - 192.168.102.30:8555 # this is my frigate instances internal IP and port
      - stun:8555 # this port is forwarded to my frigate instance and stun will help devices direct connect
  streams:
    doorbell: #Reolink Doorbell
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.6:554/h264Preview_01_main
      - ffmpeg:doorbell#audio=opus   # transcodes audio to opus for webrtc compatibility
    doorbell_sub: #Reolink Doorbell
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.6:554/h264Preview_01_sub
      - ffmpeg:doorbell_sub#audio=opus   # transcodes audio to opus for webrtc compatibility
```

Frigate card settings, I have it setup as a single panel card view that I can direct navigate to on notification. I use the substream as it is lower bandwidth when on my phone remotely and tends to load fast.

There is still a substantial audio delay of about 3 seconds in this setup however.

```
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: doorbell_sub
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
live:
  draggable: false
  zoomable: false
  controls:
    builtin: true
    next_previous:
      style: none
    thumbnails:
      mode: none
  layout:
    fit: contain
  auto_unmute: selected
  preload: false
  lazy_load: false
  transition_effect: none
  show_image_during_load: false
  microphone:
    always_connected: true
performance:
  features:
    animated_progress_indicator: false
  style:
    border_radius: false
    box_shadow: false
timeline:
  show_recordings: false
menu:
  style: overlay
  buttons:
    frigate:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    snapshots:
      enabled: false
    clips:
      enabled: false
    media_player:
      enabled: false
    microphone:
      enabled: true
      priority: 60
      type: toggle
    mute:
      enabled: true
      priority: 55
    screenshot:
      enabled: false
    timeline:
      enabled: false
    fullscreen:
      icon: mdi:overscan
  alignment: right
  position: top
  button_size: 70
```
