### ISSUE TITLE
full screen switch from sub not working

### ISSUE THREAD

**Issue by jameseck** [dermotduffy/frigate-hass-card#1479]
Hi,

I'm using the latest version of Home Assistant, 2024.6.4 and the latest version of this card 5.2.0.

I have the below card config and the behaviour I'm expecting is:
- In normal operation, the card should display video from the sub stream (which it does - no issue here)
- if I either double tap or press the full screen button on the ribbon at the bottom, the card should be displayed full screen with the hd stream.

What actually happens is: the card flickers into full screen, then the whole dashboard reloads and displays as normal (with no full screen).

I am using gortc within frigate and am exposing two streams front_sub (sub stream) and front (main stream).
Both streams work independently with this card, but when I combine the two in a single card with the config below, the issue occurs.

I've tried this with multiple different browsers, on different clients - the behaviour is always the same.  I'm sure there is something wrong with my config but I can't see it.

```
type: custom:frigate-card
view:
  actions:
    double_tap_action:
    action: custom:frigate-card-action
    frigate_card_action: fullscreen
cameras:
- camera_entity: camera.front
  id: front_sub
  live_provider: go2rtc
  go2rtc:
      modes:
      - webrtc
      stream: front_sub
  dependencies:
    cameras:
    - front_hd
- camera_entity: camera.front
  title: front HD
  live_provider: go2rtc
  go2rtc:
    modes:
    - webrtc
  id: front_hd
  hide: true
menu:
  buttons:
    substreams:
    icon: mdi:high-definition
automations:
- conditions:
    fullscreen: true
  actions:
  - action: custom:frigate-card-action
    frigate_card_action: live_substream_on
  actions_not:
  - action: custom:frigate-card-action
    frigate_card_action: live_substream_off
```
