### ISSUE TITLE
Noob question on how to not have the live stream continuously play

### ISSUE THREAD

**Issue by ezcGman** [dermotduffy/frigate-hass-card#1487]
Hey there,

since I'm using the frigate-hass-card, my mobile data usage has completely skyrocketed:
![Screenshot_2024-07-26-23-44-26-126_com miui securitycenter-edit](https://github.com/user-attachments/assets/b9847339-67f7-4bd3-aebe-8eda4daec798)

It's because I have three frigate-hass-cards configured on my dashboard and they constantly play the live stream... I just can't get them to stop doing this...
I tried playing around with triggers, I tried with the `view -> update_seconds` value, I tried with `live -> auto_play: visible / auto_pause: hidden`... All three live streams always instantly play... I would love to have the standard HA camera card behavior, where it just updates a still image every X seconds and uses the live stream whenever you go into fullscreen... But I also have the issue that I don't know where to get that still image from... I use Frigate as an Add-on, so the regular API doesn't exist (`GET /api/<camera_name>/latest.jpg`)...

This is my current, very limited config (Removed contents of `menu` and `elements`, as unrelated to my issue:
```
type: custom:frigate-card
  cameras:
    - camera_entity: camera.outside_front_yard_camera
      live_provider: ha
  view:
    default: live
    update_seconds: 30
  live:
    auto_play: visible
    auto_pause: hidden
  menu:
    [...]
  elements:
    [...]
```

With that config, I was expecting that the live stream only plays, when the tab/window is active, e.g. if I switch to another window that overlay, it stops. But it always plays...
I also was expecting that it basically renders a still image of the live stream and refreshes that every 30s. But I guess I'm wrong...
I didn't touch triggers as I don't think they help me here. I understood they are used when u have multiple cameras or use other views like the snapshot viewer, etc... 

Would love if somebody can at least help with the direction on which settings I need to look for...

Thanks and greetings,

Andy!

**Comment by ezcGman** [comment]
Sooooo, I think I got it to work... It's not obvious, imho. But maybe somebody else stumbles over this in the future:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.dining_room_camera
    live_provider: ha
view:
  # Set the default view to image
  default: image
# Now configure what the image is: Set `mode` to "camera" which will automatically pick the value of the `entity_picture` attribute from the `camera_entity` currently selected
image:
  mode: camera
  refresh_seconds: 10
# Now we need to tell it to use the live feed when going into fullscreen and reset it back when not in fullscreen:
automations:
  - conditions:
      fullscreen: true
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: live
    actions_not:
      - action: custom:frigate-card-action
        frigate_card_action: image
live:
  controls:
    builtin: false
menu:
  [...]
elements:
  [...]
```

Greetings,

Andy!
