### ISSUE TITLE
Buttons not showing on card

### ISSUE THREAD

**Issue by SG87** [dermotduffy/frigate-hass-card#1496]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Card version: 5.2.0
Frigate version:  0.14.0

**Last working release (if known):**
?

**Browser and Operating System:**
Chrome on MacOS Sanoma 14.5 
App on iPhone iOS 17.5.1

Home Assistant OS 13.0
HA version 2024.8.1

**Description of problem:**
I am trying to enable menu buttons on the card, but some of them are not showing up. The main button I want to activate is the microphone button. 2-way audio works in Frigate web UI, but not in the card.

As a test, I enabled all buttons, as you can see below.
List of buttons that appear:

- frigate
- mute
- play
- cameras
- live
- expand
- media player
- image
- screenshot

List of buttons that do not appear:
- recordings
- microphone (main interest at the moment)
- substreams
- snapshots
- clips
- camera_ui
- download
- timeline

**Frigate card diagnostic information**

```
{
  "ha_version": "2024.8.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "date": "2024-08-14T19:41:08.295Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "Europe/Brussels",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.deurbel_fluent",
        "live_provider": "auto",
        "hide": false,
        "triggers": {
          "motion": true
        }
      }
    ],
    "menu": {
      "buttons": {
        "recordings": {
          "enabled": true
        },
        "microphone": {
          "enabled": true,
          "type": "momentary",
          "icon": "mdi:microphone",
          "priority": 100
        },
        "mute": {
          "enabled": true,
          "icon": "mdi:volume-high",
          "alignment": "matching"
        },
        "play": {
          "enabled": true,
          "icon": "mdi:play-pause"
        },
        "frigate": {
          "enabled": true
        },
        "cameras": {
          "enabled": true
        },
        "expand": {
          "enabled": true
        },
        "substreams": {
          "enabled": true
        },
        "snapshots": {
          "enabled": true
        },
        "clips": {
          "enabled": true
        },
        "live": {
          "enabled": true
        },
        "camera_ui": {
          "enabled": true
        },
        "download": {
          "enabled": true
        },
        "timeline": {
          "enabled": true
        },
        "media_player": {
          "enabled": true
        },
        "screenshot": {
          "enabled": true
        },
        "image": {
          "enabled": true
        }
      },
      "style": "outside"
    },
    "view": {
      "update_force": false,
      "default": "live"
    },
    "timeline": {
      "style": "stack"
    },
    "media_viewer": {},
    "live": {
      "preload": false,
      "microphone": {
        "always_connected": true
      }
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Frigate config:

```
mqtt:
  enabled: true
  host: _ip_
  port: 1883
  user: _user_
  password: _password_
  topic_prefix: frigate

# detectors:
#  coral_pci:
#    type: edgetpu
#    device: pci:0

##########################################################################

go2rtc:
  streams:
    reolink:
      - rtsp://_user_:_password_@_ip_:554/h264Preview_01_sub
      - ffmpeg:rtsp://_user_:_password_@_ip_:554/h264Preview_01_sub#audio=pcm#audio=volume


## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://_user_:_password_@_ip_:554/h264Preview_01_sub
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
```
