### ISSUE TITLE
Live View & Gallery with Multiple Cameras/Streams not Automatically Updating Events

### ISSUE THREAD

**Issue by EPiSKiNG** [dermotduffy/frigate-hass-card#1499]
I'm trying to configure the following:

- Live view with scan mode between 7 different cameras with substreams (substream from frigate (6fps), and HD stream from Hikvision NVR integration.
- Gallery view containing events from all cameras (not just the active one) which automatically refreshes when there is a new snapshot added for any camera.

Running:

- HAOS 2024.8.2
- Frigate 0.14.0-da913d8
- Frigate Card 5.2.0
- Edge 127.0.2651.105 (Official build) and/or latest Home Assistant app on Android.

I've tried the following card where scan mode works properly, and the gallery is shown, but only shows the events from the active camera:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_walkway
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_301
    live_provider: go2rtc
    go2rtc:
      stream: front_walkway_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_301
    title: Front Walkway HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_301
    hide: true
  - camera_entity: camera.driveway
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1501
    live_provider: go2rtc
    go2rtc:
      stream: driveway_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1501
    title: Driveway HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1501
    hide: true
  - camera_entity: camera.front_door
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_101
    live_provider: go2rtc
    go2rtc:
      stream: front_door_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_101
    title: Front Door HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_101
    hide: true
  - camera_entity: camera.living_room_slider
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_901
    live_provider: go2rtc
    go2rtc:
      stream: living_room_slider_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_901
    title: Living Slider HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_901
    hide: true
  - camera_entity: camera.bedroom_slider
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1001
    live_provider: go2rtc
    go2rtc:
      stream: bedroom_slider_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1001
    title: Bedroom Slider HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1001
    hide: true
  - camera_entity: camera.side_yard
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1301
    live_provider: go2rtc
    go2rtc:
      stream: side_yard_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1301
    title: Side Yard HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1301
    hide: true
  - camera_entity: camera.pergola
    dependencies:
      cameras:
        - camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1101
    live_provider: go2rtc
    go2rtc:
      stream: pergola_sub
  - camera_entity: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1101
    title: Side Yard HD
    id: camera.ds_7616ni_i2_16p1620171008ccrr107469073wcvu_1101
    hide: true
view:
  scan:
    enabled: true
  update_force: true
menu:
  buttons:
    substreams:
      icon: mdi:high-definition
      priority: 100
    frigate:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    expand:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
  style: overlay
  position: top
  alignment: right
live:
  transition_effect: none
  auto_play: all
  controls:
    thumbnails:
      mode: below
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
visibility:
  - condition: numeric_state
    entity: sensor.sun_solar_elevation
    above: -4
```

I've also tried this gallery only card which is functional, but only refreshes when I interact with it, when the entire dashboard is refreshed, or when I set update_seconds and update_timeout to something greater than 0, but when I do that, the gallery view flickers each time it refreshes, which is a bit annoying as it catches my eye and makes me think something happened, when in reality something may not have.  I wouldn't mind this flicker if it only happened when there is a new snapshot available to review.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.driveway
    dependencies:
      all_cameras: true
  - camera_entity: camera.front_door
  - camera_entity: camera.front_walkway
  - camera_entity: camera.side_yard
  - camera_entity: camera.bedroom_slider
  - camera_entity: camera.pergola
  - camera_entity: camera.living_room_slider
view:
  default: snapshots
  update_seconds: 0
  timeout_seconds: 0
  update_entity:
    - binary_sensor.driveway_all_occupancy
    - binary_sensor.front_door_all_occupancy
    - binary_sensor.front_walkway_all_occupancy
    - binary_sensor.side_yard_all_occupancy
    - binary_sensor.bedroom_slider_all_occupancy
    - binary_sensor.pergola_all_occupancy
    - binary_sensor.living_room_slider_all_occupancy
dimensions:
  aspect_ratio_mode: unconstrained
  max_height: 203px
media_gallery:
  controls:
    thumbnails:
      show_details: true
      size: 100
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
media_viewer:
  layout:
    fit: cover
menu:
  buttons:
    frigate:
      enabled: false
automations:
  - conditions:
      state:
        - entity: binary_sensor.driveway_all_occupancy
          state: 'on'
        - entity: binary_sensor.front_door_all_occupancy
          state: 'on'
        - entity: binary_sensor.front_walkway_all_occupancy
          state: 'on'
        - entity: binary_sensor.side_yard_all_occupancy
          state: 'on'
        - entity: binary_sensor.bedroom_slider_all_occupancy
          state: 'on'
        - entity: binary_sensor.pergola_all_occupancy
          state: 'on'
        - entity: binary_sensor.living_room_all_person_occupancy
          state: 'on'
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: snapshots
    actions_not:
      - action: custom:frigate-card-action
        frigate_card_action: snapshots
```

I'm fairly certain that the automations section is unnecessary, but it was something I was trying to see if I can "force" the refresh of the card.

I should also note that there is a vehicle parked in the "driveway" zone/camera, so that sensor is always showing "1" car count and occupied.  I would like to think I can still get refreshed snapshots when other cameras/areas get triggered?

Thanks in advance for the help!
