### ISSUE TITLE
`No cameras support this view`

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/frigate-hass-card#1533]
Latest home assistant, the frigate card release of some hours ago, in home assistant companion app on latest samsung s21 firmware.
Quite randomly when opening a dashboard it reports "no cameras support this view". This was not the case before this latest beta.
I am using jspeg as live view, other then that settings are standard. Coming back to the dashboard or simply refreshing the page can make it work again.

![Screenshot_20240915_050703_Home Assistant](https://github.com/user-attachments/assets/58a09c77-b4d6-49da-8508-2c193533f529)

Didnt thought that frigare card could get better so huge thanks and compliments for this release!

**Comment by dermotduffy** [comment]
> I am using jspeg as live view, other then that settings are standard. Coming back to the dashboard or simply refreshing the page can make it work again.

Is it possible you are using an older Frigate integration (i.e. not https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.4.0 ). I think this is what you might see in that case.

If I'm wrong, would you mind holding down the Frigate button for a few seconds and paste in the diagnostics here? Thanks!

**Comment by borgqueenx** [comment]
i have the latest integration version. on my desktop, the icon for the menu does not show up, how do i get the logs then? i tried on my phone where the button shows up, but unfortunately the button to copy all the selected text does not appear. the whole text appears in the back of all other dashboard items which probably bugs the copy/paste menu on my samsung phone.

**Comment by EPiSKiNG** [comment]
I am having the same issue.  If I hard refresh, or exit browser and re-open it usually fixes itself, but appears to be intermittent/random.  I can use the same browser on a different device and it works, then refreshing brings the error.  I am also using Frigate integration version 5.4.0.

For reference, I'm accessing cameras using go2rtc and MSE.  I also have HD and substreams in use.

**Comment by dermotduffy** [comment]
> i have the latest integration version. on my desktop, the icon for the menu does not show up, how do i get the logs then? i tried on my phone where the button shows up, but unfortunately the button to copy all the selected text does not appear. the whole text appears in the back of all other dashboard items which probably bugs the copy/paste menu on my samsung phone.

For now, would you mind showing me the card config you used? Similarly @EPiSKiNG ?

Also useful would be a copy and paste of your Javascript console (F12 in Chrome/FF) to see if I can find anything useful in there....

**Comment by EPiSKiNG** [comment]
Here's the JS error:

```
card-62302d66.js:75 
 cx: No cameras support this view
    at dx.getViewByParameters (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:10539)
    at dx.getViewDefault (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:9941)
    at dx.getViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:11227)
    at ux._setViewGenericAsync (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:1521)
    at ux.setViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:690)
    at Db.initializeMandatory (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:88:7087) 
Object
qp	@	card-62302d66.js:75
card-62302d66.js:75 
 cx: No cameras support this view
    at dx.getViewByParameters (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:10539)
    at dx.getViewDefault (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:9941)
    at dx.getViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:11227)
    at ux._setViewGenericAsync (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:1521)
    at ux.setViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:690)
    at Db.initializeMandatory (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:88:7087) 
Object
qp	@	card-62302d66.js:75
```

and here's my card code:


```

type: custom:frigate-card
cameras:
  - camera_entity: camera.front_walkway
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.driveway
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.front_door
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.living_room_slider
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.bedroom_slider
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.side_yard
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.pergola
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
    triggers:
      entities:
        - binary_sensor.0x3425b4fffe64e3f0_occupancy
view:
  triggers:
    actions:
      trigger: live
      untrigger: default
    filter_selected_camera: false
  default_reset:
    interaction_mode: all
  keyboard_shortcuts:
    ptz_left:
      key: ArrowLeft
    ptz_right:
      key: ArrowRight
    ptz_up:
      key: ArrowUp
    ptz_down:
      key: ArrowDown
    ptz_zoom_in:
      key: +
    ptz_zoom_out:
      key: '-'
    ptz_home:
      key: h
  default: live
menu:
  buttons:
    substreams:
      icon: mdi:high-definition
      priority: 100
    frigate:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    expand:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
live:
  transition_effect: none
  controls:
    thumbnails:
      mode: below
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
  preload: true
  auto_play:
    - selected
    - visible
visibility:
  - condition: numeric_state
    entity: sensor.sun_solar_elevation
    above: -4
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:11'

```
