### ISSUE TITLE
Picture elements card - Conditional does not work after update to beta 6.0.0-beta.1

### ISSUE THREAD

**Issue by S-Przybylski** [dermotduffy/frigate-hass-card#1547]
**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v6..0.0-beta.1

**Last working release (if known):**
v5.2.0
**Browser and Operating System:**
Windows11 Firefox, Edge
Android, Chrome

**Description of problem:**

After migration of frigate-hass-card a error appeared that the configuration is invalid!

Compared syntax with Picture Elements Card: OK
https://www.home-assistant.io/dashboards/picture-elements/

**Frigate card diagnostic information**

not available!

Editor error:
Invalid configuration: [ "elements[0] -> conditions[0] -> condition", "elements[0] -> type", "elements[0] -> icon", "elements[0] -> entity", "elements[0] -> items", "elements[0] -> title", "elements[0] -> service", "elements[0] -> image", "elements[0] -> string" ]

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam3
elements:
  - type: conditional
    conditions:
      - entity: binary_sensor.cam3_person_occupancy
        state: 'on'
    elements:
      - type: icon
        icon: hass:run
        entity: binary_sensor.cam3_person_occupancy
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Add `condition: state` to each one and it will work, e.g.:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam3
elements:
  - type: conditional
    conditions:
      - condition: state
        entity: binary_sensor.cam3_person_occupancy
        state: 'on'
    elements:
      - type: icon
        icon: hass:run
        entity: binary_sensor.cam3_person_occupancy
```

Interestingly, it seems HA now has two different ways of specifying conditions. I updated the card to match a recent HA change, and so this appears to have broken compatibility for elements.

Syntax 1 (elements): https://www.home-assistant.io/dashboards/picture-elements/#conditional-element
Syntax 2 (actions): https://www.home-assistant.io/docs/scripts/conditions/#state-condition

Now in this case, it is completely reasonable to expect elements configuration to just work. For card automations, it's completely reasonable for actions based configuration to just work. Thinking...
