### ISSUE TITLE
Menu buttons don't always load

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#1563]
**Checklist:**

- [x] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
[v6.0.0-beta.2](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.2)
**Last working release (if known):**
[v5.2.0](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v5.2.0)
**Browser and Operating System:**
Brave/Firefox/Chrome - macOS

**Description of problem:**

I'm noticing the menu buttons don't **always** load. Sometimes it's just the camera image with no buttons (gallery, microphone, mute etc) 
Other times the menu buttons do load.

**Frigate card diagnostic information**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: dev+7fd6bc6 (Sat, 21 Sep 2024 23:08:09 GMT)
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/129.0.0.0 Safari/537.36
date: 2024-09-22T10:02:40.469Z
frigate_versions:
  b06f31dd16de1de1232765ab7d700def: 5.4.0/0.14.1-f4f3cfa
  6f4aca1bfa2cdd2f7d9ddb41662fdde6: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: Europe/London
git:
  hash: 7fd6bc6
  build_date: Sat, 21 Sep 2024 23:08:09 GMT
  commit_date: Sat, 21 Sep 2024 15:39:18 -0700
ha_version: 2024.9.2
config:
  type: custom:frigate-card
  cameras:
    - live_provider: go2rtc
      frigate:
        camera_name: frontdoor-gif-notifications
      camera_entity: camera.frontdoor
      webrtc_card:
        url: rtsp://192.168.0.22:8554/frontdoor?video=all&audio=all
        ui: false
        muted: true
      go2rtc:
        stream: frontdoor-audio
        modes:
          - webrtc
      triggers:
        entities:
          - binary_sensor.frontdoor_visitor
  view:
    default: live
    camera_select: live
    triggers:
      actions:
        trigger: live
      filter_selected_camera: false
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '4:3'
  live:
    controls:
      thumbnails:
        mode: none
        events_media_type: clips
      next_previous:
        style: none
      timeline:
        mode: none
      builtin: false
    show_image_during_load: true
    draggable: false
    zoomable: false
    preload: false
    lazy_unload:
      - hidden
  media_viewer:
    controls:
      thumbnails:
        mode: none
        show_timeline_control: false
      next_previous:
        style: chevrons
      builtin: true
    transition_effect: slide
    draggable: false
    zoomable: false
    lazy_load: true
    auto_mute:
      - hidden
  menu:
    buttons:
      frigate:
        enabled: true
      live:
        enabled: true
      clips:
        enabled: true
      snapshots:
        enabled: false
      download:
        enabled: true
      fullscreen:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      image:
        enabled: false
      camera_ui:
        enabled: false
      cameras:
        enabled: false
      recordings:
        enabled: false
      substreams:
        enabled: false
      expand:
        enabled: false
      microphone:
        enabled: true
        priority: 42
        alignment: opposing
        type: toggle
      mute:
        enabled: true
        alignment: opposing
    style: overlay
    position: right
  elements:
    - type: custom:frigate-card-conditional
      conditions:
        - condition: view
          views:
            - live
      elements:
        - type: custom:frigate-card-menu-submenu
          priority: 0
          icon: mdi:package-variant
          items:
            - title: Package at Door
              icon: mdi:door
              tap_action:
                action: perform-action
                data:
                  option: >-
                    Hi, please leave the package at the door. We will get it
                    later.
                  device_id: 4a8144c81df070f0055bcf9d0c65af32
                perform_action: select.select_option
            - title: Package in Bin
              icon: mdi:trash-can-outline
              tap_action:
                action: perform-action
                data:
                  option: Package recycling bin or bike cover
                  device_id: 4a8144c81df070f0055bcf9d0c65af32
                perform_action: select.select_option
  media_gallery:
    controls:
      thumbnails:
        show_details: false
        show_favorite_control: true
        show_timeline_control: false
      filter:
        mode: none
  performance: {}
  status_bar:
    style: none
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

<img width="462" alt="Screenshot 2024-09-22 at 11 00 40" src="https://github.com/user-attachments/assets/e9b4caad-ddb6-43df-b157-2203a6e2087e">
