### ISSUE TITLE
Untriggering does not reset to default camera

### ISSUE THREAD

**Issue by EPiSKiNG** [dermotduffy/frigate-hass-card#1564]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:** - 6.0.0-beta.2

**Last working release (if known):** 5.2.0?

**Browser and Operating System:** - Edge/Chrome/HA App.

**Description of problem:**

When using triggers to select camera based on occupancy/motion, the live camera does switch to the proper camera, but does not reset to default when occupancy/motion clears.  I would expect it to swap back to primary camera when untriggered, or at least after the untrigger_seconds time passes.

**Frigate card diagnostic information**

```yaml

card_version: dev+7fd6bc6 (Sat, 21 Sep 2024 23:08:09 GMT)
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
date: 2024-09-22T17:59:50.719Z
frigate_versions:
  33b94b614d9a45ff24f7de852bbbb308: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: America/Los_Angeles
git:
  hash: 7fd6bc6
  build_date: Sat, 21 Sep 2024 23:08:09 GMT
  commit_date: Sat, 21 Sep 2024 15:39:18 -0700
ha_version: 2024.9.2
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front_walkway
    - camera_entity: camera.driveway
    - camera_entity: camera.front_door
    - camera_entity: camera.living_room_slider
    - camera_entity: camera.bedroom_slider
    - camera_entity: camera.side_yard
    - camera_entity: camera.pergola
      triggers:
        entities:
          - binary_sensor.0x3425b4fffe64e3f0_occupancy
  cameras_global:
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  view:
    triggers:
      actions:
        trigger: live
        untrigger: default
        interaction_mode: all
      filter_selected_camera: false
      untrigger_seconds: 10
    default_reset:
      interaction_mode: all
    default: live
    camera_select: live
  menu:
    buttons:
      substreams:
        icon: mdi:high-definition
        priority: 100
      frigate:
        enabled: false
      cameras:
        enabled: false
      live:
        enabled: false
      clips:
        enabled: false
      snapshots:
        enabled: false
      recordings:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      expand:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
  live:
    transition_effect: none
    controls:
      thumbnails:
        mode: below
        show_favorite_control: false
        show_timeline_control: false
        show_download_control: false
    preload: true
    auto_play:
      - selected
      - visible
  visibility:
    - condition: numeric_state
      entity: sensor.sun_solar_elevation
      above: -4
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '16:11'
  status_bar:
    style: none

```
