### ISSUE TITLE
Appears to only show up in a single column on a dashboard

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#1580]
@dermotduffy : Thanks it work! One question: After I upgraded all my cards, i noticed that they are all visible in a single column on my desktop (where i expect at least 3 rows). In the raw Yaml I see a GRID statement while in UI mode it is not visible. Strange. Have you also noted that too?

_Originally posted by @S-Przybylski in https://github.com/dermotduffy/frigate-hass-card/issues/1547#issuecomment-2371210399_

**Comment by dermotduffy** [comment]
### Picture Glance

![image](https://github.com/user-attachments/assets/50b39b2e-df6c-4ab7-8090-0a702a6e0574)

### Frigate Card

![image](https://github.com/user-attachments/assets/8a6f54c0-87c5-43e2-83fb-047221c9af5f)

#### Config

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
view:
  default: image
image:
  mode: screensaver
```
