### ISSUE TITLE
Events drawer scroll position is incorrect

### ISSUE THREAD

**Issue by flyize** [dermotduffy/frigate-hass-card#1600]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Any v6
**Last working release (if known):**
v5
**Browser and Operating System:**
Tried on Windows/Edge as well as the Android app

**Description of problem:**

No events show when tapping the hamburger button on the right of the camera view
**Frigate card diagnostic information**

```yaml
card_version: 6.0.0-beta.4
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
date: 2024-09-30T19:12:54.948Z
frigate_versions:
  4030ef078ae309891cae35223c7c2fc3: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: America/Chicago
git:
  hash: d907ace
  build_date: Sat, 28 Sep 2024 20:41:35 GMT
  commit_date: Fri, 27 Sep 2024 18:56:59 -0700
ha_version: 2024.9.3
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front_door_cam
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
https://i.imgur.com/RVhwx8d.png
