### ISSUE TITLE
PTZ buttons are shown in all cameras in grid mode even if they do not support it

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1608]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 6.0.0

**Last working release (if known):** N/A

**Browser and Operating System:** N/A

**Description of problem:**

In grid mode, when the selected camera is PTZ capable, all other cameras will also show PTZ buttons.

https://github.com/user-attachments/assets/d23cd40f-d604-4b2a-9e4b-195ca49968de

**Frigate card diagnostic information**

N/A

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

Config:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.video_porteiro
  - camera_entity: camera.rua
    ptz:
      presets:
        home:
          action: perform-action
          perform_action: frigate.ptz
          data:
            entity_id: camera.rua
            action: preset
            argument: "1"
  - camera_entity: camera.camera_01
  - camera_entity: camera.camera_02
  - camera_entity: camera.camera_03
  - camera_entity: camera.camera_04
  - camera_entity: camera.camera_05
  - camera_entity: camera.camera_06
  - camera_entity: camera.camera_07
  - camera_entity: camera.camera_08
  - camera_entity: camera.camera_09
  - camera_entity: camera.camera_10
  - camera_entity: camera.camera_11
  - camera_entity: camera.camera_12
  - camera_entity: camera.camera_13
  - camera_entity: camera.camera_14
  - camera_entity: camera.camera_15
  - camera_entity: camera.camera_16
cameras_global:
  live_provider: go2rtc
  image:
    refresh_seconds: 1
  dimensions:
    aspect_ratio: "16:9"
live:
  draggable: true
  show_image_during_load: true
  controls:
    builtin: false
    ptz:
      position: bottom-left
      hide_zoom: true
      hide_home: true
  lazy_unload:
    - unselected
    - hidden
  auto_play:
    - selected
    - visible
  display:
    mode: grid
menu:
  buttons:
    cameras:
      alignment: opposing
      priority: 49
    snapshots:
      enabled: false
    mute:
      enabled: true
    fullscreen:
      alignment: opposing
    display_mode:
      alignment: opposing
profiles:
  - low-performance
```
