### ISSUE TITLE
Add example to documentation for a camera that is a go2rtc stream only

### ISSUE THREAD

**Issue by pergolafabio** [dermotduffy/frigate-hass-card#1609]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**  6.0.beta5

**Last working release (if known):**

**Browser and Operating System:** Chrome

**Description of problem:**

Hi; im testing your frigate card beta 5, it allows to use go2rtc camera streams, but i'm not sure if the correct syntax is right? I dont have an camera entity in HA, i want to use the stream directly, but i get the error in below screenshot
Testing the stream directly in go2rtc does work

**Frigate card diagnostic information**

```
        - type: custom:frigate-card
          cameras:
            - live_provider: go2rtc
              go2rtc:
                # modes:
                  # - mse
                stream: tuya_pepe_sale
```

**Additional information:**

![image](https://github.com/user-attachments/assets/b24fea02-6727-4fa6-92fb-ed08386d9cb4)

**Comment by pergolafabio** [comment]
tried also like below, but gives a black screen

```
        - type: custom:frigate-card
          cameras:
            - go2rtc:
                url: https://xxx
                stream: tuya_pepe_sale
```

**Comment by dermotduffy** [comment]
You are telling the card what live video provider to use, but not what kind of camera to use ("camera engine"). Normally, you'd give it an entity and it can figure it out from that, if you don't give an entity you need it extra information. Since you're using go2rtc, I assume this is a Frigate camera? Try something like this:

```yaml
type: custom:frigate-card
cameras:
  - engine: frigate
    frigate:
      camera_name: office
    go2rtc:
      stream: office
```
