### ISSUE TITLE
In grid mode the non-selected cameras disappear

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#1610]

**Comment by dermotduffy** [comment]
Only seems to be with the `go2rtc` live provider, and only with the `webrtc` mode.

**Comment by conorlap** [comment]
I'm noticing this too (I think) in regular view (not grid mode)! with `go2rtc` live provider and `webrtc` mode. 
Problem: Occasionally if I'm going between views in the Home Assistant dashboard the frigate card is black/blank upon return to my main view with the camera card. The live view only returns when I click the Live View icon but looks like it's already been loaded as it appears instantly after the click. 

```
type: custom:frigate-card
cameras:
  - live_provider: go2rtc
    frigate:
      camera_name: frontdoor-gif-notifications
    camera_entity: camera.frontdoor
    webrtc_card:
      url: rtsp://192.168.0.22:8554/frontdoor?video=all&audio=all
      ui: false
      muted: true
    go2rtc:
      stream: frontdoor-audio
      modes:
        - webrtc
    triggers:
      entities:
        - binary_sensor.frontdoor_visitor
view:
  triggers:
    actions:
      trigger: live
    filter_selected_camera: false
    show_trigger_status: true
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: "4:3"
live:
  controls:
    thumbnails:
      mode: none
      events_media_type: clips
    next_previous:
      style: none
    timeline:
      mode: none
    builtin: false
  show_image_during_load: true
  draggable: false
  zoomable: false
  preload: true
  lazy_unload:
    - hidden
  auto_play:
    - selected
    - visible
  lazy_load: true
media_viewer:
  controls:
    thumbnails:
      mode: none
      show_timeline_control: false
    next_previous:
      style: chevrons
    builtin: true
  transition_effect: slide
  draggable: false
  zoomable: false
  lazy_load: true
  auto_mute:
    - hidden
menu:
  buttons:
    frigate:
      enabled: false
    live:
      enabled: true
    clips:
      enabled: true
    snapshots:
      enabled: false
    download:
      enabled: true
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    image:
      enabled: false
    camera_ui:
      enabled: false
    cameras:
      enabled: false
    recordings:
      enabled: false
    substreams:
      enabled: false
    expand:
      enabled: false
    microphone:
      enabled: true
      priority: 42
      alignment: opposing
      type: toggle
    mute:
      enabled: true
      alignment: opposing
  style: overlay
  position: right
elements:
  - type: custom:frigate-card-conditional
    conditions:
      - condition: view
        views:
          - live
    elements:
      - type: custom:frigate-card-menu-submenu
        priority: 0
        icon: mdi:package-variant
        items:
          - title: Package at Door
            icon: mdi:door
            tap_action:
              action: perform-action
              data:
                option: >-
                  Hi, please leave the package at the door. We will get it
                  later.
                device_id: 4a8144c81df070f0055bcf9d0c65af32
              perform_action: select.select_option
          - title: Package in Bin
            icon: mdi:trash-can-outline
            tap_action:
              action: perform-action
              data:
                option: Package recycling bin or bike cover
                device_id: 4a8144c81df070f0055bcf9d0c65af32
              perform_action: select.select_option
media_gallery:
  controls:
    thumbnails:
      show_details: false
      show_favorite_control: true
      show_timeline_control: false
    filter:
      mode: none
performance: {}
status_bar:
  style: none

```
