### ISSUE TITLE
PT and Home buttons arenot displayed since beta6

### ISSUE THREAD

**Issue by Cheerpipe** [dermotduffy/frigate-hass-card#1629]
**Checklist:**

- [x] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** v6.0.0-beta.6 and v6.0.0-beta.7

**Last working release (if known):** v6.0.0-beta.5

**Browser and Operating System:** 

- Edge Chromium 130.0.2849.27 - Windows 11
- Google Chrome 129.0.6668.90 - Windows 11
- Google Chrome on Android.

**Description of problem:** PT and Home buttons arenot displayed since beta6. As a workaround, downgrading to beta 5 fix the problem.

**Frigate card diagnostic information**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.0.0-beta.7
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
date: 2024-10-09T14:43:27.904Z
frigate_versions:
  2b2acf3b1e1c825812c148500c75bbfc: 5.4.0/0.15.0-849d441
lang: es
timezone: America/Santiago
git:
  hash: '736e043'
  build_date: Wed, 09 Oct 2024 03:38:10 GMT
  commit_date: Tue, 8 Oct 2024 20:35:31 -0700
ha_version: 2024.10.0
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frigate_salon
      live_provider: go2rtc
      triggers:
        occupancy: false
      go2rtc:
        modes:
          - webrtc
        stream: salon_sub
  live:
    draggable: false
    zoomable: true
    lazy_load: true
    controls:
      next_previous:
        style: none
      thumbnails: {}
      ptz:
        orientation: horizontal
        style:
          transform: none
          right: 5%
          bottom: 40%
        hide_zoom: true
    preload: true
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '16:9'
  view:
    triggers:
      show_trigger_status: false
    default_cycle_camera: false
  elements:
    - type: custom:frigate-card-menu-state-icon
      entity: switch.camara_salon_infrared
      icon: mdi:weather-night
      tap_action:
        action: perform-action
        data:
          entity_id: switch.camara_salon_infrared
        perform_action: switch.toggle
```

**Javascript errors shown in the web inspector (if applicable):**

```
no errors
```

**Additional information:**

*Frigate PTZ info:*

```
{
    "name": "salon",
    "features": [
        "pt"
    ],
    "presets": [
        "home"
    ]
}
```
