### ISSUE TITLE
[Bug]: Menu style hidden and custom frigate icon

### ISSUE THREAD

**Issue by AntoineGauthier** [dermotduffy/frigate-hass-card#1632]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v5.2.0

**Description of problem:**

Hello,

The frigate button doesn't seem to accept custom icon while the menu style is declared as hidden. The menu just never seem to load.

Here is the configuration I'm referring to : 
```yaml
type: custom:frigate-card
menu:
  style: hidden
  position: bottom
  alignment: left
  buttons:
    frigate:
      enabled: true
      priority: 100
      icon: mdi:menu
```
Any other menu style seem to be fine though, ie : 
```yaml
type: custom:frigate-card
menu:
  style: overlay
  position: bottom
  alignment: left
  buttons:
    frigate:
      enabled: true
      priority: 100
      icon: mdi:menu
```

Am I missing something ? 
Thanks for your help
