### ISSUE TITLE
PTZ control not appearing on card

### ISSUE THREAD

**Issue by ihaettypo** [dermotduffy/frigate-hass-card#1634]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v5.2.0

**Last working release (if known):** no

**Browser and Operating System:** Safari & Chrome, macos 15

**Description of problem:**

From the [documentation](https://card.camera/#/examples?id=ptz-control) it says:

> Note that if your camera engine supports it (e.g. frigate) this will just work out of the box with no configuration at all.

And my camera does have the PTZ capability and the PTZ controls is showing up and working in the Frigate's web UI, however when I add this camera to frigate card in Homeassistant, the PTZ control just won't appear.

My camera is set up with the Frigate integration (go2rtc restream).

**Frigate card diagnostic information**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.10.0",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15",
  "date": "2024-10-12T05:30:33.819Z",
  "frigate_version": {
    "01J7ZC96JPEQC96611DN0QKJCV": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "Asia/Manila",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.basement_camera",
        "live_provider": "go2rtc"
      }
    ],
    "live": {
      "preload": false,
      "draggable": false,
      "zoomable": false
    },
    "layout_options": {
      "grid_columns": 8,
      "grid_rows": 4
    }
  }
}

```

**Javascript errors shown in the web inspector (if applicable):**

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (webrtc-camera.js, line 0)
[Error] Unhandled Promise Rejection: https://192.168.100.1:8123/webrtc/webrtc-camera.js?v=v3.5.2
```

**Additional information:**
