### ISSUE TITLE
PTZ Control Not Displayed

### ISSUE THREAD

**Issue by totalitarian** [dermotduffy/frigate-hass-card#1638]
Any idea why my PTZ controls don't appear?

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cp1_2
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
live:
  auto_unmute: all
  controls:
    thumbnails:
      mode: none
    ptz:
      mode: auto
      position: bottom-right
      orientation: horizontal
      hide_pan_tilt: false
  ptz:
    data_left:
      entity_id: camera.cp1_2
      direction: left
      speed: 5
    data_right:
      entity_id: camera.cp1_2
      direction: right
      speed: 5
    data_up:
      entity_id: camera.cp1_2
      direction: up
      speed: 5
    data_down:
      entity_id: camera.cp1_2
      direction: down
      speed: 5
menu:
  buttons:
    clips:
      enabled: false
    frigate:
      enabled: false
    microphone:
      enabled: false
      alignment: matching
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    camera_ui:
      enabled: true
  style: overlay
  position: right
```
