### ISSUE TITLE
Clicking non-event area in timeline does not open proper video feed and time

### ISSUE THREAD

**Issue by bikemike** [dermotduffy/frigate-hass-card#1648]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/129.0.0.0 Safari/537.36
date: 2024-10-16T11:20:03.353Z
frigate_versions:
  2fc97ec23d4ebf918965a8977d7b7723: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: America/Vancouver
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.9.3
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.birdseye
      live_provider: webrtc-card
      go2rtc:
        modes: []
      webrtc_card:
        url: birdseye
      frigate: {}
    - camera_entity: camera.front_yard
      go2rtc:
        modes:
          - webrtc
        stream: front_yard_high
      live_provider: webrtc-card
      webrtc_card:
        url: front_yard_high
    - camera_entity: camera.doorbell
      go2rtc:
        stream: doorbell_high
        modes:
          - webrtc
      live_provider: webrtc-card
      webrtc_card:
        url: doorbell_high
    - camera_entity: camera.coopcam
      live_provider: webrtc-card
      go2rtc:
        modes:
          - webrtc
        stream: coopcam_high
      webrtc_card:
        url: coopcam_high
    - camera_entity: camera.violetcam
      live_provider: go2rtc
      capabilities:
        disable_except:
          - substream
  menu:
    buttons:
      media_player:
        enabled: false
        priority: 50
      mute:
        enabled: true
  live: {}
  cameras_global:
    dimensions:
      layout: {}

```

**[REQUIRED] Description of problem:**

Clicking on a non-event period in the timeline does not open the proper video feed or the proper time.

In the screen capture I click on Coopcam at approximately  03:45 but the video feed that comes up is Doorbell at 03:00.

https://github.com/user-attachments/assets/5d17492e-23a8-44e2-ae79-9e7d80ddfbf1

**[OPTIONAL] Last working release (if known):**

5.2

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
