### ISSUE TITLE
Option to prevent provider from rendering if entity is specified but `unavailable`

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1650]
**[REQUIRED] Card diagnostic information:**

N/A

**[REQUIRED] Description of problem:**

When a camera entity is unavailable, the card renders the following:

![image](https://github.com/user-attachments/assets/a3283cb0-2698-4ee6-95a0-38e10b546216)

Which is nice.

However, when go2rtc is set as the live provider for the camera, such screen is not triggered even when the camera entity is unavailable:

![image](https://github.com/user-attachments/assets/2e23f140-61c2-4bc1-9f63-40d693c540e6)

**[OPTIONAL] Last working release (if known):**

N/A

**[OPTIONAL] Javascript errors shown in the web inspector:**

N/A

**[OPTIONAL] Additional information:**

Example config:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.camera_03
    live_provider: go2rtc
```

I believe the easiest way to make the camera entity become unavailable is perhaps by forcing its state in the Home Assistant developer tools.

**Comment by dermotduffy** [comment]
The issue here is that I don't want providers to depend on entities unless absolutely necessary (e.g. using `go2rtc` without an entity is not uncommon).

Technically `go2rtc` does not really use a camera_entity at all, which is why this does not currently happen. The only usage is getting the real Frigate camera name from it on camera initialization, and then that is used to identify the go2rtc stream name later (none of which cares whether the entity to be available or not).

Lets imagine this case:

```yaml
cameras:
  - camera_entity: camera.office
    frigate:
      camera_name: office
    go2rtc:
      stream: office_stream
```

Should the unavailable error be shown if the entity is unavailable? I would argue not as the live_provider does not actually care. One option could be to show it as unavailable if _only_ the entity is specified, but that's harder than it looks since the live provider cannot currently tell the difference between the `camera_name` being manually set and being autodetected. I could implement this, but I'm not really sure it's worth it ...
