### ISSUE TITLE
Reolink Argus 4 Pro always active in the dashboard

### ISSUE THREAD

**Issue by He1no** [dermotduffy/frigate-hass-card#1651]
Hello.

I have a Reolink Argus 4 Pro. I transferred this to HA via the Reolink Hub. Is there a way to integrate the camera into a dashboard without it always being active? Since it is powered by solar, this is not optimal. I've already tried the settings. 

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.terrasse_fliessend
view:
  default: live
timeline: {}
live:
  auto_play: visible
  auto_pause: hidden
```

I hope you can help me.
