### ISSUE TITLE
PTZ controls appear but do not work

### ISSUE THREAD

**Issue by murmelbahn** [dermotduffy/frigate-hass-card#1652]
Diagnostic informations:

```yaml
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101
  Firefox/131.0
date: 2024-10-17T13:15:53.279Z
frigate_versions:
  01JAA653PXBZQE5T4113FW0CRA: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: Europe/Berlin
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.10.2
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.hasenstall_nord
```

**[REQUIRED] Description of problem:**

Hi,

The PTZ controls on the card are not functioning. However, when using the Frigate web interface, I can control the PTZ without any issues. The buttons for PTZ control do appear in the card on Home Assistant, but pressing them doesn't have any effect. Unfortunately, I'm not sure how to troubleshoot this further.

**Comment by aaronjrodrigues** [comment]
Having this same issue however I am not able to even see the buttons

**Comment by ThatBlockyPenguin** [comment]
> Having this same issue however I am not able to even see the buttons

Same here

**Comment by dermotduffy** [comment]
> but pressing them doesn't have any effect. 

I can reproduce this.

> Having this same issue however I am not able to even see the buttons

Please file a separate issue for this (the first question will be whether or not they work in the frigate UI). Lets keep this issue focused on "appearing but not doing anything".

**Comment by dermotduffy** [comment]
> I can reproduce this.

Actually, I think this might be related to the ongoing saga of https://github.com/dermotduffy/frigate-hass-card/issues/1678 at least as it pertains to the default live_provider. At least with HA `2024.11` the live camera isn't loading properly. But PTZ works fine on other live providers, e.g:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    live_provider: go2rtc
```

Try this @murmelbahn ?

**Comment by amadeo-alex** [comment]
hello, I seem to be facing the same issue, PTZ controls work fine within the Frigate interface but not from within the card
test config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.camera_3
    live_provider: go2rtc
```

additional thing I've noticed is that the frigate integration PTZ service calls also don't seem to function at all

**Comment by dermotduffy** [comment]
> additional thing I've noticed is that the frigate integration PTZ service calls also don't seem to function at all

The card is just calling those same service calls. I'd focus on getting them working first, the card cannot possibly work if they don't. Is there anything in your Frigate or Home Assistant logs when you try to call them?

**Comment by dermotduffy** [comment]
@murmelbahn Can you comment on whether or not this helps: 
https://github.com/dermotduffy/frigate-hass-card/issues/1652#issuecomment-2466555390

**Comment by dermotduffy** [comment]
Please re-open if you still have issues.

**Comment by Tintef** [comment]
Hi @dermotduffy, sorry for bringing the old issue back to life 😓 but I can't seem to get my PTZ controls to work on the card.

- Controls work fine on frigate, and I can see and use all my presets as well
- Controls show on the card, but they don't work (none of them)
- Also, on the card, I only see a `home` button, not all my presents, not sure how this should work tho.

This are my card diagnostics:
```
card_version: 6.0.0-beta.9
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-08T22:21:30.962Z
lang: en_GB
timezone: America/Montevideo
git:
  hash: b2b7a08
  build_date: Wed, 04 Dec 2024 04:35:32 GMT
  commit_date: Tue, 3 Dec 2024 20:26:56 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      01J2TA0J3ZGH65WNX9RGJE0STJ: 5.5.1/0.14.0-da913d8
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front
      live_provider: go2rtc
    - camera_entity: camera.gate
      live_provider: go2rtc
    - camera_entity: camera.garden
      live_provider: go2rtc
    - camera_entity: camera.dogcam
      live_provider: go2rtc
    - camera_entity: camera.ptz
      live_provider: go2rtc
  view:
    default: live
    camera_select: live
    dark_mode: 'on'
```

> Note: I don't have the Reolink integration installed or a Replink device yet (I'll add a doorbell in a few weeks) so I'm not sure why it's reporting as detected.


I tried debugging this a bit with the chrome devtools, and I noticed that at least the events that I want to do some action is getting to an `executePTZAction` function:

```
    async executePTZAction(e, t, n) {
        const a = this._store.getCameraConfig(e);
        if (!a)
            return;
        const i = q_(a, t, n);
        if (i)
            return await this._api.getActionsManager().executeActions(i);
        const r = this._api.getHASSManager().getHASS()
          , o = this._store.getEngineForCameraID(e);
        return o && r ? await this._requestLimit.add(( () => o.executePTZAction(r, a, t, n))) : void 0
    }
```

Where:

```
e = "camera.ptz"
n = { phase: "start", preset: undefined }
t = "right"
```
