### ISSUE TITLE
How to get audio on the live view?

### ISSUE THREAD

**Issue by akcasoy** [dermotduffy/frigate-hass-card#1655]
**[REQUIRED] Card diagnostic information:**

```
{
  "ha_version": "2024.10.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
  "date": "2024-10-22T14:42:39.003Z",
  "frigate_version": {
    "01JAR2AQ33X1B3FZ52TGCYEKTE": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "de",
  "timezone": "Europe/Berlin",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ]
        }
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true
        }
      }
    }
  }
}
```

**[REQUIRED] Description of problem:**

I am **not** trying to have a 2-way-audio, which is way more complicated than i expected, especially with my Reolink Doorbell (on the newest Firmwares).

I just want to **get audio on the live view on my Home Assistant Frigate Lovelace Card**.  On Frigate UI, when i click on a cam, i have audio (I have defined the live stream in frigate config). But not on the HA Card.

I have a simple form of frigate-card config:
```
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
  menu:
    buttons:
      microphone:
        enabled: true
```

This is how the card looks like now (i do not have any progress bar or speaker icon):
![Card1](https://github.com/user-attachments/assets/7bce6c3a-4115-4875-bb79-e96319889fed)

My Recordings have audio. I can also scroll through those alerts on this card, and have audio while playing those. At this time, the card is shown a bit different to me: smaller timestamp, and with a media player progress bar, there i can also control the volume:
![audio1](https://github.com/user-attachments/assets/120d44d0-520d-473b-922d-81677797c1e5)
![audio2](https://github.com/user-attachments/assets/660c2d48-5768-4a9e-8d91-7a1a420edce1)

And this is my Frigate config File:

```yaml
mqtt:
  host: 192.168.178.6
  user: xxxxxx
  password: xxxxxxx

audio:
  enabled: true

detect:
  enabled: true

record:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
    - cat
    - umbrella

go2rtc:
  streams:
    reolink_doorbell:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.178.114/Preview_01_sub
    reolink_doorbell_sub:
      - ffmpeg:http://192.168.178.114/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
  webrtc:
    candidates:
      - 192.168.178.13:8555
      - stun:8555

cameras:
  doorbell:
    live:
      stream_name: reolink_doorbell
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
version: 0.14
```

Could you please tell me what i am missing to get audio? I just want the audio always active when i open the card..
