### ISSUE TITLE
Can't show a custom action button just for a specific camera

### ISSUE THREAD

**Issue by akcasoy** [dermotduffy/frigate-hass-card#1656]
I am using the Release Version 5.2.0.

I would like to open the IR sensor of a camera out of my HA-Card. I have made a custom action button for that, but i do not want to display that all the time in the button-menu, but only when i switch to that specific camera.

I have tried this but somehow it does not work:

```
  elements:
    - type: custom:frigate-card-conditional
      conditions:
        - condition: camera
          cameras:
            - camera.my_cam  
      elements:
        - type: custom:frigate-card-menu-icon
          icon: mdi:track-light
          entity: switch.e1_zoom_infrarotlicht_im_nachtmodus
          tap_action:
            action: toggle
```

Without the condition, the inner part works alone:

```
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:track-light
    entity: switch.e1_zoom_infrarotlicht_im_nachtmodus
    tap_action:
      action: toggle
```

Edit:
I have now created a complete new dummy card, from the examples section, it does not work either. What can be wrong here? I think it is a bug:
<img width="1007" alt="Bildschirmfoto 2024-10-22 um 19 46 03" src="https://github.com/user-attachments/assets/8b881c61-9fbe-43ca-9141-55708c971206">
