### ISSUE TITLE
Can't mute a specific cam automatically when switching to it

### ISSUE THREAD

**Issue by akcasoy** [dermotduffy/frigate-hass-card#1658]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/17.5 Safari/605.1.15
date: 2024-10-23T07:02:07.046Z
frigate_versions:
  01JAR2AQ33X1B3FZ52TGCYEKTE: 5.4.0/0.14.1-f4f3cfa
lang: de
timezone: Europe/Berlin
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.10.1
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        stream: reolink_doorbell
    - camera_entity: camera.defne_cam
      live_provider: go2rtc
      go2rtc:
        stream: reolink_e1_zoom
  menu:
    buttons:
      camera_ui:
        enabled: false
      cameras:
        enabled: false
      snapshots:
        enabled: false
      timeline:
        enabled: false
      frigate:
        enabled: true
      download:
        enabled: false
      media_player:
        enabled: false
      display_mode:
        enabled: false
      mute:
        enabled: true
        alignment: opposing
    style: outside
    position: bottom
    button_size: 40
  live:
    controls:
      next_previous:
        style: chevrons
      builtin: false
      thumbnails:
        mode: none
    preload: true
    transition_effect: slide
  dimensions: {}
  status_bar:
    style: none
  media_gallery:
    controls:
      thumbnails:
        size: 140
        show_favorite_control: false
        show_timeline_control: false
        show_download_control: false
      filter:
        mode: none
  performance:
    profile: high
  automations:
    - conditions:
        - condition: camera
          cameras:
            - camera.doorbell
      actions:
        - action: custom:frigate-card-action
          frigate_card_action: unmute
      actions_not:
        - action: custom:frigate-card-action
          frigate_card_action: mute
  elements:
    - type: custom:frigate-card-conditional
      conditions:
        - condition: camera
          cameras:
            - camera.defne_cam
      elements:
        - type: custom:frigate-card-menu-state-icon
          icon: mdi:ceiling-light
          entity: light.hue_white_lamp_kinderzimmer
          tap_action:
            action: toggle
        - type: custom:frigate-card-menu-state-icon
          icon: mdi:track-light
          entity: switch.e1_zoom_infrarotlicht_im_nachtmodus
          tap_action:
            action: toggle
```

**[REQUIRED] Description of problem:**

I have 2 cameras, and i want to hear sounds from the first camera "camera.doorbell" automatically (unmute). And as soon as i switch to the 2. camera it should mute. So this works as expected.
**But when i switch to the first camera again, it should again unmute. And this part does not work.** See the video below.

```
  automations:
    - conditions:
        - condition: camera
          cameras:
            - camera.doorbell
      actions:
        - action: custom:frigate-card-action
          frigate_card_action: unmute
      actions_not:
        - action: custom:frigate-card-action
          frigate_card_action: mute
```

https://github.com/user-attachments/assets/ccc2371a-3776-436d-a292-0b763cebc290

**Comment by dermotduffy** [comment]
I suspect the issue is the mute command is being processed before the media has loaded. Try this:

```yaml
automations:
  - conditions:
      - condition: camera
        cameras:
          - camera.back_yard
      - condition: media_loaded                 <----------------------- I added this condition
        media_loaded: true
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: unmute
    actions_not:
      - action: custom:frigate-card-action
        frigate_card_action: mute
```
