### ISSUE TITLE
webrtc mainstream does not work on Fire HD Tablet

### ISSUE THREAD

**Issue by akcasoy** [dermotduffy/frigate-hass-card#1660]
**[REQUIRED] Card diagnostic information:**

```yaml
{
  "ha_version": "2024.10.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
  "date": "2024-10-23T11:53:42.051Z",
  "frigate_version": {
    "01JAW7F0SF7AAWAFYP4K7Z7Z80": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "de",
  "timezone": "Europe/Berlin",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "go2rtc",
        "go2rtc": {
          "stream": "reolink_doorbell",
          "modes": [
            "webrtc"
          ]
        }
      }
    ]
  }
}
```

**[REQUIRED] Description of problem:**

My webrtc setup (go2rtc in mode webrtc) where i use my mainstream (2560*1920) from my doorbell **does work** on my browser and iPhone. But not on my Fire HD Tablet under Fully Kiosk. **Sub-stream works fine**. ([Here](https://github.com/AlexxIT/WebRTC/issues/459#issuecomment-1493069357) somebody says "_.. because the primary (main) stream resolution was too high to be displayed consistently on the FireHD._"). I do not know if that is really the case.. (MSE does work with this resolution, but choppy). 

When i google "webrtc fire hd", there are many similar issues in other sites (reddit etc.) where some suggest:

1- to use webrtc-card as "live_provider". This requires an additional installation and configuration of [AlexxIT's WebRTC Card](https://github.com/AlexxIT/WebRTC). Don't know if this works at the end..

2- to setup this card with **go2rtc in mode mse**. This results a choppy video on tablet (after some seconds the stream even stops), and it does not work on iPhones at all.

3- to use a substream for the tablet (which i do not want)

I just wanted to ask if there is someone who has a 4rd -better- option, or the 1. option running (optionally with reolink doorbell). 

It would be nice if someone can confirm if that problem still exists also with the v6 of this card (i am using the latest stable release build 5.2).

Thank you all.

**Comment by dermotduffy** [comment]
This is likely just related to the low power of the Fire tablet in question and high resolution streaming video.

For option 1: `webrtc-card` or `go2tc` should not really make any difference, as they both use `go2rtc` under the covers. 

You can try the low-performance profile of the card:

```
profiles:
  - low-performance
```

... but frankly if the tablet can't keep up the video, that's not likely to help much. You could try the `image` live_provider, you'll get 1 frame per second, and the tablet almost certainly will keep up, but it's only 1 FPS ...

You could experiment with lowering your camera resolution and see if the tablet keeps up better?

**Comment by akcasoy** [comment]
> You can try the low-performance profile of the card:

It still did not work.. btw. i am using v5.2 again.. i hope

```
profiles:
  - low-performance
```

is also valid for the v5.2?

**Comment by dermotduffy** [comment]
I would not recommend using anything lower than the v6 betas, as the v5 codebase is old. I hope v6 will be the stable release shortly.

**Comment by akcasoy** [comment]
ok thanks. 
btw. v6 with low-performance profile also did not bring much. I think i will have to play around with the resolution a bit.

Do you know if i can somewhere (probably in frigate config) define a 3rd stream option with dynamic scaling?

My Reolink provides just 2 streams (main and sub). Since my frigate should use the highest resolution, i would like to keep that parallel, and add a 3rd stream which has a better resolution than substream. 😕

**Comment by akcasoy** [comment]
I have found sth. like this in frigate config:

```yaml
# Optional: Live stream configuration for WebUI
live:
  stream_name: reolink_doorbell
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 20
```

so when i understand the documentation correctly, when i use this stream in my frigate-card like this:

```yaml
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        stream: reolink_doorbell
        modes:
          - webrtc
```

this should be underscaled version of my mainstream, is not it? But it does not work 😕 
I still see the full resolution of my mainstream..
