### ISSUE TITLE
Clips not loading with 0.15.0 Beta 1

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#1668]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases). ✅
- Please try clearing your browser cache. ✅

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/130.0.0.0 Safari/537.36
date: 2024-10-29T21:43:11.202Z
frigate_versions:
  b06f31dd16de1de1232765ab7d700def: 5.4.0/0.15.0-33825f6
  6f4aca1bfa2cdd2f7d9ddb41662fdde6: 5.4.0/0.15.0-33825f6
lang: en
timezone: Europe/London
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.10.4
config:
  type: custom:frigate-card
  cameras:
    - live_provider: go2rtc
      frigate:
        camera_name: frontdoor-gif-notifications
      camera_entity: camera.frontdoor
      webrtc_card:
        url: rtsp://192.168.0.22:8554/frontdoor?video=all&audio=all
        ui: false
        muted: true
      go2rtc:
        stream: frontdoor-audio
        modes:
          - webrtc
      triggers:
        entities:
          - binary_sensor.frontdoor_visitor
  view:
    triggers:
      actions:
        trigger: live
      filter_selected_camera: false
      show_trigger_status: true
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '4:3'
  live:
    controls:
      thumbnails:
        mode: none
        events_media_type: clips
      next_previous:
        style: none
      timeline:
        mode: none
      builtin: false
    show_image_during_load: true
    draggable: false
    zoomable: false
    preload: true
    lazy_unload:
      - hidden
    auto_play:
      - selected
      - visible
    lazy_load: true
  media_viewer:
    controls:
      thumbnails:
        mode: none
        show_timeline_control: false
      next_previous:
        style: chevrons
      builtin: true
    transition_effect: slide
    draggable: false
    zoomable: false
    lazy_load: true
    auto_mute:
      - hidden
    auto_unmute:
      - selected
      - visible
  menu:
    buttons:
      frigate:
        enabled: true
      live:
        enabled: true
      clips:
        enabled: true
      snapshots:
        enabled: false
      download:
        enabled: true
      fullscreen:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      image:
        enabled: false
      camera_ui:
        enabled: false
      cameras:
        enabled: false
      recordings:
        enabled: false
      substreams:
        enabled: false
      expand:
        enabled: false
      microphone:
        enabled: true
        priority: 42
        alignment: opposing
        type: toggle
      mute:
        enabled: true
        alignment: opposing
    style: overlay
    position: right
  elements:
    - type: custom:frigate-card-conditional
      conditions:
        - condition: view
          views:
            - live
      elements:
        - type: custom:frigate-card-menu-submenu
          priority: 0
          icon: mdi:package-variant
          items:
            - title: Package at Door
              icon: mdi:door
              tap_action:
                action: perform-action
                data:
                  option: >-
                    Hi, please leave the package at the door. We will get it
                    later.
                  device_id: 4a8144c81df070f0055bcf9d0c65af32
                perform_action: select.select_option
            - title: Package in Bin
              icon: mdi:trash-can-outline
              tap_action:
                action: perform-action
                data:
                  option: Package recycling bin or bike cover
                  device_id: 4a8144c81df070f0055bcf9d0c65af32
                perform_action: select.select_option
  media_gallery:
    controls:
      thumbnails:
        show_details: false
        show_favorite_control: true
        show_timeline_control: false
      filter:
        mode: none
  performance: {}
  status_bar:
    style: none

```

**[REQUIRED] Description of problem:**

I've updated my Frigate instance to 0.15.0 Beta 1. It fetches the thumbnails but clips no longer load.

 

https://github.com/user-attachments/assets/dfdf0732-0c28-46be-bd6b-151934cd9f11

**[OPTIONAL] Last working release (if known):**
0.14.1 
**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
