### ISSUE TITLE
Unable to see PTZ controls for cameras in frigate card

### ISSUE THREAD

**Issue by aaronjrodrigues** [dermotduffy/frigate-hass-card#1669]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases) - I'm already on the latest stable version.

- Please try clearing your browser cache - Done

**[REQUIRED] Card diagnostic information:**

```yaml

{
  "ha_version": "2024.10.4",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15",
  "date": "2024-10-31T08:55:59.385Z",
  "frigate_version": {
    "01J8Z24H54SV9D543G3R2HYMND": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "Asia/Johannesburg",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.entryway",
        "live_provider": "auto",
        "title": "Entryway"
      },
      {
        "camera_entity": "camera.kitchen_side",
        "live_provider": "auto",
        "title": "Kitchen Side"
      },
      {
        "camera_entity": "camera.dish_side",
        "live_provider": "auto",
        "title": "Dish Side"
      },
      {
        "camera_entity": "camera.aaron_backdoor",
        "live_provider": "auto",
        "title": "Aaron's Back Door"
      },
      {
        "camera_entity": "camera.imou_garden",
        "live_provider": "auto",
        "title": "Imou Garden"
      },
      {
        "camera_entity": "camera.aaron_room",
        "live_provider": "auto",
        "title": "Aaron's Room"
      },
      {
        "camera_entity": "camera.living_room",
        "live_provider": "auto",
        "title": "Living Room/Dining Room"
      },
      {
        "camera_entity": "camera.clothing_line",
        "live_provider": "auto",
        "title": "Clothing Line/Dog Cage"
      },
      {
        "camera_entity": "camera.open_area",
        "live_provider": "auto",
        "title": "Open Area"
      },
      {
        "camera_entity": "camera.garden",
        "live_provider": "auto",
        "title": "Garden"
      },
      {
        "camera_entity": "camera.roadside",
        "live_provider": "auto",
        "title": "Roadside"
      },
      {
        "camera_entity": "camera.gate",
        "live_provider": "auto",
        "title": "Gate"
      },
      {
        "camera_entity": "camera.rudolf_backyard",
        "live_provider": "auto",
        "title": "Rudolf's Backyard"
      },
      {
        "camera_entity": "camera.kitchen_garden",
        "live_provider": "auto",
        "title": "Kitchen Garden"
      },
      {
        "camera_entity": "camera.garage",
        "live_provider": "auto",
        "title": "Garage"
      }
    ],
    "live": {
      "preload": true
    },
    "performance": {
      "profile": "high"
    },
    "dimensions": {},
    "view": {
      "default": "live"
    },
    "menu": {}
  }
}
```

**[REQUIRED] Description of problem:**
I followed the frigate documentation to get PTZ working on my Imou cameras (aaron_room, imou_garden). I am able to control them using the frigate web ui however I am unable to see the PTZ options on frigate card on home assistant.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
