### ISSUE TITLE
"Position on the right" doesn't work with "outside menu"

### ISSUE THREAD

**Issue by liorfr-monday** [dermotduffy/frigate-hass-card#1670]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
{
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
  "date": "2024-11-01T18:43:40.883Z",
  "frigate_versions": {
    "01J9YK6B5Y1YMX42Q7S4KCE43G": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "Asia/Jerusalem",
  "git": {
    "build_version": "5.2.0-dev+gad1c323",
    "build_date": "Tue, 31 Oct 2023 21:19:55 GMT",
    "commit_date": "Tue, 31 Oct 2023 21:16:45 +0000"
  },
  "ha_version": "2024.10.4",
  "config": {
    "type": "custom:frigate-card",
    "style": "ha-card {\n  height: 100vh !important;\n  margin: 0 !important;\n  padding: 0 !important;\n}      \n",
    "cameras": [
      {
        "camera_entity": "camera.intercom_cam_2",
        "hide": false,
        "go2rtc": {
          "modes": []
        },
        "triggers": {
          "occupancy": false
        },
        "webrtc_card": {},
        "live_provider": "go2rtc"
      }
    ],
    "performance": {
      "features": {
        "animated_progress_indicator": false
      },
      "profile": "low"
    },
    "menu": {
      "style": "outside",
      "position": "right",
      "button_size": 50,
      "buttons": {
        "microphone": {
          "enabled": false,
          "type": "toggle"
        },
        "screenshot": {
          "enabled": false
        },
        "download": {
          "enabled": false
        },
        "fullscreen": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        },
        "clips": {
          "enabled": false
        },
        "live": {
          "enabled": false
        },
        "cameras": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        },
        "camera_ui": {
          "enabled": false
        }
      }
    },
    "live": {
      "auto_mute": "never",
      "controls": {
        "builtin": true,
        "title": {
          "mode": "none"
        }
      },
      "layout": {
        "fit": "fill"
      },
      "preload": true
    },
    "elements": [
      {
        "type": "custom:frigate-card-menu-icon",
        "icon": "mdi:volume-high",
        "tap_action": [
          {
            "action": "custom:frigate-card-action",
            "frigate_card_action": "unmute"
          }
        ]
      },
      {
        "type": "custom:frigate-card-menu-icon",
        "icon": "mdi:volume-off",
        "tap_action": [
          {
            "action": "custom:frigate-card-action",
            "frigate_card_action": "mute"
          }
        ]
      },
      {
        "type": "custom:frigate-card-menu-icon",
        "icon": "mdi:phone",
        "style": {
          "color": "green"
        },
        "entity": "lock.door_lock",
        "tap_action": {
          "action": "call-service",
          "service": "dahua.vto_open_door",
          "data": {
            "entity_id": "camera.front_intercom_main",
            "door_id": 1
          }
        }
      },
      {
        "type": "custom:frigate-card-menu-icon",
        "icon": "mdi:phone-hangup",
        "style": {
          "color": "red"
        },
        "tap_action": {
          "action": "call-service",
          "service": "automation.trigger",
          "data": {
            "entity_id": "automation.new_automation_2",
            "skip_condition": true
          }
        }
      }
    ],
    "dimensions": {
      "aspect_ratio_mode": "static",
      "aspect_ratio": "16:9"
    }
  }
}
```

**[REQUIRED] Description of problem:**

When I choose to show the menu buttons "Position on the right" with menu style "outside menu", the buttons are shown on the bottom.
When I change the menu style from "outside menu" to "overlay menu" the buttons are overlayed and also moved to the right position.
<img width="1003" alt="Screenshot 2024-11-01 at 20 50 20" src="https://github.com/user-attachments/assets/892c3616-0f3b-49bd-b1c2-882f95eddbb2">
<img width="1005" alt="Screenshot 2024-11-01 at 20 49 56" src="https://github.com/user-attachments/assets/18e1e6aa-da01-4a02-9582-21c6ec619f8a">

```text

```

**[OPTIONAL] Additional information:**
