### ISSUE TITLE
Allow arbitrary thumbnail size scaling

### ISSUE THREAD

**Issue by bob454522** [dermotduffy/frigate-hass-card#1676]
**[REQUIRED] Describe the feature you'd like:**

I love the media gallery (with options to strip everything except the image snapshots + update_seconds = 60) - its a great display on my various Crestron panels around my home to quickly see relevant , prior, action.

**Is there anyway to get the images ( `thumbnails:   size: 175` ) above the current max of 175px ?**

(if i try to go above that , the card throws an error,  This is expected as your Docs clearly state the maximum allowed is 175px)

the reason i want this - On one or 2 panels in particular, they are pretty far away in terms of distance from viewer, so right when you come into the home it would be nice to have some larger images so that from a distance you can quickly see some gallery images.

**[OPTIONAL] Describe alternatives you've considered:**

Ive tried modifying the CSS so i can then use card_mod, but i havent had success.
(any suggestions on this maybe?)

**[OPTIONAL] Additional context:**

example of what i run (this along with some derivatives of this - has worked GREAT for over a year on HA + my crestron panels)

```
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.alley_generator_hen
                hide: false
                dependencies:
                  all_cameras: true
              - camera_entity: camera.alley_rainbird_hen
              - camera_entity: camera.gate_back_hen
              - camera_entity: camera.pool_house_hen
              - camera_entity: camera.front_door_hen
              - camera_entity: camera.front_right_hen
              - camera_entity: camera.driveway_right_hen
              - camera_entity: camera.pump_pool_hen
            view:
              default: snapshots
              camera_select: snapshots
              update_seconds: 600
              update_force: true
              update_cycle_camera: false
            media_gallery:
              controls:
                filter:
                  mode: none
                thumbnails:
                  size: 175
                  show_favorite_control: false
                  show_timeline_control: false
                  show_download_control: false
            menu:
              style: none
              buttons:
                fullscreen:
                  enabled: true
                  priority: 50
                cameras:
                  enabled: false
                substreams:
                  enabled: false
                live:
                  enabled: false
                clips:
                  enabled: false
                snapshots:
                  enabled: true
                timeline:
                  enabled: true
                  priority: 56
                  alignment: matching
                expand:
                  enabled: true
              alignment: bottom
              position: bottom
            performance:
              profile: low
            dimensions:
              aspect_ratio_mode: dynamic
            live:
              lazy_load: false
              zoomable: false
```

thanks,
(I really love and enjoy your frigate card on HA , it's amazing the number of features you've packed into it!)
