### ISSUE TITLE
Grid view broken for version 6

### ISSUE THREAD

**Issue by gelato** [dermotduffy/frigate-hass-card#1684]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/18.0.1 Safari/605.1.15
date: 2024-11-11T21:59:00.170Z
frigate_versions:
  01J61YT17TQTTXGGM6F52W37GM: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: Europe/Simferopol
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.10.3
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.gates
      live_provider: go2rtc
      go2rtc:
        stream: gates_hq
        modes:
          - webrtc
      capabilities:
        disable: []
    - camera_entity: camera.dvor_gates
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: dvor_gates_hq
    - camera_entity: camera.door
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: door_hq
    - camera_entity: camera.dom2
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: dom2_hq
    - camera_entity: camera.street
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: street_hq
  live:
    preload: true
    auto_play:
      - visible
      - selected
    transition_effect: slide
    display:
      mode: grid
      grid_columns: 3
```

**[REQUIRED] Description of problem:**

Card is blinking (small side views blink and then disappear) for MS Edge, Brave, Chrome browsers (basically all chromium based), showing only the biggest, chosen, stream. Number of columns at that moment is 3, Windows OS. Firefox works fine, though. On macOS everything works fine even in chromium based browsers.
**[OPTIONAL] Last working release (if known):**
Any stable one
**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
Reproduced only in Windows (tried 2 different PCs)
