### ISSUE TITLE
Motion clips not playing in card

### ISSUE THREAD

**Issue by hiteshsharma** [dermotduffy/frigate-hass-card#1687]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/17.5 Safari/605.1.15
date: 2024-11-18T20:59:25.865Z
frigate_versions:
  01JA3JEMK27BDFG4XA97VS0W7P: 5.4.0/0.15.0-33825f6
lang: en
timezone: America/Los_Angeles
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.11.2
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
  menu:
    buttons:
      microphone:
        enabled: true
        type: toggle
      mute:
        enabled: true
      media_player:
        enabled: false
      timeline:
        enabled: false
      camera_ui:
        enabled: false
      download:
        enabled: false
      snapshots:
        enabled: false
      clips:
        enabled: false
      substreams:
        enabled: false
      cameras:
        enabled: false
      recordings:
        enabled: true
      fullscreen:
        enabled: true
      frigate:
        enabled: true
    position: bottom
    alignment: left
    style: outside
  live:
    controls:
      builtin: false
    lazy_load: false
    draggable: false
    preload: true
    show_image_during_load: false
    microphone:
      always_connected: true
      disconnect_seconds: 5
  layout_options:
    grid_columns: 6
    grid_rows: 7
```

**[REQUIRED] Description of problem:**

Motion Clips not playing. I see motion detected details in the right panel. It shows the thumbnail and timing, but when the card is clicked to play the clip, the clip never loads.

![image](https://github.com/user-attachments/assets/19f12c1c-341e-4c01-9332-01b9a4a43446)

**[OPTIONAL] Javascript errors shown in the web inspector:**
No JS errors

**[OPTIONAL] Additional information:**
Used to work before upgrading to the beta version recently. Upgraded to beta version to fix another issue that was reported in https://github.com/dermotduffy/frigate-hass-card/issues/1674
