### ISSUE TITLE
Hide Chevron Buttons (Camera Switching)

### ISSUE THREAD

**Issue by xip0rt** [dermotduffy/frigate-hass-card#1689]
**[REQUIRED] Describe the feature you'd like:**
We should be able to control visibility of the left/right chevron buttons that switch between cameras (when there are multiple camera entities on the card). They block a considerate portion of the view on smaller screens and are unnecessary for those who have drag/swipe enabled for the live cameras, or use the menu dropdown.

**[OPTIONAL] Describe alternatives you've considered:**
Visibility could even be controlled by the menu style setting (no menu/hover menu), or moved to the menu itself

**[OPTIONAL] Additional context:**
I can block the HTML elements on my browser, but I am unaware of a method to block them in the app.

**Comment by dermotduffy** [comment]
To disable the next/previous controls for both media viewing and live:

```yaml
media_viewer:
  controls:
    next_previous:
      style: none
live:
  controls:
    next_previous:
      style: none
```
