### ISSUE TITLE
Unable to find Frigate instance with ID: frigate

### ISSUE THREAD

**Issue by modem158** [dermotduffy/frigate-hass-card#1690]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.11.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "date": "2024-11-23T07:31:49.965Z",
  "frigate_version": {
    "01JD5HJ11DR6RSP67KEF6JA7SZ": "5.4.0/0.15.0-e76f4e9"
  },
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.alley"
      }
    ]
  }
}

```

**[REQUIRED] Description of problem:**

I can't get any streams to show up in the Frigate card.   I have the integration installed and I can see events coming in from MQTT.  I get the following error in my dashboard.

```
Failed to receive response from Home Assistant for request. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "request": {
    "type": "frigate/events/get",
    "instance_id": "frigate",
    "cameras": [
      "Alley"
    ],
    "limit": 50,
    "id": 60
  },
  "response": {
    "code": "not_found",
    "message": "Unable to find Frigate instance with ID: frigate"
  }
}
```

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

Hi All.  I've been using Frigate for a bit and up until now I've been grabbing my streams for my HA dashboard directly from the ReoLink integration.  In an effort to reduce the strain on the cameras I am trying to retrieve the substream from the re-streamer in Frigate.  I have the cameras setup using go2rtc with both main and sub streams.  Everything is working great in Frigate but I can't for the life of me get the streams to show up in HA card.  

As a side note when I click on camera.[alley/doorbell] in HA I just get a stale image and not a stream as I would expect.  

Any hel is greatly appreciated.  I'm sure I'm doing something stupid but for the life of me I can't figure it out.

Frigate card setup in HA.  

```
- type: custom:frigate-card
   cameras:
     - camera_entity: camera.doorbell
```
I've also tried this setup with the same result.
```
- type: custom:frigate-card
   cameras:
      - camera_entity: camera.doorbell
         live_provider: go2rtc
         stream:
           - Doorbell_sub
      - camera_entity: camera.alley
         live_provider: go2rtc
         stream:
           - Alley_sub
         live:
           display:
             mode: grid
```

**Comment by dermotduffy** [comment]
> "message": "Unable to find Frigate instance with ID: frigate"

The default Frigate instance usually has a client_id of `frigate`. For some reason this is not being found in your setup. Either the integration is installed incorrectly (I don't think it's this), or perhaps you have manually set your MQTT `client_id` value to something else in your Frigate config?

e.g. if you had this in your Frigate config:

```
mqtt:
  client_id: foo
```

... you'd need to tell the card with ...

```
- type: custom:frigate-card
   cameras:
      - camera_entity: camera.doorbell
        frigate:
          client_id: foo
```
