### ISSUE TITLE
Panel mode should not show scrollbars

### ISSUE THREAD

**Issue by Markus9955** [dermotduffy/frigate-hass-card#1692]
Hi

Thanks for the awesome card.

I have a number of tablets that display a camera live feed on a dashboard tab. 

At the moment the video is displayed as 100% width so i end up with a vertical scroll bar. What is the best way to make the video size the same as the available screen height below the tab icons so there are no scroll bars?

Sorry if I've posted this in the wrong place etc.

 I'm using 6.0.0-beta.8 of the card and 0.15.0-33825f6 of frigate.

**Comment by dermotduffy** [comment]
Hi @Markus9955 . Can you fill in the information requested in the template when you made this issue. I need it to try to reproduce your config and help. Thanks.

**Comment by dermotduffy** [comment]
Also a screenshot of what you mean (you can block out most of the actual image of course). Thanks.

**Comment by Markus9955** [comment]
Hi sorry, I didnt class it as a bug so clicked the create blank issue button.

Here is the diagnostics  yaml
```yaml
card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Linux; Android 14; SM-S911B Build/UP1A.231005.007; wv)
  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.108
  Mobile Safari/537.36 Home Assistant/2024.10.3-14058 (Android 14; SM-S911B)
date: 2024-11-24T23:44:28.065Z
frigate_versions:
  7c0c5e67aa8d26b84109a78b3ea0293d: 5.5.0/0.15.0-33825f6
lang: en
timezone: Europe/London
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.11.3
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.garden
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
```
