### ISSUE TITLE
Add card_mod examples back to docs

### ISSUE THREAD

**Issue by dnestico** [dermotduffy/frigate-hass-card#1693]
**[REQUIRED] Describe the feature you'd like:**

I'm still trying to figure out how to use card_mod with this card but I see the examples in the old docs has been removed.

**[OPTIONAL] Describe alternatives you've considered:**

ChatGPT, which hasn't helped me for my specific thing I'm tryna figure out.

**[OPTIONAL] Additional context:**

I'm trying to experiment with customization of this card with card_mod and target specific parts of the card, I figured out how to change the whole background of the card and the size, but I'm trying to just edit the "div.timeline" aka the mini timeline below the live view, so far I can't figure how to do it... pls help lol.

**My code**

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.garage
live:
  controls:
    builtin: false
    title:
      mode: none
    timeline:
      mode: below
      style: ribbon
      media: clips
menu:
  style: overlay
card_mod:
  style:
    frigate-card-surround-basic $:
      frigate-card-timeline-core $: |
        .timeline {
          background: red !important;
        }
```
