### ISSUE TITLE
Reolink live snapshot images don't update

### ISSUE THREAD

**Issue by haitham506** [dermotduffy/frigate-hass-card#1708]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0-beta.9
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
date: 2024-12-04T22:50:02.222Z
lang: en
timezone:
git:
  hash: b2b7a08
  build_date: Wed, 04 Dec 2024 04:35:32 GMT
  commit_date: Tue, 3 Dec 2024 20:26:56 -0800
ha_version: 2024.12.0
integrations:
  reolink:
    detected: true
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.garage_snapshots
      title: garage
      live_provider: ha
      image: {}
      triggers:
        occupancy: false
      webrtc_card: {}
      go2rtc:
        modes: []
      reolink: {}
  view:
    actions:
      double_tap_action:
        action: custom:frigate-card-action
        frigate_card_action: fullscreen
    default_reset:
      interaction_mode: all
  menu:
    button_size: 38
    buttons:
      frigate:
        enabled: true
      cameras:
        enabled: false
      media_player:
        enabled: false
      live:
        enabled: false
      screenshot:
        enabled: false
      fullscreen:
        enabled: false
    style: hover-card
  live:
    draggable: false
    zoomable: true
    lazy_load: false
    show_image_during_load: false
    controls: {}
  image: {}
  performance:
    style:
      border_radius: false
      box_shadow: false
    features:
      media_chunk_size: 500
  dimensions:
    aspect_ratio_mode: static
    aspect_ratio: '4:3'
  elements:
    - type: icon
      icon: mdi:garage-variant
      title: Close Garage
      style:
        right: 10px
        top: 10px
        color: rgba(255,255,255,1)
        background: rgba(10, 10, 10, 0.2)
        border-radius: 5px
        transform: scale(1.6,1.6)
      entity: switch.**
      tap_action:
        action: toggle
    - type: icon
      icon: mdi:garage-open-variant
      title: Open Garage
      style:
        right: 53px
        top: 10px
        color: rgba(255,255,255,1)
        background: rgba(10, 10, 10, 0.2)
        border-radius: 5px
        transform: scale(1.6,1.6)
      entity: switch.**
      tap_action:
        action: toggle
  status_bar:
    style: none
  timeline:
    show_recordings: true
```

**[REQUIRED] Description of problem:**

Hello,

Reolink Camera Stream ([Snapshots](https://www.home-assistant.io/integrations/reolink#:~:text=Snapshots%20Clear*%20(High%20resolution))) was working fine with HA 2024.10 but after updating to 2024.11 it stopped working I thought it is related to this issue #1678 ,but after updating to the latest HA 2024.12 it is still not working with the 5.2.0 card and with 6.0.0-beta.9 card.
I tried changing the live_provider to image in the card options, it shows the camera snapshots for a few seconds and then stops updating the snapshots.  + I have 4 cameras if I change all to live_provider: image same issue but sometimes just two of the cameras actually works fine only two random cameras not more.

**[OPTIONAL] Last working release (if known):**
HA 2024.10
5.2.0 Card

--

**Comment by dermotduffy** [comment]
> Reolink Camera Stream ([Snapshots](https://www.home-assistant.io/integrations/reolink#:~:text=Snapshots%20Clear*%20(High%20resolution))) was working fine with HA 2024.10 but after updating to 2024.11 it stopped working I thought it is related to this issue https://github.com/dermotduffy/frigate-hass-card/issues/1678 ,but after updating to the latest HA 2024.12 it is still not working with the 5.2.0 card and with 6.0.0-beta.9 card.

To make sure I understand, do you just the Home Assistant live stream? What if you open that same stream in Home Assistant outside of the card does that work (press 'e', find the entity in the list, see what loads)?

**Comment by pcartwright81** [comment]
This is my config

type: custom:frigate-card
cameras:
  - camera_entity: camera.driveway_camera_clear
view:
  default: live

If I go to the page after 1 second it will show blank and count.

<img width="546" alt="image" src="https://github.com/user-attachments/assets/81b6eb3d-d3ac-4b17-9ee8-0fb812cc6ff7">

The automatic provider does not work
live_provider: webrtc-card 
Makes my image work correctly, and removing that line blanks the image out immediately.

So this is my working config.

type: custom:frigate-card
cameras:
  - camera_entity: camera.driveway_camera_clear
    live_provider: webrtc-card
view:
  default: live

**Comment by dermotduffy** [comment]
> What if you open that same stream in Home Assistant outside of the card does that work (press 'e', find the entity in the list, see what loads)?

Would you mind answering this question? I'm trying to tell if the issue is the card, or Home Assistant.

**Comment by pcartwright81** [comment]
Just found this card today, and the regular camera cards are working correctly.  I do have issues with RSTP when I tried to install MotionEye.  RLC-810A has issues,   Reolink Video Doorbell PoE works great in automatic. 

I just realized that Home Assistant Video stream is probably being used for automatic.
<img width="761" alt="image" src="https://github.com/user-attachments/assets/57510753-971a-42c6-8b05-d56aa7cb51f4">
<img width="755" alt="image" src="https://github.com/user-attachments/assets/84640693-1a7c-43c3-badf-8546cd324d54">
Also here is the default card.

<img width="401" alt="image" src="https://github.com/user-attachments/assets/a9eb33f7-e3e8-4360-a744-b6e616ff1bde">

Interesting...This works
<img width="758" alt="image" src="https://github.com/user-attachments/assets/08fbe7bb-ddfa-408e-862f-74d5323785f6">

**Comment by dermotduffy** [comment]
> I just realized that Home Assistant Video stream is probably being used for automatic.

That's right.

On any Home Assistant dashboard, can you press 'e' on your keyboard, find the "broken" entity and tell me if the stream loads correctly?

**Comment by pcartwright81** [comment]
Yes, looks same as the default card.

**Comment by dermotduffy** [comment]
> Yes, looks same as the default card.

I don't know what the default card is. Do you mean it looks correct outside the card, but incorrect inside the card?

**Comment by dermotduffy** [comment]
Does anything show up on your Javascript console when you try to access the broken stream inside the Frigate card? You can see the console by pressing F12 in Chrome.

**Comment by pcartwright81** [comment]
No errors.

**Comment by dermotduffy** [comment]
Currently at a bit of a loss as to what's going on here, however the `beta.9` code includes lots of Reolink specific functionality for the first time (Reolink media viewing in card), and I wondering if that somehow broke the live stream, since you're both using Reolink cameras. 

Would you mind adding this to your config and see if it changes anything:

```
 cameras:
    - camera_entity: camera.garage_snapshots
      title: garage
      live_provider: ha
      engine: generic            <----------------------------- ADDED
```

This will tell the card to treat the camera like a "generic" camera and not something that gets special reolink functionality.

**Comment by pcartwright81** [comment]
Did not work for me.  There are a lot of new issues on the Reolink integration, and that is probably what broke the card.  Specifically, https://github.com/home-assistant/core/issues/130091 is of interest to me.  My core version is 2025.1.0.dev202412050235.  My card version is 5.2.0 so this is most likely a HA issue.

**Comment by dermotduffy** [comment]
> version is 5.2.0 so this is most likely a HA issue.

... oh, I missed that it's not associated with the new beta card release. I only have a single Reolink camera and hadn't ever enabled the '_snapshots' entities before. I see the same problem as you when I do after I enable them.

Looks like, for some reason, the snapshot associated with any of the cameras is not being updated.

Let me look into this more. Fundamentally, a premise I want to keep is: If it works in HA, it should work in the card. And that does not seem to happen here.

**Comment by Dieghito72** [comment]
> Currently at a bit of a loss as to what's going on here, however the `beta.9` code includes lots of Reolink specific functionality for the first time (Reolink media viewing in card), and I wondering if that somehow broke the live stream, since you're both using Reolink cameras.
> 
> Would you mind adding this to your config and see if it changes anything:
> 
> ```
>  cameras:
>     - camera_entity: camera.garage_snapshots
>       title: garage
>       live_provider: ha
>       engine: generic            <----------------------------- ADDED
> ```
> 
> This will tell the card to treat the camera like a "generic" camera and not something that gets special reolink functionality.

Not sure if it's related, but I'm using Reolink camera with WebRTC card and since beta 8 everything was OK. 
Today I updated to 6.0.0 official and all my Reolink live streams stopped working.

The card instead of live streams shows this error:
```
request:
  type: media_source/browse_media
  media_content_id: media-source://reolink/RES|XXXXXXXXXXXXXXXXX|0|sub
  id: 299
response:
  code: unknown_error
  message: Unknown error
```

Adding **engine: generic** to camera configuration fixed the problem.
