### ISSUE TITLE
custom:frigate-card-menu-icon state_color not reflected

### ISSUE THREAD

**Issue by danlo315** [dermotduffy/frigate-hass-card#1710]
```yaml
card_version: 6.0.0-beta.9
browser: Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
date: 2024-12-06T14:10:53.810Z
lang: en
timezone: America/New_York
git:
  hash: b2b7a08
  build_date: Wed, 04 Dec 2024 04:35:32 GMT
  commit_date: Tue, 3 Dec 2024 20:26:56 -0800
ha_version: 2024.12.0
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      279672cc46de4241ae0bae4d97d805c8: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.backyard_2
      live_provider: ha
      go2rtc:
        modes:
          - mp4
          - webrtc
          - mse
      image:
        mode: camera
      capabilities:
        disable:
          - ptz
  menu:
    style: hidden
    buttons:
      media_player:
        enabled: true
      clips:
        enabled: false
      snapshots:
        enabled: false
      cameras:
        enabled: false
      live:
        enabled: false
      mute:
        enabled: true
      expand:
        enabled: true
      fullscreen:
        enabled: false
      frigate:
        enabled: true
        icon: mdi:menu
    position: top
  view:
    default: live
  live:
    show_image_during_load: true
    controls:
      builtin: false
    zoomable: false
    lazy_load: false
  media_gallery:
    controls:
      thumbnails:
        show_timeline_control: false
        show_download_control: false
        show_favorite_control: false
  media_viewer:
    draggable: false
    zoomable: false
    lazy_load: false
    snapshot_click_plays_clip: false
    controls:
      builtin: false
  timeline:
    show_recordings: false
  performance: {}
  elements:
    - type: custom:frigate-card-menu-icon
      alignment: opposing
      permanent: false
      enabled: true
      entity: camera.backyard_2
      icon: mdi:video
      style:
        color: lightblue
      tap_action:
        action: navigate
        navigation_path: /lovelace/backyard-cam
    - type: custom:frigate-card-menu-icon
      entity: switch.backyard_detect
      alignment: opposing
      state_color: true
      icon: mdi:toggle-switch-outline
      tap_action:
        action: toggle
    - type: state-icon
      entity: switch.backyard_detect
      tap_action:
        action: toggle
      style:
        top: 90%
        left: 5%
        background: transparent
        '--paper-item-icon-color': white
    - type: icon
      icon: mdi:circle
      entity: switch.backyard_detect
      tap_action:
        action: toggle
      style:
        top: 90%
        left: 5%
        opacity: 40%
        transform: translate(-50%,-50%) scale(1.5,1.5)
    - type: state-icon
      entity: binary_sensor.backyard_motion_2
      style:
        top: 90%
        left: 40%
        background: transparent
        '--paper-item-icon-color': white
    - type: icon
      icon: mdi:circle
      entity: binary_sensor.backyard_motion_2
      tap_action:
        action: more-info
      style:
        top: 90%
        left: 40%
        opacity: 40%
        transform: translate(-50%,-50%) scale(1.5,1.5)
    - type: state-icon
      entity: binary_sensor.backyard_person_occupancy
      style:
        top: 90%
        left: 50%
        background: transparent
        '--paper-item-icon-color': white
    - type: icon
      icon: mdi:circle
      entity: binary_sensor.backyard_person_occupancy
      tap_action:
        action: more-info
      style:
        top: 90%
        left: 50%
        opacity: 40%
        transform: translate(-50%,-50%) scale(1.5,1.5)
  profiles:
    - low-performance
```

**[REQUIRED] Description of problem:**

```yaml
    - type: custom:frigate-card-menu-icon
      entity: switch.backyard_detect
      alignment: opposing
      state_color: true
      icon: mdi:toggle-switch-outline
      tap_action:
        action: toggle
```

I added a card menu icon and specified state_color: true.  However, I am not seeing this reflected?
![image](https://github.com/user-attachments/assets/9868f591-1310-4922-a842-37171e1f5c62)
