### ISSUE TITLE
Grid now working or maybe I don't understand what it does

### ISSUE THREAD

**Issue by turboc1208** [dermotduffy/frigate-hass-card#1714]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell_2
    live_provider: go2rtc
  - camera_entity: camera.hvac_2
    live_provider: go2rtc
  - camera_entity: camera.sunroom_2
    live_provider: go2rtc
  - camera_entity: camera.shed
    live_provider: go2rtc
  - camera_entity: camera.drivewaygate_2
    live_provider: go2rtc
  - camera_entity: camera.onecar_2
    live_provider: go2rtc
  - camera_entity: camera.twocar_2
    live_provider: go2rtc
live:
  display:
    grid_max_columns: 4
    mode: grid
view:
  default: live
menu:
  style: hover-card
media_gallery:
  controls:
    thumbnails:
      show_details: true
timeline:
  style: ribbon
grid_options:
  columns: 9
  rows: 3


```

**[REQUIRED] Description of problem:**

**[OPTIONAL] Last working release (if known):**
Just installed yesterday
**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
Please provide a description of the problem.

**Comment by dermotduffy** [comment]
(I can't tell what you are expecting to happen, and what you see. More details, and possibly a screenshot, would avoid me having to guess! Thank you)

**Comment by dermotduffy** [comment]
BTW: I don't recognize this as a valid card option, it's possible HA or something else  is adding this. Please try a plain dashboard without this, and see if it makes any difference:

```yaml
grid_options:
  columns: 9
  rows: 3
```
