### ISSUE TITLE
PTZ Controls do not work.

### ISSUE THREAD

**Issue by Tintef** [dermotduffy/frigate-hass-card#1715]
**Versions:**

- Frigate Card: v6.6.0-beta9
- Frigate: v5.5.1

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0-beta.9
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-08T22:21:30.962Z
lang: en_GB
timezone: America/Montevideo
git:
  hash: b2b7a08
  build_date: Wed, 04 Dec 2024 04:35:32 GMT
  commit_date: Tue, 3 Dec 2024 20:26:56 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      01J2TA0J3ZGH65WNX9RGJE0STJ: 5.5.1/0.14.0-da913d8
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front
      live_provider: go2rtc
    - camera_entity: camera.gate
      live_provider: go2rtc
    - camera_entity: camera.garden
      live_provider: go2rtc
    - camera_entity: camera.dogcam
      live_provider: go2rtc
    - camera_entity: camera.ptz
      live_provider: go2rtc
  view:
    default: live
    camera_select: live
    dark_mode: 'on'
```

**[REQUIRED] Description of problem:**

I can't seem to get my PTZ controls to work on the card.

- Controls work fine on frigate, and I can see and use all my presets as well
- Controls show on the card, but they don't work (none of them)
- Also, on the card, I only see a home button, not all my presents, not sure how this should work tho

> Note: I don't have the Reolink integration installed or a Replink device yet (I'll add a doorbell in a few weeks) so I'm not sure why it's reporting as detected.

**[OPTIONAL] Last working release (if known):**

I just installed this camera so I don't know if it's release related. I tried on beta-8 and beta-9, none worked.

**[OPTIONAL] Javascript errors shown in the web inspector:**

None.

**[OPTIONAL] Additional information:**

I tried debugging this a bit with the chrome devtools, and I noticed that at least the events that I want to do some action is getting to an executePTZAction function:

```js
    async executePTZAction(e, t, n) {
        const a = this._store.getCameraConfig(e);
        if (!a)
            return;
        const i = q_(a, t, n);
        if (i)
            return await this._api.getActionsManager().executeActions(i);
        const r = this._api.getHASSManager().getHASS()
          , o = this._store.getEngineForCameraID(e);
        return o && r ? await this._requestLimit.add(( () => o.executePTZAction(r, a, t, n))) : void 0
    }
```

Where:

```
e = "camera.ptz"
n = { phase: "start", preset: undefined }
t = "right"
```

**Comment by dermotduffy** [comment]
> Note: I don't have the Reolink integration installed or a Replink device yet (I'll add a doorbell in a few weeks) so I'm not sure why it's reporting as detected.
> Also, on the card, I only see a home button, not all my presents, not sure how this should work tho

FYI: Both of these are working as intended (reolink is part of HA core, and the card only supports using the 1st preset so far).

Can you visit https://<PATH_TO_YOUR_FRIGATE_INSTANCE>/api/<CAMERA_NAME>/ptz/info

... and tell me what you get back? It'll be a JSON blob.

**Comment by Tintef** [comment]
> FYI: Both of these are working as intended (reolink is part of HA core, and the card only supports using the 1st preset so far).

Perfect, thanks for the clarification.

> Can you visit https://<PATH_TO_YOUR_FRIGATE_INSTANCE>/api/<CAMERA_NAME>/ptz/info and tell me what you get back? It'll be a JSON blob.

```json
{
  "features": [
    "pt",
    "zoom",
    "pt-r",
    "zoom-r",
    "zoom-a"
  ],
  "name": "PTZ",
  "presets": [
    "door",
    "middle",
    "back",
    "door_zoomed"
  ]
}
```

**Comment by dermotduffy** [comment]
I assume whichever camera has the PTZ controls (probably `camera.ptz`), is an entity from the Frigate integration and not some other camera?

Looking at the config, and that JSON, it's not clear why it's not working.

**Comment by Tintef** [comment]
Yes, I only have one camera with PTZ controls, named `ptz` so the ha entity is `camera.ptz` (naming is hard 😅).

Yeah, it should work, but I can't find anything that's wrong.

Maybe I could install the card manually instead of via HACS to add some console logs? Is there a guide to so? More than happy to take a look at what's going on and report back with my findings

**Comment by dermotduffy** [comment]
If you're comfortable playing around in devtools, that might help us figure this out. This is the ultimate call to the Frigate integration to do the PTZ move:

https://github.com/dermotduffy/frigate-hass-card/blob/main/src/camera-manager/frigate/engine-frigate.ts#L1043

I'd love to know if the call gets in there. [This is the code you linked to](https://github.com/dermotduffy/frigate-hass-card/blob/main/src/camera-manager/manager.ts#L784), it should call the above. Right now I can't tell if the card is not making the call and nothing is happening, or the card is messing up.

The other idea would be to manually call the services from `/developer-tools/action` on your HA instance, try a call like this and see if your camera moves:

```yaml
action: frigate.ptz
target:
  entity_id: camera.ptz
data:
  action: move
  argument: left <-------------- Change this to right/left to move all the way right or left
```

If it doesn't move calling the service manually, there's no way the card could work. If it does work when you call it manually, but doesn't via the card, something is wrong with the card...
