### ISSUE TITLE
tap_action for the whole card

### ISSUE THREAD

**Issue by Tuxie** [dermotduffy/frigate-hass-card#172]
With `picture-entity` cards I can define `tap_action` like this to navigate somewhere when clicking anywhere on the card:
```
- type: picture-entity
  entity: camera.front_yard
  tap_action:
    action: navigate
    navigation_path: /lovelace/camera-front-yard
```

I would like to do the same on the `frigate-card`. Having a small jsmpeg video without the menu on the main dashboard and navigate to a different view on click/tap, where there is only a large frigate-card using the webrtc provider.

Or is it possible to get the mpeg stream to `picture-entity` somehow? The problem with the rtmp/rtsp stream views is that I found them unreliable or slow to start displaying something when navigating to a view. Only jsmpeg is near-instant to display and never freezes.
