### ISSUE TITLE
Android stops background audio when any video stream loads

### ISSUE THREAD

**Issue by Loic691** [dermotduffy/frigate-hass-card#1720]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```
card_version: 6.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-09T07:57:27.346Z
lang: fr
timezone: Europe/Paris
git:
  hash: '4590558'
  build_date: Mon, 09 Dec 2024 00:16:17 GMT
  commit_date: Sun, 8 Dec 2024 16:05:13 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      772d8e2890c52f6f536c5cbe86b1c920: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frigate_doorbird
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: interphone-webrtc
      image: {}
  live:
    preload: true
    controls:
      thumbnails:
        mode: none
      builtin: false
    show_image_during_load: true
  view:
    default: live
    interaction_seconds: 120
  menu:
    style: overlay
    buttons:
      frigate:
        enabled: true
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: false
      clips:
        enabled: false
      timeline:
        enabled: false
      snapshots:
        enabled: false
      microphone:
        enabled: false
      mute:
        enabled: false
    position: right
  media_gallery:
    controls:
      filter:
        mode: left
  media_viewer:
    controls:
      builtin: false
```

and

```
card_version: 6.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-09T08:00:28.949Z
lang: fr
timezone: Europe/Paris
git:
  hash: '4590558'
  build_date: Mon, 09 Dec 2024 00:16:17 GMT
  commit_date: Sun, 8 Dec 2024 16:05:13 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      772d8e2890c52f6f536c5cbe86b1c920: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frigate_cour
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
        stream: cour-webrtc-sub
      webrtc_card: {}
    - go2rtc:
        modes:
          - webrtc
        stream: cour-est-webrtc-sub
      dependencies:
        all_cameras: false
      camera_entity: camera.frigate_cour_est
      live_provider: go2rtc
    - camera_entity: camera.frigate_terrasse
      go2rtc:
        modes:
          - webrtc
        stream: terrasse-webrtc-sub
      live_provider: go2rtc
  view:
    default: live
    interaction_seconds: 120
    triggers:
      actions:
        trigger: live
      filter_selected_camera: false
    default_cycle_camera: true
    default_reset:
      every_seconds: 3
  menu:
    style: overlay
    buttons:
      frigate:
        enabled: true
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: false
      clips:
        enabled: false
      timeline:
        enabled: false
      snapshots:
        enabled: false
      mute:
        enabled: true
    position: right
  media_gallery:
    controls:
      thumbnails:
        size: 160
        show_details: false
  live:
    preload: true
    controls:
      thumbnails:
        mode: none
      builtin: false
  media_viewer:
    controls:
      builtin: false
```
```yaml

```

**[REQUIRED] Description of problem:**

On Android Device, when I launch Dashbord with these two frigate cards, Audio of other applications (Deezer, Spotify or all others one) are shutted off while camera are muted. So I have to re launch my other audio Application (eg Deezer).
I'm not understanding why music audio stream are replaced by HA Frigate Audio; The camera are all muted.
Strange things, the real streams of the camera are been muted because I heared no sounds from the camera. I have to click on the unmute button off frigate card to hear the sound...

**[OPTIONAL] Last working release (if known):**
No last working.
If I'm using standard viewer (no webrtc), audio music app are not shut while launching HA frigate Dahsboard
