### ISSUE TITLE
`unknown_error` for reolink cameras without media

### ISSUE THREAD

**Issue by Dhostetter** [dermotduffy/frigate-hass-card#1723]
My apologies if this was discussed, but I didn't find anything.
 
New issue started this morning. Camera feeds on cards load correctly for a sec or two then error out. 
I cleared cache and cookies.
Any suggestions?

This is what is displayed.
request:
  type: media_source/browse_media
  media_content_id: media-source://reolink/RES|01J7Y9YB5FJYVMV3CDPYZ5XR5P|0|sub
  id: 65
response:
  code: unknown_error
  message: Unknown error

Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6
Frigate Card 6.0.0

**[REQUIRED] Card diagnostic information:**
```yaml
card_version: 6.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
date: 2024-12-09T15:25:29.460Z
lang: en
timezone: America/New_York
git:
  hash: '4590558'
  build_date: Mon, 09 Dec 2024 00:16:17 GMT
  commit_date: Sun, 8 Dec 2024 16:05:13 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.driveway_reolink_duo_wifi_fluent
  view:
    default: live
  dimensions: {}
  menu:
    buttons:
      screenshot:
        enabled: true
      cameras:
        enabled: false
  profiles: []
```

**Comment by priddyma** [comment]
Same issue here. Going into Edit mode shows every camera live stream.
This is happening only on the "Sections" dashboard type.
I created a Masony dashboard page with just this card and it is displaying properly.


```
type: custom:frigate-card
cameras:
  - camera_entity: camera.g4_doorbell_pro_high
  - camera_entity: camera.garage_high
  - camera_entity: camera.patio_high
  - camera_entity: camera.north_high
  - camera_entity: camera.entry_high
  - camera_entity: camera.entry_door_high
  - camera_entity: camera.backyard_south_high
  - camera_entity: camera.front_yard_high
  - camera_entity: camera.g4_bullet_high
  - camera_entity: camera.g4_dome_high
live:
  display:
    mode: grid
grid_options:
  columns: 36
  rows: 6
view:
  default: live
  camera_select: live
  triggers:
    show_trigger_status: false
    filter_selected_camera: true

```

**Comment by tomsh123** [comment]
+1 happening only externally to the WIFI network (using NABU CASA)

**Comment by dermotduffy** [comment]
These sound like three unrelated issues (reolink issue, dashboards sections vs masonry issue, WIFI vs external). @tomsh123 and @priddyma suggest you file your own issues, and lets keep this one focused on Reolink.

@Dhostetter Can you try this:

```yaml
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.driveway_reolink_duo_wifi_fluent
      engine: generic <---------------- Added
```

I bet this will "paper over" your issue. Also, there is probably something logged in your Home Assistant logs at the same time you get the `unknown_error`, can you see what you find?
