### ISSUE TITLE
Cannot subscribe to topic 'frigate/events'

### ISSUE THREAD

**Issue by samotion2** [dermotduffy/frigate-hass-card#1729]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-09T19:06:18.664Z
lang: en_GB
timezone: *****
git:
  hash: '4590558'
  build_date: Mon, 09 Dec 2024 00:16:17 GMT
  commit_date: Sun, 8 Dec 2024 16:05:13 -0800
ha_version: 2024.12.0
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      *********: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.cam5
```

**[REQUIRED] Description of problem:**

After updating to the latest version, I encounter the following error. Each time I refresh the page, the error appears for a different camera. I’ve tried clearing the cache, but it didn’t help. Additionally, I’m seeing errors in Frigate itself. When I revert to version 5.2.0, everything works perfectly without making any changes to the configuration.

Is there something specific that needs to be updated or adjusted for this version?
![image](https://github.com/user-attachments/assets/98071361-a0ba-4d3c-979c-b7d7701010ff)
![image](https://github.com/user-attachments/assets/5c1d9f9e-1459-41b6-8133-0d03d2c85e86)

**[OPTIONAL] Last working release (if known):**
5.2.0
**[OPTIONAL] Javascript errors shown in the web inspector:**
```text
[Cannot subscribe to topic 'frigate/events](card-7cd05290.js:75 Cannot subscribe to topic 'frigate/events', make sure MQTT is set up correctly)
```
