### ISSUE TITLE
Carousel with 6.0

### ISSUE THREAD

**Issue by Ramias1** [dermotduffy/frigate-hass-card#1730]
This was working before I updated to the 6.0 version of the card.  I have four camera entities configured and I cycle through each camera every few seconds.

Here is the code that worked in the previous (5.2?) version of the card:

```
      cameras:
        - camera_entity: camera.front_low_resolution_channel
        - camera_entity: camera.garage_low_resolution_channel
        - camera_entity: camera.yard_low_resolution_channel
        - camera_entity: camera.deck_low_resolution_channel
      view:
        default: live
        update_seconds: 4
        update_cycle_camera: true
        update_force: true
```

I've noticed that update_seconds and update_cycle_camera_true are not options in the new 6.0 documentation.  I tried changing it to default_cycle_camera: true and interaction_seconds: 4  and reset_after_interaction: true but those don't seem to work for me.

On a computer and tablet I can scroll cameras by swiping left and right but it should be on auto-pilot every 4 seconds.

Asking for assistance on how to get a carousel/cycle view of my four cameras with v 6 of the card.

Thanks

**Comment by Ramias1** [comment]
Update:

I think I have it; posting here in case this helps anybody else:

```
      view:
        default: live
        default_reset:
          every_seconds: 4
        default_cycle_camera: true
```
