### ISSUE TITLE
Live stream loading icon permanently visible

### ISSUE THREAD

**Issue by raydenl** [dermotduffy/frigate-hass-card#1732]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
date: 2024-12-10T04:02:11.757Z
lang: en
timezone: Pacific/Auckland
git:
  hash: '4590558'
  build_date: Mon, 09 Dec 2024 00:16:17 GMT
  commit_date: Sun, 8 Dec 2024 16:05:13 -0800
ha_version: 2024.11.3
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      ff2083730d0567f02e00e2af415a4b9e: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front_door
    - camera_entity: camera.back_door
    - camera_entity: camera.deck
    - camera_entity: camera.office
  live:
    controls:
      next_previous:
        style: none
      thumbnails:
        show_download_control: false
        show_timeline_control: false
        show_favorite_control: false
        size: 75
        show_details: false
  menu:
    buttons:
      download:
        enabled: false
      timeline:
        enabled: false
  profiles: []
  status_bar:
    style: none
```

**[REQUIRED] Description of problem:**

The "Waiting for live stream to load ..." blue icon is permanently visible. Never seen this before v6.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
![image](https://github.com/user-attachments/assets/923d7297-8b5c-4fb5-9cc9-3d3a87df079d)
