### ISSUE TITLE
Another(?) API error

### ISSUE THREAD

**Issue by jaymunro** [dermotduffy/frigate-hass-card#1733]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
Diagnostics seem unavailable. Holding down on the 'flying bird' icon does nothing.
```

**[REQUIRED] Description of problem:**
Since upgrading to 6.0.0 after upgrading HA to 2024.12.1 this issue occurred on the Frigate cards.
- Updated to 6.0.2
- Cleared cache

```
request:
  type: frigate/events/get
  instance_id: frigate
  cameras:
    - garagecam
  limit: 50
  id: 128
response:
  code: frigate_error
  message: >-
    API error whilst retrieving events for cameras ['garagecam'] for Frigate
    instance frigate
```
or
```
request:
  type: frigate/events/get
  instance_id: frigate
  cameras:
    - gatecam
  limit: 50
  has_snapshot: true
  id: 468
response:
  code: frigate_error
  message: >-
    API error whilst retrieving events for cameras ['gatecam'] for Frigate
    instance frigate
```
An example of a card config is:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.garagecam
    live_provider: go2rtc
    go2rtc:
      stream: garagecam_hd
```
The config just above gives:
```
dependencies:
  all_cameras: false
  cameras: []
triggers:
  motion: false
  occupancy: false
  entities: []
  events:
    - events
    - clips
    - snapshots
engine: auto
frigate:
  client_id: frigate
motioneye:
  images:
    directory_pattern: '%Y-%m-%d'
    file_pattern: '%H-%M-%S'
  movies:
    directory_pattern: '%Y-%m-%d'
    file_pattern: '%H-%M-%S'
reolink:
  media_resolution: low
live_provider: go2rtc
image:
  mode: auto
  refresh_seconds: 1
ptz:
  r2c_delay_between_calls_seconds: 0.5
  c2r_delay_between_calls_seconds: 0.2
proxy:
  media: auto
  dynamic: true
  ssl_verification: auto
  ssl_ciphers: auto
camera_entity: camera.garagecam
go2rtc:
  stream: garagecam_hd
id: camera.garagecam
```

**[OPTIONAL] Last working release (if known):**
pre 6.0

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
