### ISSUE TITLE
Onvif is not setup for <camera>

### ISSUE THREAD

**Issue by coserotondo** [dermotduffy/frigate-hass-card#1736]
```
card_version: 6.0.2
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-10T10:45:00.078Z
lang: en
timezone: Europe/Rome
git:
  hash: 216ded2
  build_date: Tue, 10 Dec 2024 02:14:31 GMT
  commit_date: Mon, 9 Dec 2024 18:13:23 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
    devices:
      01J58S0CDBKVM5FA71CPHQJCR2: 5.5.1/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.giardino
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.ingresso_est
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.ingresso_ovest
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.patio
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.vialetto_nord
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
    - camera_entity: camera.vialetto_sud
      live_provider: auto
      go2rtc:
        modes:
          - webrtc
  live:
    controls:
      ptz:
        mode: 'off'

```

Just installed the latest Frigate Card and I'm having the following errors on Frigate (0.14.1-f4f3cfa):

![Screenshot 2024-12-10 115054](https://github.com/user-attachments/assets/28097667-44e7-4a16-bd3b-7a42c5f92137)
