### ISSUE TITLE
Small video screen on chrome and android

### ISSUE THREAD

**Issue by pro2call-nl** [dermotduffy/frigate-hass-card#1737]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.2
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-10T16:13:55.070Z
lang: en
timezone: Europe/Amsterdam
git:
  hash: 216ded2
  build_date: Tue, 10 Dec 2024 02:14:31 GMT
  commit_date: Mon, 9 Dec 2024 18:13:23 -0800
ha_version: 2024.12.1
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.5.1
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.voortuin
      live_provider: ha
  view:
    default: live
  menu:
    style: outside
  performance:
    profile: high
    style:
      border_radius: true
      box_shadow: true
```

**[REQUIRED] Description of problem:**
When i open HA on android very often 9/10 the image of the feed is small. i need to click the fullscreen button and than size it down again to make it visible.  This hapens also on google chrome. 

![Android Fault](https://github.com/user-attachments/assets/bb14e949-5c19-4950-a79e-3b7e7b02c7f8)
![Android Good](https://github.com/user-attachments/assets/c01b3d07-df79-4630-a60b-a15148e7dcc7)
![Google Chrome](https://github.com/user-attachments/assets/32183309-364e-4a0b-8e2b-e15b0746cd3b)

**[OPTIONAL] Last working release (if known):**
Unknow it was happening in version 5 also. 

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
