### ISSUE TITLE
Unable to Configure PTZ for Multiple Cameras from Version 6.x

### ISSUE THREAD

**Issue by oded106e** [dermotduffy/frigate-hass-card#1739]
After upgrading to version 6, I am no longer able to configure the PTZ (Pan-Tilt-Zoom) functionality for multiple cameras. Below are the configurations:

Old Configuration (5.x):
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.garden_camera1
    live_provider: ha
    hide: false
    triggers:
      occupancy: false
  - camera_entity: camera.tapo_c200_35ac_hd_stream
    live_provider: ha
    title: Garden Camera 2
    icon: mdi:video
    triggers:
      occupancy: false
  - camera_entity: camera.reolink_video_doorbell_wifi_fluent
    live_provider: ha
    triggers:
      occupancy: false
live:
  preload: false
  auto_unmute: never
  auto_pause: never
  auto_play: all
  controls:
    builtin: false
    next_previous:
      style: none
    timeline:
      mode: none
  draggable: true
  zoomable: true
  show_image_during_load: true
  lazy_load: true
  lazy_unload: hidden
  layout:
    position:
      x: 50
      'y': 50
    fit: fill
  transition_effect: slide
menu:
  buttons:
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: true
    media_player:
      enabled: false
    timeline:
      enabled: false
    clips:
      enabled: false
    live:
      enabled: false
    frigate:
      enabled: true
    substreams:
      enabled: true
    cameras:
      enabled: true
    expand:
      enabled: true
    mute:
      enabled: true
  style: hover-card
performance:
  features:
    animated_progress_indicator: false
  profile: low
view:
  default: live
  camera_select: live
  update_force: true
  timeout_seconds: 0
  update_seconds: 120
elements:
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.garden_camera1
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          right: 77%
          top: 60%
          transform: scale(1.5, 1.5)
          background: rgba(255, 255, 255, 0.0)
        service: eufy_security.ptz
        data_left:
          entity_id: camera.garden_camera1
          direction: LEFT
        data_right:
          entity_id: camera.garden_camera1
          direction: RIGHT
        data_up:
          entity_id: camera.garden_camera1
          direction: UP
        data_down:
          entity_id: camera.garden_camera1
          direction: DOWN
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.tapo_c200_35ac_hd_stream
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          right: 77%
          top: 60%
          transform: scale(1.5, 1.5)
          background: rgba(255, 255, 255, 0.0)
        service: button.press
        data_left:
          entity_id: button.tapo_c200_35ac_move_left
        data_right:
          entity_id: button.tapo_c200_35ac_move_right
        data_up:
          entity_id: button.tapo_c200_35ac_move_up
        data_down:
          entity_id: button.tapo_c200_35ac_move_down
media_viewer:
  draggable: false
  zoomable: false
  lazy_load: false
timeline:
  show_recordings: false
dimensions:
  aspect_ratio_mode: static
```

New Configuration (Post-Automatic Conversion) ver 6.x:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.garden_camera1
    live_provider: ha
    triggers:
      occupancy: false
  - camera_entity: camera.tapo_c200_35ac_hd_stream
    live_provider: ha
    title: Garden Camera 2
    icon: mdi:video
    triggers:
      occupancy: false
  - camera_entity: camera.reolink_video_doorbell_wifi_fluent
    live_provider: ha
    triggers:
      occupancy: false
live:
  preload: false
  controls:
    builtin: false
    next_previous:
      style: none
    timeline:
      mode: none
    ptz:
      orientation: horizontal
      style:
        right: 77%
        top: 60%
        transform: scale(1.5, 1.5)
        background: rgba(255, 255, 255, 0.0)
  draggable: true
  zoomable: true
  show_image_during_load: true
  lazy_load: true
  transition_effect: slide
  lazy_unload:
    - hidden
menu:
  buttons:
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: true
    media_player:
      enabled: false
    timeline:
      enabled: false
    clips:
      enabled: false
    live:
      enabled: false
    frigate:
      enabled: true
    substreams:
      enabled: true
    cameras:
      enabled: true
    expand:
      enabled: true
    mute:
      enabled: true
  style: hover-card
performance:
  features:
    animated_progress_indicator: false
view:
  default: live
  camera_select: live
  interaction_seconds: 0
  default_reset:
    interaction_mode: all
    every_seconds: 120
media_viewer:
  draggable: false
  zoomable: false
  lazy_load: false
timeline:
  show_recordings: false
dimensions:
  aspect_ratio_mode: static
cameras_global:
  dimensions:
    layout:
      position:
        x: 50
        "y": 50
      fit: fill
  ptz:
    data_left:
      entity_id: camera.garden_camera1
      direction: LEFT
    data_right:
      entity_id: camera.garden_camera1
      direction: RIGHT
    data_up:
      entity_id: camera.garden_camera1
      direction: UP
    data_down:
      entity_id: camera.garden_camera1
      direction: DOWN
    service: eufy_security.ptz
profiles:
  - low-performance
```
Issue:
In the old configuration, I could define separate PTZ entities and settings for each camera. However, in the new configuration, PTZ seems to be applied globally and does not allow me to specify individual settings for each camera.

Expected Behavior:
Ability to configure unique PTZ services and entities for each camera, as supported in previous versions.

Observed Behavior:
The new configuration applies a single PTZ setting globally, which doesn't align with the distinct setups required for each camera.

Could you please assist in resolving this issue? Is there a workaround or adjustment I can make to regain individual PTZ configuration for multiple cameras?

Thank you!
