### ISSUE TITLE
Live stream freeze all time with reolink cameras

### ISSUE THREAD

**Issue by Gamso** [dermotduffy/frigate-hass-card#1741]
I cleared my browser cache and i used the latest version of Home Assistant.
![image](https://github.com/user-attachments/assets/63321e0c-b05e-48b2-b26e-27ad90d24521)

**Card diagnostic information:**

```yaml
card_version: 6.0.3
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101
  Firefox/133.0
date: 2024-12-11T16:21:19.199Z
lang: fr
timezone: Europe/Paris
git:
  hash: 47fdfbc
  build_date: Wed, 11 Dec 2024 03:36:17 GMT
  commit_date: Tue, 10 Dec 2024 19:35:09 -0800
ha_version: 2024.12.2
integrations:
  reolink:
    detected: true
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.e1_zoom_salon_fluent
      title: Salon
      live_provider: ha
      engine: reolink
      dependencies:
        cameras:
          - camera.e1_zoom_salon_clair
      capabilities:
        disable_except: []
      ptz:
        presets:
          home:
            action: perform-action
            perform_action: button.press
            target:
              entity_id: button.e1_zoom_salon_guard_go_to
        service: button.press
        data_left_start:
          entity_id: button.e1_zoom_salon_ptz_gauche
        data_left_stop:
          entity_id: button.e1_zoom_salon_arret_ptz
        data_right_start:
          entity_id: button.e1_zoom_salon_ptz_droit
        data_right_stop:
          entity_id: button.e1_zoom_salon_arret_ptz
        data_up_start:
          entity_id: button.e1_zoom_salon_ptz_haut
        data_up_stop:
          entity_id: button.e1_zoom_salon_arret_ptz
        data_down_start:
          entity_id: button.e1_zoom_salon_ptz_bas
        data_down_stop:
          entity_id: button.e1_zoom_salon_arret_ptz
        data_zoom_in_start:
          entity_id: button.e1_zoom_salon_ptz_zoom_avant
        data_zoom_in_stop:
          entity_id: button.e1_zoom_salon_arret_ptz
        data_zoom_out_start:
          entity_id: button.e1_zoom_salon_ptz_zoom_arriere
        data_zoom_out_stop:
          entity_id: button.e1_zoom_salon_arret_ptz
    - camera_entity: camera.e1_zoom_salon_clair
      live_provider: ha
      engine: reolink
      capabilities:
        disable_except:
          - substream
    - camera_entity: camera.e1_zoom_bureau_fluent
      title: Bureau
      live_provider: ha
      engine: reolink
      dependencies:
        cameras:
          - camera.e1_zoom_bureau_clair
      capabilities:
        disable_except: []
      ptz:
        presets:
          home:
            action: perform-action
            perform_action: button.press
            target:
              entity_id: button.e1_zoom_bureau_guard_go_to
        service: button.press
        data_left_start:
          entity_id: button.e1_zoom_bureau_ptz_gauche
        data_left_stop:
          entity_id: button.e1_zoom_bureau_arret_ptz
        data_right_start:
          entity_id: button.e1_zoom_bureau_ptz_droit
        data_right_stop:
          entity_id: button.e1_zoom_bureau_arret_ptz
        data_up_start:
          entity_id: button.e1_zoom_bureau_ptz_haut
        data_up_stop:
          entity_id: button.e1_zoom_bureau_arret_ptz
        data_down_start:
          entity_id: button.e1_zoom_bureau_ptz_bas
        data_down_stop:
          entity_id: button.e1_zoom_bureau_arret_ptz
        data_zoom_in_start:
          entity_id: button.e1_zoom_bureau_ptz_zoom_avant
        data_zoom_in_stop:
          entity_id: button.e1_zoom_bureau_arret_ptz
        data_zoom_out_start:
          entity_id: button.e1_zoom_bureau_ptz_zoom_arriere
        data_zoom_out_stop:
          entity_id: button.e1_zoom_bureau_arret_ptz
    - camera_entity: camera.e1_zoom_bureau_clair
      live_provider: ha
      engine: reolink
      capabilities:
        disable_except:
          - substream
  view:
    default: live
  live:
    preload: false
  menu:
    style: overlay
    buttons:
      microphone:
        enabled: true
      mute:
        enabled: true
      screenshot:
        enabled: true
      recordings:
        enabled: false
      frigate:
        enabled: true
      cameras:
        enabled: true
      substreams:
        enabled: true
        icon: mdi:high-definition
      live:
        enabled: true
      clips:
        enabled: true
      media_player:
        enabled: false
      image:
        enabled: false
      download:
        enabled: false
      ptz_controls:
        enabled: true
      camera_ui:
        enabled: true
      timeline:
        enabled: false
      snapshots:
        enabled: false
      expand:
        enabled: false
      ptz_home:
        enabled: false
      play:
        enabled: false
```

**Description of problem:**

Since version 6.0.3, my live freeze every time even in low quality.
In this version, I can also look into the past, as I have the impression that the card generates a buffer.

Here a GIF  showing the problem :
![firefox_Ef7CtZd8Bq](https://github.com/user-attachments/assets/c7840945-5beb-42db-83a9-054f9eb98a11)

**Additional information:**

I use reolink E1 with Home Assistant integration (i'm not use frigate).
I rollback in version 6.0.2 and problem gone.
