### ISSUE TITLE
API error whilst subscribing to events for unknown Frigate instance frigate

### ISSUE THREAD

**Issue by mickeybyte** [dermotduffy/frigate-hass-card#1742]
Since the last update of the frigate-card in my Home Assistant, it doesn't show the camera's anymore, but only the message: 

> Camera initialization failed: API error whilst subscribing to events for unknown Frigate instance frigate. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
![image](https://github.com/user-attachments/assets/f1121bb8-4ef1-496b-af80-5529310a87e1)

I've checked everywhere, but I can't find what's going wrong. 
Frigate addon version: 0.14.1 (latest)
Frigate HACS integration version: 5.6.0 (latest)
Frigate-card HACS integration version: 6.0.3 (latest)

Browser cache cleared (although the error does not seem related to browser cache)

In my Frigate addon, I have 2 camera's configured: 1 Reolink doorbell and 1 Imou Life ONVIF camera. Both work fine in Frigate and show live feed.

When I create a new frigate card on my dashboard, it shows by default a weather radar as camera feed. As soon as I change the camera feed to one of my frigate camera's or add an extra camera the error above pops up and nothing is shown anymore on the card (also no frigate default logo which I can long-click to see diagnostics) When I add the default menu on the card, it gives the following diagnostics:

```
view: diagnostics
cameras_capabilities: {}
```
When I check diagnostics on a frigate card with my Weather feed it gives me this: 

```
card_version: 6.0.3
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
date: 2024-12-11T14:05:39.458Z
lang: en
timezone: Europe/Brussels
git:
  hash: 47fdfbc
  build_date: Wed, 11 Dec 2024 03:36:17 GMT
  commit_date: Tue, 10 Dec 2024 19:35:09 -0800
ha_version: 2024.12.2
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JA37YHK43DFXGYJXZEQQ4JFC: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.radar_thuis
```

My original yaml for the frigate card with 2 camera feeds (the one that is now showing the error):
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam_deurbel
    live_provider: ha
  - camera_entity: camera.cam_achterkant
    live_provider: ha
menu:
  position: bottom
  button_size: 40
  alignment: right
  buttons:
    frigate:
      enabled: true
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: true
      alignment: opposing
    clips:
      enabled: false
    recordings:
      enabled: false
    expand:
      enabled: true
    timeline:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
    screenshot:
      enabled: false
  style: overlay
live:
  controls:
    thumbnails:
      mode: none
    builtin: false
  preload: true
  transition_effect: slide
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
performance:
  style:
    border_radius: true
    box_shadow: true
  features:
    animated_progress_indicator: true
layout_options:
  grid_columns: full
  grid_rows: 6
view:
  default: live
  camera_select: live
  triggers:
    untrigger_seconds: 15
    actions:
      trigger: live
    filter_selected_camera: false
  default_cycle_camera: true
  default_reset:
    interaction_mode: all
    every_seconds: 60
  dark_mode: "on"
cameras_global:
  dimensions:
    layout:
      fit: contain
profiles: []

```

I have also checked out https://github.com/dermotduffy/frigate-hass-card/issues/1727 but that didn't help either. My client_id in frigate.yaml is "Frigate" and when I add that client_id in the card yaml I keep getting the same error. 

I hope someone can help me out, cause I can't seem to find what is wrong...

Thanks a lot! 
Michiel.

**Comment by dermotduffy** [comment]
The default Frigate instance usually has a client_id of `frigate`. Sounds like you have changed that to `Frigate` (it will be case-sensitive).

It's one of these is descending order of likelihood:

1. You are mismatching `client_id` between the Frigate config and card config.
1. Your Frigate integration isn't installed correctly.
1. Your MQTT integration isn't installed correctly.

For idea #1, you must exactly match the client_id field, e.g.:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam_deurbel
    live_provider: ha
    frigate:
      client_id: Frigate <------------------------- Added, case sensitive
```

... where `Frigate` is the value you are using in your frigate (not card) configuration.

If you're sure that's right (and it isn't in the config you pasted!), then check if there is anything in your Home Assistant logs that shows up when the shows this. That would help you figure out if the problem is 2 or 3 as mentioned above.
