### ISSUE TITLE
Grid mode should not let Nest API rate limits block whole grid

### ISSUE THREAD

**Issue by dnestico** [dermotduffy/frigate-hass-card#1743]
I have a nest doorbell wired and it has webRTC support from what I read online, I'm wondering if this card supports Nest webRTC so I can take advantage of that, webRTC for nest extends the streams so it doesn't constantly show rate limit errors, when that error appears it blocks the whole card and you can't watch the other non nest frigate cameras anymore (grid mode).

Or would be nice if there's a solution to make that error not block all the other cameras so they can at least still be viewable since they're separate and not nest cameras.

https://developers.google.com/nest/device-access/api/doorbell-wired
https://www.reddit.com/r/homeassistant/comments/116ys32/nest_doorbell_wired_2nd_gen_webrtc_source_for/ 
<img width="466" alt="Screenshot 2024-12-11 at 7 28 50 PM" src="https://github.com/user-attachments/assets/aec950b2-d2b1-4711-92d6-3aae9e36cb62" />

**Comment by dermotduffy** [comment]
The card certainly makes no special attempt to make Nest Doorbells work, so: "I don't know" is pretty much the answer. However, assuming you get WebRTC from Nest in HA (which I think is supported), there's no reason you should not be able to see that same stream in the card, i.e. minimally if the stream works in HA, the same stream should work in the card (but not necessarily any other features).

I have not seen an error like that before. 

> webRTC for nest extends the streams so it doesn't constantly show rate limit errors

What do you mean by this?

> Or would be nice if there's a solution to make that error not block all the other cameras

Yes, but I think that's already been done, but may depend on the error. What version of the card are you using? (Please hold down the Frigate card menu button for a few seconds and paste the diagnostics that result in here).

**Comment by dnestico** [comment]
> Yes, but I think that's already been done, but may depend on the error. What version of the card are you using? (Please hold down the Frigate card menu button for a few seconds and paste the diagnostics that result in here).

This is what I mean, in the 1st image the doorbell is working and showing fine, but because the nest doorbell has strict rate limits by default when it shows the rate limit as you can see it blocks all other cameras from being shown in the card until the rate limit expires, I am using the latest update with the new grid view so all those cameras are on 1 single card.

<img width="407" alt="Screenshot 2024-12-11 at 11 28 58 PM" src="https://github.com/user-attachments/assets/387c651a-f77a-4306-9718-48dc9ba498f2" />
<img width="407" alt="Screenshot 2024-12-11 at 11 28 43 PM" src="https://github.com/user-attachments/assets/2f402f71-3823-4b7b-8aac-86a930187ff4" />



> What do you mean by this?

Let me try and explain. So the card allows sources like WebRTC and go2rtc, well Nest also has its own WebRTC implementation ([explained here](https://github.com/AlexxIT/go2rtc#source-nest)) when using that it allows the stream limit to "extend" itself so you don't have to worry about the rate limit as much, so would be nice if that could be added as its own source for nest cameras to this card, according to this [reddit thread](https://www.reddit.com/r/homeassistant/comments/116ys32/comment/jvlt7qj/) Frigate 12 added support for this, my doorbell isn't added to Frigate cuz I couldn't figure that out but could still work on this card, hopefully you understand what I  mean lol.

**Comment by dermotduffy** [comment]
You missed this: "Please hold down the Frigate card menu button for a few seconds and paste the diagnostics that result in here"

Perhaps the summary is if the camera is accessible via Frigate, or via `go2rtc`, this should all work just fine. I think you're accessing just the camera in Home Assistant directly, though. That should _also_ work, but looks like it's prone to some rate limit (???), and your point is that when this rate limit is hit the card blocks out the whole grid -- instead of just blocking out the Nest camera. You'd like it to only block out the Nest camera.

Am I understanding correctly?

**Comment by dnestico** [comment]
> You missed this: "Please hold down the Frigate card menu button for a few seconds and paste the diagnostics that result in here"

```
card_version: 6.0.3
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-12T04:56:24.740Z
lang: en
timezone: America/Toronto
git:
  hash: 47fdfbc
  build_date: Wed, 11 Dec 2024 03:36:17 GMT
  commit_date: Tue, 10 Dec 2024 19:35:09 -0800
ha_version: 2024.12.2
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JCZC5Y7VR4S3CN5QWHXHMGRY: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front_door_doorbell
      dimensions:
        layout:
          fit: cover
    - camera_entity: camera.porch
      live_provider: go2rtc
      frigate:
        url: 192.168.2.176
      go2rtc:
        modes:
          - mse
          - webrtc
      webrtc_card:
        entity: camera.porch
      dependencies:
        all_cameras: true
    - camera_entity: camera.driveway
      live_provider: go2rtc
      frigate:
        url: 192.168.2.176
      go2rtc:
        modes:
          - mse
          - webrtc
      webrtc_card:
        entity: camera.driveway
      dependencies:
        all_cameras: true
    - camera_entity: camera.garage
      live_provider: go2rtc
      frigate:
        url: 192.168.2.176
      go2rtc:
        modes:
          - mse
          - webrtc
      webrtc_card:
        entity: camera.garage
      dependencies:
        all_cameras: true
    - camera_entity: camera.luna
      live_provider: go2rtc
      frigate:
        url: 192.168.2.176
      go2rtc:
        modes:
          - mse
          - webrtc
      webrtc_card:
        entity: camera.luna
      dependencies:
        all_cameras: true
  status_bar:
    style: outside
    items:
      engine:
        enabled: false
    position: top
    height: 35
  menu:
    style: overlay
    position: bottom
    buttons:
      cameras:
        enabled: true
      clips:
        enabled: false
      snapshots:
        enabled: false
      timeline:
        enabled: false
      mute:
        enabled: true
        alignment: opposing
      screenshot:
        enabled: true
        alignment: opposing
        icon: mdi:cellphone-screenshot
      download:
        alignment: opposing
      display_mode:
        icon: mdi:view-grid
        enabled: false
      live:
        enabled: false
      play:
        alignment: opposing
        enabled: true
      frigate:
        icon: mdi:home
        priority: 60
        permanent: true
      substreams:
        enabled: false
      camera_ui:
        enabled: false
  view:
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
    default: live
  live:
    display:
      mode: grid
      grid_columns: 2
      grid_max_columns: 2
    controls:
      timeline:
        mode: below
        style: ribbon
        pan_mode: seek-in-camera
        events_media_type: clips
        show_recordings: true
      builtin: false
      thumbnails:
        mode: above
        media_type: events
        show_favorite_control: false
        show_timeline_control: false
        size: 75
    lazy_unload:
      - unselected
    auto_play:
      - visible
    auto_pause:
      - hidden
    auto_mute:
      - unselected
    auto_unmute:
      - selected
  dimensions:
    aspect_ratio_mode: dynamic
  media_viewer:
    auto_play:
      - selected
    auto_pause:
      - unselected
    auto_mute:
      - unselected
    auto_unmute:
      - selected
    display:
      mode: grid
      grid_columns: 2
      grid_max_columns: 1
    controls:
      next_previous:
        style: chevrons
      timeline:
        mode: below
        style: ribbon
        events_media_type: clips
        show_recordings: false
      thumbnails:
        size: 75
        show_favorite_control: false
        show_timeline_control: false
        mode: above
```

Interesting that says "reolink detected: true" when I have no reolink cameras.

> and your point is that when this rate limit is hit the card blocks out the whole grid -- instead of just blocking out the Nest camera. You'd like it to only block out the Nest camera.

If possible and I'm just missing a setting then yes, cuz as you can see in the screenshot above it effects all the other cameras when that happens which are local cams, and don't have any rate limits like Nest does.



> Perhaps the summary is if the camera is accessible via Frigate, or via `go2rtc`, this should all work just fine. I think you're accessing just the camera in Home Assistant directly, though

Correct I am accessing this through HA Nest integration, maybe I might try [this](https://github.com/blakeblackshear/frigate/issues/3057#issuecomment-1937808953) soon though as it seems like the only way to generate an RTSP/WebRTC stream link for Nest cameras. Now that I think about it, even if you did implement this in the card it probably wouldn't work through the Nest HA integration anyways... damn Nest.
