### ISSUE TITLE
`default` menu button does not behave as expected

### ISSUE THREAD

**Issue by stevenmccord** [dermotduffy/frigate-hass-card#1744]
**Checklist:**

I am on the latest version and have cleared cached

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.0.8
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-16T00:10:01.831Z
lang: en
timezone: America/New_York
git:
  hash: 67f03fb
  build_date: Sun, 15 Dec 2024 00:55:11 GMT
  commit_date: Sat, 14 Dec 2024 16:53:58 -0800
ha_version: 2024.12.3
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01J88JD7Q93J9RJVAWX1W475NH: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frontyard_frigate
      live_provider: webrtc-card
      title: Front Yard
      go2rtc:
        modes: []
      image:
        mode: camera
  view:
    default: snapshot
    default_reset:
      after_interaction: true
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
    triggers:
      actions:
        trigger: none
        untrigger: default
      filter_selected_camera: false
  menu:
    alignment: bottom
    buttons:
      frigate:
        enabled: true
        permanent: true
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: true
      clips:
        enabled: false
      snapshots:
        enabled: true
        permanent: true
      image:
        enabled: false
      play:
        enabled: false
      timeline:
        enabled: false
      download:
        enabled: false
    style: overlay
  status_bar:
    height: 20
    items:
      title:
        enabled: true
        priority: 50
      resolution:
        enabled: false
      technology:
        enabled: false
        priority: 7
      engine:
        enabled: false
        priority: 88
    style: overlay
  media_viewer:
    auto_play:
      - selected
    auto_pause: []
    display:
      mode: single
    snapshot_click_plays_clip: true
  image:
    mode: camera
  performance:
    style:
      border_radius: true
      box_shadow: true
    features:
      media_chunk_size: 54
  media_gallery:
    controls:
      thumbnails:
        size: 175
        show_details: false
      filter:
        mode: none
  profiles: []
  live:
    preload: true
    draggable: false
    zoomable: false
    lazy_load: true
  elements:
    - type: state-label
      entity: sensor.blank_blank
      prefix: Front Yard
      tap_action:
        action: navigate
        navigation_path: /config/areas/area/front_yard
      style:
        top: 4px
        right: 0px
        color: rgb(255,255,255)
        font-size: 16px
        transform: rotate(0deg)
  dimensions:
    aspect_ratio: '16:9'
    aspect_ratio_mode: static
```

**Description of problem:**
I am not sure if this is a bug, or how it is supposed to work or if I just don't know what I am doing. But I have my card defaulted to the most recent snapshot. That works great. However, when I go to the live view to see the current state and then go back to the default view with the menu button to reset to the default view, it goes to the snapshot and auto plays the clip. I believe it is because it sees it as an interaction, but I would prefer the default view to just reset and go back to the snapshot image and not autoplay the clip. The only way I can go back to that is either refreshing the page, or going into the image thumbnails. Just curious if I am doing something wrong, or there is some configuration I am not setting. Appreciate any help!!
