### ISSUE TITLE
Implement recordings from Synology Surveillance Station

### ISSUE THREAD

**Issue by Jack77777777** [dermotduffy/frigate-hass-card#1748]
Hello,

First of all i love frigate and the frigate card.
I have setup frigate only for live view of my cameras in docker onto Synology DS718+. Seems like for the detection feature of frigate my Synology has not enough power and no detector. For this reason i use the Surveillance Station from Synology for detection and recordings.

Is there a way to implement recordings from Synology Surveillance Station into frigate or frigate card?

Best regards,
Jack

**Comment by dermotduffy** [comment]
> First of all i love frigate and the frigate card.

Glad you find it useful!

> Is there a way to implement recordings from Synology Surveillance Station into frigate or frigate card?

Of course, anything is technically possible, just might be a lot of work. Does Surveillance Station have an Home Assistnat integration, and can you already access Surveillance Station recordings through Home Assistant (e.g. the Media Browser)? 

- If yes, we could probably get recordings into the card with a moderate amount of work
- If no, we could probably get recordings into the card with a _substantial_ amount of work 

Both would likely require someone _with_ a Surveillance Station do the work though...

**Comment by dermotduffy** [comment]
@Jack77777777 Realistically, to do this right, it needs a developer with both the capability to integrate this into the card *AND* the necessary hardware to test. That is not me. Sounds like it is also not you :-) We can leave this issue open and hope that someone comes along better suited to implement this.

Another idea I've had more generally is to just allow the Frigate card to browse media separate from the camera system. This wouldn't allow any kind of media filtering, link between camera and media, or timeline support, but would be pretty much "Have a version of the HA media browser" _in_ the card, i.e. Anything you could see in the HA media browser, you could "browse to" yourself in the Frigate card. That might be a hacky way to give you somewhat close to what you want, but wouldn't be anything like the same level of integration the card has for `frigate`, `reolink`, `motioneye`, etc.

**Comment by Jack77777777** [comment]
@dermotduffy could you make it possible to copy recordings manually to frigate storage and have them visible? I already tried this by renaming folders and files to fit frigate structre (https://docs.frigate.video/configuration/record/). But the recordings are not visble in media browser->frigate. I read that this is nothing intented but probably there is way ;) ?

I could set up a job to copy and rename automatically i think.

**Comment by dermotduffy** [comment]
> @dermotduffy could you make it possible to copy recordings manually to frigate storage and have them visible? I already tried this by renaming folders and files to fit frigate structre (https://docs.frigate.video/configuration/record/). But the recordings are not visble in media browser->frigate. I read that this is nothing intented but probably there is way ;) ?

Both the card and HA are asking Frigate what events happened between date X and Y. Simply having the media present is not sufficient.

**Comment by Jack77777777** [comment]
Ok. Regarding to link media browser to the card. Would it be possible to link each camera to different folders in mymedia?

cam1: media browser/mymedia/recordings_cam1
cam2: media browser/mymedia/recordings_cam2
.
.
.

**Comment by Jack77777777** [comment]
In best case seperate for Recordings, Snapshots... for each cam 😅

**Comment by dermotduffy** [comment]
> In best case seperate for Recordings, Snapshots... for each cam 😅

Yes, perhaps something like (making this up):

```yaml
camera:
  - camera.foo:
    media_library:
      paths:
        snapshots: ["My Camera Ecosystem", "Images", "Baz"]
        clips: ["My Camera Ecosystem", "Events", "Baz"]
        recordings: ["My Camera Ecosystem", "24x7 Recordings", "Baz"]
```
     
None of these would work:
 - Timeline
 - Media filtering of any kind
 - "Infinite scrolling back in time"

It would simply present the same contents of the Media Browser, in the card (but perhaps starting at the paths as specified above).

**Comment by Jack77777777** [comment]
@dermotduffy this would fit my needs 👍🏻.

**Comment by apos-t** [comment]
@dermotduffy It would be great if you can implement local paths as media source. Thats the feature I'm missing in the moment. Switching from frigate to basic reolink detection and upload the clips/images to an ftp on my ha server. That feature would work, for all cameras with ftp support - also for the battery driven.

There is an other card https://github.com/lukelalo/gallery-card  using local media - maybe that helps

For the timeline they exctract the filenames - which needs to be configurable - for reolink my config looks like:

entities:
  - camera.camera_einfahrt_fliessend
  - path: media-source://media_source/local/camera-einfahrt/
    recursive: true
    include_images: false
menu_alignment: bottom
maximum_files: 5
file_name_date_begins: 19
file_name_format: YYYYMMDDHHmmss
caption_format: MM/DD HH:mm

**Comment by dermotduffy** [comment]
> For the timeline they exctract the filenames - which needs to be configurable - for reolink my config looks like:

This is part of the problem with this feature, honestly. The card _already_ supports fancy media handling, and extracting times from filenames (this is what `reolink` and `motioneye` cameras do in the card), and is much more extensible than a configuration like this. But it needs someone who has the willingness & hardware to implement it.

If this "generic folder" feature turns into something like the above -- I fear we're missing the point, and should just implement support for that camera type "properly" into the card.

**Comment by apos-t** [comment]
Thank you for the answer, I understand your point to support camera types and not create something generic with all the support this feature will have in the future. Your suggestion should definetly work - with reolink ftp for example you always get the snapshot and the clip in the same folder - with a different timestamp for the same event, not really great for automations...

**Comment by haforme** [comment]
I struggle with a similar use case.  I use the frigate card for my ring camera.  Any of the motion or ding event videos are uploaded from ring to my media folder.  To review the videos, I have to go to the media folder and drill down to the "My Media" folder.  It works but having similar functionality from the frigate card would be the cats meow!

**Comment by dermotduffy** [comment]
[A few thoughts about how this could work](https://docs.google.com/document/d/1BER-n4zoD0zwqvDS0cVLloXrcbZcFUs1u_d0yb1_ei8/edit?usp=sharing) . Comments very welcome here or in the doc.

**Comment by oeiber** [comment]
> [A few thoughts about how this could work](https://docs.google.com/document/d/1BER-n4zoD0zwqvDS0cVLloXrcbZcFUs1u_d0yb1_ei8/edit?usp=sharing) . Comments very welcome here or in the doc.

Looks very good!

**Comment by haforme** [comment]
I reviewed your plan, and it appears to meet my needs in that I want to be able to tag a specific camera to a specific directory.  Thanks for doing this. It will make a great addition for the non-Frigate cameras.  This would also be a reason to rename the card to a more universal name.

**Comment by apos-t** [comment]
Looks good, I have one point:
the logic of creating the timeline from the file names would be delivered true the attached camera? When I understand it correctly,  this will work only for reolink cameras at the moment

**Comment by dermotduffy** [comment]
> the logic of creating the timeline from the file names would be delivered true the attached camera? When I understand it correctly, this will work only for reolink cameras at the moment

It works for `frigate`, `reolink` and `motioneye` all of which have some sort of "proper" camera engines implemented in the card. To start, I don't want to go anywhere near making that generic, so in v1 of this feature there'll be no timeline association whatsoever with media in the folders and barebones filtering (if any).

Timeline support would come **if** we implement the work described under "Future Possibilities", but that would not be in the initial version.

**Comment by apos-t** [comment]
That's also my understanding and is completly fine, I just want to make it clear for everybody with other brands like ring etc.

**Comment by Jack77777777** [comment]
> [A few thoughts about how this could work](https://docs.google.com/document/d/1BER-n4zoD0zwqvDS0cVLloXrcbZcFUs1u_d0yb1_ei8/edit?usp=sharing) . Comments very welcome here or in the doc.

This would be fantastic!

**Comment by oeiber** [comment]
@dermotduffy what do you think? will this feature be implemented, in neqr future?

**Comment by dermotduffy** [comment]
@oeiber Definitely still planning to implement this, I think it'll be a great feature. [Cannot make any promises on timeline](https://github.com/dermotduffy/advanced-camera-card/issues/1248) though. Help welcome!

**Comment by tombadog99** [comment]
Just wanted to add my voice to this. I really hope this could be implemented even in limited way as the custom gallery card is no longer supported. The ability to play recorded clips from media would be a great feature.

**Comment by nnjim** [comment]
I too am looking forward to this feature in Advanced Camera Card; I current use the Custom Gallery Card, but it is no longer supported. It works well, but I image one day after an HA update it will fail....
I use Tapo cameras and I store motion detected clips locally in the media folder.

**Comment by dermotduffy** [comment]
Experimental basic support for HA media folders has been added. A lot more to do, but enough for anyone interested to test at least ...

Upgrade to at least [v7.7.0](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.7.0) and add this to your config to add a basic folder at the HA root. See [folder documentation](https://card.camera/#/configuration/folders) to tweak from there.

```yaml
folders:
  - type: ha
```

**Comment by dnestico** [comment]
Wow! This is great and it seems to somewhat work to finally show my Nest Doorbell clips on the card, problem is not sure why clips won't play though.

https://github.com/user-attachments/assets/1ca5bb4c-7ba3-45d7-a9b1-14c34c733bdc

Another thing I would love is an option to turn off the back button cuz I don't need my family trying to navigate the rest of the file system lol

**Comment by haforme** [comment]
Looking good! I have installed the updated card and have got it to display my Ring Camera media files.  Will test and advise

**Comment by dnestico** [comment]
I fixed this error by adding a different camera that supports frigate events and moving it to the first camera in the list.

But as shown in my video above it doesn't seem to play regardless just without that error now.

**Comment by dermotduffy** [comment]
Thanks for testing folks! Some responses to the multiple questions:

> Would like an option to turn off the back arrow, only want the linked folder to be accessible, not all my HA folders

@dnestico  To clarify, if you navigate downwards, I assume you still want to be able to navigate back "up"? So perhaps you mean just to not allow navigation "above" the folder you have configured as the root? If that's right, would you mind opening a new feature request for this so I can track it separately?

> Is it possible to customize like you can on the media viewer already? Like for example the size of the thumbnails, etc

@dnestico This should already work. It's the same `media_gallery` configuration settings.

> Would be cool in the future if it were possible to integrate this into "Clips" so all the imported folder media shows up there rather than a separate tab/button

@dnestico This one won't happen, as folders are fundamentally different since they are not associated with a camera and they behave differently (e.g. clips gallery extends infinitely, clips knows the time of thumbnails, clips can use a media filter, etc). It's also obviously possible to have both clips for a camera and a folder you want to look, mixing them would be strange.

> I fixed this error by adding a different camera that supports frigate events and moving it to the first camera in the list.

That is definitely a bug! However, I'm not sure why it's not playing. Do these media items play okay when you view them in the HA media browser? If they work there, they should work in the card (playing them obviously works okay for me). Anything showing up in the browser console (F12)?

**Comment by dermotduffy** [comment]
[On mobile] /That/ is definitely a bug (fix in progress, ETA tomorrow). I was referring to how the clip still wouldn't play even with @dnestico 's clever workaround of having a Frigate camera selected (just without the error).

**Comment by dnestico** [comment]
> [@dnestico](https://github.com/dnestico) To clarify, if you navigate downwards, I assume you still want to be able to navigate back "up"? So perhaps you mean just to not allow navigation "above" the folder you have configured as the root? If that's right, would you mind opening a new feature request for this so I can track it separately?

Yea pretty much, they just need access to the root folder I set.

> [@dnestico](https://github.com/dnestico) This should already work. It's the same `media_gallery` configuration settings.

Oh I see, good to know.

> [@dnestico](https://github.com/dnestico) This one won't happen, as folders are fundamentally different since they are not associated with a camera and they behave differently (e.g. clips gallery extends infinitely, clips knows the time of thumbnails, clips can use a media filter, etc). It's also obviously possible to have both clips for a camera and a folder you want to look, mixing them would be strange.

Ah damn I see. Maybe it's possible with a button on my dashboard to make the card change to the folders tab, I already have this to switch between cameras on 1 single card so I'll have to check.

> That is definitely a bug! However, I'm not sure why it's not playing. Do these media items play okay when you view them in the HA media browser? If they work there, they should work in the card (playing them obviously works okay for me). Anything showing up in the browser console (F12)?

Yup they work fine in the media browser, they are just 1 second clips provided by the Nest integration. I see nothing in my console tbh.

**Comment by tombadog99** [comment]
Thanks so much for doing this. The way you've integrated seems great. I am, however, running into the "The selected camera does not support this view" error. Not sure if I am doing something wrong. The file does play in the HA media browser.

**Comment by Jack77777777** [comment]
The folder option works great.
But for me it is showing no thumbnails in gallery.
![Image](https://github.com/user-attachments/assets/6698688f-94c3-4deb-adfa-e76af13cd2bc)

```
folders:
  - type: ha
    icon: mdi:movie
    ha:
      url: >-
        /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2F
      path:
        - title_re: Foscam C1
        - title_re: 2025.*
```

**Comment by dermotduffy** [comment]
Again, multiple replies below:

> I am, however, running into the "The selected camera does not support this view" error. Not sure if I am doing something wrong. The file does play in the HA media browser.

@tombadog99 You're not doing anything wrong. The "The selected camera does not support this view" is a bug that I need to fix (ETA: today).

> But for me it is showing no thumbnails in gallery.

@Jack77777777 Are you saying it shows thumbnails in the Home Assistant Media browser (from the sidebar), but NOT in the card? If there are no thumbnails in _either_, then there's nothing the card can do, there's just no thumbnails! You'd need to take up the issue with whatever integration is providing the media.

> Would it be possible to add several folders and have the recordings all together in the media gallery at one click?

@Jack77777777 This is exactly the kind of conversation we need to have, I think there'll be a lot of things like this that are necessary to make this usable. In this exact case, there's a chance this might just work already, as the code is written to allow multiple matches, maybe try something like this:

```yaml
[...]
    ha:
      url: >-
        /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2F
      path:
        - title_re: "(Foscam C1|Instar IN-9020|Reolink Doorbell)
        - title_re: 2025.*
```

I could imagine we add something like this to be clearer (not implemented):

```yaml
[...]
      path:
        - title_multiple:
            - Foscam C1
            - Instar IN-9020
            - Reolink Doorbell
```

### Other ideas I had (please express opinions!)

#### Conditions

Use conditions that the card already supports. This would let us do extremely flexible things, like change the path depending on which camera you're viewing in the card, or any arbitrary HA state:

```yaml
[...]
      path:
        - title_conditional:
          condition:
            - condition: camera
              cameras:
                - camera.office
          path:
            - title: "Office"
            - title: "subdir"       
```

#### Folder merging

A new kind of folder that just merges multiple potentially unrelated folders, e.g.:

```yaml
folders:
  - type: ha
    id: one
    [...]
  - type: ha
    id: two
    [...]
  - type: merged
    folders:
      - one
      - two
```

**Comment by Jack77777777** [comment]
> [...]
>     ha:
>       url: >-
>         /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2F
>       path:
>         - title_re: "(Foscam C1|Instar IN-9020|Reolink Doorbell)"
>         - title_re: 2025.*

@dermotduffy this works. Is there a way to sort the recordings by date (asc, desc) and not by name? 




> Are you saying it shows thumbnails in the Home Assistant Media browser (from the sidebar), but NOT in the card? If there are no thumbnails in either, then there's nothing the card can do, there's just no thumbnails! You'd need to take up the issue with whatever integration is providing the media.

Good point. I started indexing for the forders with my recordings. Will see if this creates thumbnails.

**Comment by tombadog99** [comment]
Great that a fix is incoming - many thanks. I have got one more suggestion. It would be able to set the folder view as the default view or even better, set a default file as the default view. For my use of the folder feature, I have my last motion event recorded by HA as an mp4, which overwrites the same file so it would be really good to be able to set this as the default view for the card. Thanks for all the great work!

**Comment by dermotduffy** [comment]
> Is there a way to sort the recordings by date (asc, desc) and not by name?

Not currently, as this is not ant easy to do so extensibly. HA media have no time associated with them, just a string title. Integrations often do put dates in titles, but in all imaginable time formats and timezones, sometimes with different parts of the date in different subfolders (e.g. YYYY -> MM -> DD -> HH -> MM), sometimes in different languages, etc. A mess! I do plan to implement something about it, either some very versatile parsing, or allow the user to specify the format per "folder". Still thinking about it.

**Comment by tombadog99** [comment]
> The `selected camera does not support this view` should be fixed in [v7.7.4](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.7.4).

Just tested out and all working, thanks for all the hard work. Figured out setting the default view as folder, thanks. It would be even better if you could specify the default view as a specific file. Not sure how useful this may be for others, so not sure if it is worth your precious time!

**Comment by dermotduffy** [comment]
@Jack77777777 Yup, understood. I'm not suggesting it's impossible, just much harder than it should be to do well :-) On thumbnails, you are saying gallery-card _does_ show thumbnails, but HA media doesn't (and so Advanced Camera Card also doesn't)?

**Comment by Jack77777777** [comment]
@dermotduffy yes, ha and advenced canera card shows no thumbnails. 
I am not sure if the picture (from gallery card) in my last post is showing thumbnails or something else. Could it be that this are pre-loaded recordings instead of thumbnails?

**Comment by dermotduffy** [comment]
> Could it be that this are pre-loaded recordings instead of thumbnails?

Yes -- it could be loading the videos but not playing them.

**Comment by oeiber** [comment]
thank you for your help, now it’s working. 
Is the message „ The selected camera does not support this view“ an expected behavior, when I try to open timeline view?

**Comment by dermotduffy** [comment]
Note for those using this experimental functionality, the `folder` view has been renamed to `folders`, and a new `folder` view added that shows media from the default folder directly (i.e. not a gallery), see:
https://github.com/dermotduffy/advanced-camera-card/pull/2077

This matches the style of `clip` and `clips`, `snapshot` and `snapshots, `recording` and `recordings`, etc.

**Comment by oeiber** [comment]
Hi,
playing media from media folder does not work for me on my iphone. Neither with companion app nor with safari:

![Image](https://github.com/user-attachments/assets/6e60340b-71ef-4758-a01e-28edb5b38b83)

Do you have the same problem on mobiles?
Thank you!

Oliver

**Comment by dermotduffy** [comment]
> playing media from media folder does not work for me on my iphone.

Android works fine, I cannot speak to iPhone. Does the same piece of media work, or not work, when viewed in the HA Media browser (not the card)?

**Comment by Jack77777777** [comment]
I tried a lot but can not get it to work with my pathes.
In the default media folder i have **Foscam C1, Instar IN-9020, Reolink Doorbell**.
Underneath of each of this folders are folders i.e. **20250507AM**
Underneath this are the media files in the string of **Foscam C1-20250507-064944-1746593384919-3.mp4**.

I am facing two issues.
1. No clue how can i add all three folders **Foscam C1, Instar IN-9020, Reolink Doorbell**
2. Don´t know how to extract the time stamps

My config:
```
folders:
  - type: ha
    icon: mdi:movie
    title: Aufnahmen
    ha:
      url: >-
        /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2F
      path:
        - matchers:
            - type: title
              title: Foscam C1
        - parsers:
            - type: startdate
        - parsers:
            - type: startdate
```

Screenshot:

![Image](https://github.com/user-attachments/assets/ef2b27f1-e749-46e0-8bcb-70ff4b3d3517)

**Comment by dermotduffy** [comment]
@Jack77777777 I think your reply is not related to the last one, you are not commenting on whether or not this works on mobile, so I think yours is a more general query. Just to make sure, I hope you've seen the documentation that includes a [worked example](https://card.camera/#/configuration/folders).

> No clue how can i add all three folders Foscam C1, Instar IN-9020, Reolink Doorbell

If they have different path hierarchies, you'd just create a separate entry in the `folders` array for each of them with different matchers, i.e.

```yaml
[...]
folders:
  - type: ha
    [details for folder 1]
  - type: ha
    [details for folder 2]
```

If the contents of each folder follow the same style, you could also just create 1 folder in the card config and it can match across all 3 (see below example).

> Don´t know how to extract the time stamps

This is hard to answer without details of what you've tried. I will say that `20250507AM` looks like an highly ambiguous format. I have no idea what that is intended to mean ;-)

Here's an example for illustration, but you'll need to play around yourself:

```yaml
folders:
  - type: ha
    icon: mdi:movie
    title: Aufnahmen
    ha:
      url: >-
        /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2F
      path:
        - matchers:
            - type: title
              # Match all 3 top level directories
              regexp: "(Foscam C1|Instar IN-9020|Reolink Doorbell)"
        - parsers:
              # At this level there are directories of the format '20250507AM'. I don't know what that is!
              # But if it's 2025-05-07 and we ignore the 'AM', then try this to just only look at the numerical
              # values. It should guess the format from here.
            - type: startdate
              # Only match the digit values and ignore the 'AM'.
              # We could also specify a different date format here with the `format` argument.
              regexp: "\d+"
        # At the last level, the filenames themselves do not contain anything useful to parse or match
        # so just match everything.
        - {}
```

Hope that's enough for you to experimental with. As above, see the worked example in the documentation too which has screenshots that may help you understand how it works.

**Comment by oeiber** [comment]
> > playing media from media folder does not work for me on my iphone.
> 
> Android works fine, I cannot speak to iPhone. Does the same piece of media work, or not work, when viewed in the HA Media browser (not the card)?

Playing media directly in ha works as espected ;-)

Update: Seems Safari has a problem, loading the media files correctly:

![Image](https://github.com/user-attachments/assets/705c2b4e-20b3-4ee6-a4eb-89a8b01b5fbf)

By the way: There's no error in browser's debug console.

**Comment by dermotduffy** [comment]
> Playing media directly in ha works as espected ;-)

Just to confirm, you mean the _same_ piece of media works in the HA media browser, on the _same_ phone, with the _same_ network settings -- but does not on the card? That should not happen. However, it's not at all uncommon for media that works on your home network to not work on a mobile device unless the integration is proxying the media though the HA instance.

I don't have an iPhone so cannot easily test this. Can anyone else verify this behavior?

**Comment by haforme** [comment]
Works on iPAD okay but if I use the iPhone it does not load until I got to another video then back to the one I originally selected.  Both connections were over a VPNTrevor CloseOn Jun 5, 2025, at 9:30 AM, Dermot Duffy ***@***.***> wrote:﻿dermotduffy left a comment (dermotduffy/advanced-camera-card#1748)

Playing media directly in ha works as espected ;-)

Just to confirm, you mean the same piece of media works in the HA media browser, on the same phone, with the same network settings -- but does not on the card? That should not happen. However, it's not at all uncommon for media that works on your home network to not work on a mobile device unless the integration is proxying the media though the HA instance.
I don't have an iPhone so cannot easily test this. Can anyone else verify this behavior?

**Comment by Jack77777777** [comment]
@dermotduffy 
> Hope that's enough for you to experimental with. As above, see the worked example in the documentation too which has screenshots that may help you understand how it works.

I experimented lot but the only thing i had success is to parse the date, but not the time.

My media file string is like below, the first **bold** marked area is the date and the second the time. For time it shows 00:00 for each record.

Foscam C1-**20250507**-**171758**-1746631078004-3.mp4

```
folders:
  - type: ha
    icon: mdi:movie
    title: Aufnahmen
    ha:
      url: >-
        /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2F
      path:
        - matchers:
            - type: title
              regexp: Foscam C1
        - parsers:
            - type: startdate
              regexp: \d+
        - parsers:
            - type: startdate
              regexp: Foscam C1-yyyyMMdd-HHmmss
```

![Image](https://github.com/user-attachments/assets/d48eb656-3eb2-4d42-8757-e5555a26f555)

**Comment by dermotduffy** [comment]
@Jack77777777 I've added a worked example that is somewhat based on your setup, see [Worked Example 2](https://card.camera/#/configuration/folders?id=worked-example-2). It shows two different ways to parse the date/time, if you use the second make sure you update to >= [v7.13.1](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.13.1).

I hope this will give you additional things to try.

**Comment by oeiber** [comment]
> > Playing media directly in ha works as espected ;-)
> 
> Just to confirm, you mean the _same_ piece of media works in the HA media browser, on the _same_ phone, with the _same_ network settings -- but does not on the card? That should not happen. However, it's not at all uncommon for media that works on your home network to not work on a mobile device unless the integration is proxying the media though the HA instance.
> 
> I don't have an iPhone so cannot easily test this. Can anyone else verify this behavior?

I've figured out, that automatic playback is the problem on ios devices. So if ingegrated media control is disabled, there's no way to play the clip

**Comment by oeiber** [comment]
Hi,
currently, when pressing the folder icon, the media browser is opened. when pressing the icon long, the latest clip is played in media player. It would be nice, there were an option to to set media player as default option with a short press.

**Comment by dermotduffy** [comment]
> It would be nice, there were an option to to set media player as default option with a short press.

You can just add your own [menu custom icon](https://card.camera/#/examples?id=menu-icons) that calls the [folder action](https://card.camera/#/configuration/actions/custom/README?id=folder), and hide the default folder icon.

**Comment by oeiber** [comment]
> You can just add your own [menu custom icon](https://card.camera/#/examples?id=menu-icons) that calls the [folder action](https://card.camera/#/configuration/actions/custom/README?id=folder), and hide the default folder icon.
> 
> 

That's working, thank you!
Is there a filter condition for folder ids? Because of I've configured two folders with a button for each. When I click the first one, the second button will also became active. 
Also, when using thumbnail drawer, buttons well become inactive, after clicking a clip.

**Comment by dermotduffy** [comment]
@oeiber 

> Is there a filter condition for folder ids?

If you just mean to show a specific folder instead of just the first, then yes, there is -- as per the linked documentation and the `folder` parameter.

> Also, when using thumbnail drawer, buttons well become inactive, after clicking a clip.

I don't follow this I'm afraid. If you'd like to discuss specific things, lets open a new issue (1 problem per filed issue please). This issue is more about closing out a basic set of folder features, and if we mix specific bug reports or feature requests into it, it will be impossible to follow and very noisy for other folks on this thread. Thanks for understanding!

**Comment by Jack77777777** [comment]
> [@Jack77777777](https://github.com/Jack77777777) I've added a worked example that is somewhat based on your setup, see [Worked Example 2](https://card.camera/#/configuration/folders?id=worked-example-2). It shows two different ways to parse the date/time, if you use the second make sure you update to >= [v7.13.1](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.13.1).
> 
> I hope this will give you additional things to try.

Finally i had time to implement this. I had one more folder in between so needed a - {} more as in the example.
Thanks a lot.

```
folders:
  - type: ha
    icon: mdi:movie
    title: Aufnahmen
    ha:
      url: >-
        /media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source
      path:
        - {}
        - {}
        - parsers:
            - type: date
              regexp: \d{8}-\d{6}
              format: yyyyMMdd-HHmmss
```
