### ISSUE TITLE
Frigate card stream doesn't work over Nabu Casa

### ISSUE THREAD

**Issue by T0m112233** [dermotduffy/frigate-hass-card#1749]
**Checklist:**

- Updated to latest version
- Cleared cache on my browser

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.0.4
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-13T11:54:00.191Z
lang: en
git:
  hash: 1992db2
  build_date: Thu, 12 Dec 2024 04:43:25 GMT
  commit_date: Wed, 11 Dec 2024 20:42:05 -0800
ha_version: 2024.12.2
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.6.0
    devices:
      *********
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front_door
      live_provider: auto
  menu:
    style: overlay
    buttons:
      substreams:
        enabled: false
      cameras:
        enabled: false
      timeline:
        enabled: false
      expand:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      clips:
        enabled: false
      live:
        enabled: true
  view:
    default: image
  image:
    mode: camera
    refresh_seconds: 1
  dimensions: {}
  media_viewer:
    draggable: true
  performance: {}
  status_bar:
    style: outside
    position: bottom
```

**[REQUIRED] Description of problem:**

Since upgrading to home assistant 2024.11 (webRTC support) - the frigate card no longer working over nabu casa (only on wifi).

Tried to enable, disable go2rtc in both frigate configuration and card without luck.
Sometihng was changed with the latest version and broke the stream.

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
"Subscription not found."
```

Thanks
