### ISSUE TITLE
Hiding `builtin` controls does not work on first camera

### ISSUE THREAD

**Issue by oded106e** [dermotduffy/frigate-hass-card#1751]
I’ve integrated my camera and can view live feed through the camera entity. However, I noticed that the timeline is displayed as shown in the attached screenshot when i move over the card with the cursor. Is there an option to completely remove this timeline from being displayed?
![image](https://github.com/user-attachments/assets/e9738542-52ad-4b0d-ad6e-7d8d30b3f768)

```
card_version: 6.0.6
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-14T11:28:26.643Z
lang: en
timezone: Asia/Jerusalem
git:
  hash: ed0bb99
  build_date: Fri, 13 Dec 2024 16:12:40 GMT
  commit_date: Fri, 13 Dec 2024 08:11:26 -0800
ha_version: 2024.12.3
integrations:
  reolink:
    detected: true
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.garden_camera
      ptz:
        data_left:
          entity_id: camera.garden_camera
          direction: LEFT
        data_right:
          entity_id: camera.garden_camera
          direction: RIGHT
        data_up:
          entity_id: camera.garden_camera
          direction: UP
        data_down:
          entity_id: camera.garden_camera
          direction: DOWN
        service: eufy_security.ptz
      dimensions:
        layout:
          fit: fill
      live_provider: ha
    - camera_entity: camera.tapo_c200_35ac_hd_stream
      ptz:
        service: button.press
        data_left:
          entity_id: button.tapo_c200_35ac_move_left
        data_right:
          entity_id: button.tapo_c200_35ac_move_right
        data_up:
          entity_id: button.tapo_c200_35ac_move_up
        data_down:
          entity_id: button.tapo_c200_35ac_move_down
      title: Garden Camera 2
      icon: mdi:video
      triggers:
        occupancy: false
      live_provider: auto
      dimensions:
        layout:
          fit: fill
    - camera_entity: camera.reolink_video_doorbell_wifi_fluent
      live_provider: ha
      triggers:
        occupancy: false
      capabilities:
        disable:
          - clips
          - recordings
      dimensions:
        layout:
          fit: fill
  live:
    preload: true
    controls:
      builtin: false
      next_previous:
        style: none
      timeline:
        show_recordings: false
      ptz:
        orientation: horizontal
        style:
          right: 81%
          top: 70%
          transform: scale(1.5, 1.5)
          background: rgba(255, 255, 255, 0.0)
    draggable: false
    zoomable: true
    show_image_during_load: true
    lazy_load: true
    lazy_unload:
      - hidden
  menu:
    buttons:
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      media_player:
        enabled: false
      timeline:
        enabled: false
      clips:
        enabled: false
      live:
        enabled: false
      frigate:
        enabled: true
      substreams:
        enabled: true
      cameras:
        enabled: true
      expand:
        enabled: false
      mute:
        enabled: true
      display_mode:
        enabled: false
    style: hover
  performance:
    features:
      animated_progress_indicator: false
      media_chunk_size: 300
    style:
      border_radius: false
      box_shadow: false
  view:
    default: live
    camera_select: live
    interaction_seconds: 0
    default_reset:
      interaction_mode: all
      every_seconds: 120
  media_viewer:
    draggable: false
    zoomable: false
    lazy_load: false
    controls:
      builtin: false
      timeline:
        show_recordings: false
    snapshot_click_plays_clip: false
  timeline:
    show_recordings: false
  dimensions:
    aspect_ratio_mode: static
    height: 300px
  image:
    zoomable: false
  media_gallery:
    controls:
      thumbnails:
        show_favorite_control: false
        show_download_control: false
        show_timeline_control: false
  profiles: []
```

Thank you!
