### ISSUE TITLE
  auto_mute with microphone not working (Reolink Doorbell)

### ISSUE THREAD

**Issue by Jack77777777** [dermotduffy/frigate-hass-card#1754]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.0.6
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
date: 2024-12-14T13:25:07.856Z
lang: en
timezone: Europe/Berlin
git:
  hash: ed0bb99
  build_date: Fri, 13 Dec 2024 16:12:40 GMT
  commit_date: Fri, 13 Dec 2024 08:11:26 -0800
ha_version: 2024.12.2
integrations:
  reolink:
    detected: true
  frigate:
    detected: true
    version: 5.6.0
    devices:
      7759016f1044d7688056bc4493acca8c: 5.6.0/0.13.2-6476f8a
  hass_web_proxy:
    detected: false
  motioneye:
    detected: true
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.haustuer
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
      title: Haustür
  menu:
    buttons:
      microphone:
        enabled: true
        permanent: false
        type: toggle
        alignment: opposing
      cameras:
        enabled: true
      substreams:
        enabled: true
      mute:
        enabled: true
        permanent: false
        alignment: opposing
      snapshots:
        enabled: false
      clips:
        enabled: false
      live:
        enabled: true
      display_mode:
        enabled: true
  live:
    lazy_load: true
    preload: true
    draggable: true
    auto_play:
      - selected
      - visible
    auto_mute:
      - microphone
    auto_unmute:
      - microphone
    show_image_during_load: false
    auto_pause: []
    controls:
      builtin: false
  view: {}
```

**[REQUIRED] Description of problem:**
auto_unmute with microphone is working. But auto_mute with microphone doesn´t.
