### ISSUE TITLE
Slower than expected time to initial image

### ISSUE THREAD

**Issue by spiderjuka** [dermotduffy/frigate-hass-card#1769]
After update Frigate Card form version 5.2.0 to > 6.x.x I noticed a significant latency in the appearance of the camera image.
Version v5.2.0 has much less video latency when compared to v6.x.x (current 6.0.12)
For Frigate Card version 5.2.0 after switching to the camera the image from the camera is visible almost immediately. After update to version > 6.x.x (currently tested on 6.0.12) sometimes need to wait even 1-2 seconds which is problem when operating the intercom (Hikvison Doorbell).

**My hardware configuration:**
HAOS is installed on Dell Wyse 5070 (Intel J5005) with Proxmox.

**Frigate Card setup:**
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.hikvision
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
menu:
  style: outside
  position: bottom
  buttons:
    microphone:
      enabled: true
      type: toggle
    screenshot:
      enabled: false
    download:
      enabled: false
    fullscreen:
      enabled: false
    snapshots:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    clips:
      enabled: false
    live:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    camera_ui:
      enabled: false
live:
  auto_mute: never
  controls:
    builtin: true
    title:
      mode: none
  layout:
    fit: fill
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:volume-high
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: unmute
  - type: custom:frigate-card-menu-icon
    icon: mdi:volume-off
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: mute
  - type: custom:frigate-card-menu-icon
    icon: mdi:phone
    tap_action:
      - action: call-service
        service: button.press
        service_data:
          entity_id: button.ds_kv8213_answer_call
      - action: call-service
        service: button.press
        service_data:
          entity_id: button.ds_kv8213_hangup_call
      - action: custom:frigate-card-action
        frigate_card_action: unmute
      - action: custom:frigate-card-action
        frigate_card_action: microphone_unmute
  - type: custom:frigate-card-menu-icon
    icon: mdi:phone-hangup
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: microphone_mute
  - type: custom:frigate-card-menu-icon
    icon: mdi:door-open
    entity: switch.ds_kv8213_door_relay_0
    tap_action:
      action: toggle
  - type: custom:frigate-card-menu-icon
    icon: mdi:gate-open
    entity: switch.ds_kv8213_door_relay_1
    tap_action:
      action: toggle
dimensions:
  aspect_ratio: "16:9"
  aspect_ratio_mode: dynamic
```

I had to back to version 5.2.0 because I have no idea how to solev the problem.
Can you support me to solve it?

**Comment by dermotduffy** [comment]
> Version v5.2.0 has much less video latency when compared to v6.x.x (current 6.0.12)

When you say video latency, do you mean (i) time from a blank page to first image to load, or do you mean (ii) delay between real-time and what you see on camera generally?

**Comment by spiderjuka** [comment]
> > Version v5.2.0 has much less video latency when compared to v6.x.x (current 6.0.12)
> 
> When you say video latency, do you mean (i) time from a blank page to first image to load, or do you mean (ii) delay between real-time and what you see on camera generally?

Good question!
I mean time from a blank page to first image to load - that is big problem.

**Comment by dermotduffy** [comment]
> I mean time from a blank page to first image to load - that is big problem.

Huh. OK. Can't say I noticed any difference. Let me try out your config.

**Comment by dermotduffy** [comment]
As a cursory check: Do you see anything unusual logged to your Javascript console? (F12 in Chrome)

**Comment by spiderjuka** [comment]
Javascript console I will check today afternoon - when I will back to home.
At my hardware - Intel J5005 it is really noticeable difference.
The problem is that when someone calls home from the intercom, they have to wait a bit before the intercom image appears on the tablet. I didn't have this problem with version 5.2.0.

The configuration of the Frigate card I have provided above.
Below you can find the configuration for frigate itself:
```
mqtt:
  enabled: true
  host: 192.168.100.37
  user: mqtt
  password: mqtt

environment_vars:
  LIBVA_DRIVER_NAME: i965

cameras:
  Hikvision:
    detect:
      enabled: false

    ffmpeg:
      hwaccel_args: preset-vaapi

      inputs:
        - path: rtsp://admin:200371Jurek@192.168.100.54:554/Streaming/Channels/101

go2rtc:
  streams:
    Hikvision:
      - rtsp://admin:200371Jurek@192.168.100.54:554/Streaming/Channels/101
      - isapi://admin:200371Jurek@192.168.100.54:80/

version: 0.14
```

**Comment by dermotduffy** [comment]
@spiderjuka Thanks. As well as checking the Javascript console, any chance you could take a short video clip / screen capture of the loading and what you see?

**Comment by spiderjuka** [comment]
Below you can find some finding at Java console - I don't know if it is important or not?
But I noticed something interesting. You can reduce the delay time by touching the area where the camera image should appear with finger or mouse cursor - you can see this in the videos I sent as well.

Frigate Card v5.2.0 on Tablet - OK:
https://github.com/user-attachments/assets/010e9b82-702b-4179-8ab4-5d001969f5ee
Frigate Card v6.1.0 on Tablet - NOK:
https://github.com/user-attachments/assets/3204ccd1-f0c5-4c26-80f4-45904a649cf6
Frigate Card v6.1.0 on PC - NOK:
https://github.com/user-attachments/assets/67149307-41a3-4b0d-b694-d4ebaeb6675d
Java console:
![Java_console](https://github.com/user-attachments/assets/c9fc9d1f-3e9c-47c0-b9b4-07903767fa98)

**Comment by dermotduffy** [comment]
Those logs are just Frigate being over loggy, that was fixed in a later Frigate release, I highly doubt it's related. You could try:

```
cameras:
  - camera_entity: camera.hikvision
    capabilities:
      disable:
        - ptz
```

Your issue looks like a rendering problem (the fact it updates when you move the mouse over it).

**Comment by dermotduffy** [comment]
@spiderjuka Are you using any [URL actions](https://card.camera/#/usage/url-actions), i.e. query parameters in your dashboard URL?

**Comment by spiderjuka** [comment]
> Those logs are just Frigate being over loggy, that was fixed in a later Frigate release, I highly doubt it's related. You could try:
> 
> ```
> cameras:
>   - camera_entity: camera.hikvision
>     capabilities:
>       disable:
>         - ptz
> ```
> 
> Your issue looks like a rendering problem (the fact it updates when you move the mouse over it). The PTZ thing is just "another thing" the card needs to do at startup. My theory is the initialization is finished, but for some reason the card is not being re-rendered and then "coincidentally" re-renders when something else forces it to (e.g. mouse move).

I already did it - unfortunatelly still error in logs is present:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.hikvision
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
    capabilities:
      disable:
        - ptz
```
![Onvif is not setup for Hikvision](https://github.com/user-attachments/assets/e3280f16-453a-443e-ac2f-4b758d00dbc9)

**Comment by dermotduffy** [comment]
> Yes, only for two buttons: one is nevigate to camera doorbel (lovelance) and second navigate to outside standard camera.

When you don't use the URL actions, do you still have your delay?

> But it is important to note that in the Frigate Card v5.2.0 there was no PTZ error

`v5.2.0` could not automatically detect PTZ capabilities.

> and there was no significant delay in the camera image appearing - why?

Well, that's the whole point of this issue, to find out :-) The codebase changed _massively_ between  `v5.2.0` and now, so it could be any of thousands of lines of code.

**Comment by spiderjuka** [comment]
> > Yes, only for two buttons: one is nevigate to camera doorbel (lovelance) and second navigate to outside standard camera.
> 
> When you don't use the URL actions, do you still have your delay?
> 
> > But it is important to note that in the Frigate Card v5.2.0 there was no PTZ error
> 
> `v5.2.0` could not automatically detect PTZ capabilities.
> 
> > and there was no significant delay in the camera image appearing - why?
> 
> Well, that's the whole point of this issue, to find out :-) The codebase changed _massively_ between `v5.2.0` and now, so it could be any of thousands of lines of code.

I changed url to navigate and after I deleted button - still this same delay.
Second camera I have out of Frigate card.
This card work very well - without any problem:
```
square: false
type: grid
cards:
  - show_state: true
    show_name: true
    camera_view: live
    type: picture-entity
    entity: camera.ds_2cd2655fwd_izs20171218aawr145253995_101
columns: 1
```

But why still PTZ error exist in logs even capabilities was disabled for it?
