### ISSUE TITLE
Menu should not overlap with certain views like the clips gallery

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1776]
I don't know if this is bug or a feature request, thus I bypassed the template. I apologize for that.

The rationale is simple: I think menu should not overlap with certain views like the clips gallery.

First note: menu would only overlap if its style were `overlay` or `hover`.

While I think it makes sense that these styles apply for like when a media is being shown, I don't think it makes sense to overlap when the card is not rendering a media, potentially affecting the user experience by covering some buttons and whatnot.

Example:

![image](https://github.com/user-attachments/assets/632ed77c-118c-403f-b829-158f8bbe9c7e)

In the example above, you can see that the menu bar covers half of the first clips row, making it more difficult to click (or even impossible to click in the icons at the top of the thumbnail).

Here is a simple config example:

```yaml
type: custom:frigate-card
menu:
  style: overlay
cameras:
  - camera_entity: camera.video_porteiro
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: "16:9"
```

What do you think?

I think regardless of the menu style, certain views should never have the menu overlay-ed.

**Comment by dermotduffy** [comment]
I think the current behavior is arguably the least surprising.

If the user wants that behavior, an override could help, like this for the `clips` view:

```yaml
type: custom:frigate-card
menu:
  style: overlay
cameras:
  - camera_entity: camera.office
overrides:
  - conditions:
      - condition: view
        views:
          - clips
    merge:
      menu:
        style: none
```
