### ISSUE TITLE
The camera streams failed when frigate integration is connected to frigate via authentication API

### ISSUE THREAD

**Issue by janusn** [dermotduffy/frigate-hass-card#1778]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.1.0
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-17T19:18:26.223Z
lang: en
timezone: Europe/London
git:
  hash: 0b68140
  build_date: Tue, 17 Dec 2024 05:06:29 GMT
  commit_date: Mon, 16 Dec 2024 21:05:17 -0800
ha_version: 2024.12.3
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JFAZZ4D10QMPKQX5K9YN5E17: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.video_doorbell
      live_provider: go2rtc
      dependencies:
        cameras: []
      go2rtc:
        modes:
          - mse
        stream: video_doorbell
  view:
    dark_mode: auto
    default: live
  live:
    zoomable: true
    draggable: true
    preload: false
    lazy_load: true
  menu:
    style: hover-card
    buttons:
      substreams:
        icon: mdi:high-definition
        alignment: opposing
        enabled: false
      cameras:
        enabled: false
      frigate:
        enabled: true
      screenshot:
        enabled: true
        alignment: opposing
      mute:
        enabled: true
        alignment: opposing
      expand:
        enabled: false
        alignment: opposing
      live:
        enabled: true
      clips:
        enabled: true
      snapshots:
        enabled: true
      recordings:
        enabled: true
      image:
        enabled: false
      download: {}
      fullscreen:
        alignment: opposing
      media_player:
        alignment: opposing
  media_gallery:
    controls:
      thumbnails:
        show_details: false
  performance: {}
  automations:
    - conditions:
        - condition: fullscreen
          fullscreen: true
      actions:
        - action: custom:frigate-card-action
          frigate_card_action: live_substream_on
      actions_not:
        - action: custom:frigate-card-action
          frigate_card_action: live_substream_off
  elements:
    - type: icon
      icon: mdi:cctv
      title: Show Hello Video Doorbell Tab
      style:
        left: 10px
        top: 50%
        color: '#fcba03'
      entity: camera.video_doorbell
      tap_action:
        action: navigate
        navigation_path: hello-doorbell-camera
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_person_occupancy
          state: 'on'
      elements:
        - type: state-icon
          icon: mdi:account
          style:
            left: 45%
            top: 90%
            transform: translate(-50%,-50%)
            '--paper-item-icon-color': '#fcba03'
          entity: binary_sensor.video_doorbell_person_occupancy
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_person_occupancy
          state: 'off'
      elements:
        - type: state-icon
          icon: mdi:account-off
          style:
            left: 45%
            top: 90%
            transform: translate(-50%,-50%)
          entity: binary_sensor.video_doorbell_person_occupancy
    - type: state-label
      style:
        left: 45%
        top: 90%
        color: white
        transform: translate(-50%,0%)
      entity: sensor.video_doorbell_person_count
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_car_occupancy
          state: 'on'
      elements:
        - type: state-icon
          icon: mdi:car
          style:
            left: 60%
            top: 90%
            transform: translate(-50%,-50%)
            '--paper-item-icon-color': '#fcba03'
          entity: binary_sensor.video_doorbell_car_occupancy
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_car_occupancy
          state: 'off'
      elements:
        - type: state-icon
          icon: mdi:car-off
          style:
            left: 60%
            top: 90%
            transform: translate(-50%,-50%)
          entity: binary_sensor.video_doorbell_car_occupancy
    - type: state-label
      style:
        left: 60%
        top: 90%
        color: white
        transform: translate(-50%,0%)
      entity: sensor.video_doorbell_car_count
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_dog_occupancy
          state: 'on'
      elements:
        - type: state-icon
          icon: mdi:dog-side
          style:
            left: 75%
            top: 90%
            transform: translate(-50%,-50%)
            '--paper-item-icon-color': '#fcba03'
          entity: binary_sensor.video_doorbell_dog_occupancy
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_dog_occupancy
          state: 'off'
      elements:
        - type: state-icon
          style:
            left: 75%
            top: 90%
            transform: translate(-50%,-50%)
          entity: binary_sensor.video_doorbell_dog_occupancy
    - type: state-label
      style:
        left: 75%
        top: 90%
        color: white
        transform: translate(-50%,0%)
      entity: sensor.video_doorbell_dog_count
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_cat_occupancy
          state: 'on'
      elements:
        - type: state-icon
          icon: mdi:cat
          style:
            left: 90%
            top: 90%
            transform: translate(-50%,-50%)
            '--paper-item-icon-color': '#fcba03'
          entity: binary_sensor.video_doorbell_cat_occupancy
    - type: conditional
      conditions:
        - entity: binary_sensor.video_doorbell_cat_occupancy
          state: 'off'
      elements:
        - type: state-icon
          icon: janus:cat-off
          style:
            left: 90%
            top: 90%
            transform: translate(-50%,-50%)
          entity: binary_sensor.video_doorbell_cat_occupancy
    - type: state-label
      style:
        left: 90%
        top: 90%
        color: white
        transform: translate(-50%,0%)
      entity: sensor.video_doorbell_cat_count
```

**[REQUIRED] Description of problem:**

When the frigate hass integration connects to the frigate container via authenticated API (port 8971). The frigate card can no longer show the live stream. The entity shown on the frigate hass integration has no problem streaming from the camera.

**[OPTIONAL] Last working release (if known):** Never. Frigate hass integration has just supported authentication API since v5.6.0.

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
