### ISSUE TITLE
Frigate card stopped working after update. Getting unknown_command error when initializing cameras in frigate card.

### ISSUE THREAD

**Issue by Edgar-Grigoryan** [dermotduffy/frigate-hass-card#1783]
I am encountering an unknown_command error when trying to initialize cameras with the frigate-card in Home Assistant. The error occurs when the card attempts to load the cameras, specifically for the camera entity camera.reolink_sub.

<img width="464" alt="Screenshot 2024-12-18 at 23 58 43" src="https://github.com/user-attachments/assets/54c0a888-3428-4b0b-a901-55edc0ad5545" />

Here is the card configuration I am using:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.reolink_sub
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
      stream: reolink_sub
menu:
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      priority: 0
      type: momentary
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
      alignment: opposing
    mute:
      enabled: true
      alignment: opposing
      priority: 5
    camera_ui:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: true
      alignment: opposing
    clips:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: true
      alignment: opposing
      priority: 10
    fullscreen:
      priority: 0
  style: overlay
  position: bottom
  button_size: 60
  alignment: top
live:
  controls:
    thumbnails:
      mode: none
    builtin: false
  preload: false
  draggable: false
  zoomable: true
  lazy_load: false
  microphone:
    always_connected: true
    disconnect_seconds: 0
dimensions:
  aspect_ratio_mode: dynamic
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
media_viewer:
  controls:
    builtin: false
    timeline:
      mode: above
  draggable: false
  zoomable: true
  lazy_load: false
  snapshot_click_plays_clip: false
timeline:
  show_recordings: false
performance:
  features:
    animated_progress_indicator: false
image:
  mode: camera
  refresh_seconds: 60
view:
  default: image
  camera_select: live
  interaction_seconds: 60
  default_reset:
    every_seconds: 0
grid_options:
  columns: 12
  rows: auto
debug:
  logging: true
```

The unknown_command message prevents the camera from being initialized. The configuration is set to use the go2rtc stream provider with the webrtc mode. I have verified that the camera entity camera.reolink_sub exists and is functioning correctly in Home Assistant.

Could you please investigate why this error occurs and suggest a fix or provide guidance on resolving it?

Thank you!
