### ISSUE TITLE
Missing camera in filter when using multiple cameras in clips galery 

### ISSUE THREAD

**Issue by florian-asche** [dermotduffy/frigate-hass-card#1784]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.1.0
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
date: 2024-12-20T00:07:56.108Z
lang: en
timezone: Europe/Paris
git:
  hash: 0b68140
  build_date: Tue, 17 Dec 2024 05:06:29 GMT
  commit_date: Mon, 16 Dec 2024 21:05:17 -0800
ha_version: 2024.12.4
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      46c0b222f5f69c3bd52fabdd017a7dcb: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.eingang
    - camera_entity: camera.garten
    - camera_entity: camera.tuerklingel
  view:
    default: clips
    default_reset:
      after_interaction: true
      every_seconds: 60
    camera_select: clip
    dark_mode: auto
  menu:
    style: overlay
    buttons:
      frigate:
        enabled: true
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: false
      clips:
        enabled: true
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      fullscreen:
        enabled: true
      media_player:
        enabled: false
      display_mode:
        enabled: false
      timeline:
        enabled: false
      recordings:
        enabled: true
    position: top
    alignment: top
  media_gallery:
    controls:
      thumbnails:
        size: 140
        show_favorite_control: true
        show_timeline_control: true
        show_details: false
        show_download_control: true
      filter:
        mode: right
  media_viewer:
    auto_play:
      - visible
      - selected
  layout_options:
    grid_columns: full
    grid_rows: 8
  dimensions:
    height: 750px
  timeline:
    show_recordings: false

```

**[REQUIRED] Description of problem:**

When using the frigate card for displaying the clips galery and its configured for multiple cameras, the default filter is always, by default (after reload) only set with the first camera. Means the other media are missing and after reload you have to add them into the filter.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
> When using the frigate card for displaying the clips galery and its configured for multiple cameras, the default filter is always, by default (after reload) only set with the first camera. Means the other media are missing and after reload you have to add them into the filter.

Do you mean, the issue is that it doesn't "remember" your filter settings between reloads?

**Comment by florian-asche** [comment]
> > When using the frigate card for displaying the clips galery and its configured for multiple cameras, the default filter is always, by default (after reload) only set with the first camera. Means the other media are missing and after reload you have to add them into the filter.
> 
> Do you mean, the issue is that it doesn't "remember" your filter settings between reloads?

I mean that although I have configured three cameras in the card, there is always only one camera in the filter, e.g. after a reload or even before.

**Comment by florian-asche** [comment]
When using multiple camera's for reviewing clips only the first camera is added to the filter on site load.

**Comment by dermotduffy** [comment]
I think this is a misunderstanding rather than a bug: by default it only shows the events associated with the selected camera. That's intentional. If you want it to show events from other cameras as well, add them as dependencies like this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.kitchen
    dependencies:
      cameras:
        - camera.office
  - camera_entity: camera.office
```

... this will show you events for both. I think this is what you want. Let me know if it I'm missing the point.
