### ISSUE TITLE
Grid view - Expand only selected camera

### ISSUE THREAD

**Issue by fjluquerodriguez** [dermotduffy/frigate-hass-card#1785]
Currently in grid mode, if i use expand action:

```
action: custom:frigate-card-action
frigate_card_action: expand
```
full grid (with all cameras) is expanded, so really, there is no so much difference...  Maybe It will be more usefull if only selected camera will be expanded...

Alternatively I'm triying to open a popup with tap_action:

```
  actions:
    tap_action:
      - action: perform-action
        perform_action: script.popup_camera
        data:
          camera: camera.porche
```

This works but as you can see camera is static... I don't know how do it dynamic:

I've tried templating:

```
  actions:
    tap_action:
      - action: perform-action
        perform_action: script.popup_camera
        data:
          camera: "{{this.entity_id}}"
```
but seems that templates are not evaluated...

Thanks

**Comment by dermotduffy** [comment]
@fjluquerodriguez It would help if you could describe what are you trying to do. Would you mind saying a little more about what you are trying to achieve, and I'll see if I can think of way to achieve it?

**Comment by fjluquerodriguez** [comment]
@dermotduffy i'm trying to show a camera in full screen or expanded (only that camera) when I click on the camera in grid mode. Now, it expands all cameras (full grid). I know that I can do clicking in the camera (camera is selected) and then click in the grid button of the menu. But when I have a lot of cameras, thats is not easy or "confortable"... I think It will be better to click to zoom and a close button in order to return to the grid view. Thats is that i'm triting with tap_action and script but without templating available is imposible... thanks

**Comment by dermotduffy** [comment]
Thanks @fjluquerodriguez . When you click on a camera in grid mode, it should already "zoom into that camera" (the degree it scales is controlled by [`grid_selected_width_factor`](https://card.camera/#/configuration/live?id=display). I think you're looking for some sort of alternative, that instead of scaling that camera within the grid, when you click on it, it instead "pops up" only that camera. Is that right?

I could imagine a new parameter `grid_select_action` which has these values:

 - `scale`: Scales the camera within the grid [default today]
 - `expand`: Selects that camera only, and expands it. When the expanded camera closes, it returns the card to the grid.

Is that the kind of thing you're looking for?

**Comment by fjluquerodriguez** [comment]
That's exactly @dermotduffy. It would be great to have it! Thanks

**Comment by dermotduffy** [comment]
OK, got it. The more votes the top comment gets, the more likely I am to prioritize this on the stack.

**Comment by breakingspell** [comment]
I think what's described here is technically achievable already with the menu button for `display_mode`  to toggle the grid view on and off. My usage is 4 cameras in a small 2x2 grid, constrained by width: 
```
live:
  display:
    mode: grid
    grid_selected_width_factor: 1
    grid_columns: 2

menu:
  style: outside
  buttons:
    display_mode:
      priority: 49
    fullscreen:
      priority: 48
```

To "popup" or isolate a camera view in the card, i'll select one, then tap the `display_mode` button, then the same button again to go back. If I want to full-screen further from there, i've manually positioned the buttons to always be adjacent.

However it's certainly not perfect or the most intuitive. At the moment the "expand" button expands the entire view, regardless of it's contents, so I leave the button disabled.

A better solution would be a single tap (or double tap) action for the selected camera to properly "expand" and then back to grid view, as proposed 👍
