### ISSUE TITLE
Issue w/ v6 - View of last snapshot doesn't work unless you allow thumbnails in media_viewer controls

### ISSUE THREAD

**Issue by kohlerryan** [dermotduffy/frigate-hass-card#1787]
**[REQUIRED] Describe the feature you'd like:**

Prior to v6, I used a card that pulled all cameras events and showed the snapshow of the last event.  I used the buttons on the right and left to navigate to previous event snapshots, and to play the event I used the option to click the snapshot.  I hid all menus to keep it very clean and simple.

Since v6, my config below for media_viewer is causing an issue where no media is loaded.  If I remove `thumbnails: mode: none`, it works fine, but I get the menu along the side that I would like to not have showing.

```
media_viewer:
  draggable: false
  transition_effect: none
  controls:
    builtin: false
    thumbnails:
      mode: none
```

**[OPTIONAL] Describe alternatives you've considered:**

Removing `thumbnails: mode: none`, but I don't get the desired result of not having the sidebar menu to navigate clips.  I only want to have the right/left buttons.

**[OPTIONAL] Additional context:**
