### ISSUE TITLE
Reolink Doorbell Onvif Error in 2 Way Audio

### ISSUE THREAD

**Issue by sharbich** [dermotduffy/frigate-hass-card#1788]
Hello,
when I use the Frigate card to connect a 2-way audio to the Reolink Doorbell camera, I see the following error message in the Frigate AddOn logging:
```
error 2024-12-23 13:00:05 frigate.ptz.onvif Onvif is not setup for reolink
error 2024-12-23 13:01:08 frigate.ptz.onvif Onvif is not setup for reolink
error 2024-12-23 13:47:26 frigate.ptz.onvif Onvif is not setup for reolink
error 2024-12-23 13:58:49 frigate.ptz.onvif Onvif is not setup for reolink
```
If I establish the 2-way connection via the Frigate AddOn then I don't see any error message.
```
homeassistant:/config# cat frigate.yml
mqtt:
  host: 172.30.32.1            # YOUR MQTT IP
  user: #####_mqtt             # YOUR MQTT USERNAME
  password: Marlies(12)        # YOUT MQTT PASSWORD
go2rtc:
  streams:
    webrtc:
      candidates:
      - 192.168.20.151:8555
      - stun: 8555
    reolink:
      - ffmpeg:https://192.168.130.143/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=#####&password=Marlies1234#video=copy#audio=copy#audio=opus
      - rtsp://#####:Marlies1234@192.168.130.143:554/h264Preview_01_sub
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    zones:
      reolink_zone:
        coordinates: 0,480,800,480,543,323,362,329,0,61     # WATCH MY FRIGATE VIDEO SHOWING YOU WHAT THIS IS
    motion:
      mask:
        - 613,309,275,0,297,339                             # WATCH MY FRIGATE VIDEO SHOWING YOU WHAT THIS IS
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7
detect:
  width: 800
  height: 400
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7
record:
  enabled: true
  retain:
    days: 7
  events:
    retain:
      default: 7
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
version: 0.14
```

```
frigate card
type: custom:frigate-card
cameras:
  - camera_entity: camera.reolink
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
menu:
  buttons:
    microphone:
      enabled: true
      alignment: opposing
      type: toggle
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
      alignment: opposing
    camera_ui:
      enabled: false
  style: overlay
  position: left
live:
  controls:
    thumbnails:
      mode: none
  preload: false
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
```
Reolink Firmware: v3.0.0.4110_2410111119
Frigate Version: 0.14.1
go2rtc Version: 1.9.7 from AlexIT
HACS Frigate Card Version: 6.1.0

I have a WIFI doorbell that is connected to the WLAN via 5Ghz. I get an echo in the 2-way communication when I say something from the end device (web browser, iPhone, Android phone, tablet, etc.).

There doesn't seem to be a working solution with this camera. Do you have any other experiences?

[ccab4aaf_frigate_2024-12-23T13-24-49.955Z.log](https://github.com/user-attachments/files/18229803/ccab4aaf_frigate_2024-12-23T13-24-49.955Z.log)

Greetings from Stefan Harbich
