### ISSUE TITLE
startOfHour-34edc6a8.js' doesn't provide an export named: 's'. 

### ISSUE THREAD

**Issue by muddro1** [dermotduffy/frigate-hass-card#1795]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
No cameras support this view. Check troubleshooting.

view: diagnostics
cameras_capabilities: {}

```

**[REQUIRED] Description of problem:**
Getting an error: 
```
Camera initialization failed: The requested module 'https://mydomain/hacsfiles/frigate-hass-card/startOfHour-34edc6a8.js' doesn't provide an export named: 's'. Check troubleshooting.
```

**[OPTIONAL] Last working release (if known):**
Don't recall last working version, but it was working.
**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
What version of the Frigate integration are you using?

**Comment by dermotduffy** [comment]
> Camera initialization failed: The requested module 'https://mydomain/hacsfiles/frigate-hass-card/startOfHour-34edc6a8.js' doesn't provide an export named: 's'. Check troubleshooting.

Hmm. Wondering if your browser is still caching files it shouldn't be, or your installation is somehow corrupted?

**Comment by muddro1** [comment]
> What version of the Frigate integration are you using?

5.6.0 with 14.1

**Comment by muddro1** [comment]
> > Camera initialization failed: The requested module 'https://mydomain/hacsfiles/frigate-hass-card/startOfHour-34edc6a8.js' doesn't provide an export named: 's'. Check troubleshooting.
> 
> Hmm. Wondering if your browser is still caching files it shouldn't be, or your installation is somehow corrupted?

I've tried removing the card, clearing cache, reinstalling, and still doesnt work

**Comment by dermotduffy** [comment]
And what version of the card?

**Comment by muddro1** [comment]
> And what version of the card?

Latest. 6.1.2

**Comment by dermotduffy** [comment]
> Camera initialization failed: The requested module 'https://mydomain/hacsfiles/frigate-hass-card/startOfHour-34edc6a8.js' doesn't provide an export named: 's'. Check troubleshooting.

Manually installed `v6.1.2` seems to work fine. Can you paste me your config? 

[If you haven't already, recommend trying a different device just to be sure there isn't some weird caching going on]

**Comment by muddro1** [comment]
My mobile seems to work. I tried private window, that does not work.

```
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.front_door_bell
        live_provider: go2rtc
        triggers:
          motion: true
      - camera_entity: camera.garage_camera
        live_provider: go2rtc
      - camera_entity: camera.work_room_camera
        live_provider: go2rtc
      - camera_entity: camera.front_door
        live_provider: go2rtc
      - camera_entity: camera.driveway
        live_provider: go2rtc
      - camera_entity: camera.street
        live_provider: go2rtc
      - camera_entity: camera.back_patio
        live_provider: go2rtc
      - camera_entity: camera.backyard
        live_provider: go2rtc
      - camera_entity: camera.backyard_right_side
        live_provider: go2rtc
      - camera_entity: camera.side
        live_provider: go2rtc
      - camera_entity: camera.backyard_left_side
        live_provider: go2rtc
    view:
      dark_mode: auto
    live:
      display:
        mode: grid
```
