### ISSUE TITLE
show WebRTC stream insted HLS

### ISSUE THREAD

**Issue by oded106e** [dermotduffy/frigate-hass-card#1802]
Hi,
I noticed that the card displays an HLS stream while WebRTC is available.
How can I configure it to always display WebRTC instead of HLS?

![399165906-35ce7682-ad94-4ba9-ac2c-9d8a21a7c4d0](https://github.com/user-attachments/assets/d13d5744-43e4-450c-acd8-2e1bfe3f66ef)

![399165958-42ea8a91-afbb-4944-88ad-b80628287e69](https://github.com/user-attachments/assets/9fb4dba5-a5bd-4986-8716-0c9decc37b87)

this happend on 3/3 of my cameras (not only tapo) randomaly.

card config:

```
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2024-12-29T21:44:09.421Z
lang: en
timezone: Asia/Jerusalem
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2024.12.5
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.garden_camera
      ptz:
        data_left:
          entity_id: camera.garden_camera
          direction: LEFT
        data_right:
          entity_id: camera.garden_camera
          direction: RIGHT
        data_up:
          entity_id: camera.garden_camera
          direction: UP
        data_down:
          entity_id: camera.garden_camera
          direction: DOWN
        service: eufy_security.ptz
      dimensions:
        layout:
          fit: fill
      webrtc_card:
        entity: camera.garden_camera
      live_provider: ha
    - ptz:
        service: button.press
        data_left:
          entity_id: button.tapo_camera_move_left
        data_right:
          entity_id: button.tapo_camera_move_right
        data_up:
          entity_id: button.tapo_camera_move_up
        data_down:
          entity_id: button.tapo_camera_move_down
      title: Garden Camera 2
      icon: mdi:video
      triggers:
        occupancy: false
      live_provider: ha
      dimensions:
        layout:
          fit: fill
      camera_entity: camera.tapo_camera_hd_stream
      webrtc_card: {}
    - triggers:
        occupancy: false
      capabilities:
        disable:
          - recordings
          - snapshots
      dimensions:
        layout:
          fit: fill
      webrtc_card: {}
      go2rtc:
        modes: []
      reolink: {}
      proxy:
        dynamic: false
      camera_entity: camera.doorbell_clear
      live_provider: ha
      title: Doorbell
  live:
    preload: false
    controls:
      builtin: false
      next_previous:
        style: none
      timeline:
        show_recordings: false
      ptz:
        orientation: horizontal
        style:
          right: 81%
          top: 70%
          transform: scale(1.5, 1.5)
          background: rgba(255, 255, 255, 0.0)
      thumbnails:
        mode: none
    draggable: false
    zoomable: true
    show_image_during_load: true
    lazy_load: false
    lazy_unload:
      - hidden
  menu:
    buttons:
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      media_player:
        enabled: false
      timeline:
        enabled: false
      clips:
        enabled: false
      live:
        enabled: false
      frigate:
        enabled: true
      substreams:
        enabled: true
      cameras:
        enabled: true
      expand:
        enabled: false
      mute:
        enabled: true
      display_mode:
        enabled: false
    style: hover
  performance:
    features:
      animated_progress_indicator: false
      media_chunk_size: 500
    style:
      border_radius: false
      box_shadow: false
  view:
    default: live
    camera_select: live
    interaction_seconds: 0
    default_reset:
      interaction_mode: all
      every_seconds: 120
  media_viewer:
    draggable: false
    zoomable: false
    lazy_load: false
    controls:
      builtin: false
      timeline:
        show_recordings: false
      thumbnails:
        mode: none
        show_details: false
        show_favorite_control: false
        show_timeline_control: false
        show_download_control: false
    snapshot_click_plays_clip: false
  timeline:
    show_recordings: false
  dimensions:
    aspect_ratio_mode: static
    height: 300px
  image:
    zoomable: false
  media_gallery:
    controls:
      thumbnails:
        show_favorite_control: false
        show_download_control: false
        show_timeline_control: false
  profiles: []
  status_bar:
    popup_seconds: 10
```

Thanks!
Oded
