### ISSUE TITLE
Camera static image no longer stretches to fill 16:9 card

### ISSUE THREAD

**Issue by Elliot1423** [dermotduffy/frigate-hass-card#1804]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2025-01-01T13:30:20.091Z
lang: en
timezone: Europe/London
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2024.12.5
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01J5TTF73MAMAK1CES7R6A3AEF: 5.6.0/0.14.0-
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell_fluent
      live_provider: auto
      dimensions:
        layout:
          zoom: 7.6
          fit: cover
          pan:
            x: 60
            'y': 60
        aspect_ratio: '16:9'
      reolink:
        media_resolution: high
  view:
    default: image
    keyboard_shortcuts:
      ptz_left:
        key: ArrowLeft
      ptz_right:
        key: ArrowRight
      ptz_up:
        key: ArrowUp
      ptz_down:
        key: ArrowDown
      ptz_zoom_in:
        key: +
      ptz_zoom_out:
        key: '-'
      ptz_home:
        key: h
  image:
    mode: camera
    refresh_seconds: 5
    zoomable: false
  dimensions:
    aspect_ratio_mode: static
```

Description of problem:

Using a reolink door bell that doesn't have a 16:9 ratio stream, I used to be able to use the camera layout setting to stretch the image to fit a 16:9 card, this no longer works. 
<img width="482" alt="Screenshot 2025-01-01 at 13 33 25" src="https://github.com/user-attachments/assets/f47de266-c7e2-4752-afa3-6634267afaa0" />

Last working release (if known):**

Not sure on last working release, it hasn't worked for the last 2 or 3 updates
