### ISSUE TITLE
Card cannot be read with `darkreader` extension

### ISSUE THREAD

**Issue by spaceboy76** [dermotduffy/frigate-hass-card#1807]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases). YES
- Please try clearing your browser cache. YES

**[REQUIRED] Card diagnostic information:**
had to get this from chrome as i can barely see the card in FF or Edge

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2025-01-04T13:49:43.227Z
lang: en
timezone: Europe/London
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2025.1.0
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      27b4991160e7bb61efda82f596c6fc1b: 5.6.0/0.15.0-e76f4e9
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.192_168_1_15
```

```yaml

```

**[REQUIRED] Description of problem:**
![image](https://github.com/user-attachments/assets/d7dacb8d-c85c-437e-8157-4ac28f6eba30)
![image](https://github.com/user-attachments/assets/f9125422-c073-4ac2-8252-617419c4f1b7)
Surprised that no-one else is seeing this - since the last update i just get this text overlaid on the frigate card in firefx ad edge browsers, everything is fine in the HA app and in a chrome browser

**[OPTIONAL] Last working release (if known):**
probably the previous version
**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
