### ISSUE TITLE
Microphone breaks after switching to static image and back

### ISSUE THREAD

**Issue by swazrgb** [dermotduffy/frigate-hass-card#1810]
**Checklist:**

- [x] Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- [x] Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/131.0.0.0 Safari/537.36
date: 2025-01-07T02:03:15.208Z
lang: en
timezone: Europe/Amsterdam
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2024.12.5
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JGZ0XC6QYCWPXA2EWQ20Q2CK: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
      image:
        mode: camera
  menu:
    buttons:
      microphone:
        enabled: true
      frigate:
        enabled: true
      substreams:
        enabled: true
      live:
        enabled: true
        priority: 99
      image:
        enabled: true
        priority: 100
      cameras:
        priority: 100
        enabled: false
      mute:
        enabled: true
      fullscreen:
        priority: 10
      expand:
        enabled: false
      display_mode:
        priority: 0
    style: outside
  live:
    microphone:
      always_connected: true
    preload: false
    lazy_load: true
    controls:
      builtin: false
    show_image_during_load: true
  view:
    default: image
    default_cycle_camera: false
  status_bar:
    position: bottom
    style: hover
  image:
    mode: camera
    refresh_seconds: 1

```

**[REQUIRED] Description of problem:**

When loading the page and switching to the live view the microphone is transmitted correctly while the microphone button is pressed. Then when switching to static image, and then back to live view, the microphone is no longer transmitted while the microphone button is pressed.

To reproduce:

1. Load card as provided above
2. Observe card loads Static image view
3. Click Live view
4. Click Microphone button
5. Observe microphone is transmitted correctly
6. Click Static image
7. Click Live view
8. Click Microphone button
9. Observe microphone is no longer transmitted

**[OPTIONAL] Last working release (if known):**

Unknown, this is my first version.

**[OPTIONAL] Javascript errors shown in the web inspector:**

None

**[OPTIONAL] Additional information:**

Tested in both Chrome & Firefox on Linux
