### ISSUE TITLE
Cameras don't display until being moused over after switching lovelace tabs

### ISSUE THREAD

**Issue by swazrgb** [dermotduffy/frigate-hass-card#1811]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

Cameras tab card 1:

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/131.0.0.0 Safari/537.36
date: 2025-01-07T03:16:32.546Z
lang: en
timezone: Europe/Amsterdam
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2024.12.5
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JGZ0XC6QYCWPXA2EWQ20Q2CK: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
      image:
        mode: camera
  menu:
    buttons:
      microphone:
        enabled: true
      frigate:
        enabled: true
      substreams:
        enabled: true
      live:
        enabled: true
        priority: 99
      image:
        enabled: true
        priority: 100
      cameras:
        priority: 100
        enabled: false
      mute:
        enabled: true
      fullscreen:
        priority: 10
      expand:
        enabled: false
      display_mode:
        priority: 0
    style: outside
  live:
    microphone:
      always_connected: true
    preload: false
    lazy_load: true
    controls:
      builtin: false
    show_image_during_load: true
  view:
    default: image
    default_cycle_camera: false
  status_bar:
    position: bottom
    style: hover
  image:
    mode: camera
    refresh_seconds: 1

```

Cameras tab card 2:

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/131.0.0.0 Safari/537.36
date: 2025-01-07T03:16:59.850Z
lang: en
timezone: Europe/Amsterdam
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2024.12.5
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JGZ0XC6QYCWPXA2EWQ20Q2CK: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.your_reolink_camera
      live_provider: go2rtc
      image:
        mode: camera
  menu:
    buttons:
      microphone:
        enabled: false
      frigate:
        enabled: true
      substreams:
        enabled: true
      live:
        enabled: true
        priority: 99
      image:
        enabled: true
        priority: 100
      cameras:
        priority: 100
        enabled: false
      mute:
        enabled: true
      fullscreen:
        priority: 10
      expand:
        enabled: false
      display_mode:
        priority: 0
    style: outside
  live:
    preload: false
    lazy_load: true
    controls:
      builtin: false
    show_image_during_load: true
  view:
    default: image
    default_cycle_camera: false
  status_bar:
    position: bottom
    style: hover
  image:
    mode: camera
    refresh_seconds: 1

```

Doorbell tab card:

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/131.0.0.0 Safari/537.36
date: 2025-01-07T03:17:40.396Z
lang: en
timezone: Europe/Amsterdam
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2024.12.5
custom_integrations:
  frigate:
    detected: true
    version: 5.6.0
    devices:
      01JGZ0XC6QYCWPXA2EWQ20Q2CK: 5.6.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.doorbell
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
      image:
        mode: camera
  menu:
    buttons:
      microphone:
        enabled: true
      frigate:
        enabled: true
      substreams:
        enabled: true
      live:
        enabled: true
        priority: 99
      image:
        enabled: false
        priority: 100
      cameras:
        priority: 100
        enabled: false
      mute:
        enabled: true
      fullscreen:
        priority: 10
      expand:
        enabled: false
      display_mode:
        priority: 0
    style: outside
  live:
    microphone:
      always_connected: true
    preload: false
    lazy_load: true
    controls:
      builtin: false
    show_image_during_load: true
    auto_unmute:
      - visible
      - selected
      - microphone
    auto_mute: []
  view:
    default: live
    default_cycle_camera: false
  status_bar:
    position: bottom
    style: hover
  image:
    mode: camera
    refresh_seconds: 1

```

**[REQUIRED] Description of problem:**

I have a lovelace dashboard with cameras in two tabs. When loading the page everything displays correctly, but after switching to another tab and then back, the cameras no longer display until being moused over.

https://github.com/user-attachments/assets/93bc66e9-153e-4bcd-b9da-1aaee1152c5a

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

None

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
Possibly related to: https://github.com/dermotduffy/frigate-hass-card/issues/1769

Sadly, like in that issue, I cannot currently reproduce (even with the exact configs used here).

**Comment by swazrgb** [comment]
That's unfortunate, this is a fresh home assistant installation without much else going on yet. I've been able to replicate the issue on Chrome & Firefox on Windows, Linux, Android. Sometimes it only occurs after switching back and forth twice, but it can always reliably be triggered.

I've simplified my configuration and can still trigger the issue with this dashboard:

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.doorbell
  - type: sections
    max_columns: 4
    title: Tab 2
    path: tab-2
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.doorbell
```
