### ISSUE TITLE
Media Viewer Ignores Display Mode (grid or single) setting; Uses the setting for Live View instead

### ISSUE THREAD

**Issue by rrowe629** [dermotduffy/frigate-hass-card#1812]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/18.2 Safari/605.1.15
date: 2025-01-07T19:53:42.126Z
lang: en
timezone: America/Chicago
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2025.1.1
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JGPW3W30B6HKG4Y8HX6X1FJN: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  dimensions:
    aspect_ratio_mode: unconstrained
  cameras:
    - camera_entity: camera.driveway
    - camera_entity: camera.garage
    - camera_entity: camera.back
    - camera_entity: camera.house
  live:
    display:
      mode: grid
      grid_columns: 1
      grid_max_columns: 1
    preload: true
  media_gallery:
    display:
      mode: single
    controls:
      thumbnails:
        show_details: true
        show_download_control: false
        show_favorite_control: false
        show_timeline_control: false
        size: 200
  media_viewer:
    display:
      mode: single
      grid_columns: 1
      grid_max_columns: 1
    auto_play:
      - selected
    transition_effect: none
    controls:
      builtin: false
  performance:
    features:
      max_simultaneous_engine_requests: 1
  menu:
    style: outside
    buttons:
      snapshots:
        enabled: false
      download:
        enabled: false
      camera_ui:
        enabled: false
      fullscreen:
        enabled: false
      timeline:
        enabled: false
      media_player:
        enabled: false
      display_mode:
        enabled: false
      ptz_controls:
        enabled: true
      frigate:
        enabled: true
      substreams:
        enabled: false
      cameras:
        enabled: false
    button_size: 60
```

**[REQUIRED] Description of problem:**
With Live view display mode set to "grid", the Media Viewer shows a clip from each camera after selecting a single clip from the gallery. With Live view display mode set to "single" the Media Viewer shows only the clip selected from the gallery. It appears the Media Viewer ignores the configured display mode and uses the display mode of the Live view.

See above. Media Viewer should use configured display mode.

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
