### ISSUE TITLE
Dashboard scrolls to card upon load 

### ISSUE THREAD

**Issue by patienttruth** [dermotduffy/frigate-hass-card#1814]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.1.2
browser: >-
  Mozilla/5.0 (Linux; Android 10; K; wv) AppleWebKit/537.36 (KHTML, like Gecko)
  Version/4.0 Chrome/131.0.0.0 Mobile Safari/537.36 Home
  Assistant/2024.12.1-14604 (Android 15; Pixel 6)
date: 2025-01-08T04:19:41.323Z
lang: en
timezone: America/Los_Angeles
git:
  hash: bc95f55
  build_date: Tue, 24 Dec 2024 00:23:18 GMT
  commit_date: Mon, 23 Dec 2024 16:22:10 -0800
ha_version: 2025.1.0
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frigate_lorex_03_playset
  view:
    default: clips
    camera_select: live
  media_viewer: {}
  timeline:
    style: ribbon
  media_gallery:
    controls:
      thumbnails:
        size: 107
        show_details: true
      filter:
        mode: right
  dimensions: {}
  menu:
    buttons:
      media_player:
        enabled: false
      timeline:
        enabled: false
      fullscreen:
        enabled: false
      snapshots:
        enabled: false
      substreams:
        enabled: false

```

**[REQUIRED] Description of problem:**

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
