### ISSUE TITLE
PTZ controls default state

### ISSUE THREAD

**Issue by Cocoader** [dermotduffy/frigate-hass-card#1819]
It would be nice to have a default option for the PTZ controls.
- Always on
- Always off
- Last state

![Screenshot 2025-01-09 at 23 55 52](https://github.com/user-attachments/assets/9ac02259-0744-482d-baed-8ead6490c9df)

I do like the controls on the desktop browser but on mobile I only want them displayed occasionally.
As far as I understand it I currently have to enable it in the menu and always press the menu button to hide it on mobile.

![Screenshot 2025-01-10 at 00 09 05](https://github.com/user-attachments/assets/30138139-5658-46b7-ba38-df7f81e0f1f5)

Another more elaborate approach would be a fourth option. Make states specific to the user agent / screen width if you have access to this information. This might be also useful for other menu bar items for a custom layout on smaller / bigger screens.

**Comment by dermotduffy** [comment]
[Example of what I think you're trying to achieve](https://card.camera/#/examples?id=disable-ptz-controls-in-the-home-assistant-companion-app)

**Comment by Cocoader** [comment]
Thank you for the fast solution which I updated to(6.3.0).
I haven't used ``overrides`` before so this might be a problem on my end. Is something wrong with the indentation?

![Screenshot 2025-01-10 at 17 39 54](https://github.com/user-attachments/assets/1af120be-ce69-420d-982c-afb5e0792c89)


```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front
    live_provider: go2rtc
    go2rtc:
      stream: front_main
overrides:
  - conditions:
      - condition: user_agent
        companion: true
    set:
      live.controls.ptz.mode: 'off'
view_layout:
  position: main
menu:
  buttons:
    download:
      enabled: false
    expand:
      enabled: false
    ptz_controls:
      enabled: true
      permanent: true
    camera_ui:
      enabled: true
    ptz_home:
      enabled: false
      permanent: false
  style: outside
media_gallery:
  controls:
    thumbnails:
      show_download_control: false
      show_favorite_control: false
dimensions: {}
live:
  controls:
    builtin: true
    ptz:
      hide_pan_tilt: false
      hide_zoom: false
      hide_home: false
  show_image_during_load: true

```
I tried some overrides to see if they work in general, which seem to work:
```
overrides:
  - conditions:
      - condition: state
        entity: light.office_main_lights
        state: 'on'
    merge:
      menu:
        position: bottom
```
