### ISSUE TITLE
The condition for the element is not working.

### ISSUE THREAD

**Issue by przeniek** [dermotduffy/frigate-hass-card#1820]
The condition for the element is not working.

```
elements:
  - type: custom:frigate-card-menu-submenu-select
    entity: select.cam_3_ptz_preset
    conditions:
      - condition: state
        entity: binary_sensor.snapshots_running
        state: "on"
```

**Comment by dermotduffy** [comment]
That's not the right syntax for what I think you're trying to achieve, try this:

```yaml
elements:
  - type: conditional
    conditions:
      - condition: state
        entity: binary_sensor.snapshots_running
        state: "on"
    elements:
      - type: custom:frigate-card-menu-submenu-select
        entity: select.cam_3_ptz_preset
```

[Relevant example](https://card.camera/#/examples?id=conditional-menu-icons)
