### ISSUE TITLE
frigate-hass-card vs webrtc-camera-card - possible to maybe integrate the two via an option?

### ISSUE THREAD

**Issue by Sarah-Connelli** [dermotduffy/frigate-hass-card#1827]
Hi, latest version looking great!

I just recently wanted to add the HD button idea so that I can get a high-quality stream coming through when required, however I noticed that it only works internally via http://IP:8123, but externally would require opening up more ports via the router etc.

Indeed I do not need to do this with the WebRTC Camera card for external access as I'm guessing all the legwork of proxying etc is done behind the scenes in HA.

Is it at all possible to integrate the WebRTC Camera card view into the Frigate-hass-card for streams? because then all I need to do is click on the HD button and it then gives me the stream via the WebRTC camera card?

The Frigate-hass-card works fine with the HD button if I browse locally direct to HA http://IP:8123.

If it were possible to basically inside the config for the frigate-hass-card, to specify the live-provider as 'webrtc-card', and specify the rtsp url, then the frigate-hass-card effectively renders the webrtc-camera-card, that would be really helpful?

For now I've created another HA page with just the webrtc-camera-cards showing the high-definition streams, not ideal of course.

Notes:

Basically the webrtc-camera-card renders both the high-definition 30fps with audio frigate internal go2rtc rstp streams and the HA internal go2rtc rstp streams nicely externally via a HA URL of https://site.com - without needing to open/forward any ports.

However the frigate-hass-card can only stream those very same go2rtc streams if I browse the HA site via the local IP only. If I try to browse via the https://site.com url, I just get a spinner. Indeed if I specify the live-provider as 'ha' or 'auto', it works fine, but of course that is the frigate camera 'detect' stream which isn't the high quality 30fps with audio stream that I'm after.

**Comment by Sarah-Connelli** [comment]
ps. I could be wrong in all of this, and maybe I've hit a bug? or maybe if the frigate-hass-card just simply for 'live-provider: go2rtc' took an rstp url as config and did the same thing as the webrtc-camera-card then all would work externally as well as internally.

The fact the webrtc-camera-card works just fine externally with those high-quality go2rtc rtsp streams, means HA is doing its thing fine.

But I cannot get it to work externally with the frigate-hass-card and those very same go2rtc streams.

**Comment by Sarah-Connelli** [comment]
The card:

`type: custom:frigate-card
cameras:
  - camera_entity: camera.house_gate
    live_provider: auto
    dependencies:
      cameras:
        - house_gate_hd
  - camera_entity: camera.house_gate
    title: House Gate HD
    live_provider: go2rtc
    id: house_gate_hd
    go2rtc:
      stream: housegate
    capabilities:
      disable_except:
        - substream
menu:
  buttons:
    substreams:
      icon: mdi:high-definition
live:
  controls:
    thumbnails:
      mode: below
      show_details: false
  preload: false
  lazy_load: true
  auto_mute:
    - hidden
  auto_unmute:
    - selected
    - visible
    - microphone
  auto_play: []
view:
  default: live
  dim: false
media_viewer:
  controls:
    thumbnails:
      show_details: true
performance: {}
status_bar:
  style: none
webrtc_card:
  background: true`


This works great if I use non-secure http://x.x.x.x:8123 (local-ip) for the HA UI.

But if I use secure https://www.xxx.com for the HA UI, then it just shows that blue 'loading' circle in the top right of the card. The https certificate is valid, and the webrtc-camera-card works just fine with that same stream, though yes with that card I specify the stream as rtsp://localip:go2rtcport/stream.

The stream works from go2rtc with webrtc-camera-card, so I guess we can exclude that from being an issue.

Just wondering, I do not have a secure local-ip access method (https), is this possibly a reason why the frigate-hass-card has an issue remotely via https://domain-name.com access?

**Comment by Sarah-Connelli** [comment]
@dermotduffy - ok went in and changed the live provider to webrtc-card, WORKS!!!!

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.house_gate
    live_provider: auto
    dependencies:
      cameras:
        - house_gate_hd
  - camera_entity: camera.house_gate
    title: House Gate HD
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://localip:port/House-Gate
    id: house_gate_hd
    go2rtc:
      stream: housegate
    capabilities:
      disable_except:
        - substream
menu:
  buttons:
    substreams:
      icon: mdi:high-definition
live:
  controls:
    thumbnails:
      mode: below
      show_details: false
  preload: false
  lazy_load: true
  auto_mute:
    - hidden
  auto_unmute:
    - selected
    - visible
    - microphone
  auto_play: []
view:
  default: live
  dim: false
media_viewer:
  controls:
    thumbnails:
      show_details: true
performance: {}
status_bar:
  style: none
```

But now a new issue popped its head, once I click on HD button, the stream switches to the HD version with audio, beautiful, but then when I want to go back to the old stream and click on the HD button again, it just hangs with the webrtc media player controls in view and the hd video stopped, none of the media play controls are accessible (all greyed out).

Any ideas?
