### ISSUE TITLE
PTZ controls should work with a `substream`

### ISSUE THREAD

**Issue by Sarah-Connelli** [dermotduffy/frigate-hass-card#1829]
I have the default PTZ controls availabe on the card via Frigate integration, and all works fine.

But when I switch to the HD stream via the HD button, the PTZ controls no longer function, guessing because there is no binding in the substream camera.

Maybe a nice feature would be to have a flag in the PTZ config section, something like "source: " and then the variable could be:

the default being "auto" (just does what it currently does)
optional being "camera.whatever" (so that way we can fix it to just one camera permenantly)?

Card config currently:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.hill
    live_provider: ha
    dependencies:
      cameras:
        - hill_hd
  - camera_entity: camera.hill
    title: Hill HD
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://localip:port/Hill
    id: hill_hd
    capabilities:
      disable_except:
        - substream
menu:
  buttons:
    substreams:
      icon: mdi:high-definition
live:
  controls:
    ptz:
      mode: "on"
      orientation: vertical
      position: top-right
    thumbnails:
      mode: below
      show_details: false
  preload: false
  lazy_load: true
  auto_mute:
    - hidden
  auto_unmute:
    - selected
    - visible
    - microphone
  auto_play: []
view:
  default: live
  dim: false
media_viewer:
  controls:
    thumbnails:
      show_details: true
performance: {}
status_bar:
  style: none
elements:
  - type: custom:frigate-card-menu-state-icon
    entity: switch.iot_chimney_hill_light_2
    tap_action:
      action: toggle
```

**Comment by dermotduffy** [comment]
I agree this should work, but doesn't appear to. Simplest might just be to, when it's a substream, offer the PTZ controls bound to the substream -- and if they don't exist, offer the controls of the base stream. I actually thought I already done this, let me look into it!

**Comment by dermotduffy** [comment]
Actually, I think the issue in your config (and my test) is we both disabled PTZ in the substream.

This:

```yaml
  - camera_entity: camera.hill
    capabilities:
      disable_except:
        - substream
```

Should be:

```yaml
  - camera_entity: camera.hill
    capabilities:
      disable_except:
        - substream
        - ptz
```

Does that do what you want?
