### ISSUE TITLE
Frigate card & Nabu Casa WebRTC & external connection

### ISSUE THREAD

**Issue by humplemann** [dermotduffy/frigate-hass-card#1832]
Hi,

the issue I am facing is:
When using HA from my smartphone with external Nabu Casa link (no wifi) my Frigate cards run into buffering (loading circle icon) shortly after starting, then my HA app loses connection until I do an app restart. I can work around that by navigating quickly into another tab or menu item to keep my connection alive. However, I'd like to use my dashboard when I am away from home.
Everything is fine when I am connected with my local wifi, both on HA app and desktop.

Unfortunately, I cannot open WebRTC/Stun ports to the outside, so I'll have to stick to Nabu Casa WebRTC, which seems to limit the bandwidth (?). I am looking for a solution for me to be able to use my dashboard, preferably:

with HD video playing, or if not possible
with SD video playing, or if not possible
with no video playing when connected through mobile network

I am unsure whether I am doing something really wrong. Any hints?

The setup is:

- HA (v2025.1.2) on local VM, active Nabu Casa subscription
- Frigate in a local docker container, with WebRTC enabled (as per https://docs.frigate.video/configuration/live/)
- HA dashboard contains 6 Frigate cards (v6.3.3), each showing their own camera entity (go2rtc provider, live view)
- The cameras are provided by the Frigate integration (v5.7.0) (no Frigate add-on running)
- WebRTC option in Nabu Casa settings active

Example frigate card config/card diagnostic:

```
card_version: 6.3.3
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2025-01-16T10:28:08.208Z
lang: en
timezone: Europe/Berlin
git:
  hash: 6b3736b
  build_date: Mon, 13 Jan 2025 00:27:45 GMT
  commit_date: Sun, 12 Jan 2025 16:26:30 -0800
ha_version: 2025.1.2
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JEE8PTVXFZNCD0GB41XEBGT4: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.kamera_01_wohnzimmer
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
      title: Wohnzimmer
      icon: hue:room-living
  live: {}
  menu: {}
  view:
    default: live
    triggers: {}
  performance:
    style:
      border_radius: true
      box_shadow: true
  media_gallery:
    controls:
      filter: {}
  cameras_global:
    dimensions:
      layout: {}
```

Frigate config:

```
mqtt:
  enabled: false

snapshots:
  enabled: True
  timestamp: True
  retain:
      default: 60
  quality: 85

record:
  enabled: true
  retain:
    days: 6
    mode: motion
  events:
    retain:
      default: 10
      mode: active_objects

review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person
      - speech

ffmpeg:
  hwaccel_args: preset-vaapi

database:
  path: /config/frigate.db

detect:
  enabled: True
  fps: 5

go2rtc:
  streams:
    Kamera-01-Wohnzimmer:
      - rtsp://user:pw@ip:554/h264Preview_01_main
      - ffmpeg:Kamera-01-Wohnzimmer#audio=opus
    Kamera-01-Wohnzimmer-sub:
      - rtsp://user:pw@ip:554/Preview_01_sub
      - "ffmpeg:Kamera-01-Wohnzimmer-sub#audio=opus"
    Kamera-04-Flur:
      - rtsp://user:pw@ip:554/h264Preview_01_main
      - "ffmpeg:Kamera-04-Flur#audio=opus"
    Kamera-04-Flur-sub:
      - rtsp://user:pw@ip:554/Preview_01_sub
      - "ffmpeg:Kamera-04-Flur-sub#audio=opus"
    Kamera-03:
      - rtsp://user:pw@ip:554/h264Preview_01_main
      - "ffmpeg:Kamera-03#audio=opus"
    Kamera-03-sub:
      - rtsp://user:pw@ip:554/Preview_01_sub
      - "ffmpeg:Kamera-03-sub#audio=opus"
    Kamera-02:
      - rtsp://user:pw@ip:554/h264Preview_01_main
      - "ffmpeg:Kamera-02#audio=opus"
    Kamera-02-sub:
      - rtsp://user:pw@ip:554/Preview_01_sub
      - "ffmpeg:Kamera-02-sub#audio=opus"
    Kamera-05-Flur-unten:
      - rtsp://user:pw@ip:554/h264Preview_01_main
      - "ffmpeg:Kamera-05-Flur-unten#audio=opus"
    Kamera-05-Flur-unten-sub:
      - rtsp://user:pw@ip:554/Preview_01_sub
      - "ffmpeg:Kamera-05-Flur-unten-sub#audio=opus"
  webrtc:
    candidates:
      - stun:8555  # if you have dynamic public IP-address

cameras:
  Kamera-01-Wohnzimmer:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera-01-Wohnzimmer
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera-01-Wohnzimmer-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Kamera-01-Wohnzimmer-sub

  Kamera-04-Flur:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera-04-Flur
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera-04-Flur-sub
          input_args: preset-rtsp-restream
          roles:
            - detect

  Kamera-03:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera-03
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera-03-sub
          input_args: preset-rtsp-restream
          roles:
            - detect

  Kamera-02:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera-02
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera-02-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  
  Kamera-05-Flur-unten:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Kamera-05-Flur-unten
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Kamera-05-Flur-unten-sub
          input_args: preset-rtsp-restream
          roles:
            - detect

detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14```


Any ideas what my best approach would be? Thanks!
