### ISSUE TITLE
iOS HA app crashed by frigate card

### ISSUE THREAD

**Issue by jazzjackrabbit-exe** [dermotduffy/frigate-hass-card#1833]
![Image](https://github.com/user-attachments/assets/ebcefc1f-d1e6-4ca1-a9b5-388b1e91b945)

**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.3.4
browser: >-
  Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15
  (KHTML, like Gecko) Home Assistant/2024.12.2 (io.robbie.HomeAssistant;
  build:2024.1058; iOS 18.1.1) Mobile/HomeAssistant, like Safari
date: 2025-01-18T07:51:49.157Z
lang: en
timezone: Europe/Warsaw
git:
  hash: 57a687d
  build_date: Fri, 17 Jan 2025 04:01:41 GMT
  commit_date: Thu, 16 Jan 2025 20:00:31 -0800
ha_version: 2025.1.2
custom_integrations:
  frigate:
    detected: false
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.ca31
      live_provider: auto
      cast:
        method: dashboard
  live:
    controls:
      builtin: false
    lazy_load: false
  view:
    default: live
  performance:
    features:
      media_chunk_size: 249
```
**[REQUIRED] Description of problem:**

For some time now, I've been struggling with an issue where the Frigate card crashes my HA app on iOS. The problem only occurs on mobile internet – when I'm on Wi-Fi in the network where Home Assistant is running, everything works fine. The sequence of events is as follows: I launch the HA app, go to the tab with the Frigate cards. The image loads, I see the camera preview, and after a few seconds, I get a reconnecting message and a notification about losing connection to Home Assistant. At that point, I have to close the entire app, and after a few seconds, I can open it again. Does anyone know how to solve this problem?

**[OPTIONAL] Last working release (if known):*just installed*

```text

```

**[OPTIONAL] Additional information:**
