### ISSUE TITLE
Missing functionality of input_number and input_button

### ISSUE THREAD

**Issue by PovilasID** [dermotduffy/frigate-hass-card#1841]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
Card diagnostics. Please review for confidential information prior to sharing
card_version: 6.3.6
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36
date: 2025-01-20T00:19:20.179Z
lang: en
timezone: Europe/Vilnius
git:
  hash: 99fe613
  build_date: Sun, 19 Jan 2025 03:07:16 GMT
  commit_date: Sat, 18 Jan 2025 19:06:09 -0800
ha_version: 2024.12.4
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      71a171bf4c0c4b639d319d92b530b5d3: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.durys0
      live_provider: go2rtc
      go2rtc:
        modes:
          - webrtc
      dependencies:
        cameras:
          - durys0_sd
    - camera_entity: camera.durys0
      title: Durys SD
      live_provider: go2rtc
      id: durys0_sd
      go2rtc:
        stream: durys0_sub
      capabilities:
        disable_except:
          - substream
    - camera_entity: camera.kamera1
    - camera_entity: camera.siltnamis
    - camera_entity: camera.durys
      live_provider: webrtc-card
      go2rtc:
        modes: []
  view:
    default_cycle_camera: true
  menu:
    style: overlay
    buttons:
      substreams:
        icon: mdi:standard-definition
      expand:
        enabled: true
      recordings:
        enabled: true
      snapshots:
        enabled: false
      microphone:
        enabled: true
        type: toggle
        icon: mdi:microphone
      play:
        enabled: false
  elements:
    - type: custom:frigate-card-conditional
      conditions:
        - condition: camera
          cameras:
            - camera.durys0
      elements:
        - type: custom:frigate-card-menu-state-icon
          title: Lights
          icon: mdi:lightbulb
          entity: input_boolean.door_cam_light_switch
          tap_action:
            action: toggle
        - type: custom:frigate-card-menu-icon
          title: Alarm
          icon: mdi:bullhorn
          entity: input_button.door_camera_alarm
        - type: custom:frigate-card-menu-icon
          title: Brightness
          icon: mdi:brightness-percent
          entity: input_number.door_camera_light_brightness
  dimensions:
    height: 92vh
```

**[REQUIRED] Description of problem:**
Menu items using `input_number` and `input_button` are disabled. Are they not available in this new version? How to recreate functionality of editing a digital value or having a confirmation dialog before turning on the sirens?
Could not find any mentions of anything other than `input_select` in the repo and documentation. 

**[OPTIONAL] Last working release (if known):**
5.x 

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text
---
```

**[OPTIONAL] Additional information:**
If I try redownload an older version oldest I can go are 6.0 beta 8 . Is it limitation of HACS or is there some kind of incompatibility? How to force it back to 5.x?

**Comment by dermotduffy** [comment]
Are you saying this worked previously?

**Comment by PovilasID** [comment]
@dermotduffy Yah it did a dialog window would pop up for number it was a slider with history and for button it was a button with history.
How it shows up if you add those entities in any dashboard and click on them. I think it just passed the click event to open the entities default view.
This what I see now.
![Image](https://github.com/user-attachments/assets/49433abb-afff-4cb3-ab98-f070c7680f14)
(Log book may be from an addon I have)

Anyway is it safe to downgrade to 5.2?

**Comment by dermotduffy** [comment]
I'm unable to reproduce this with a test config, feel free to re-open if this is still an issue:

```yaml
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.office
elements:
  - type: custom:advanced-camera-card-menu-state-icon
    entity: input_number.numbertest
```
