### ISSUE TITLE
Cannot view gallery of recordings in Frigate Card

### ISSUE THREAD

**Issue by rosinscj** [dermotduffy/frigate-hass-card#1845]
**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.3.6
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
date: 2025-01-21T02:06:53.403Z
lang: en
timezone: America/Chicago
git:
  hash: 99fe613
  build_date: Sun, 19 Jan 2025 03:07:16 GMT
  commit_date: Sat, 18 Jan 2025 19:06:09 -0800
ha_version: 2025.1.2
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JJ37D1RWN8JMX2CGNK57C14H: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.front_door_doorbell
      frigate:
        zones:
          - front_yard
  view:
    default: recordings
    camera_select: recordings
```

**[REQUIRED] Description of problem:**
Cannot view recordings in the card. The card is always blank. No logs present in HA, Frigate, or browser console. The camera live view works as expected in another Frigate card. The media is viewable/playable in the HA Media section.

Screenshot of blank card: https://imgur.com/a/oyQW1bM

**[OPTIONAL] Last working release (if known):**
Unknown, this is my first attempt at setting this up.

**[OPTIONAL] Javascript errors shown in the web inspector:**
None

**[OPTIONAL] Additional information:**
Also discussed here: https://community.home-assistant.io/t/frigate-custom-card-not-showing-gallery-of-events-or-recording/653508/5
