### ISSUE TITLE
double_tap_action has no effect on iOS

### ISSUE THREAD

**Issue by webjib** [dermotduffy/frigate-hass-card#1853]
**Card diagnostic information:**

```
card_version: 6.3.8
browser: >-
  Mozilla/5.0 (iPhone; CPU iPhone OS 18_3 like Mac OS X) AppleWebKit/605.1.15
  (KHTML, like Gecko) Home Assistant/2025.1 (io.robbie.HomeAssistant;
  build:2025.1073; iOS 18.3.0) Mobile/HomeAssistant, like Safari
date: 2025-01-22T16:27:31.598Z
lang: en
timezone: Europe/Paris
git:
  hash: 805a211
  build_date: Wed, 22 Jan 2025 03:43:55 GMT
  commit_date: Tue, 21 Jan 2025 19:42:47 -0800
ha_version: 2025.1.3
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      ***: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.***
```

**Description of problem:**

Configuring a double_tap_action either for the view or just the live, has no effect on iOS. It works on Safari for Mac.
Tap and Hold actions are working fine on iOS.

```
live:
  actions:
    double_tap_action:
      action: custom:frigate-card-action
      frigate_card_action: ptz_digital
      ptz_action: zoom_in
      absolute:
        zoom: 1.5
```

**Comment by dermotduffy** [comment]
I don't have an iPhone to test, but playing around on Browserstack and I see this same behavior. The video element is swallowing the interaction. The same sadly happens on Android:

 - https://card.camera/#/troubleshooting?id=double_tap-does-not-work-in-android

Given that touch/mouse interaction with the video element is desirable, I am not sure there is anything that can/should be done here other than updating that troubleshooting description to include iOS in this limitation.

**Comment by dermotduffy** [comment]
> Thanks for your answer! I don't have any clue how Home Assistant is doing that, but they support the double tap action on the Picture Glance card. This card is using an HTML video element, but maybe there's some hidden overlay over the video that capture the event? If you configure a double tap, it takes precedence over the tap action.

This is likely because (i) by default Picture Glance shows an image not a video, (ii) when you configure it to show a video, it won't show media controls.

If you're prepared to sacrifice media controls, maybe this will work for you:

```yaml
live:
  controls:
    builtin: false                <------------------------ Turns off builtin media controls
  actions:
    double_tap_action:
      action: custom:frigate-card-action
      frigate_card_action: ptz_digital
      ptz_action: zoom_in
      absolute:
        zoom: 1.5
```
