### ISSUE TITLE
Inconsistent load times when playing a clip from the media gallery

### ISSUE THREAD

**Issue by rrowe629** [dermotduffy/frigate-hass-card#1854]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```
card_version: 6.3.6
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/18.2 Safari/605.1.15
date: 2025-01-22T16:23:09.811Z
lang: en
timezone: America/Chicago
git:
  hash: 99fe613
  build_date: Sun, 19 Jan 2025 03:07:16 GMT
  commit_date: Sat, 18 Jan 2025 19:06:09 -0800
ha_version: 2025.1.2
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JGPW3W30B6HKG4Y8HX6X1FJN: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.driveway

```

**[REQUIRED] Description of problem:**

It's likely I'm just missing something here, but everything is working great with the card, except when I select a clip to play from the Media Gallery. Live views load quickly and the gallery loads reasonably fast. However, when I select a clip to play from the gallery, it can often take 5 - 10 seconds or longer to load before playing. If I select the same clip through the api, i.e. http://<frigate ip>:5000/api/events/<event id>/clip.mp4, it plays almost instantaneously. This is true even if I clear caches immediately beforehand.

I've seen the same behavior with the mobile companion app connected to my local network and with Safari on my Mac.

A timeline trace on the Mac shows that the bulk of the delay occurs in "seg-1-v1.ts" and "seg-2-v1.ts". The best I've seen is somewhere on the order of 4 seconds total for the two, which is livable, but this does not occur reliably and still doesn't square with the performance I'm seeing when accessing the API directly.

I've experimented with max_simultaneous_engine_requests in the media_viewer YAML, but that does not seem to have an effect.

Is this expected behavior?

**[OPTIONAL] Last working release (if known):**

New user, but has been this way since I started approximately one month ago.

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**
Both Home Assistant and Frigate run on a Synology 720+. Home Assistant is supervised and running on a Virtual Machine. Frigate runs in a Synology Docker container with its own IP address. Card is V6.3.8, Frigate is 0.14.1-f4f3cfa.
