### ISSUE TITLE
Trigger issue (or documentation unclear)

### ISSUE THREAD

**Issue by nappa85** [dermotduffy/frigate-hass-card#1856]
I'm trying to configure the card to switch live camera on trigger. I don't have a frigate server, I'm using vanilla HA. From the documentation is stated that only frigate cameras have built-in motion trigger. But I can use binary sensors, documentation states it works for frigate and non-frigate cameras.

Config example
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.a
    triggers:
      entities:
        - binary_sensor.a_motion
        - input_boolean.motion_a
  - camera_entity: camera.b
    triggers:
      entities:
        - binary_sensor.b_motion
        - input_boolean.motion_b
  - camera_entity: camera.c
    triggers:
      entities:
        - binary_sensor.c_motion
        - input_boolean.motion_c
view:
  default: live
  triggers:
    filter_selected_camera: false
    actions:
      trigger: live
      untrigger: none
      interaction_mode: all
automations:
  - conditions:
      - condition: triggered
        triggered:
          - camera.a
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: camera_select
        camera: camera.a
      - action: custom:frigate-card-action
        frigate_card_action: log
        message: a
        level: error
  - conditions:
      - condition: triggered
        triggered:
          - camera.b
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: camera_select
        camera: camera.b
      - action: custom:frigate-card-action
        frigate_card_action: log
        message: b
        level: error
  - conditions:
      - condition: triggered
        triggered:
          - camera.c
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: camera_select
        camera: camera.c
      - action: custom:frigate-card-action
        frigate_card_action: log
        message: c
        level: error
```

With this config I would expect, when I trigger a camera, to have at least an error log in browser's console, but nothing happens.
Automations have been added after default view trigger configuration did not work.

The two kind of sensors are:
* binary_sensor.<camera>_motion is the built-in motion sensor, it works but it goes off quite quickly
* input_boolean.motion_<camera> is a boolean sensor I manage with a timer to keep it on for at least 1 minute

Those sensors are working correctly in another dashboard where all cameras built-in HA live view are present, but I control each one visibility via those boolean sensors.

Am I doing something wrong or does triggers not work without a frigate server?
