### ISSUE TITLE
PTZ Controls Interfere with Fullscreen Icon Selection on Video Card

### ISSUE THREAD

**Issue by lasharor** [dermotduffy/frigate-hass-card#1860]
I am sorry for not following the template. I cannot get the first step with the diagnostic information to show. 

![Image](https://github.com/user-attachments/assets/5b569dd6-7412-4bf8-8083-6573582cc2e6)

When using PTZ cameras in version 6.4.0, selecting the fullscreen icon is difficult because the mouse interacts with the PTZ controls instead of properly targeting the fullscreen icon.

**Comment by lasharor** [comment]
Made the diagnostic info work.

```
card_version: 6.4.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/132.0.0.0 Safari/537.36
date: 2025-01-28T11:30:58.917Z
lang: nl
timezone: Europe/Amsterdam
git:
  hash: 3e8e688
  build_date: Mon, 27 Jan 2025 15:24:21 GMT
  commit_date: Mon, 27 Jan 2025 07:23:07 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01J6H0T3VSECM2ZPJEMP7D47WZ: 5.7.0/0.14.1-
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.kinderkamer
      frigate:
        url: 192.168.1.114:5000
      go2rtc:
        modes:
          - webrtc
      live_provider: go2rtc
      capabilities:
        ptz: continuous
  image:
    zoomable: false
  live:
    preload: false
    draggable: true
    zoomable: false
    controls:
      ptz:
        mode: 'on'
        hide_zoom: true
        hide_home: true
      hide_home: false
    lazy_load: true
  menu:
    style: overlay
    buttons:
      frigate:
        enabled: true
      cameras:
        enabled: false
      substreams:
        enabled: false
      live:
        enabled: true
        alignment: opposing
        priority: 49
      clips:
        enabled: false
      snapshots:
        enabled: false
      download:
        enabled: false
      fullscreen:
        enabled: false
      media_player:
        enabled: false
      microphone:
        enabled: true
      camera_ui:
        enabled: false
  performance:
    style:
      border_radius: false
  view:
    triggers: {}
  cameras_global:
    dimensions:
      layout: {}
```

**Comment by dermotduffy** [comment]
I think you're suggesting just moving the PTZ controller a little bit further up so it overlaps less with the controls?

PS: As a workaround you could also just enable the fullscreen button on the menu. It's going to put the card into fullscreen, which is better than putting just the singular video into fullscreen anyway.

**Comment by XVs32** [comment]
Ran into the same issue here, 
my situation is always misclicking the Fullscreen button instead of PTZ control tho.

Later I found a solution from the Advanced Camera Card document.
https://card.camera/#/configuration/live?id=controls

You could disable the builtin control bar with the following yaml

```
    type: custom:advanced-camera-card
    live:
      controls:
        builtin: false
```
