### ISSUE TITLE
Cropped media viewer on mobile

### ISSUE THREAD

**Issue by Mincka** [dermotduffy/frigate-hass-card#1864]
```yaml
card_version: 6.4.0
browser: >-
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0
date: 2025-01-29T20:37:15.233Z
lang: en
timezone: Europe/Paris
git:
  hash: 3e8e688
  build_date: Mon, 27 Jan 2025 15:24:21 GMT
  commit_date: Mon, 27 Jan 2025 07:23:07 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      0ae4ae0143cc572b898ec2bbe17b2b8c: 5.7.0/0.15.0-83ac42c
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frigate_maison_avant
      frigate:
        zones:
          - rue
        labels:
          - person
      dependencies:
        all_cameras: true
    - camera_entity: camera.frigate_sonnette
      frigate:
        labels:
          - person
  view:
    default: snapshots
  dimensions:
    aspect_ratio_mode: unconstrained
  media_viewer:
    controls:
      thumbnails:
        show_details: true
        show_favorite_control: true
        show_timeline_control: true
  menu:
    buttons:
      cameras:
        enabled: false
      frigate:
        enabled: true
      live:
        enabled: false
      timeline:
        enabled: false
      fullscreen:
        enabled: false
      clips:
        enabled: false
      media_player:
        enabled: false
  media_gallery:
    controls:
      thumbnails:
        show_favorite_control: false
        show_details: true
        show_timeline_control: false
        show_download_control: false
        size: 300
      filter:
        mode: none
  performance:
    features:
      card_loading_indicator: false
```

**[REQUIRED] Description of problem:**
I use the card to have a infinite scroll of events on one column.

To do that, I use this:
```yaml
dimensions:
  aspect_ratio_mode: unconstrained
```

On mobile, it works fine for the thumbnails, however, when I click on one of them, on the media viewer (playing or not), the image is cropped on both sides so I cannot see the Frigate button on the left and the menu on the right.

I tried without specifying `aspect_ratio_mode`, but it did not change anything for the media viewer.

<img src="https://github.com/user-attachments/assets/165699fa-cef4-4d9d-8a38-dd48b966a74f" width="400">

<img src="https://github.com/user-attachments/assets/8a45e846-3a79-408f-ac80-54ba9594eb60" width="400">

Phone : Pixel 7 Pro
Screen resolution : 1440 x 3120 pixels
Display size setting : 2 (1 to 5)

While I was looking for useful info for debug on Android, I saw that I was not using the minimum for "Display size" (I guess "1" is the native resolution, without scaling). It actually helps a little bit when it's set to 1/5, see below. But of course, I would prefer to keep my current setting.

<img src="https://github.com/user-attachments/assets/25b902b0-51fa-4128-aeb9-53407b72cd25" width="400">

**Other infos:**

Mix of cameras, they all have 16/9 resolution except one below. But this issue is present for the different types of cameras.
Camera: Reolink Doorbell POE
Resolution: 2560X1920 
Ratio: 4/3

Setup of the HA view:

```yaml
type: sections
max_columns: 1
title: Personnes dans la rue
path: personnes-dans-la-rue
icon: mdi:motion-sensor
subview: true
sections:
  - type: custom:frigate-card
  [...]
```

**Comment by dermotduffy** [comment]
I'm not sure I follow: So you have the "unconstrained" gallery (as shown above on the left), and when you click on one of the media items the media viewer is somehow "chopped off" (as some above on the right)? And it's not just the media is chopped, but the whole card appears to be (i.e. menu button not visible either).

Is this right?

**Comment by Mincka** [comment]
That's correct, I cannot see left and right parts of the card. There's an horizontal scroll bar, but even I can move a little bit, I cannot reach the left of the card to see the menu icon for instance.

**Comment by dermotduffy** [comment]
@Mincka OK, thanks, that's incredibly strange. Is it possible you are using some other browser extension, or frontend plugin (e.g. `card_mod`) that is somehow causing interference? Do you get the same behavior on multiple browsers?

**Comment by Mincka** [comment]
It's like that in the Companion App on Android, on Edge on Android, tested also on another phone, smaller, same issue.
I have a lot a custom things (including browser_mod, card_mod...) but the card is isolated in a dedicated column of a section.

It seems to be related to the combination of these two cameras with different aspect ratios in the media items. 

I manage to get the bug with only this config:
```
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.frigate_maison_avant
        frigate:
          zones:
            - rue
        dependencies:
          all_cameras: true
      - camera_entity: camera.frigate_sonnette
```

When all the media items are from the same camera (no mix of aspect ratios), there is no issue in the media viewer.
