### ISSUE TITLE
PTZ does not work with Tapo C510W via card.

### ISSUE THREAD

**Issue by gobris** [dermotduffy/frigate-hass-card#1865]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
card_version: 6.4.0
browser: >-
  Mozilla/5.0 (Linux; Android 12; M2007J3SY Build/SKQ1.211006.001; wv)
  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/132.0.6834.122
  Mobile Safari/537.36 Home Assistant/2025.1.6-15120 (Android 12; M2007J3SY)
date: 2025-01-31T14:01:33.976Z
lang: en
timezone: Europe/Istanbul
git:
  hash: 3e8e688
  build_date: Mon, 27 Jan 2025 15:24:21 GMT
  commit_date: Mon, 27 Jan 2025 07:23:07 -0800
ha_version: 2025.1.4
custom_integrations:
  frigate:
    detected: true
    version: 5.7.0
    devices:
      01JJKG9RZM3PVMJYKVTRCQQ3TW: 5.7.0/0.14.1-f4f3cfa
  hass_web_proxy:
    detected: false
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.frigate_my_camera
    - camera_entity: camera.tapo_mainstream
      live_provider: auto
```

**[REQUIRED] Description of problem:**

Hello, I am using two cameras with frigate integration. One is a haikon camera with rtsp feed (not PTZ) , second camera is a Tapo C510W integrated to Frigate with onvif configuration.

When I try to pan/tilt camera from frigate screen or from developers menu /onvif state, camera moves normally. But when I enable PTZ controls on card, it shows no effect.. I tried to change the order of the cameras...or even keep only single tapo camera on card but no solution.
Everything else except ptz, works from the card.
**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

PTZ controls visible on both streams.. It would be better to select which stream has this controls.
