### ISSUE TITLE
Let's define image icon

### ISSUE THREAD

**Issue by thundergreen** [dermotduffy/frigate-hass-card#199]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I setup th card and would like to use th status image as a privacy function. Bit the icon for the static icon is a picture and I would like to change this icon .any idea or do I have to add an icon myself with a button that calls the function to show the static image ?
**Describe alternatives you've considered**

**Additional context**

**Comment by dermotduffy** [comment]
There's no way to do that with the built-in default menu items. Your best bet (as you guessed) would be to do something like this:

```yaml
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:butterfly
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: image
```

There are two downsides to this:
 - With the in-built menu icons, they are styled/emphasized  when that view is active (e.g. click on 'Clips' and notice how the color of the icon will change to show it is selected). That would not happen with the above idea.
 - Support for `custom:frigate-card-action` is not in any released build, so you'd need to wait for the next one.
