### ISSUE TITLE
Document each of the default menu buttons

### ISSUE THREAD

**Issue by ksignorini** [dermotduffy/frigate-hass-card#223]
Would it be possible to add a link to the card (a button like some of the other buttons on it) that lets you jump straight to the camera in Frigate? Maybe an item in the ... menu?

**Comment by dermotduffy** [comment]
Easiest way is to ensure `frigate.url` is set and the `frigate_ui` menu button is enabled:

```yaml
type: custom:frigate-card
[rest of config]
frigate:
  url: http://path.to.your.frigate
menu:
  buttons:
    frigate_ui: true
```

This will make a  'globe' button that takes you to the camera 'homepage'.

<img width="403" alt="Screen Shot 2021-11-27 at 9 52 53 PM" src="https://user-images.githubusercontent.com/1136829/143731353-3a94ac65-a30a-4e48-af04-e9c6e03bb292.png">
