### ISSUE TITLE
Unknown Error when clicking on clips

### ISSUE THREAD

**Issue by k2xl** [dermotduffy/frigate-hass-card#248]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
```
    type: custom:frigate-card
    camera_entity: camera.driveway
    live:
      provider: frigate
    event_viewer:
      controls:
        next_previous:
          style: thumbnails
        thumbnails:
          mode: below
      lazy_load: true
      draggable: true
```
![image](https://user-images.githubusercontent.com/965260/146810607-743b0133-adfd-43e5-9689-d870e0429dac.png)

Live view seems to work fine. But I don't see any thumbnails of clips for the camera nor do I see any images to select below. Tried various setting can't seem to get it to show up.
**Javascript errors shown in the web inspector (if applicable):**

```
I don't see any error on the console suprisingly.
```

**Additional information:**
