### ISSUE TITLE
Live stream delay with Amcrest AD410

### ISSUE THREAD

**Issue by CZonin** [dermotduffy/frigate-hass-card#250]
I have 3 Amcrest cameras that work perfectly with this card, but my AD410 always takes a long time to load in the live stream or sometimes doesn't load at all. I don't think it's a hardware or network limitation on my end, and the stream when viewing the camera directly through Frigate doesn't seem to have a delay.

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Only started using the card within the past 2 releases and experienced the problem on both.

**Last working release (if known):**
n/a

**Browser and Operating System:**
Chrome on my Windows 11 PC and the HA app on an Android device.

**Comment by dermotduffy** [comment]
Can you paste your card config so I can see what live provider you're using?

**Comment by CZonin** [comment]
`type: custom:frigate-card
camera_entity: camera.front_doorbell
view:
  default: live
  update_force: false
live:
  provider: frigate
  preload: true
menu:
  mode: above
  buttons:
    live: true
    frigate: false
event_viewer:
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: below
`

**Comment by CZonin** [comment]
> Can you paste your card config so I can see what live provider you're using?

```
type: custom:frigate-card
camera_entity: camera.front_doorbell
view:
  default: live
  update_force: false
live:
  provider: frigate
  preload: true
menu:
  mode: above
  buttons:
    live: true
    frigate: false
event_viewer:
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: below
```
