### ISSUE TITLE
Static image is not refetched correctly

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#255]
I currently using this card to show static camera `image` by default. Image does not refresh unless you reload browser page. I used before Generic Camera built-in integration. It updates `static_image_url` every 10 seconds. Maybe it's possible to add same functionality for this card? Configuration could be something like this:

```
image:
  src: http://192.168.1.104:5000/api/camera/latest.jpg #latest snapshot URL from frigate
  refresh: true
  timeout: 10
```

**Comment by dermotduffy** [comment]
You should be able to already do this, see here: https://github.com/dermotduffy/frigate-hass-card#card-refreshes--updates

Something like this (untested) may work for you:

```
view:
  default: image
  timeout: 10
  force: true
```

**Comment by peledzius** [comment]
Forgot to mention, I already tried this type of configuration without success. When watching live video, it just goes back to image view after 10 seconds without updating the image.

**Comment by dermotduffy** [comment]
Oh, so it does go back to the image view, but the image is just not updating? OK -- can you provide the configuration you used? I'll look into it.

**Comment by peledzius** [comment]
Yes, goes back but does not update. Here's my configuration:

```
type: custom:frigate-card
camera_entity: camera.living_room
view:
  default: image
  timeout: '10'
  force: true
live:
  provider: webrtc
  webrtc:
    entity: camera.living_room_rtsp
image:
  src: http://192.168.1.104:5000/api/living_room/latest.jpg
```
