### ISSUE TITLE
Out of bounds memory access

### ISSUE THREAD

**Issue by balonchiks** [dermotduffy/frigate-hass-card#257]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:** 2.1.0

**Browser and Operating System:** Safari on a Macbook pro 14, with latest Macos Monterey (also same behaviour on Edge on Windows 11 and in Safari on iPhone)

**Description of problem:**

Hi, i currently have 8 cameras added to lovelace, all coming from Frigate integration (latest version as well) and while it perfectly works in Firefox, in Safari on macbook all i am seeing is 8 white rectangles. Sometimes they do appear and work fine however, but mostly not. it's like 2 out of 10 times they show up correctly, and other 8 - not. The browser console is filled with the errors below, which i haven't been able to google myself as nothing but Unity related stuff pops up

**Javascript errors shown in the web inspector (if applicable):**

```
[Error] RuntimeError: Out of bounds memory access (evaluating 'this.functions._mpeg1_decoder_create(this.bufferSize,this.bufferMode)')
	<?>.wasm-function[52] (frigate-hass-card.js:304:97873)
	<?>.wasm-function[49]
	<?>.wasm-function[2]
	wasm-stub
	(anonymous function) (frigate-hass-card.js:304:97873)
	(anonymous function) (frigate-hass-card.js:304:98322)
	(anonymous function) (frigate-hass-card.js:304:77270)
	(anonymous function) (frigate-hass-card.js:304:98619)
	(anonymous function) (frigate-hass-card.js:304:76338)
	(anonymous function) (frigate-hass-card.js:304:74899)
	(anonymous function) (frigate-hass-card.js:304:74414)
	(anonymous function) (frigate-hass-card.js:304:71696)
	(anonymous function)
```

**Additional information:**

Here's my lovelace card config:

```
      - type: 'custom:frigate-card'
        camera_entity: camera.outside-1
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.outside-1
      - type: 'custom:frigate-card'
        camera_entity: camera.outside-2
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.outside-2
      - type: 'custom:frigate-card'
        camera_entity: camera.entrance
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.entrance
      - type: 'custom:frigate-card'
        camera_entity: camera.corridor
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.corridor
      - type: 'custom:frigate-card'
        camera_entity: camera.office-1
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.office-1
      - type: 'custom:frigate-card'
        camera_entity: camera.office-2
        live:
          provider: frigate-jsmpeg
          jsmpeg:
           entity: camera.office-2
      - type: 'custom:frigate-card'
        camera_entity: camera.office-3
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.office-3
      - type: 'custom:frigate-card'
        camera_entity: camera.office-4
        live:
          provider: frigate-jsmpeg
          jsmpeg:
            entity: camera.office-4
```

Is there something I am doing wrong? Or it's the amount of cameras that is the issue? I have tried randomly removing cameras - but that doesn't seem to help.

Thanks in advance!
