### ISSUE TITLE
Support refreshing static image without switching the view

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#262]
With current configuration I can't watch Live feed properly, because after 10 seconds it switches back to `image` view. Would like to have support for static image refresh without having to switch current view. 

Current configuration:
```
type: custom:frigate-card
view:
  default: image
  timeout: '10'
  update_force: true
image:
  src: https://xxxx/frigate_reverse_proxy/api/living_room/latest.jpg
cameras:
  - camera_entity: camera.living_room_frigate
    live_provider: frigate
```
