### ISSUE TITLE
Elements disappear in live view

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#267]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** `main` branch

**Last working release (if known):** `v2.1.0`

**Browser and Operating System:** 
Firefox 96.0, Ubuntu 20.04
Home Assistant Companion iOS 2021.12.1, iOS 15.2

**Description of problem:** When switching from `image` view to `live` view PTZ elements disappear. Elements can be seen only until it loads the video.

![image](https://user-images.githubusercontent.com/24360494/150303209-cd8f0043-5976-483e-b47e-03741ea1626e.png)
![image](https://user-images.githubusercontent.com/24360494/150303410-f3e58f68-e517-4414-98ed-0d84e5a6eaa8.png)
![image](https://user-images.githubusercontent.com/24360494/150303366-08356ef6-15c7-4fcc-ab6c-c5081dd69075.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Same problem without `custom:frigate-card-conditional`

```
type: custom:frigate-card
view:
  default: image
image:
  src: https://frigate/api/living_room/latest.jpg
  refresh_seconds: 5
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
        - image
    elements:
      - type: icon
        icon: mdi:arrow-up
        style:
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 25px
          bottom: 85px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            tilt: UP
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
      - type: icon
        icon: mdi:arrow-down
        style:
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 25px
          bottom: 35px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            tilt: DOWN
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
      - type: icon
        icon: mdi:arrow-left
        style:
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 50px
          bottom: 60px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            pan: LEFT
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
      - type: icon
        icon: mdi:arrow-right
        style:
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 0px
          bottom: 60px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            pan: RIGHT
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
live:
  controls:
    next_previous:
      style: none
menu:
  buttons:
    live: true
    snapshots: false
    frigate_ui: false
    download: false
    frigate: false
    clips: true
    image: true
  mode: above
event_viewer:
  autoplay_clip: false
  controls:
    next_previous:
      style: chevrons
event_gallery:
  min_columns: 5
cameras:
  - camera_entity: camera.living_room_frigate
    live_provider: frigate
```
