### ISSUE TITLE
Cannot set action to none for picture element

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#275]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** `main` branch

**Last working release (if known):**

**Browser and Operating System:** Firefox 96.0, Ubuntu 20.04

**Description of problem:** 

Can't set action for picture element to `none`

**Javascript errors shown in the web inspector (if applicable):**

```
card custom:frigate-card Error: Invalid configuration: [
 "elements[0] -> tap_action -> action",
 "elements[0] -> tap_action -> service",
 "elements[0] -> tap_action -> navigation_path",
 "elements[0] -> tap_action -> url_path",
 "elements[0] -> tap_action -> frigate_card_action",
 "elements[0] -> tap_action -> camera"
]
    setConfig frigate-hass-card.js:16996
    s ha-logbook.ts:28
    d ha-logbook.ts:28
    d ha-logbook.ts:28
    l ha-logbook.ts:28
    v ha-logbook.ts:28
    value hui-masonry-view.ts:44
    _cards hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.a59fd8af.js:1243
    scheduleUpdate app.a59fd8af.js:1243
    _$EC app.a59fd8af.js:1243
ha-logbook.ts:28
    l ha-logbook.ts:28
    v ha-logbook.ts:28
    value hui-masonry-view.ts:44
    _cards hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.a59fd8af.js:1243
    scheduleUpdate app.a59fd8af.js:1243
    _$EC app.a59fd8af.js:1243
```

**Additional information:**
```
elements:
  - type: state-label
    entity: sensor.living_room_multisensor_temperature
    style:
      top: 5%
      left: 10%
      font-weight: bold
      color: rgb(153, 255, 153)
    tap_action:
      action: none
```
