### ISSUE TITLE
Add support for WebRTC 'mse' and 'ice_servers'

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#281]
**Is your feature request related to a problem? Please describe.**

If stream can't start with WebRTC then it will stream using MSE. For me MSE is very laggy and pausing non stop. To avoid streaming via MSE there is `mse: false` option in WebRTC Camera card, but it seems this card doesn't have support for that yet. 

There is also `ice_servers` option for custom STUN and TURN servers. It would be nice to get support for that here too. 

**Additional context**

Example for stun/turn:
```
webrtc:
  url: rtsp://xxx:xxx@192.168.222.103:554/live/ch1
  ui: true
  mse: false
  ice_servers:
    - urls: stun:stun.xxx.eu:3478
    - urls: turn:turn.xxx.eu:3478
      username: xxx
      credential: xxx
```

**Comment by dermotduffy** [comment]
The `frigate-hass-card` doesn't really "support" or not particular WebRTC card features -- it'll just seamlessly pass your options through, i.e. did you try just using this as your Frigate card config:

```
live:
  webrtc:
    url: rtsp://xxx:xxx@192.168.222.103:554/live/ch1
    ui: true
    mse: false
    ice_servers:
      - urls: stun:stun.xxx.eu:3478
      - urls: turn:turn.xxx.eu:3478
        username: xxx
        credential: xxx
```

Apologies if you already tried this, I can't tell.

PS: As the arguments may vary by camera, you'd probably need to use the new [override](https://github.com/dermotduffy/frigate-hass-card#override-options) functionality to override the parameters per camera (supporting different webrtc flags for some cameras is one of the motivations for overrides in the first place).
