### ISSUE TITLE
Add banner to documentation to point to particular release versions of the documentation

### ISSUE THREAD

**Issue by AbDhops** [dermotduffy/frigate-hass-card#282]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
None

**Browser and Operating System:**
Chrome

**Description of problem:**
Frigate Card complain about "Cannot autodetect Frigate Camera name. You need to set Camera_entity and / or Figrate.camera_name"

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I have working frigate configuration. It works and detects events, there are recordings and snapshots. Both Frigate and Home Assistant are working on different docker containers on same network. i.e. both are able to communicate with each other. Still when I installed Frigate lovelace card, I get above error.
Any leads on how to solve this error ?

Many thanks.

**Comment by dermotduffy** [comment]
Nothing beyond the contents of the error message you're receiving! Can you include a copy and paste of your card config and I'll take a look? Thanks!

**Comment by AbDhops** [comment]
My installation of custom card (I have many, below is only part of Frigate card):
```
lovelace:
  resources:
    - url: /local/resources/frigate-hass-card.js
      type: module
```

Here is my lovelace entry:

```
  - id: frigate_camera
    type: custom:frigate-card
    cameras:
      - camera_entity: camera.back
```
