### ISSUE TITLE
Update Instructions for v3.0.0

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#304]
## Visual Card Editor Users

Users of the visual card editor should receive a message prompting _"An automated card configuration upgrade is available, please visit the visual card editor"_. Opening the card editor, clicking "Upgrade" and "Save" should convert the card for the vast majority of users.

## Manual / YAML Users

<table>
<tr>
<tr>
<th>
Before
(Shows all impacted values)
</th>
<th>
After
(Only include values as needed)
</th>
</tr>
<tr>
<td>

```yaml
camera_entity: camera.office
frigate:
  camera_name: office_door
  client_id: frigate-server-2
  label: person
  url: http://my-frigate-server/
  zone: office_door
live:
  provide: webrtc
  webrtc:
    entity: camera.office_rtsp
    url: 'rtsp://USERNAME:PASSWORD@CAMERA:554/RTSP_PATH'
    any_other_webrtc_option: value
```

</td>
<td>

```yaml
cameras:
  - camera_entity: camera.office
    camera_name: office_door
    client_id: frigate-server-2
    label: person
    frigate_url: http://my-frigate-server/  # Note: Key name change.
    zone: office_door
    live_provider: webrtc  # Note: Key name change.
    webrtc:
      entity: camera.office_rtsp
      url: 'rtsp://USERNAME:PASSWORD@CAMERA:554/RTSP_PATH'
live:
  webrtc:
      any_other_webrtc_option: value
```

</td>
</tr>

<tr>
<td>

```yaml
menu:
  conditions:
    [key]: [value]
```

</td>
<td>

```yaml
overrides:
  - conditions:
      [key]: [value]
    overrides:
      menu:
        mode: none
```

</td>
</tr>

<tr>
<td>

```yaml
tap_action:
  action: custom:frigate-card-action
  frigate_card_action: frigate
```

</td>
<td>

Depending on the desired behavior, users may use the following to toggle the menu:

```yaml
tap_action:
  action: custom:frigate-card-action
  frigate_card_action: menu_toggle
```

... or the following to change to the default view ...

```yaml
tap_action:
  action: custom:frigate-card-action
  frigate_card_action: default
```

</td>
</tr>

<tr>
<td>

```yaml
view:
  timeout: 10
```

</td>
<td>

```yaml
view:
  timeout_seconds: 10
```

</td>
</tr>

</table>
