### ISSUE TITLE
`double_tap` as a card-level action does not work on Android

### ISSUE THREAD

**Issue by grimmaldus** [dermotduffy/frigate-hass-card#333]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Double tap doesn't perform action fullscreen on android Fully Kiosk when it's used with different provider but frigate-jsmpeg.

**Last working release (if known):**

**Browser and Operating System:**

- Fully Kiosk 1.45-play
- Galaxy Tab A7 (SM-T500) 
- Android Version 11 (SDK 30)

**Description of problem:**

Double tap action on card in Fully Kiosk Browser doesn't perform fullscreen action when it's used with different provider but frigate-jsmpeg. It performs fast forward or backward depends on area of touch. 

Yaml config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.garage
live:
  actions:
    double_tap_action:
      action: custom:frigate-card-action
      frigate_card_action: fullscreen
  controls:
    thumbnails: {}
    next_previous:
      style: none
```
