### ISSUE TITLE
Waiting for WebRTC card to load ...

### ISSUE THREAD

**Issue by thundergreen** [dermotduffy/frigate-hass-card#335]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
latest
**Last working release (if known):**
---
**Browser and Operating System:**
Chrome

**Description of problem:**
I added a webrtc camera with new core integration and webrtc server addon fpr hassio. Instead of getting webrtc card i get spinning waiting to load webrtc card

**Javascript errors shown in the web inspector (if applicable):**

```
38188e47.js:2 
        
      
        
        
      
        
      
       
        
       GET https://home-assistant.ddns.me/webrtc/webrtc-camera.js?v2.2.0 net::ERR_ABORTED 404
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
      
        
        
      
        
      
       
        
       GET https://home-assistant.ddns.me/webrtc/webrtc-camera.js net::ERR_ABORTED 404
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
      
        
        
      
        
      
       
        
       GET https://home-assistant.ddns.me/local/sip/jssip-3.5.3.min.js net::ERR_ABORTED 404
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
      
        
        
      
        
      
       
        
       GET https://home-assistant.ddns.me/local/sip/gensipdoor-card.js net::ERR_ABORTED 404
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
      
        
        
      
        
      
       
        
       GET https://home-assistant.ddns.me/asterisk/sipjs-card.js net::ERR_ABORTED 404
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
main.js:3  Thermostat Card   Version  1.3.0 
38188e47.js:2 
        
       Uncaught (in promise) https://home-assistant.ddns.me/webrtc/webrtc-camera.js?v2.2.0
(anonym) @ 38188e47.js:2
error (asynchron)
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
       Uncaught (in promise) https://home-assistant.ddns.me/webrtc/webrtc-camera.js
(anonym) @ 38188e47.js:2
error (asynchron)
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
       Uncaught (in promise) https://home-assistant.ddns.me/local/sip/jssip-3.5.3.min.js
(anonym) @ 38188e47.js:2
error (asynchron)
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
38188e47.js:2 
        
       Uncaught (in promise) https://home-assistant.ddns.me/local/sip/gensipdoor-card.js
(anonym) @ 38188e47.js:2
error (asynchron)
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
338188e47.js:2 
        
       Uncaught (in promise) https://home-assistant.ddns.me/asterisk/sipjs-card.js
(anonym) @ 38188e47.js:2
error (asynchron)
(anonym) @ 38188e47.js:2
r @ 38188e47.js:2
s @ 38188e47.js:2
(anonym) @ ha-icon-button-arrow-next.ts:8
s @ ha-icon-button-arrow-next.ts:8
(anonym) @ ha-panel-lovelace.ts:144
Promise.then (asynchron)
value @ ha-panel-lovelace.ts:144
(anonym) @ dwains-hash-switch-card.js:1
await in (anonym) (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
load (asynchron)
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
s @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
(anonym) @ dwains-hash-switch-card.js:1
```

** Config of the card **

```
type: custom:frigate-card
styles:
  card:
    - height: 200px;
cameras:
  - webrtc:
      entity: camera.webrtc_test
    camera_entity: camera.doorbell
    live_provider: webrtc
  - camera_entity: camera.front_door
    live_provider: frigate-jsmpeg
  - camera_entity: camera.garage
    live_provider: frigate-jsmpeg
  - camera_entity: camera.garden
    live_provider: frigate-jsmpeg
  - camera_entity: camera.garden_upstairs_2
    live_provider: frigate-jsmpeg
view:
  update_cycle_camera: true
  default: live
  camera_select: live
menu:
  buttons:
    image: false
    frigate: true
  button_size: 80px
  mode: overlay-bottom
live:
  preload: true
  lazy_unload: true
  auto_unmute: true
  controls:
    next_previous:
      size: 100px
      style: none
    thumbnails:
      media: clips
      mode: none
    title:
      mode: popup-bottom-right
      duration_seconds: 8
event_gallery:
  min_columns: 8
event_viewer:
  auto_unmute: true
  controls:
    next_previous:
      style: chevrons
      size: 10px
    thumbnails:
      size: 10px
      mode: above
    title:
      duration_seconds: 8
      mode: popup-top-right
dimensions:
  aspect_ratio: '16:8'
  aspect_ratio_mode: static
elements:
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.front_door
    elements:
      - type: state-badge
        entity: sensor.dark_sky_humidity
        style:
          right: 150px
          top: 86px
          color: rgba(0,0,0,0)
          opacity: 0.7
      - type: state-badge
        entity: sensor.solar_powered_outdoor_siren_air_temperature
        style:
          right: 80px
          top: 110px
          color: rgba(0,0,0,0)
          opacity: 0.7
      - type: custom:frigate-card-menu-state-icon
        entity: lock.main_door
        tap_action:
          action: toggle
      - type: custom:frigate-card-menu-state-icon
        entity: script.restart_foscam
        tap_action:
          action: toggle
      - type: custom:frigate-card-menu-state-icon
        entity: script.preset_garage
        tap_action:
          action: toggle
      - type: custom:frigate-card-menu-state-icon
        entity: script.preset_street
        tap_action:
          action: toggle
      - type: custom:frigate-card-menu-state-icon
        entity: script.preset_maindoor
        tap_action:
          action: toggle
      - type: custom:frigate-card-conditional
        conditions:
          view:
            - live
        elements:
          - type: icon
            icon: mdi:arrow-up
            style:
              background: rgba(10, 10, 10, 0.75)
              border-radius: 5px
              right: 180px
              bottom: 250px
              transform: scale(3, 3)
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.turn_up
          - type: icon
            icon: mdi:arrow-down
            style:
              background: rgba(10, 10, 10, 0.75)
              border-radius: 5px
              right: 180px
              bottom: 125px
              transform: scale(3, 3)
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.turn_down
          - type: icon
            icon: mdi:arrow-left
            style:
              background: rgba(10, 10, 10, 0.75)
              border-radius: 5px
              right: 255px
              bottom: 185px
              transform: scale(3, 3)
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.turn_left
          - type: icon
            icon: mdi:arrow-right
            style:
              background: rgba(10, 10, 10, 0.75)
              border-radius: 5px
              right: 105px
              bottom: 185px
              transform: scale(3, 3)
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.turn_right
          - type: icon
            icon: mdi:magnify-plus
            style:
              background: rgba(10, 10, 10, 0.75)
              border-radius: 5px
              right: 105px
              bottom: 450px
              transform: scale(3, 3)
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.zoom_in
          - type: icon
            icon: mdi:magnify-minus
            style:
              background: rgba(10, 10, 10, 0.75)
              border-radius: 5px
              right: 105px
              bottom: 350px
              transform: scale(3, 3)
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.zoom_out
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.doorbell
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: lock.main_door
        tap_action:
          action: toggle
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.garage
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: light.garage
        tap_action:
          action: toggle
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.garden
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: light.porch_garden
        icon: mdi:track-light
        tap_action:
          action: toggle
```

**Additional information:**
![image](https://user-images.githubusercontent.com/13320319/152814802-910b1088-0335-4cac-a97e-ad0854f828d2.png)
