### ISSUE TITLE
Weird resizing issue on moving from live view to events gallery - v3.0.0-rc.1 

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#336]
**Checklist:**

- ✅ I updated to the latest version available
- ✅ I cleared the cache of my browser

**Release with the issue:**
v2.0.1
v3.0.0-rc.1 

**Last working release (if known):**
v2.0.0

**Browser and Operating System:**
Chrome on Android 12

**Description of problem:**

I'm using Chrome on Android 12, I've 'installed' the URL to appear as an app on my home screen as I prefer this to the official HA app (I can pull to refresh if any loading issues occur and most importantly, pinch to zoom to see camera's better)

On v3.0.0-rc.1 I'm noticing some weird sizing issues on the right side of the screen when I switch between the live feed and the events gallery, video below to show what's happening:

https://user-images.githubusercontent.com/57415184/152811469-e202475e-ae58-43b8-ba9f-3ed65be5c9a6.mov

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
This issue doesn't exist in v2.0.0 but does in v2.0.1 and v3.0.0-rc.1 
The issue doesn't occur on official Android HA companion app.

**Comment by dermotduffy** [comment]
Dang, I can't reproduce this, in either browser or 'installed' on Android. Mind including a paste of your config so I can try to replicate exactly?

**Comment by dermotduffy** [comment]
Also: can you try other views (e.g. image or snapshot) to see if you can localize which one of live or the gallery is causing that flicker (which somehow appears to also affect that Lovelace UI body itself somehow).

**Comment by conorlap** [comment]
I've tried the other views, same issue. I've double checked and yeah, the last stable version where this issue didn't exist was v2.0.0 

I think I know the issue now, I have zoom-enable.js added to my lovelace resources so I can pinch to zoom. I removed this and cleared cache and cannot reproduce the issue on v3.0.0-rc.1. However v2.0.0 works fine with the zoom-enable.js resource.

Details about the zoom-enable.js resource: https://community.home-assistant.io/t/ha-web-interface-enable-pinch-to-zoom-on-mobile-devices/30389/18?u=conorlap

**Card config:**

```
type: custom:frigate-card
cameras:
  - live_provider: webrtc
    webrtc:
      entity: camera.amcrest_camera
    camera_entity: camera.amcrest_camera
    camera_name: frontdoor
view:
  default: live
  camera_select: live
menu:
  buttons:
    frigate: false
    fullscreen: false
    frigate_ui: false
    snapshots: false
    image: false
    live: true
    clips: true
    download: true
  mode: overlay-right
event_gallery:
  min_columns: 5
event_viewer:
  draggable: true
  auto_unmute: true
  controls:
    next_previous:
      style: chevrons
    title:
      mode: none
live:
  preload: true
  draggable: false
  auto_unmute: false
  controls:
    next_previous:
      style: none
    title:
      mode: none
overrides:
  - conditions:
      camera:
        - camera.amcrest_camera
    overrides:
      live:
        provider: webrtc
        webrtc:
          mse: false

```
