### ISSUE TITLE
Unable to set multiple cameras on single card

### ISSUE THREAD

**Issue by dm7500** [dermotduffy/frigate-hass-card#338]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 2.1.0

**Last working release (if known):**

**Browser and Operating System:**

Windows 10

Chrome/Firefox

**Description of problem:**

When adding multiple cameras to a Frigate card, it's not showing any of them. YAML of lovelace card below:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_door
  - camera_entity: camera.dining_room
  - camera_entity: camera.living_room
```

Results in this view on the card:

![image](https://user-images.githubusercontent.com/5718250/152846336-935468b0-0da1-440c-ba2e-1876a7731d04.png)

Clearing browser cache or trying a different browser had no effect. If I set a single camera via the visual editor, it works just fine.

**Additional information:**
