### ISSUE TITLE
Cannot autodetect Frigate camera name on Home Assistant Android app (but works with Chrome/Firefox)

### ISSUE THREAD

**Issue by pdecat** [dermotduffy/frigate-hass-card#341]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

[v3.0.0-rc.1](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v3.0.0-rc.1)

**Last working release (if known):**

[v2.1.0](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v2.1.0)

**Browser and Operating System:**

Does not work with Home Assistant Android app.

Works fine with Chrome on same Android phone, and with Chrome and Firefox on Ubuntu 21.10.

**Description of problem:**

Since upgrading from frigate-hass-card v2.1.0 to v3.0.0-rc.1, on Home Assistant Android app the camera stream is not shown and the following message appears instead:

> Cannot autodetect Frigate camera name, you need to either set camera_entity and / or frigate.camera_name.

![image](https://user-images.githubusercontent.com/318490/152992449-b8d6528e-ffdb-43ca-8e5f-9c976487dc1d.png)

The same issue occurs for all the `custom:frigate-card` instances in my lovelace configuration.

In Chrome on same Android phone, it works fine:

![image](https://user-images.githubusercontent.com/318490/152992688-8d2db6d6-a94c-4c35-b673-552f6772c192.png)

It also works on desktop Chrome:

![image](https://user-images.githubusercontent.com/318490/152992882-71124943-bb9a-430d-9d83-5d6f89a57123.png)

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

Card configuration:

```
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.coop
                frigate: {}
            live:
              provider: webrtc
              webrtc:
                url: rtsp://192.168.1.66:554/Streaming/Channels/101
                background: false
              controls:
                next_previous:
                  style: none
            elements:
              - type: custom:frigate-card-conditional
                conditions:
                  view:
                    - live
                elements:
                  - type: icon
                    icon: mdi:arrow-up
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 75px
                      bottom: 125px
                    tap_action:
                      action: call-service
                      service: script.camera_1_tilt_up
                  - type: icon
                    icon: mdi:arrow-down
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 75px
                      bottom: 75px
                    tap_action:
                      action: call-service
                      service: script.camera_1_tilt_down
                  - type: icon
                    icon: mdi:arrow-left
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 50px
                      bottom: 100px
                    tap_action:
                      action: call-service
                      service: script.camera_1_pan_left
                  - type: icon
                    icon: mdi:arrow-right
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 100px
                      bottom: 100px
                    tap_action:
                      action: call-service
                      service: script.camera_1_pan_right
                  - type: icon
                    icon: mdi:magnify-minus
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 125px
                      bottom: 125px
                    tap_action:
                      action: call-service
                      service: script.camera_1_zoom_out
                  - type: icon
                    icon: mdi:magnify-plus
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 125px
                      bottom: 75px
                    tap_action:
                      action: call-service
                      service: script.camera_1_zoom_in
                  - type: icon
                    icon: mdi:star-face
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 175px
                      bottom: 50px
                    tap_action:
                      action: call-service
                      service: script.camera_1_ptz_0
                  - type: icon
                    icon: mdi:star-circle
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 200px
                      bottom: 50px
                    tap_action:
                      action: call-service
                      service: script.camera_1_ptz_1
                  - type: icon
                    icon: mdi:star-circle-outline
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 225px
                      bottom: 50px
                    tap_action:
                      action: call-service
                      service: script.camera_1_ptz_2
                  - type: icon
                    icon: mdi:door
                    style:
                      background: rgba(255, 255, 255, 0.25)
                      border-radius: 5px
                      left: 250px
                      bottom: 50px
                    tap_action:
                      action: call-service
                      service: script.camera_1_ptz_3
```
