### ISSUE TITLE
`card_mod` styles not being re-injected after HA state change

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#343]
**Is your feature request related to a problem? Please describe.**
I'm using `custom:frigate-card-menu-icon` to toggle `input_boolean` entity state which hides/unhides conditional Picture Elements in Frigate Lovelace card views. For Picture element icon I'm using usual `icon` type but for text after the icon I'm using `card-mod` with `::after` selector. The problem I'm having is that when I hide elements, switch/refresh a view and then toggle elements again, `card-mod` won't get injected until I press menu button for view. I think this GIF would make more sense for you:

![issue](https://user-images.githubusercontent.com/24360494/153100609-40e3d0c2-ff7e-4715-892b-c1feb4333f9b.gif)

**Describe the solution you'd like**
I think you know better how to solve this, but I can suggest adding special action to `custom:frigate-card-action` to refresh current view that acts just like when you press menu button for view. Though I don't know if that would solve anything, because I tried [Defining multiple actions for Elements](https://github.com/dermotduffy/frigate-hass-card#defining-multiple-actions-for-elements) to toggle the elements and switch the view, but it didn't work for me(maybe there is a need for some delay before view is switched).
```
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:information
    tap_action:
      - action: call-service
        service: input_boolean.toggle
        service_data:
          entity_id: input_boolean.switch_elements
      - action: custom:frigate-card-action
        frigate_card_action: image
```

**Comment by peledzius** [comment]
For reference, short gif and config with single picture element that has problem described above:
![example](https://user-images.githubusercontent.com/24360494/153330513-6d1aefea-ebc9-4c25-8f9e-842805733a91.gif)
```
type: custom:frigate-card
view:
  default: image
image:
  src: https://url/
  refresh_seconds: 5
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - image
        - live
    elements:
      - type: custom:frigate-card-menu-icon
        icon: mdi:information
        tap_action:
          - action: call-service
            service: input_boolean.toggle
            service_data:
              entity_id: input_boolean.switch_elements
      - type: conditional
        conditions:
          - entity: input_boolean.switch_elements
            state: 'on'
        elements:
          - type: icon
            icon: mdi:thermometer
            entity: sensor.living_room_multisensor_temperature
            style:
              top: 0
              left: 33%
              right: 0
              height: 0%
              font-weight: bold
              color: rgb(153, 255, 153)
              background: rgba(67, 66, 62, 0.7)
      - type: icon
        icon: mdi:arrow-up
        style:
          color: rgba(255, 255, 255, 0.7)
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 25px
          bottom: 125px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            tilt: UP
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
      - type: icon
        icon: mdi:arrow-down
        style:
          color: rgba(255, 255, 255, 0.7)
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 25px
          bottom: 75px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            tilt: DOWN
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
      - type: icon
        icon: mdi:arrow-left
        style:
          color: rgba(255, 255, 255, 0.7)
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 50px
          bottom: 100px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            pan: LEFT
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
      - type: icon
        icon: mdi:arrow-right
        style:
          color: rgba(255, 255, 255, 0.7)
          background: rgba(255, 255, 255, 0.2)
          border-radius: 15px
          opacity: 0.8
          right: 0px
          bottom: 100px
        tap_action:
          action: call-service
          service: onvif.ptz
          service_data:
            entity_id: camera.living_room_onvif
            pan: RIGHT
            move_mode: ContinuousMove
            speed: 0
            distance: 0.01
            continuous_duration: 0
menu:
  buttons:
    live: true
    snapshots: false
    frigate_ui: false
    download: false
    frigate: true
    clips: false
    image: true
    fullscreen: false
  mode: above
event_viewer:
  controls:
    next_previous:
      style: chevrons
    title:
      duration_seconds: 5
      mode: popup-top-left
  draggable: false
  lazy_load: true
  auto_unmute: true
  auto_play: true
event_gallery:
  min_columns: 5
cameras:
  - camera_entity: camera.living_room_frigate
    live_provider: frigate
    title: Living room
live:
  controls:
    next_previous:
      style: none
    title:
      mode: none
  lazy_unload: true
  lazy_load: true
  draggable: false
  auto_unmute: true
card_mod:
  style:
    frigate-card-elements $:
      hui-icon-element.element $: |
        ha-icon:not([title*="onvif.ptz"]) {
          background: rgba(67, 66, 62, 0.7);
          padding: 4px;
        }
        ha-icon:not([title*="onvif.ptz"])::after {
          font-weight: bold;
          content: "{% if states('sensor.living_room_multisensor_temperature') != 'unknown' %} {{ states('sensor.living_room_multisensor_temperature') }}°C {%else%} N/A {%endif%}";
        }
```
