### ISSUE TITLE
State isn't displayed at the button on the card

### ISSUE THREAD

**Issue by kryzpee** [dermotduffy/frigate-hass-card#360]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v3.0.0-rc.1

**Last working release (if known):**
2.1

**Browser and Operating System:**
Chrome (latest), Win11/Android

**Description of problem:**
`State_color = true` (by default) but state isn't displayed at the button on the card.
![image](https://user-images.githubusercontent.com/60070086/153616933-4e448d20-13bf-4554-85bd-8e883056b90e.png)

```
elements:
  - type: custom:frigate-card-menu-state-icon
    entity: switch.light
    title: Licht
    icon: mdi:lightbulb
    tap_action:
      action: toggle
  - type: custom:frigate-card-menu-state-icon
    entity: switch.cam
    title: Detect
    tap_action:
      action: toggle
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
