### ISSUE TITLE
Expand each camera to a button in the buttons bar

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#378]
Instead of:

![image](https://user-images.githubusercontent.com/29582865/153920670-ce0bc4e4-29e9-423a-9194-d620a65cbf59.png)

Something like this:

![image](https://user-images.githubusercontent.com/29582865/153924966-ab84e47d-085d-4480-87ac-774c838f5bb8.png)

(I made this on MS Paint)

Where each icon would be one camera, and their icon could be rendered with the camera's initial letter, like "(R)ua", "(P)ortão", "(M)orro", "(V)ídeo porteiro". Of course, if the initial letter matches, some strategies can be taken, like using multiple initials if multiple words, or initial and a number like C1, C2.

Or, better yet, but probably not simple to implement for now, to display the snapshot of the cameras in the icon.

In my example, the cameras buttons are rendered in the opposite direction of the regular buttons, and I believe that would look better.

The advantages are that less clicks/taps are required to reach other cameras, and a visual indicator of the current camera being displayed (like when "live" is active, the icon turns blue).

This would be especially useful when using button layouts like "Above" or "Below".

The "Previous/Next" buttons to switch cameras does something some sort of similar, but I find them too big, and overall, I prefer not to pollute the camera frame.

**Comment by dermotduffy** [comment]
I'm not sure this is worth implementing as described. Everyone has a pretty different aesthetic preferences, so someone else will inevitably want something _slightly_ different. Better might be to have decent defaults and extensibility -- and maybe we're close to that already.

For example with `v3.0.0-rc.1` you can do this, which is pretty close to what you want:

```yaml
elements:
  - type: custom:frigate-card-menu-icon
    title: Front Door
    icon: mdi:alpha-f-box
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.sitting_room
  - type: custom:frigate-card-menu-icon
    title: Office
    icon: mdi:alpha-o-box
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.office
```

Or something like this if you want the styling when the camera is selected:

```yaml
elements:
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.front_door
    elements:
      - type: custom:frigate-card-menu-icon
        title: Front Door
        icon: mdi:alpha-f-box
        style:
          color: green
        tap_action:
          action: custom:frigate-card-action
          frigate_card_action: camera_select
          camera: camera.front_door
      - type: custom:frigate-card-menu-icon
        title: Office
        icon: mdi:alpha-o-box
        tap_action:
          action: custom:frigate-card-action
          frigate_card_action: camera_select
          camera: camera.office
  - type: custom:frigate-card-conditional
    conditions:
      camera:
        - camera.office
    elements:
      - type: custom:frigate-card-menu-icon
        title: Front Door
        icon: mdi:alpha-f-box
        tap_action:
          action: custom:frigate-card-action
          frigate_card_action: camera_select
          camera: camera.front_door
      - type: custom:frigate-card-menu-icon
        title: Office
        icon: mdi:alpha-o-box
        style:
          color: green
        tap_action:
          action: custom:frigate-card-action
          frigate_card_action: camera_select
          camera: camera.office
```

I think the main bits missing from your description are:

* Getting the visual indicator when selected is not scalable (the second YAML example would be really horrible if you had 10 cameras instead of 2).
* No alignment to the right for these icons.

Maybe that's close enough? Or maybe the feature request should be to address one or both of those gaps?

**Comment by felipecrs** [comment]
Thanks a lot for the detailed reply.

> Better might be to have decent defaults and extensibility -- and maybe we're close to that already.

I agree with this statement 100%. Therefore, let's focus on trying to address the two gaps you mentioned. Here's my suggestions:

1. Conditional styles for elements:

```yaml
elements:
  - type: custom:frigate-card-menu-icon
    title: Front Door
    icon: mdi:alpha-f-box
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.sitting_room
    conditional_style:
      condition:
        camera:
          - camera.front_door
      style:
        color: green
  - type: custom:frigate-card-menu-icon
    title: Office
    icon: mdi:alpha-o-box
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.office
    conditional_style:
      condition:
        camera:
          - camera.office
      style:
        color: green
```

But actually, I'm not sure about the name `conditional_style`, because I don't only mean `style`, I mean any attribute (because why not support changing any attribute like `icon`, `title`, or even `tap_action`?).

2. New attribute `align` for `custom:frigate-card-menu-icon`, similar to [`menu.align`](https://github.com/dermotduffy/frigate-hass-card/issues/376#:~:text=So%20in%20all%20I%20think%20my%20tweaked%20proposal%20is%3A), but that works with it.

- `align: "inherit"`: inherits the `menu.align` of the whole bar, the default.
- `align: "opposite"`: opposes to the default alignment of the bar.

```yaml
elements:
  - type: custom:frigate-card-menu-icon
    title: Front Door
    icon: mdi:alpha-f-box
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.sitting_room
    align: "opposite"
  - type: custom:frigate-card-menu-icon
    title: Office
    icon: mdi:alpha-o-box
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.office
    align: "opposite"
```
