### ISSUE TITLE
State color doesn't change for submenu items

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#389]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** [`main`](https://github.com/dermotduffy/frigate-hass-card/tree/main)

**Last working release (if known):** 

**Browser and Operating System:** Firefox 97.0, Ubuntu 20.04

**Description of problem:**

Similar to https://github.com/dermotduffy/frigate-hass-card/issues/360, but the issue is with submenu items. 

![image](https://user-images.githubusercontent.com/24360494/154510732-2dbd86b8-26c6-4a09-81bb-c3e4a5e71d7a.png)

```
elements:
  - type: custom:frigate-card-menu-submenu
    icon: mdi:lightbulb
    items:
      - entity: switch.living_room_light_switch
        tap_action:
          action: toggle
      - entity: switch.living_room_wall_light_switch
        tap_action:
          action: toggle
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
