### ISSUE TITLE
Card-wide Actions should ignore icons

### ISSUE THREAD

**Issue by luzik** [dermotduffy/frigate-hass-card#410]
With card-wide actions defined, clicking, (for example) on frigate menu icon run also defined action.
It would be awesome that card-wide action would only run on action clicked on video/picture.

My personal use case is to use frigate-hass-card as "panel: true" and I switch to this tab when someone ring doorbell. I got full screen video on my wall tablet, and want to connect tap action with door lock opening service.

I know I can define new custom icon button, but when someone knock the door I want open doors as easy as possible, and still have to be able touch frigate menu without opening doors

```yaml
live:
  actions:
    device_id: cd69c6a3a5b899f01581a261181f68cf
    tap_action:
      action: call-service
      service: dahua.vto_open_door
      service_data:
        device_id: cd69c6a3a5b899f01581a261181f68cf
  preload: true
```
