### ISSUE TITLE
Helping to set up the config of my cards.

### ISSUE THREAD

**Issue by Tuurkevg** [dermotduffy/frigate-hass-card#416]
I want to make an frigate card with an submenus for all my camera's in 1 card. I have multiple errors while setting it up. Can someone give me an example of his config card I followed the example on the readme page but it isn't working

```
`type: custom:frigate-card
cameras:
  - camera_entity: camera.cam0_2
  - camera_entity: camera.cam1_2
  - camera_entity: camera.cam2_2
  - camera_entity: camera.cam3
frigate:
  mode: above
  buttons:
    cameras: true
    image: true
    live: true
    frigate: true
    frigate_ui: true
elements:
  - type: custom:frigate-card-menu-state-icon
    entity: switch.gate_relay_0
    tap_action:
      action: toggle
view:
  default: live
  timeout: '30'
live:
  auto_unmute: true
  lazy_load: true
  provider: frigate
  preload: true
event_viewer:
  auto_unmute: true
  controls:
    next_previous:
      style: thumbnails
    thumbnails:
      mode: below
  lazy_load: true
  autoplay_clip: true
image:
  src: >-
    https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.gludy.com%2Fphotos%2F0%2FAnonymous-wallpaper_950.jpg&f=1&nofb=1
dimensions:
  aspect_ratio_mode: dynamic
`
```
![image](https://user-images.githubusercontent.com/77327545/155842200-d88f2811-a9a6-4e1d-8838-9eb5f7f96283.png)
