### ISSUE TITLE
Allow overrides to use HA state conditions

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#418]
**Is your feature request related to a problem? Please describe.**
I have a menu button to power on/off smart plug that supplies power for camera. When I turn off camera for privacy purposes, image view keeps refreshing last available snapshot(from Frigate or HA camera entity). 

**Describe the solution you'd like**
Implement new Frigate Card condition which would check specific HA entity state. Maybe then it would be possible to use `overrides` functionality to override `image` block and use screensaver mode or custom url when camera is off.

For example:

```
overrides:
  conditions:
    state:
      - entity: switch.plug_living_room_camera
        state: 'off'
  overrides:
    image:
      mode: screensaver
      refresh_seconds: 0
```

**Describe alternatives you've considered**
I currently couldn't think of any.
