### ISSUE TITLE
Add priority field to menu items

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#449]
Current situation: 
![image](https://user-images.githubusercontent.com/24360494/156904431-d0bb469b-d34b-4432-bbb0-470e5129d41a.png)

Expectation:
![image](https://user-images.githubusercontent.com/24360494/156904382-50e4e7d3-cadb-4698-b558-07e9b734dd6c.png)

I think card parses `custom:frigate-card-conditional` last one, that's why it does not respect the order. 

<details>
<summary>Card config:</summary>

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room_frigate
    live_provider: ha
    title: Living room
view:
  camera_select: live
  default: image
  timeout_seconds: 0
menu:
  mode: above
  buttons:
    frigate: false
    live: true
    clips: false
    snapshots: false
    download: false
    frigate_ui: false
    fullscreen: false
image:
  refresh_seconds: 5
  mode: camera
elements:
  - type: custom:frigate-card-menu-submenu
    icon: mdi:lightbulb
    items:
      - entity: switch.living_room_light_switch
        state_color: true
        tap_action:
          action: toggle
      - entity: switch.living_room_wall_light_switch
        tap_action:
          action: toggle
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - image
        - live
    elements:
      - type: custom:frigate-card-menu-state-icon
        entity: input_boolean.switch_elements
        state_color: false
        icon: mdi:information
        tap_action:
          action: toggle
  - type: custom:frigate-card-menu-submenu
    icon: mdi:power
    items:
      - entity: switch.plug_living_room_camera
        state_color: true
        tap_action:
          action: toggle
```
</details>

**Comment by dermotduffy** [comment]
They are added to the menu in the order in which they are _**loaded by the browser**_ (which is not necessarily the order in which they are configured). It is indeed the conditional that's the issue, because it's a child element `<frigate-card-elements-core>` that will always load later than the parent & its peers. A hacky workaround is to have the "peers" at the same level, by having everything 'under' a (fake) conditional [I tested this, and it works].

I agree this is surprising (this not particularly easy to fix).

**Comment by dermotduffy** [comment]
Seems like there are two paths to a solution here:

1. Statically analyze the configuration and try to work out the desired order
2. Have a variable (e.g. `priority`) that lets custom menu icons be positioned.

The trouble with idea 1, is that there could be arbitrary depth of `elements` here, with arbitrary conditionals in it, including elements that are just `custom:whatever` but that could include menu items further down the chain that the card cannot reasonable understand. I do think this kind of very complex configuration is probably unlikely -- but my point is idea 1 is difficult to correctly & completely implement.

So how about idea 2? 

```yaml
- type: custom:frigate-card-menu-state-icon
  entity: input_boolean.switch_elements
  state_color: false
  icon: mdi:information
  priority: 100
  tap_action:
    action: toggle
- type: custom:frigate-card-menu-state-icon
  entity: input_boolean.switch_elements
  state_color: false
  icon: mdi:information
  priority: 200
  tap_action:
    action: toggle
```

... the second icon would render first. If priority is not specified, the existing browser-load order behavior is preserved.
