### ISSUE TITLE
Newer HA icons are not displayed (replaced with a check)

### ISSUE THREAD

**Issue by domneedham** [dermotduffy/frigate-hass-card#456]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 
v3.0.2

**Last working release (if known):** 
(I think HA icon update broke it?)

**Browser and Operating System:** 
iOS, macOS, Firefox, Chrome

**Description of problem:** 
When using frigate-card-menu-state-icon, the new person motion sensor icon does not display correctly. It is replaced by a default check icon for a binary sensor.

![image](https://user-images.githubusercontent.com/34138267/157074326-f3326ab5-9d75-4e6e-9e74-8aaa7913745b.png)

In this image, the first check is a person motion sensor and the other is related to the 'music-note' icon. 

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**

**Comment by dermotduffy** [comment]
Not quite following this. My motion sensors are showing as as the "walking human" icon -- would you mind including your config, and perhaps a screenshot of what you expected to show up? Did this work in a prior version

> (I think HA icon update broke it?)

I'm not aware about this -- mind saying a bit more?

**Comment by domneedham** [comment]
Hmm strange. My yaml for the config (changed camera name):

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.1
    title: 1 Substream
    id: sub
    live_provider: webrtc-card
    webrtc_card:
      entity: camera.1_substream
  - camera_entity: camera.2
    title: 2 Mainstream
    id: main
    live_provider: webrtc-card
    webrtc_card:
      entity: camera.2_mainstream
menu:
  mode: below
  buttons:
    image: false
    clips: true
    download: true
    frigate: false
    live: true
    snapshots: false
    frigate_ui: false
event_viewer:
  controls:
    next_previous:
      style: thumbnails
dimensions:
  aspect_ratio_mode: dynamic
live:
  controls:
    next_previous:
      style: none
    draggable: false
    # thumbnails:
    #   mode: below
    #   media: clips
view:
  default: live
elements:
  - type: custom:frigate-card-menu-state-icon
    entity: binary_sensor.1_person_motion
    tap_action:
      action: more-info
  - type: custom:frigate-card-menu-state-icon
    entity: binary_sensor.1_dog_motion
    tap_action:
      action: more-info
  - type: custom:frigate-card-menu-state-icon
    entity: binary_sensor.dog_barking
    tap_action:
      action: more-info
  - type: custom:frigate-card-menu-submenu
    icon: mdi:bell
    items:
      - entity: input_boolean.notify_1_camera_if_one_person_home
        tap_action:
          action: more-info
      - entity: input_boolean.notify_1_camera_if_both_home
        tap_action:
          action: more-info
      - entity: input_boolean.notify_1_camera_if_away
        tap_action:
          action: more-info
```

I am referring to when they updated the mdi icon set (it was in a release note - I just can't remember which :)). To be honest, it has been off a while, I should have raised the issue sooner than now. It wasn't a frigate card update that broke. 

If it helps, I know the mushroom cards had the same issue and they released a fix (https://github.com/piitaya/lovelace-mushroom/pull/147).
