### ISSUE TITLE
Problems with card in Android HA App

### ISSUE THREAD

**Issue by TheQue42** [dermotduffy/frigate-hass-card#499]
**Checklist:**

* Running card v.3
* No problem in browser, just in Android HA App.

**Release with the issue:**
Card version v.3.0.0, with Home Assistant 2022.3.7

**Last working release (if known):**
none

**Browser and Operating System:**
Android, on a Samsung S20 Ultra.

**Description of problem:**
I'm not sure if this is pebcac or bug, so...

I've had some issues updating my frigate cards, since I changed to v.3.0.0. Even creating a new element completely, didnt make the visual editor trigger properly. Eventually, after some manual yaml fiddling, I started getting the "update" prompts in lovelace, and I managed to change all my frigate cards to use the new yaml format etc. (I think).

But....they only work in my browser? The official HA app complains on "_can not auto-detect camera name, you need to set..._" and setting the _name_ doesnt help, and the entities are already there...

The lovelace config for on element says:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.fr_framsida
    zone: fr_entre
    live_provider: frigate-jsmpeg
    title: FramSida
    camera_name: fr_framsida
  - camera_entity: camera.fr_baksidan
    live_provider: frigate-jsmpeg
event_viewer:
  auto_play: true
  controls:
    title:
      duration_seconds: 0
  transition_effect: none
view:
  default: snapshot
  update_cycle_camera: true
  update_seconds: 0
  timeout_seconds: 0
  camera_select: live
menu:
  buttons:
    frigate: true
    live: true
    clips: true
    snapshots: true
    fullscreen: true
  mode: overlay-top
dimensions:
  aspect_ratio_mode: dynamic
```
What am I doing wrong?

And if I haven't said so before, thanks a million for all the work you put into the frigate software!
