### ISSUE TITLE
Native support for select entities

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#516]
**Is your feature request related to a problem? Please describe.**
I like to have control over the night vision mode of my Tuya camera. Fortunately, the Tuya integration provides a [_Select_](https://www.home-assistant.io/integrations/select/) entity with the options _Automatic_, _On_ and _Off_.

I wanted to include a menu button in the Frigate card that would allow me to switch between these options.

**Describe the solution you'd like**
Something like below:

```yaml
- type: custom:frigate-card-menu-select
  conditions:
    view:
      - live
    camera:
      - camera.rua
    entity: select.camera_da_rua_night_vision
```

That could auto-color the icon based on entity's icon and auto-mark the selected option as selected. And, of course, auto-render a submenu based on the available options.

**Describe alternatives you've considered**
The following, but I haven't figured out yet how could I mark the selected option as selected based on the entity state.

```yaml
- type: custom:frigate-card-menu-submenu
  icon: mdi:theme-light-dark
  conditions:
    view:
      - live
    camera:
      - camera.rua
  items:
    - title: Automatic
      icon: mdi:theme-light-dark
      tap_action: 
        action: call-service
        service: select.select_option
        service_data:
          entity_id: select.camera_da_rua_night_vision
          option: '0'
    - title: Off
      icon: mdi:weather-sunny
      tap_action: 
        action: call-service
        service: select.select_option
        service_data:
          entity_id: select.camera_da_rua_night_vision
          option: '1'
    - title: On
      icon: mdi:weather-night
      tap_action: 
        action: call-service
        service: select.select_option
        service_data:
          entity_id: select.camera_da_rua_night_vision
          option: '2'
```

**Additional context**
None.

**Comment by dermotduffy** [comment]
I think you're describing a kind of submenu. So it would be something like this:

```yaml
elements:
  - type: custom:frigate-card-menu-submenu-select
    icon: mdi:menu
    entity: select.camera_da_rua_night_vision
```

If you go to `Developer Tools` -> `States` -> `select.camera_da_rua_night_vision` ... can you paste what you get? Would you be happy if the item titles were just what was included in the `Options` attribute [which you will presumably find]?

PS: I don't get why there are `conditions` in here, I think that would just be kept separate, and you'd nest this new element under a condition?

**Comment by felipecrs** [comment]
State attributes:

```yaml
options:
  - '0'
  - '1'
  - '2'
device_class: tuya__basic_nightvision
icon: mdi:theme-light-dark
friendly_name: Câmera da rua Night Vision
```

Unfortunately, the titles are not there (which is perhaps because they would need to be localized). However, the native _Entities_ card finds them somehow.

https://user-images.githubusercontent.com/29582865/163842330-71716e4b-5124-4942-bd00-7e7fc3742b1d.mp4

**Comment by felipecrs** [comment]
> I think you're describing a kind of submenu. So it would be something like this:
> 
> ```yaml
> elements:
>   - type: custom:frigate-card-menu-submenu-select
>     icon: mdi:menu
>     entity: select.camera_da_rua_night_vision
> ```

Right. Precisely right.

> PS: I don't get why there are conditions in here, I think that would just be kept separate, and you'd nest this new element under a condition?

Ops, sorry, that's my mistake. I meant:

```yaml
- type: custom:frigate-card-menu-submenu-select
  conditions:
    view:
      - live
    camera:
      - camera.rua
  entity: select.camera_da_rua_night_vision
```

Just like how I have:

```yaml
- type: custom:frigate-card-menu-submenu
  icon: mdi:theme-light-dark
  conditions:
    view:
      - live
    camera:
      - camera.rua
  items: [...]
```

**Comment by felipecrs** [comment]
I could not yet find how the HA frontend accesses the localized title for the value, but I found where it is defined:

https://github.com/home-assistant/core/blob/e70c8fa35984de5e7c65aef176e6f0b01c40bfd0/homeassistant/components/tuya/strings.select.json#L8-L13

**Comment by dermotduffy** [comment]
Asked in the frontend development discord, got this response:

```
Try hass.localize("component.select.state.tuya__basic_nightvision.0")
Here tuya__basic_nightvision would be the device_class of the entity and 0 its state.
```

This didn't immediately work for me, but I don't have that integration installed. Need to experiment more -- including it here for when I get around to this.

**Comment by felipecrs** [comment]
That worked for me! It returned _Automatic_, as it should.

**Comment by felipecrs** [comment]
@dermotduffy sorry, I got pretty hard confused. Forget everything about `conditionals`. This is done by the `custom:frigate-card-conditional` and has nothing to do with this new custom element. It should be the following:

```yaml
- type: custom:frigate-card-conditional
  conditions:
    view:
      - live
    camera:
      - camera.rua
  elements:
    - type: custom:frigate-card-menu-submenu-select
      icon: mdi:menu
      entity: select.camera_da_rua_night_vision
```

**Comment by dermotduffy** [comment]
Yup, figured! This is on my list, don't think it will be too difficult.

**Comment by dermotduffy** [comment]
This will be in the v4 release. I added in the localization logic from above, but as I have no way to test that the jury is out until you give it a shot.

You'd need configuration something like this for your example:

Minimal:

```yaml
elements:
  - type: custom:frigate-card-menu-submenu-select
    entity: select.camera_da_rua_night_vision
```

To use custom icons per option (as HA does not support this natively in the entity itself), or to override the menu icon itself something like this:

```yaml
elements:
  - type: custom:frigate-card-menu-submenu-select
    icon: mdi:cow
    entity: select.camera_da_rua_night_vision
    options:
      0:
        icon: mdi:theme-light-dark
      1:
        icon: mdi:weather-sunny
      2:
        icon: mdi:weather-night
```
