### ISSUE TITLE
Card stops working intermittently: Unknown error

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#568]
I'm using the current latest v4.0.0. Nothing shows in the browser logs. Happens frequently, but I still can't determine why.

https://user-images.githubusercontent.com/29582865/167648294-1f719e1f-41d6-41f1-9982-80c5561327ba.mp4

This didn't happen in v3.

This is the configuration of one of my cards, but the problem happens to all of them:

```yaml
- type: custom:frigate-card
    view:
      default: live
      update_force: false
    menu:
      buttons:
        frigate:
          enabled: false
        snapshots:
          enabled: false
        image:
          enabled: false
      style: outside
      position: top
    live:
      preload: false
      controls:
        next_previous:
          style: none
        title:
          mode: none
      lazy_load: true
      lazy_unload: all
      auto_unmute: never
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '16:9'
    event_viewer:
      auto_play: never
    elements:
      - type: custom:frigate-card-conditional
        conditions:
          view:
            - live
          camera:
            - camera.rua
        elements:
          - type: icon
            icon: mdi:arrow-up
            style:
              background: rgba(255, 255, 255, 0.75)
              border-radius: 5px
              right: 25px
              bottom: 115px
            tap_action:
              action: call-service
              service: onvif.ptz
              service_data:
                entity_id: camera.rua_onvif
                tilt: UP
                move_mode: ContinuousMove
                speed: 0.05
                continuous_duration: 0.05
          - type: icon
            icon: mdi:arrow-down
            style:
              background: rgba(255, 255, 255, 0.75)
              border-radius: 5px
              right: 25px
              bottom: 65px
            tap_action:
              action: call-service
              service: onvif.ptz
              service_data:
                entity_id: camera.rua_onvif
                tilt: DOWN
                move_mode: ContinuousMove
                speed: 0.05
                continuous_duration: 0.05
          - type: icon
            icon: mdi:arrow-left
            style:
              background: rgba(255, 255, 255, 0.75)
              border-radius: 5px
              right: 50px
              bottom: 90px
            tap_action:
              action: call-service
              service: onvif.ptz
              service_data:
                entity_id: camera.rua_onvif
                pan: LEFT
                move_mode: ContinuousMove
                speed: 0.05
                continuous_duration: 0.05
          - type: icon
            icon: mdi:arrow-right
            style:
              background: rgba(255, 255, 255, 0.75)
              border-radius: 5px
              right: 0px
              bottom: 90px
            tap_action:
              action: call-service
              service: onvif.ptz
              service_data:
                entity_id: camera.rua_onvif
                pan: RIGHT
                move_mode: ContinuousMove
                speed: 0.05
                continuous_duration: 0.05
      - type: custom:frigate-card-conditional
        conditions:
          view:
            - live
          camera:
            - camera.rua
        elements:
          - type: custom:frigate-card-menu-submenu-select
            entity: select.camera_da_rua_night_vision
    cameras:
      - camera_entity: camera.rua
        live_provider: frigate-jsmpeg
        id: camera.rua
        title: Rua
        camera_name: rua
      - camera_entity: camera.morro
        live_provider: frigate-jsmpeg
      - camera_entity: camera.portao
        live_provider: frigate-jsmpeg
      - camera_entity: camera.video_porteiro
        live_provider: ha
```
