### ISSUE TITLE
Camera tap action or clips gallery to display from a different camera

### ISSUE THREAD

**Issue by CZonin** [dermotduffy/frigate-hass-card#586]
**Is your feature request related to a problem? Please describe.**
I currently use an Amcrest camera as a baby monitor. Frigate does not support audio passthrough, thus I can't get audio through a Frigate card. I still like having the functionality of the card though (ie. clips gallery) so my solution has been to use a picture entity card  using live view and use the generic camera integration with the same camera. I then use the Frigate card to display just the clips gallery from the same camera through the Frigate integration below it on my dashboard.

**Describe the solution you'd like**
If I could set the tap action on the camera within the card, I could set it so it's displaying the Frigate camera, but tapping it would open the live view from the generic camera integration full screen with audio.

**Describe alternatives you've considered**
Another solution would be to allow the clips gallery to display from a different camera. That way I could have the live view of the Frigate card come from my generic camera integration and then set the clips gallery to display from the Frigate integration.

**Comment by dermotduffy** [comment]
> I currently use an Amcrest camera as a baby monitor. Frigate does not support audio passthrough, thus I can't get audio through a Frigate card.

This is not correct. It is true with the `jsmpeg` live provider, but either the `ha` or `webrtc-card` live providers can provide audio in the card.

> I still like having the functionality of the card though (ie. clips gallery) so my solution has been to use a picture entity card using live view and use the generic camera integration with the same camera.

Anything the picture entity card can do, this card should be able to do also!

> If I could set the tap action on the camera within the card, I could set it so it's displaying the Frigate camera, but tapping it would open the live view from the generic camera integration full screen with audio.

If I understand you, you'd like an action to change camera in the card -- if so then you can already do this. The following will change to the `camera.front_door` camera, if you hold down on the live view of the `camera.sitting_room` camera.

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.sitting_room
  - camera_entity: camera.back_yard
  - camera_entity: camera.front_door
overrides:
  - conditions:
      camera:
        - camera.sitting_room
      view:
        - live
    overrides:
      live:
        actions:
          hold_action:
            action: custom:frigate-card-action
            frigate_card_action: camera_select
            camera: camera.front_door
```

**Comment by CZonin** [comment]
Ty for all the info!

I think this is a really niche use-case so trying to communicate what I'm trying to achieve is difficult. To add more clarity:

I can use a different live provider for audio pass through, but not if it's a Frigate camera entity. Frigate camera entities won't get audio regardless of the provider. And without using a Frigate camera entity, I can't get the clips gallery.

Basically I want to have the card display both a camera live view with audio, and have the clips gallery for that camera. I can only have one of those at once currently:

- Use a generic camera entity in the card gives me a live stream with audio, but since it's not referencing a Frigate entity, I have no clips.
- Use a Frigate camera entity in the card which gives me live stream, no audio, and access to clips.

With that, I think the most logical solution would be to have the ability to set a camera where the clips are coming from as an option if possible. That way I can set the live stream from a generic camera entity and get audio pass through, and then set the clips to pull from the Frigate camera entity.

Let me know if that makes more sense, or if I'm still missing something that can be done with current functionality.

**Comment by dermotduffy** [comment]
> I can use a different live provider for audio pass through, but not if it's a Frigate camera entity. 

This is not accurate. I'm doing it right now! Frigate provided camera entity -- has audio -- in the Frigate card. If it's not working for you, and the camera definitely provides audio, I'd suggest playing with the audio encoding options in your Frigate configuration. See [here](https://docs.frigate.video/faqs#audio-in-recordings). This is not related to the Frigate card, or the Frigate integration.

> Basically I want to have the card display both a camera live view with audio, and have the clips gallery for that camera. 

On a generic camera, just set the `camera_name` parameter to the Frigate camera name (from your Frigate config) and events (gallery, etc) should work just fine even though the camera entity is not a Frigate provided one.

But, as per above, you actually shouldn't need to go this route.

**Comment by CZonin** [comment]
Hmm strange. I was taking that info from here https://github.com/blakeblackshear/frigate/issues/2874

But it looks like you're right, though that documentation linked only mentions recordings.

An odd thing I noticed is that one of my cameras gets audio and shows video controls on hover: 
![Screenshot 2022-05-14 112322](https://user-images.githubusercontent.com/67965669/168435996-853abe0f-6439-453e-8416-4102f6b47d76.png)
But none of my other cameras do.
![Screenshot 2022-05-14 112358](https://user-images.githubusercontent.com/67965669/168436588-ba1b5c49-9bc5-49a6-935a-8eb2fc8842dc.png)


None of my config options are different between those cameras. I know this is now becoming more of a general Frigate discussion, but let me know if you have any suggestions or if anything stands out that could be related.

```
# frigate.yml
mqtt:
  host: xxxx
  port: 1883
  user: hamqtt
  password: xxxx

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
    max_seconds: 120
    pre_capture: 1
    post_capture: 1
    retain:
      default: 1
      mode: motion

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 1

birdseye:
  enabled: false

detectors: 
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

cameras:
  front_doorbell:
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        person:
          min_score: 0.8
          min_area: 20000
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 960
      fps: 5
    live:
      height: 960
      quality: 8
    motion:
      mask:
        - 2352,623,2385,1009,2303,1619,2560,1812,2560,0,1880,0,2171,102
        - 1804,0,299,0,347,411,1110,277,1702,287
    zones:
      my_driveway:
        coordinates: 2162,1371,2028,1337,2011,1322,2011,1252,2038,1187,2083,1159,2176,1114,2372,1091,2335,1378
        objects:
          - person
          - motorcycle
      neighbor_driveway_1:
        coordinates: 1734,1187,1677,1133,1621,1072,1494,1075,1517,1125,1568,1196
        objects:
          - person
          - motorcycle
      neighbor_driveway_2:
        coordinates: 2052,1136,1949,1063,1891,1057,1767,1052,1694,1117,1897,1179
        objects:
          - person
          - motorcycle
    mqtt:
      quality: 85
      bounding_box: false
      height: 960
  den:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://xxxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 0,0,1920,0,1920,190,1515,112,1159,86,649,82,306,99,0,169
        - 0,834,0,1080,88,1080,29,953
    zones:
      office_entry:
        coordinates: 0,640,114,996,576,996,493,98,0,192
        objects:
          - person
    mqtt:
      quality: 85
      bounding_box: false
      height: 720
  backyard:
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.8
        cat:
          min_score: 0.8
        dog:
          min_score: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://xxxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 1920,0,1829,90,1784,124,1717,211,1435,140,1057,120,844,129,653,162,400,203,0,493,0,323,0,0
    mqtt:
      quality: 85
      bounding_box: false
      height: 720
  nursery:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: xxxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 0,376,0,1080,352,1080,140,722
        - 1920,459,1920,1080,1532,1080,1705,827
    mqtt:
      quality: 85
      bounding_box: false
      height: 720
```
