### ISSUE TITLE
Question about frigate-hass-card camera definitions

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#648]
I have a question/possible bug with how my cameras are setup in the frigate-hass-card.  I have 6 cards defined similar to the following:

```
type: "custom:frigate-card"
cameras:
  - camera_name: Lisa
    live_provider: webrtc-card
    webrtc_card:
      url: 'rtsp://username:password@192.168.1.165/live'
```
Four of the cards reference cameras that are defined in frigate.yaml, while two of them are not.  

Now for my question: 
1) If the frigate addon is running, and I open the view containing the 6 camera cards, they all display their respective streams correctly.  
2) If the frigate addon is not running when I open the view, each card has this error displayed  "Unknown error: Check troubleshooting"
3) If I clear the cache and repeat item 2, the camera streams are displayed correctly for 1-2 seconds before the error is reported on each of them
4) If I start the frigate addon and open the view, as mentioned above all cameras stream correctly.  The funny thing is, I can stop frigate at this point and the cameras continue to work correctly until either the screen or lovelace is refreshed, at which point the errors are displayed.  It seems like the cards should be viewable even if frigate is not currently running, am I correct?

I have one further unrelated question about defining cameras in the frigate-hass-card for cameras also defined in frigate.yaml.  My frigate.yaml for the camera is:

```
cameras:
  frontyard:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.119:8554/frontyard
```
and I have the definition in frigate-hass-card as follows:

```
type: "custom:frigate-card"
cameras:
  - camera_name: frontyard
    frigate_url: http://192.168.1.119:5000/birdseye
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://192.168.1.119:8554/frontyard
```
Note that the camera name in both is "frontyard".  Is this the correct way to define this?  I also tried camera_entity instead of camera_name but the display streams seemed more unreliable.
