### ISSUE TITLE
Auto upgrade from v3.0.0 disables image menu button

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#663]
**Release with the issue:** [release-4.0.0](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0)

**Description of problem:**

After I used automatic configuration upgrade function, image menu button disappeared and became disabled.

**Comment by dermotduffy** [comment]
i.e. image button was enabled, then you did the automatic update, then image button had gone back to being disabled?

**Comment by peledzius** [comment]
Yes.

Before:

```
menu:
  buttons:
    live: true
    snapshots: false
    frigate_ui: false
    download: false
    frigate: false
    clips: false
    image: true
    fullscreen: false
  mode: above
```

After:

```
menu:
  buttons:
    frigate:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    frigate_ui:
      enabled: false
    fullscreen:
      enabled: false
  style: outside
  position: top
```
