### ISSUE TITLE
Image refreshing faster than it should 

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#666]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** [release-4.0.0](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0)

**Last working release (if known):** v3.0.0

**Browser and Operating System:** Firefox, Chrome

**Description of problem:**

Image being refreshed more frequent than declared `refresh_seconds: 5`. I tried increasing `refresh_seconds` to 10, but after first 10 seconds it starts to behave same way.

Minimal configuration to reproduce: 

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam
image:
  refresh_seconds: 5
  mode: camera
view:
  default: image
```
