### ISSUE TITLE
De-duplicate multiple cameras in the timeline if they have the same name/clientid

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#667]
**Release with the issue:** [release-4.0.0](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0)

**Description of problem:**

I configured two cameras with exact same `camera_entity`, but with different providers. Timeline shows them as separate cameras. I think it would make sense two merge them and show only one. :) 

![image](https://user-images.githubusercontent.com/24360494/173202910-d7b188d0-3bfc-489e-a7e2-cc9816d23927.png)

Config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room_frigate
    live_provider: webrtc-card
    id: living_room_webrtc
    title: Living room
    webrtc_card:
      url: rtsp://xxx:xxx@192.168.222.103:554/live/ch1
  - camera_entity: camera.living_room_frigate
    id: living_room
    live_provider: ha
    title: Living room(with audio)
...
```

<br></br>
P.S. This v4.0.0 release is a bomb! So many new options and timeline is epic! Thank you so much for your hard work @dermotduffy!

<br></br>
