### ISSUE TITLE
aspect-ratio does not match image in Firefox

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#670]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** [release-4.0.0](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0)

**Last working release (if known):** v3.0.0

**Browser and Operating System:** only on Firefox

**Description of problem:**

With menu positioned outside image sides are cut off(image on the left).

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam
view:
  default: image
menu:
  style: outside
```

![image](https://user-images.githubusercontent.com/24360494/173207114-d1a2e8d0-797e-48ad-bac4-ca2beddc7306.png)

Adding 

```
dimensions:
  aspect_ratio_mode: unconstrained
```
fixes the issue in Firefox(image on the right).
