### ISSUE TITLE
card-mod DOM element keeps refreshing

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#678]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** [release-4.0.0](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0)

**Last working release (if known):** v3.0.0

**Browser and Operating System:** Chrome, Firefox, etc.

**Description of problem:**

Card-mod keeps updating very frequently, causes performance issues.

Card-mod version: 3.1.4

![Peek 2022-06-12 14-28](https://user-images.githubusercontent.com/24360494/173231179-a696d4ea-8eee-4005-8346-baf162998701.gif)

Minimal configuration to reproduce:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cam
card_mod:
  style:
    frigate-card-menu $: |
      div {
        font-size: 12px;
      }
```

**Comment by dermotduffy** [comment]
Suspect it's being updated on each HA state update.

Just to confirm: Is this actually causing you a performance issue, or this is just theoretically suboptiomal -- i.e. what are you noticing?

**Comment by peledzius** [comment]
> Just to confirm: Is this actually causing you a performance issue

Yes, it does.

> what are you noticing?

Look at this short gif below, I noticed that card becomes very laggy for me when card-mod gets reinjected every time.


![Peek 2022-06-14 01-09](https://user-images.githubusercontent.com/24360494/173454282-599dd236-8750-4674-908d-a20e73c67c79.gif)

**Comment by dermotduffy** [comment]
Would you mind trying https://github.com/dermotduffy/frigate-hass-card/pull/685 and see if that improves it?

**Comment by peledzius** [comment]
It's been a while, today I finally upgraded to v4.0.0 from v4.0.0-rc.2. Amazing as always! 

After upgrade I noticed that image view refresh causes flickering for elements with card-mod injection:

![Peek 2022-11-21 05-34](https://user-images.githubusercontent.com/24360494/202969344-e129d10a-9144-4818-9aa1-0918648311a4.gif)

I attempted to find which commit caused that. Findings - in v4.0.0-rc.3 it showed up first, then I narrowed it to this commit https://github.com/dermotduffy/frigate-hass-card/commit/c19a62d42621a6f9599ac3bbdc09e3d0acce36cf.

Basic configuration to reproduce:
(checked in Firefox and iOS HA app)

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.living_room_frigate
view:
  default: image
image:
  refresh_seconds: 2
  mode: camera
elements:
  - type: icon
    icon: mdi:thermometer
    title: Multisensor
    entity: sensor.living_room_multisensor_temperature
    style:
      top: 62px
      left: 35px
      font-weight: bold
      font-size: 16px
      color: rgb(153, 255, 153)
      background: rgba(67, 66, 62, 0.9)
      pointer-events: none
menu:
  style: outside
card_mod:
  style:
    frigate-card-elements $ hui-icon-element:
      $: |
        ha-icon[title="Multisensor"]::after {
          content: "{{ states('sensor.living_room_multisensor_temperature') }}°C";
        }
```
