### ISSUE TITLE
Elements should not scroll

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#729]

**Comment by peledzius** [comment]
I just installed rc-4.0.2. My elements with CSS `top` property got disorganized. I needed to adjust every element to make it look like before. Shouldn't this be a breaking change, what do you think?

**Comment by dermotduffy** [comment]
Maybe. Can you say a little more about what behavior you relied on before and what you need to change now?

**Comment by peledzius** [comment]
Before:

![image](https://user-images.githubusercontent.com/24360494/178164012-18e3a399-087f-45ac-b603-9d765d646cc3.png)

After: 

![image](https://user-images.githubusercontent.com/24360494/178164051-2add5103-9196-4b94-a36c-7c44b33d7689.png)

```
...

style:
  top: 10px
  left: 35px
  font-weight: bold
  font-size: 16px
  color: rgb(153, 255, 153)
  background: rgba(67, 66, 62, 0.9)
  pointer-events: none
```

I updated `top` property to 62px to make it look same as before.

I assume menu rendered below has similar problem.
