### ISSUE TITLE
Add support for single-click toggling menu entities

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#74]
As requested by @tbrausch in https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1312843

> I don't know if this is possible, but is there a chance that you could add another option per entity that would allow the default "click" option to toggle the state of the entity rather than displaying the more-info card? This would allow detection to be turned on and off with a single click. For example:

```yaml
webrtc:
  entity: camera.patio
entities:
  - entity: switch.frigate_patio_detect
    toggle: true
  - entity: binary_sensor.frigate_patio_person_motion
    show: false          
```
