### ISSUE TITLE
Support browser_mod fire-dom-event

### ISSUE THREAD

**Issue by totalitarian** [dermotduffy/frigate-hass-card#761]
Currently this card doesn't support browser_mod's `fire-dom-event` mentioned here

https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0

Here is an example config I have tried

```
live:
  lazy_load: false
  preload: true
  draggable: false
  auto_play: all
  actions:
    tap_action:
      action: fire-dom-event
      browser_mod:
        command: toast
        message: Hello, world!
```

and here is the error I get

```
invalid configuration: [ "live -> actions -> tap_action -> action", "live -> actions -> tap_action -> service", "live -> actions -> tap_action -> navigation_path", "live -> actions -> tap_action -> url_path", "live -> actions -> tap_action -> frigate_card_action", "live -> actions -> tap_action -> camera", "live -> actions -> tap_action -> media_player", "live -> actions -> tap_action -> media_player_action", "live -> actions -> tap_action" ]
type: custom:frigate-card
cameras:
  - camera_entity: camera.side
    live_provider: ha
menu:
  style: outside
  position: right
  alignment: bottom
  buttons:
    frigate:
      enabled: false
live:
  lazy_load: false
  preload: true
  draggable: false
  auto_play: all
  actions:
    tap_action:
      action: fire-dom-event
      browser_mod:
        command: toast
        message: Hello, world!
```
