### ISSUE TITLE
Live Always Loads

### ISSUE THREAD

**Issue by Danny2100** [dermotduffy/frigate-hass-card#765]
I am using `v4.0.0-rc.2`. 

Is it possible for the card to only load the live  feed of the camera when it is tapped to open full screen? Then show a snapshot of the camera that updates every 10 seconds? I tried using the view of the most recent snapshot but on mobile it's not actually visually appealing and there's no ability to click to live stream still to my knowledge.

The "on selection" doesn't work to prevent pre-loading when using single cards by themselves.  The reason I want to prevent pre-loading is that the Dashboard and I think even the web UI all together locks up as a result of trying to load 3 simultaneous streams. When I had these 3 cameras on the dashboard as seen in the screenshot preloading I repeatedly lost access to the UI for a few minutes on the companion app, browser and even through the nabucasa url. No errors in the logs as to where it came from. I removed the cameras and it was fine. It also slows the ability to edit the cards with them all live at once.

Mobile Dashboard:

![Screenshot_20220718-081224_Home Assistant](https://user-images.githubusercontent.com/47092714/179510194-bd033b33-9da9-4a58-90d1-01681bf638b2.jpg)

Using view most recent snapshot a circle appears that blocks the full image:
![Screenshot_20220718-081550_Home Assistant](https://user-images.githubusercontent.com/47092714/179510166-1af1548b-e91e-404e-bcd8-053a6de1fc54.jpg)

Current Code:

```
type: horizontal-stack
cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.outdoor_4
        live_provider: frigate-jsmpeg
    menu:
      style: none
    live:
      preload: true
      auto_play: visible
      draggable: false
      actions:
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: fullscreen
          - action: custom:frigate-card-action
            frigate_card_action: live
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '5:4'
    image:
      mode: camera
      refresh_seconds: 10
    view:
      default: live
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.outdoor_3
        live_provider: frigate-jsmpeg
    menu:
      style: none
    live:
      preload: true
      auto_play: visible
      draggable: false
      actions:
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: fullscreen
          - action: custom:frigate-card-action
            frigate_card_action: live
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '5:4'
    image:
      mode: camera
      refresh_seconds: 10
    view:
      default: live
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.outdoor_2
        live_provider: frigate-jsmpeg
    menu:
      style: none
    live:
      preload: true
      auto_play: visible
      draggable: false
      actions:
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: fullscreen
          - action: custom:frigate-card-action
            frigate_card_action: live
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '5:4'
    image:
      mode: camera
      refresh_seconds: 10
    view:
      default: live
```

**Comment by dermotduffy** [comment]
I'm afraid I'm not quite following the feature request -- maybe you could try describing what behavior you'd like to see?

From your description, I don't understand why just using the `image` view as the default view is not the answer -- you already have it refreshing every 10 seconds. Having that as your default view would mean the streams don't load, but you still get a somewhat refreshed feed -- which sounds like what you want. You can also just use the live menu button when you want to load the streams, or configure a [Card Action](https://github.com/dermotduffy/frigate-hass-card#triggering-card-actions) if you wanted to make that a little more convenient (e.g. double tapping on the image could take change to the live stream, etc).

**Comment by dermotduffy** [comment]
This will disable the circles that go to the next/previous snapshot or clip in the media viewer:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.back_yard
media_viewer:
  controls:
    next_previous:
      style: none
```

You can navigate to the next/previous snapshot by dragging the carousel. Is this what you're looking for?

**Comment by dermotduffy** [comment]
* You are incorrectly listing the actions under `live`, when you want them to work when you're in the media viewer (not live).
* Setting `thumbnails -> mode` to `none` will cause the thumbnail drawer to disappear (the 3 lines).

This is what the `media_viewer` section should look like:

```yaml
media_viewer:
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: none
  actions:
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: live
      - action: custom:frigate-card-action
        frigate_card_action: fullscreen
```

I can't easily exactly test your config, but here is the full version that I'd guess should work:

```yaml
type: horizontal-stack
cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.outdoor_4
        live_provider: frigate-jsmpeg
    menu:
      style: none
    live:
      preload: false
      auto_play: never
      draggable: false
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '5:4'
    image:
      mode: camera
      refresh_seconds: 10
    view:
      default: snapshot
    media_viewer:
      controls:
        next_previous:
          style: none
        thumbnails:
          mode: none
      actions:
        tap_action:
          - action: custom:frigate-card-action
            frigate_card_action: live
          - action: custom:frigate-card-action
            frigate_card_action: fullscreen
```

**Comment by dermotduffy** [comment]
> That worked!! Is there anyway to remove the whitespace between the camera view and edge of card? I tried messing with the aspect ratios and it didn't work.

Not sure what whitespace you are referring to. Can you take a screenshot/photo and highlight the whitespace you mean?

> Also it's not a huge deal but is there a way after closing the full screen view to stop live? It will stop after stopping the companion app and when I reopen it's back to Snapshot but would be nice to make sure it stops when it's closed as well without having to stop the companion app and reopen it.

There's no way to trigger an action based on when fullscreen mode _exits_ (which I think is what you're asking). I have a few ideas though you could experiment with:

* One simple suggestion is to give a timeout after which the card reverts to snapshot mode, e.g. the below would go back to snapshot mode 30 seconds after human interaction with the card stops:

```yaml
view:
  default: snapshot
  timeout_seconds: 30
```

* Another hackier way could be to add an action handler on the live view, so if it's tapped it goes back to snapshot.

* A final fancier way would be to configure a custom element on the card that shows a button when the card is in the live view and in fullscreen mode, that when clicked exits fullscreen mode and changes the view back to snapshot. This still wouldn't help if the user exits fullscreen mode in a different way (e.g. hitting Escape on the keyboard). See the 'Elements section (stock Home Assistant elements)' section in the  [documentation](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#illustrative-expanded-configuration-reference) if you're not familiar with configuring elements.

**Comment by dermotduffy** [comment]
You're forcing the aspect_ratio, just remove this section from your config and by default the card will adapt to the size of the media:

Remove this:

```yaml
    dimensions:
      aspect_ratio_mode: static
      aspect_ratio: '5:4'
```

If this still doesn't work, it's possible the fact you have this in a horizontal stack is causing it to be a fixed size, try it without the stack to see if that works? (And if it does, well, seems like the issue is more with the stack than the Frigate card).
