### ISSUE TITLE
Update documentation regarding `webrtc_card` running in the background

### ISSUE THREAD

**Issue by totalitarian** [dermotduffy/frigate-hass-card#766]
HI, love this card but i'm struggling with an issue. As per the docs

<html>
<body>

Whether or not to preload the live view. Preloading causes the live view to render in the background regardless of what view is actually shown, so it's instantly available when requested. This consumes additional network/CPU resources continually.
--

</body>
</html>

When the page loads, I can see the spinner and then the camera feed appears, but i'm finding that when I switch to another tab and back, the camera view loads again. It's as if the camera is being unloaded when switching tabs. Any idea what i'm doing wrong?

```
type: custom:frigate-card
cameras:
  - live_provider: auto
    camera_entity: camera.doorbell_main_proxy
    frigate:
      camera_name: doorbell
    webrtc_card:
      entity: camera.doorbell_main_proxy
menu:
  style: outside
  position: right
  alignment: bottom
  buttons:
    frigate:
      enabled: false
    media_player:
      enabled: false
live:
  draggable: false
  auto_play: all
  lazy_load: false
  preload: true
timeline:
  media: clips
  show_recordings: true
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '3:4'

```

**Comment by dermotduffy** [comment]
Hi @totalitarian , thanks for the feedback. I dug into this a little: at first I couldn't reproduce it, but if I use a WebRTC card camera then I can. The Frigate card "embeds" the WebRTC card, so whatever behavior that card uses underneath is a little opaque to the Frigate card -- this is one instance where surprise can occur. By default the WebRTC card won't allow streams to persist in the background, to enable that you need to pass the right option through.

When I use this it works:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.back_yard
    live_provider: webrtc-card
    webrtc_card:
      entity: camera.back_yard_rtsp
live:
  webrtc_card:
    background: true
```

The last line is the key one.
