### ISSUE TITLE
Support for "elements" like "picture-elements" card

### ISSUE THREAD

**Issue by dougmaitelli** [dermotduffy/frigate-hass-card#77]
I currently have a "custom card" I made using the picture-elements card that displays the camera feed and has buttons for moving the camera PTZ.
Would be nice to support an "elements" in this Frigate card as well so people could implement their own customizations, like this one.

**Comment by dermotduffy** [comment]
I can absolutely see why this would be nice. I fear reproducing the versatility of [the picture elements card](https://www.home-assistant.io/lovelace/picture-elements/) would be a huge amount of work, as it has a large array of options/modes that would need to be recreated.

Perhaps there's an more barebones set of functionality though...

**Comment by dermotduffy** [comment]
@dougmaitelli would you mind pasting your elements configuration so I can see what the minimum is that would work for your usecase? Still trying to see if this, or part of it, is worth the fairly large effort it would take to make this work ...

**Comment by dougmaitelli** [comment]
Hey @dermotduffy

This is what I have for my picture-elements:
```
type: picture-elements
camera_image: camera.{{ camera }}
camera_view: live
elements:
  - type: icon
    icon: 'mdi:arrow-up'
    style:
      background: 'rgba(255, 255, 255, 0.25)'
      right: 25px
      bottom: 50px
    tap_action:
      action: call-service
      service: amcrest.ptz_control
      service_data:
        entity_id: camera.amc_{{ camera }}
        movement: up
  - type: icon
    icon: 'mdi:arrow-down'
    style:
      background: 'rgba(255, 255, 255, 0.25)'
      right: 25px
      bottom: 0px
    tap_action:
      action: call-service
      service: amcrest.ptz_control
      service_data:
        entity_id: camera.amc_{{ camera }}
        movement: down
  - type: icon
    icon: 'mdi:arrow-left'
    style:
      background: 'rgba(255, 255, 255, 0.25)'
      right: 50px
      bottom: 25px
    tap_action:
      action: call-service
      service: amcrest.ptz_control
      service_data:
        entity_id: camera.amc_{{ camera }}
        movement: left
  - type: icon
    icon: 'mdi:arrow-right'
    style:
      background: 'rgba(255, 255, 255, 0.25)'
      right: 0px
      bottom: 25px
    tap_action:
      action: call-service
      service: amcrest.ptz_control
      service_data:
        entity_id: camera.amc_{{ camera }}
        movement: right
  - type: icon
    icon: 'mdi:magnify'
    style:
      background: 'rgba(255, 255, 255, 0.25)'
      right: 25px
      bottom: 25px
    tap_action:
      action: call-service
      service: amcrest.ptz_control
      service_data:
        entity_id: camera.amc_{{ camera }}
        movement: zoom_in
    hold_action:
      action: call-service
      service: amcrest.ptz_control
      service_data:
        entity_id: camera.amc_{{ camera }}
        movement: zoom_out
```

Important part is basically custom icons that can call a service. And in my case I have the custom position for these buttons using the custom style.
