### ISSUE TITLE
Title parameter has no effect on state-badge

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#772]
I am trying to display several state-badges without a label beneath them.  Added an element of type state-badge but cannot override the displayed title.  It still displays as the default title "Processor Use".  

```
    elements:
      - type: state-badge
        entity: sensor.processor_use
        style:
          left: 760px
          top: 50px
        title: ""

```
Your example seems to indicate that this should work:

```
elements:
  - type: state-badge
    entity: sensor.kitchen_dining_multisensor_air_temperature
    style:
      left: 100px
      top: 50px
    title: "Temperature"
```
