### ISSUE TITLE
Conflicting information?

### ISSUE THREAD

**Issue by ragenhe** [dermotduffy/frigate-hass-card#81]
I figured I might as well learn HACs and install the frigate-hass-card using it.

I have HACs installed and working.  Not the same results so far on the card.

When installation is complete, this information is presented:

``` When installed, this will be located in '/config/www/community/frigate-hass-card' ```

But the instruction, give this information to add to HA configuration file:
```
lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
```
Should it be the above, or this:
```
lovelace:
  resources:
    - url: /config/www/community/frigate-hass-card/frigate-hass-card.js
      type: module
```
Once this is done, as it should be, I should then see the "frigate" card available to add?
