### ISSUE TITLE
High CPU Usage on Wall tablets and older PCs with 7 cam's

### ISSUE THREAD

**Issue by S-Przybylski** [dermotduffy/frigate-hass-card#821]
Question: Is there any improvement possible to speed up 7 parallel used cards on a wall tablet?

I use the Lovelace card for longer time now. I am impressed about the improvements of the project! The last beta release maybe the last two (i am not sure), i realize massive hangs on my Samsung T-500 tablets, which is used as a dashboard (Kiosk Browser).
Currently I present 7 cam's one one dashboard. 
If I choose the Home Assistant picture-elements card (camera_image), it runs smoothly. If I change all 7 cards to the frigate-hass-card, it slow down the whole tablet. I use the HA android app and Kiosk Browser - both seems to be the same.

**Comment by dermotduffy** [comment]
Can you provide your card version and config?

**Comment by dermotduffy** [comment]
Also: what you're doing in the card when it slows down.

Thanks!

**Comment by luzik** [comment]
I have also issue with browser performance. I have only one camera, but it get slower and slower day by day. I also monitor my serwer upload, and I noticed that switching view do not end video stream (browser refresh do). Switching back to view with frigate-card restart stream, so there is no need for background stream. I am using V3.0.0.
How can I debug memory/cpu usage of frigate-card ?


```
type: custom:frigate-card
cameras:
  - camera_entity: camera.wejscie
    webrtc: {}
    live_provider: frigate-jsmpeg
menu:
  buttons:
    snapshots: false
    image: false
live:
  controls:
    thumbnails:
      mode: none
  actions:
    device_id: cd69c6a3a5b899f01581a261181f68cf
    tap_action:
      action: call-service
      service: dahua.vto_open_door
      service_data:
        device_id: cd69c6a3a5b899f01581a261181f68cf
  draggable: false
event_viewer:
  draggable: false
event_gallery:
  min_columns: 5
```

**Comment by dermotduffy** [comment]
@luzik Can you try upgrading to [v4](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.3)? Performance hasn't personally been an issue for me so I'm certainly not promising it'll be better for you, but the code is substantially different so we need to check if this is still an issue. There's a relationship between the Frigate backend server, the integration and the card -- they all have pre-release versions and will all shortly be released together. You'd need to upgrade all three.

If performance is still an issue, please describe what you're doing at the time / how you see the performance issue, so I can try to replicate.

> I also monitor my serwer upload, and I noticed that switching view do not end video stream (browser refresh do). 

What do you mean by 'switching view' here?

In the v4 card, you can configure [when the card will unload your stream](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#live-options). Some users prefer to keep the stream running, so it is available "instantly", some want the opposite -- so the card tries to be configurable for things like this.

**Comment by luzik** [comment]
Switching view ..I am using dashboards views (like tabs in menu), so when I switch to view without frigate-card, stream seems to be running in background (even i do not watch it), but when I goes back to view with frigate-card it reload the stream, so if it was background stream to 'instantly' show on card it do not work.

Ok, I will update and let you know.

**Comment by luzik** [comment]
It looks much better under v4. Switching view out of frigate-card do end streaming, so no more background bandwidth/resources will be eaten when no video on screen! I will test performance on my wall-tablet in a long run. Give me few days..

My extra observations:
- JSMpeg shows almost instant when switching to view with frigate-card, home-assistant provider need extra 2 seconds (
- JSMpeg is ~1.5 seconds behind home-assistant live provider
- preload seems do not change anything when use with home-assistant live provider (camera is frontend_stream_type: web_rtc)

**Comment by S-Przybylski** [comment]
I use 
- Frigate v11 rc2 on rapi4 64bit
- HA 2022-09-2 (on Synology NAS)
- Frigate integration version 3 rc4
- Frigate card version 4 rc3
The dashboard uses grid to position all cams besides other buttons, etc...
Attached is one configuration as an example - all others are similar:
````
type: custom:frigate-card
live:
  preload: true
  controls:
    title:
      mode: none
    next_previous:
      style: none
view:
  timeout_seconds: 30
camera_view: live
elements:
  - type: conditional
    conditions:
      - entity: binary_sensor.cam1_person_occupancy
        state: 'on'
    elements:
      - type: icon
        icon: hass:none
        entity: binary_sensor.cam1_person_occupancy
        style:
          top: 0%
          left: 0%
          right: 0%
          bottom: 0%
          color: rgb(254, 65, 78)
          opacity: 1
          transform: none
          border: solid
          border-width: 8px
          border-color: rgb(255, 65, 78)
      - type: icon
        icon: hass:run
        entity: binary_sensor.cam1_person_occupancy
        style:
          bottom: 2%
          right: 2%
          color: rgb(254, 0, 0)
          opacity: 0.8
          transform: none
  - type: state-label
    entity: sensor.temperature
    style:
      bottom: 20%
      right: 68%
      transform: none
      color: rgb(0, 0, 0)
      font-family: Trebuchet MS
      font-size: 150%
      opacity: 1
  - type: state-label
    prefix: 'pm2.5: '
    entity: sensor.ld_pm2_5
    style:
      bottom: 0%
      right: 66%
      transform: none
      color: rgb(0, 0, 0)
      font-family: Trebuchet MS
      font-size: 130%
      opacity: 1
  - type: state-label
    prefix: 'pm10: '
    entity: sensor.ld_pm10
    style:
      bottom: 10%
      right: 66%
      transform: none
      color: rgb(0, 0, 0)
      font-family: Trebuchet MS
      font-size: 130%
      opacity: 1
  - type: state-badge
    entity: sensor.power
    style:
      top: 20%
      left: 17%
  - type: state-badge
    entity: sensor.pv
    style:
      top: 55%
      left: 17%
menu:
  style: hidden
  position: top
cameras:
  - camera_entity: camera.cam1
    live_provider: ha
````

**Comment by dermotduffy** [comment]
@S-Przybylski That's a fairly basic configuration. Can you comment on what you're doing when you observe the 'performance issue', and what you see specifically?

@luzik 

> JSMpeg shows almost instant when switching to view with frigate-card, home-assistant provider need extra 2 seconds (

What do you see during those 2 seconds? Do you see the same issue when using a picture glance card? [My theory is you will]

BTW: Check out the `show_image_during_load` [option](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#live-options) which might visually make this appear more instantaneous.

> JSMpeg is ~1.5 seconds behind home-assistant live provider

You are probably using the 'native' HA WebRTC support for streaming (otherwise JSMPEG would be significantly lower latency), in which case this latency difference is to be expected: https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#available-live-providers

> preload seems do not change anything when use with home-assistant live provider (camera is frontend_stream_type: web_rtc)

Preload behavior is independent of the live provider choice (it's really just rendering the live view hidden and then unhiding it). Once enabled, it should mean the live view (except initial load) will be instantaneous. Is this not what you see? Any chance you can capture a video showing what you see if not this?

**Comment by S-Przybylski** [comment]
I made different experiences from time to time: I do not have the same slow reaction all the time. Some times it's about less then 2-3 seconds. Sometimes it took 10 sec. to see some reaction. Some times i noticed that the cam's are delayed:
- If i navigate to a different dashboard card/sheet this takes from one to 10 seconds at least. 
- Also i noticed if i switch back to the initial dashboad card which includes all cam's using the frigate custom card, this takes 2-4 sec to display all details. 

If I compare a picture-card with frigate custom card the custom card: The custom card needs more time to initialize and display the live picture +1-2 seconds ).

I seldom use the custom card features, like looking into the detection history (e.g. person), etc.

I am going to experiment with different dashboard setups in the next days...

Btw: Do you have problems with modifiing the aspect ratio if embedded into GRIDs?
I have two Dahua cams with a different aspect ratio, that need to be aligned. ...

**Comment by S-Przybylski** [comment]
Today I renamed my media folder within frigate and created an empty one. Now it's much faster and responsive again. It seems that it have something to do with the amount of snapshots and detections of all 7 cam's I believe.

Other Question: One one camera i see "Live: cam5" for a while. But I do not understand what is different to other cams configuration. Do I oversee something?

**Comment by luzik** [comment]
Ok, few more tests done.
My last observation was done from internet with slow bandwidth. Running same test via LAN was smooth for both cases (with JSMpeg 1sec behind HA provider). So with slow connection HA provider need extra time to load because of its amount of data (no problem). While loading HA stream (those 2 seconds), there was a spining circle. I have connected go2rtc using RTSPtoWebRTC integration, I do not have AlexxIT's WebRTC Card. While using HA provider I believe that HA is using WebRTC from go2rtc.

New observations :)
1. When I switch provider to "webrtc-card" ( I do not have any webrtc-card installed) stream shows fast, but it have very low frame rate ..about 1fps (while JSMpeg have ~4fps, and HA is smooth).
2. I configured view with 3 frigate-cards, same camera, 3 different live providers. Under my macOS (checked safari and chromium) everything is fine, but under my slower wall android tablet, there is strange behavior: after reloading browser URL switching first time to view with frigate-cards shows all 3 streams, but after switching to other view and then back - only two appears - HA provider circle is rotating and need extra time to load. So I've checked JS logs and found:

```
Unhandled Promise Rejection: AbortError: The operation was aborted.
(anonimowa funkcja)
rejectPromise
(anonimowa funkcja) — ha-web-rtc-player.ts:56
https://local.ha.klawy.net:1238/api/camera_proxy/camera.imou_profile000?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkODg3NWVhOWFhNDY0NTE3OGZiOTY0N2U1MjFhMTJlMyIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuaW1vdV9wcm9maWxlMDAwIiwicGFyYW1zIjp7fSwiaWF0IjoxNjYzNDQzMzE0LCJleHAiOjE2NjM0NDMzNDR9.Gn39zjl66Aom6TUnd31aw6al4lhY98IwtRchBgcjfTY&width=1344&height=756
```

and


```
[Error] There are too many active WebGL contexts on this page, the oldest context will be lost.
	getContext
	t (frigate-hass-card.js:276:85810)
	t (frigate-hass-card.js:276:149565)
	(anonimowa funkcja) (frigate-hass-card.js:276:33664)
	t (frigate-hass-card.js:276:33205)
	(anonimowa funkcja) (frigate-hass-card.js:558:53643)
	Promise
	(anonimowa funkcja) (frigate-hass-card.js:558:53595)
	asyncFunctionResume
	(anonimowa funkcja) (frigate-hass-card.js:558:54868)
	asyncFunctionResume
	(anonimowa funkcja)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] WebGL: INVALID_OPERATION: loseContext: context already lost
	getContext
	t (frigate-hass-card.js:276:85810)
	t (frigate-hass-card.js:276:149565)
	(anonimowa funkcja) (frigate-hass-card.js:276:33664)
	t (frigate-hass-card.js:276:33205)
	(anonimowa funkcja) (frigate-hass-card.js:558:53643)
	Promise
	(anonimowa funkcja) (frigate-hass-card.js:558:53595)
	asyncFunctionResume
	(anonimowa funkcja) (frigate-hass-card.js:558:54868)
	asyncFunctionResume
	(anonimowa funkcja)
	promiseReactionJobWithoutPromise
	promiseReactionJob

```

BTW ..how to hide and not to load any events from frigate ? (I mean I want to reduce resource load, not only hide it)

**Comment by dermotduffy** [comment]
> 1. When I switch provider to "webrtc-card" ( I do not have any webrtc-card installed)

Hmm. I'm not sure how this works at all. `webrtc-card` just embeds AlexxIT's card, so if you don't have that installed I'd expect it to not render anything useful at all honestly. Perhaps use the devtools inspector to see what is actually playing the video stream you're seeing in this case?

> 2. [Tablet example]

`[Error] There are too many active WebGL contexts on this page, the oldest context will be lost.`

There is a known issue with Android webview, see this [FAQ entry](https://github.com/dermotduffy/frigate-hass-card#android-will-not-render-4-jsmpeg-live-views) . Sometimes it takes a while to free up a previously used context, so this could explain the exception -- but it's very unlikely that is related to the slow loading of the HA provider.

> HA provider circle is rotating and need extra time to load.

So it does eventually load, just slow? If you use a picture glance card in this same 3-card configuration, do you get the same behavior or different?

> BTW ..how to hide and not to load any events from frigate ? (I mean I want to reduce resource load, not only hide it)

In which view? For the media viewer or live view, just disable the thumbnails display and it should not fetch events, e.g. something like this should do it for the live view:

```
live:
  controls:
    thumbnails:
      mode: none
```
