### ISSUE TITLE
Changing from fullscreen mode back to static aspect ratio does not work correctly

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#830]
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.landing
  - camera_entity: camera.living_room
  - camera_entity: camera.sitting_room
view:
  default: live
  timeout_seconds: 300
  update_seconds: 5
  update_force: false
  actions:
    double_tap_action:
      action: custom:frigate-card-action
      frigate_card_action: fullscreen
live:
  layout:
    fit: cover
  controls:
    thumbnails:
      mode: none
    title:
      mode: none
overrides:
  - conditions:
      fullscreen: true
    overrides:
      live:
        layout:
          fit: contain
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '9:16'
```
