### ISSUE TITLE
Cannot override layout.position

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#834]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 4.0.0

**Last working release (if known):** N/A

**Browser and Operating System:** N/A

**Description of problem:**

By default I want my card to have the following position:

```yaml
layout:
  fit: cover
  position:
    x: 0
    'y': 0
```

But when in full screen, I want:

```yaml
layout:
  fit: contain
  position:
    x: null
    'y': null
```

But the validation does not let me proceed:

https://user-images.githubusercontent.com/29582865/191889202-06f8b2d4-3418-49d9-8800-2e3f4ca7c39e.mp4

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

N/A
