### ISSUE TITLE
Allow to override settings when the card is being displayed in PiP mode

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#853]
**Is your feature request related to a problem? Please describe.**
When in PiP mode (see the video below for clarification), I would like to change the menu style to `hover` instead of my predefined `overlay` for full-screen videos.

**Describe the solution you'd like**
Something like below:

```yaml
type: custom:frigate-card
menu:
  style: outside
overrides:
  - conditions:
      fullscreen: true
    overrides:
      menu:
        style: overlay
  - conditions:
      pip: true
    overrides:
      menu:
        style: hover
```

**Describe alternatives you've considered**
To set `hover` while in full-screen. That isn't perfect for me, since I find `overlay` the best option for full-screen.

**Additional context**

https://user-images.githubusercontent.com/29582865/193464939-685a9d8a-7d40-48c2-9311-527bd3b81181.mp4
