### ISSUE TITLE
Allow to override settings depending on orientation while in full-screen mode

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#854]
**Is your feature request related to a problem? Please describe.**
All my cameras have a 16:9 aspect ratio. It means that when displayed in a vertical screen, there will be always black bars (since I've chosen the "contain" layout for it), therefore, there is extra room to keep the menu style as `overlay`. However, when displaying in a landscape orientation, there isn't extra room, so I'd like to change the menu style to `hover`.

**Describe the solution you'd like**
Something like:

```yaml
type: custom:frigate-card
menu:
  style: outside
overrides:
  - conditions:
      fullscreen: true
      orientation: portrait
    overrides:
      menu:
        style: overlay
  - conditions:
      fullscreen: true
      orientation: landscape
    overrides:
      menu:
        style: hover
```

**Describe alternatives you've considered**
To use `overlay` always, or `hover` always.

**Additional context**
Nothing.
