### ISSUE TITLE
Unable to play event clips

### ISSUE THREAD

**Issue by Morphy99** [dermotduffy/frigate-hass-card#873]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
v4.0.0
**Last working release (if known):**

**Browser and Operating System:**
Win 7 Chrome, iPad OS

**Description of problem:**

Trying to load latest events results in "Timeout while starting stream. [Check troubleshooting]"

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
* Please hold down your Frigate menu button and paste the diagnostics here.
* Please check your Home Assistant log file for any exceptions.
* Please check your Frigate log file for any exceptions.

This is rarely an issue with the card, and more likely something going wrong on the HA or Frigate side.

**Comment by Morphy99** [comment]
I've checked both logs before as I suspected that too but it does seem something with the cards. I've just tried it on a new dashboard with just basic options and it works OK, so I suspect something with my card options:

```
type: vertical-stack
cards:
  - camera_view: auto
    type: picture-glance
    title: Tap to open Live view
    entities:
      - entity: camera.drive
    camera_image: camera.drive
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.drive
    view:
      default: clips
    menu:
      style: outside
      buttons:
        frigate:
          enabled: true
        cameras:
          enabled: false
        live:
          enabled: false
        clips:
          enabled: false
        snapshots:
          enabled: false
        image:
          enabled: false
        timeline:
          enabled: false
    media_viewer:
      auto_play: all
      auto_pause: hidden
      controls:
        next_previous:
          style: none
        thumbnails:
          mode: below
        title:
          mode: popup-bottom-right
      layout:
        fit: contain
      lazy_load: false
      transition_effect: slide
      draggable: false
    timeline:
      controls:
        thumbnails:
          mode: below
    event_gallery:
      controls:
        thumbnails:
          show_timeline_control: false
          size: 175
```
Diagnostics:

```
{
  "ha_version": "2022.10.3",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
  "date": "2022-10-15T20:46:40.623Z",
  "frigate_version": {
    "51b3a55097281cdd4b3a544841a236d1": "3.0.0/0.11.1-2eada21"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.drive"
      }
    ],
    "view": {
      "default": "clips"
    },
    "menu": {
      "style": "outside",
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        },
        "live": {
          "enabled": false
        },
        "clips": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "image": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        }
      }
    },
    "media_viewer": {
      "auto_play": "all",
      "auto_pause": "hidden",
      "controls": {
        "next_previous": {
          "style": "none"
        },
        "thumbnails": {
          "mode": "below"
        },
        "title": {
          "mode": "popup-bottom-right"
        }
      },
      "layout": {
        "fit": "contain"
      },
      "lazy_load": false,
      "transition_effect": "slide",
      "draggable": false
    },
    "timeline": {
      "controls": {
        "thumbnails": {
          "mode": "below"
        }
      }
    },
    "event_gallery": {
      "controls": {
        "thumbnails": {
          "show_timeline_control": false,
          "size": 175
        }
      }
    }
  }
}
```
