### ISSUE TITLE
auto_play: never not working with ha Live Provider

### ISSUE THREAD

**Issue by Morphy99** [dermotduffy/frigate-hass-card#874]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v4
**Last working release (if known):**

**Browser and Operating System:**
Win7 Chrome x64 

I was looking to use the frigate live view card instead of picture-glance however the stream buffers upon the page loading despite these settings:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.drive
    triggers:
      occupancy: false
live:
  auto_play: never
  lazy_load: true
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: none
  draggable: false
  auto_pause: all
view:
  default: live
```

The result is a buffering live stream which is what I don't want:
![image](https://user-images.githubusercontent.com/5853979/196025949-7d75eb92-986b-4b41-99b1-cc61703eb692.png)

I'm not sure why it always starts at 21 seconds as well, it doesn't take that long to load the stream.

I also had to disable play on occupancy option to stop it from playing but this doesn't stop it buffering:
    triggers:
      occupancy: false
Maybe this should be disabled by default?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
I've found Chrome can be over-eager with autoplaying, could this be the issue: https://github.com/dermotduffy/frigate-hass-card#chrome-autoplays-when-a-tab-becomes-visible-again

It would help to describe what behavior you're looking for? Why load live unless you actually want it to play? If you're just looking for an image of what live is, try the `image` view?

**Comment by Morphy99** [comment]
> I've found Chrome can be over-eager with autoplaying, could this be the issue: https://github.com/dermotduffy/frigate-hass-card#chrome-autoplays-when-a-tab-becomes-visible-again

I'm not sure it is that. I'm refreshing the page and the live stream just starts buffering. 

> It would help to describe what behavior you're looking for? Why load live unless you actually want it to play? If you're just looking for an image of what live is, try the `image` view?

Behaviour like picture glance but with options like the menu which Frigate offers was what I was aiming for. The camera streams are high-ish res and loading this up along with event thumbnails is quite taxing, especially on mobile data. Picture glance is ideal, as it gives a frame every ten seconds and if I want to see the stream I just tap on it.

It's no big deal though, I can cope with Picture Glance for now, I just thought I'd log the behaviour as it doesn't seem what is intended by the auto_play setting.

**Comment by dermotduffy** [comment]
> I'm not sure it is that. I'm refreshing the page and the live stream just starts buffering.

Buffering, or playing? Buffering of a live stream is expected. Playing is not expected (if `never` is specified).

> Behaviour like picture glance but with options like the menu which Frigate offers was what I was aiming for. The camera streams are high-ish res and loading this up along with event thumbnails is quite taxing, especially on mobile data. Picture glance is ideal, as it gives a frame every ten seconds and if I want to see the stream I just tap on it.

How is this different from the image view? Try this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.drive
    triggers:
      occupancy: false
live:
  auto_play: never
  lazy_load: true
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: none
  draggable: false
  auto_pause: all
image:
  refresh_seconds: 10
  mode: camera
view:
  default: image
```
