### ISSUE TITLE
Help with config for PTZ Camera

### ISSUE THREAD

**Issue by jokerigno** [dermotduffy/frigate-hass-card#876]
Hi,

I have a Foscam Cam that has PTZ functionality.

I tried to config a home assistand card but I need support:

This is what I've done so far:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.cameretta
    live_provider: auto
elements:
  - type: custom:frigate-card-conditional
    conditions:
      mediaLoaded: true
      view:
        - live
        - image
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 180px
        service: foscam.ptz
        data_left:
          cmd: left
        data_right:
          cmd: right
        data_up:
          cmd: up
        data_down:
          cmd: down
```
Thank you in advance

**Comment by dermotduffy** [comment]
Would you mind clarifying what is not working? That configuration works fine for me (i.e. I see the PTZ control rendered correctly).

If the issue is that the service calls (when you click the buttons) don't actually move the camera, I'm afraid that's not related to the card and is something you should ask to the provider of the camera integration you are using. My suggestion in that case is to play with `Developer Tool` -> `Services` (in HA) until you can manually call the relevant service successfully (which depends on the camera/integration), and then when you can make the camera move that way, just re-use the parameters in the card configuration. This takes the card out of the way until you confidently move the camera.

If it's some other issue, let me know. Thanks!

**Comment by jokerigno** [comment]
Hi, well yes the issue is that the service call doesn't work...

I know that the service is correct because this configuration (that use the same call) works as expected.
```

type: picture-elements
image: camera.cameretta
camera_image: camera.cameretta
camera_view: live
elements:
  - type: icon
    icon: mdi:arrow-up
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 25px
      bottom: 50px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: up
  - type: icon
    icon: mdi:arrow-down
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 25px
      bottom: 0px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: down
  - type: icon
    icon: mdi:arrow-left
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 50px
      bottom: 25px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: left
  - type: icon
    icon: mdi:arrow-right
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 0px
      bottom: 25px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: right
  - type: icon
    icon: mdi:arrow-top-left
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 50px
      bottom: 50px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: top_left
  - type: icon
    icon: mdi:arrow-top-right
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 0px
      bottom: 50px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: top_right
  - type: icon
    icon: mdi:arrow-bottom-left
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 50px
      bottom: 0px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: bottom_left
  - type: icon
    icon: mdi:arrow-bottom-right
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 0px
      bottom: 0px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.foscam1
        movement: bottom_right
```

**Comment by dermotduffy** [comment]
[Quick reply from mobile] I notice you are not passing the `entity_id` in the service calls using the Frigate card, but are in the picture glance card ...

**Comment by jokerigno** [comment]
Hi, any update?

**Comment by dermotduffy** [comment]
I already replied: https://github.com/dermotduffy/frigate-hass-card/issues/876#issuecomment-1282892952

I think this is a configuration issue on your end.

**Comment by jokerigno** [comment]
Well I think also that I miss something in the config. 
I opened this issue because in the parameters for the custom:frigate-card-ptz there's no example on how to create a card so I'm doing trials and errors...

Below a new tentative adding entity ID on both action and data, and using the correct data (movement). Now I don't see the error when call a service but still camera does not move:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.cameretta
    live_provider: auto
elements:
  - type: custom:frigate-card-conditional
    conditions:
      mediaLoaded: true
      view:
        - live
        - image
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 180px
        actions_left:
          service: foscam.ptz
          entity_id: camera.foscam1
        data_left:
          movement: left
          entity_id: camera.foscam1
        actions_right:
          service: foscam.ptz
          entity_id: camera.foscam1
        data_right:
          movement: right
          entity_id: camera.foscam1
        actions_up:
          service: foscam.ptz
          entity_id: camera.foscam1
        data_up:
          movement: up
          entity_id: camera.foscam1
        actions_down:
          service: foscam.ptz
          entity_id: camera.foscam1
        data_down:
          movement: down
          entity_id: camera.foscam1
```

**Comment by jokerigno** [comment]
I tried a bit.

Below the config the works for future reference:
```

type: custom:frigate-card
cameras:
  - camera_entity: camera.cameretta
    live_provider: auto
elements:
  - type: custom:frigate-card-conditional
    conditions:
      mediaLoaded: true
      view:
        - live
        - image
    elements:
      - type: custom:frigate-card-ptz
        orientation: horizontal
        style:
          transform: none
          right: 20px
          top: 180px
        service: foscam.ptz
        data_left:
          movement: left
          entity_id: camera.foscam1
        data_right:
          movement: right
          entity_id: camera.foscam1
        data_up:
          movement: up
          entity_id: camera.foscam1
        data_down:
          movement: down
          entity_id: camera.foscam1
```
