### ISSUE TITLE
Pinch to Zoom not working in Android Companion App in Fullscreen mode

### ISSUE THREAD

**Issue by Daniel-dev22** [dermotduffy/frigate-hass-card#883]
I can zoom in on anything else in the companion app including the frigate camera page through the iframe panel. 

I can't zoom in if I tap for full screen using the frigate card.

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorbell
    live_provider: frigate-jsmpeg
menu:
  style: none
live:
  preload: false
  auto_play: never
  draggable: false
  actions:
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: image
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '5:4'
image:
  mode: camera
  refresh_seconds: 5
view:
  default: image
  timeout_seconds: 90
  actions:
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: live
      - action: custom:frigate-card-action
        frigate_card_action: fullscreen
media_viewer:
  controls:
    next_previous:
      style: none
    thumbnails:
      mode: none
  actions:
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: live
      - action: custom:frigate-card-action
        frigate_card_action: fullscreen
```

On a separate note are there any plans to add the capability to do digital zoom right now it sort of just expands the image but clarity doesn't necessarily increase or is that Simply because I'm using jsmpeg and not a full resolution stream, with go2rtc full resolution if I pinch to Zoom I would actually see more given the higher resolution available?  

I think blue iris does at least .5x digital zoom for example. I have blue iris as well and it is nice to be able to zoom in this much. 

![Screenshot_20221020-184847_Chrome](https://user-images.githubusercontent.com/47092714/197187939-1427c5f3-72df-4779-aa2f-135be288e324.jpg)
