### ISSUE TITLE
Live feed not refreshing after leaving camera dashboard view and then returning

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#887]
**Checklist:**

- ✅ I updated to the latest version available
- ✅ I cleared the cache of my browser

**Release with the issue:**
release-4.1.0

**Last working release (if known):**
n/a
**Browser and Operating System:**
Firefox 106.0.3 - macOS Ventura

**Description of problem:**

I've noticed a bug where the live feed won't refresh when I return to my main dashboard after being on a different page within Home Assistant. I've taken a video to show. 

The live feed refreshes automatically any time that I return to the Home Assistant **tab** within my browser. However any time that I spend some time on a different page/dashboard within Home Assistant (HACS/other views etc), when I return to my camera dashboard only the still image loads. Even if I leave it for a while to refresh the live feed, it doesn't. 

https://user-images.githubusercontent.com/57415184/199532863-2233a53a-cbc2-4005-ac24-2409d9a2b10b.mov

_So that you can differentiate; my still image has black bars down the sides - the live feed doesn't. Once I refresh the entire tab, you can see the live feed works again._ 

**Javascript errors shown in the web inspector (if applicable):**

```
n/a
```

**Card config:**

```
type: custom:frigate-card
cameras:
  - live_provider: webrtc-card
    webrtc_card:
      url: rtsp://192.168.0.22:8554/frontdoor
    frigate:
      camera_name: frontdoor
    camera_entity: camera.frontdoor
view:
  default: live
  camera_select: live
  dark_mode: 'off'
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '4:3'
live:
  preload: true
  draggable: false
  controls:
    next_previous:
      style: none
    title:
      mode: none
    thumbnails:
      mode: none
  provider: webrtc
  webrtc_card:
    background: true
    mse: false
  show_image_during_load: true
  auto_play: all
  auto_mute: all
  transition_effect: none
  lazy_unload: all
  auto_pause: never
  image:
    refresh_seconds: 1
  auto_unmute: never
frigate:
  camera_name: frontdoor
media_viewer:
  controls:
    title:
      mode: none
    thumbnails:
      mode: none
      show_timeline_control: false
    next_previous:
      style: chevrons
  auto_unmute: all
  transition_effect: slide
  auto_mute: hidden
  draggable: false
event_gallery:
  controls:
    thumbnails:
      show_details: false
      show_favorite_control: true
      show_timeline_control: false
timeline:
  show_recordings: true
  controls:
    thumbnails:
      mode: none
      show_details: true
      show_favorite_control: true
      show_timeline_control: true
menu:
  buttons:
    frigate:
      enabled: false
    live:
      enabled: true
    clips:
      enabled: true
    snapshots:
      enabled: false
    download:
      enabled: true
    frigate_ui:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    image:
      enabled: false
  style: overlay
  position: right
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - live
    elements:
      - type: custom:frigate-card-menu-submenu
        priority: 0
        icon: mdi:package-variant
        items:
          - title: Package at Door
            icon: mdi:door
            tap_action:
              action: call-service
              service: shell_command.doorbelltts
              data: {}
              target: {}
          - title: Package in Bin
            icon: mdi:trash-can-outline
            service: shell_command.doorbellttsrecycling
            tap_action:
              action: call-service
              service: shell_command.doorbellttsrecycling
              data: {}
              target: {}
image:
  mode: camera
  refresh_seconds: 1
  layout:
    fit: fill
```
