### ISSUE TITLE
Support request: Using browser_mod to make the card fullscreen?

### ISSUE THREAD

**Issue by hawkeye217** [dermotduffy/frigate-hass-card#890]
I have a wall-mounted tablet that displays a dashboard containing a Frigate card and some additional elements. I'm currently using an automation employing [browser_mod.popup](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modpopup) with its fullscreen mode to bring up another Frigate card showing me the birdseye view when a person is detected.

Something like this:

```
service: browser_mod.popup
data:
  content:
    type: custom:frigate-card
    cameras:
      - camera_entity: camera.frontcam
        live_provider: frigate-jsmpeg
        frigate:
          camera_name: birdseye
  size: fullscreen
  browser_id:
    - wall_tablet_browser
```

This is working, but there's a small delay because it's loading a second Frigate card in the popup in addition to the one displaying on the dashboard.

Is there a programmatic way I can toggle Frigate card's fullscreen mode? That would be better than loading an entirely new card in a popup.

I noted from the docs that a ``custom:frigate-card-action`` can be set up, but I haven't found a way to call an action with browser_mod in an automation. Can something be done with the conditionals feature?

Thanks in advance for any advice you can give!

**Comment by hawkeye217** [comment]
Looking at conditionals, maybe I don't need browser_mod? Can I do something like this?

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.frontcam
    live_provider: frigate-jsmpeg
    frigate:
      camera_name: birdseye
elements:
  - type: custom:frigate-card-conditional
    conditions:
      view:
        - fullscreen
      state:
        - entity: binary_sensor.frontcam_person_occupancy
          state: 'on'
```

Maybe I'm misunderstanding...
