### ISSUE TITLE
PTZ for tapo cameras do not work in custom:frigate-card-ptz

### ISSUE THREAD

**Issue by Nafania** [dermotduffy/frigate-hass-card#892]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
4.0.0

**Last working release (if known):**
none

**Browser and Operating System:**
Chrome, mac os

**Description of problem:**
Can't figure out how to properly configure PTZ in custom:frigate-card-ptz with tapo cameras provided by foloowing integration https://github.com/JurajNyiri/HomeAssistant-Tapo-Control . It have entities for control PTZ like `button.tapo_camera_e772_move_left` or `button.tapo_camera_e772_move_right` and so on.

Here is my configuration for card

```
- type: custom:frigate-card-conditional
        conditions:
          mediaLoaded: true
          view:
            - live
            - image
        elements:
          - type: custom:frigate-card-ptz
            orientation: horizontal
            style:
              transform: none
              right: 1%
              bottom: 20%
            actions_left:
              action: call-service
              service: button.tapo_camera_e772_move_left
            actions_right:
              action: call-service
              service: button.tapo_camera_e772_move_right
            actions_up:
              action: call-service
              service: button.tapo_camera_e772_move_up
            actions_down:
              action: call-service
              service: button.tapo_camera_e772_move_down
```

But when i click on PTZ buttons on card just nothing happens.

What im doing wrong?

**Comment by dermotduffy** [comment]
I obviously have no way of testing this, but give this a shot:

```
- type: custom:frigate-card-conditional
        conditions:
          mediaLoaded: true
          view:
            - live
            - image
        elements:
          - type: custom:frigate-card-ptz
            orientation: horizontal
            style:
              transform: none
              right: 1%
              bottom: 20%
            actions_left:
              action: call-service
              service: button.press
              service_data:
                entity_id: button.tapo_camera_e772_move_left
            actions_right:
              action: call-service
              service: button.press
              service_data:
                entity_id: button.tapo_camera_e772_move_right
            actions_up:
              action: call-service
              service: button.press
              service_data:
                entity_id: button.tapo_camera_e772_move_up
            actions_down:
              action: call-service
              service: button.press
              service_data:
                entity_id: button.tapo_camera_e772_move_down
```
