### ISSUE TITLE
Low-res (substream) live-view with frigate configured as rtmp proxy 

### ISSUE THREAD

**Issue by arigit** [dermotduffy/frigate-hass-card#893]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
v4.0

**Last working release (if known):**
none

**Browser and Operating System:**
Firefox in linux & macos & android, same behavior observed in chrome and edge

**Description of problem:**
I have frigate configured to use a doorbell substream to do detection, and the full-hd stream as rtmp proxy, like so,

```
cameras:
  doorbell: 
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://@192.168.1.x:554/Streaming/Channels/102  #102 is the subsstream; 101 HD stream
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - '1'
        - path: rtsp://192.168.1.x:554/Streaming/Channels/101
          roles:
            - rtmp
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - '1'
           
```

In lovelace, I used to use this:

```
       - type: picture-glance   
           camera_image: camera.doorbell  #camera.doorbell_mainstream
           camera_view: live
           title: Doorbell
```

Picture-glance + frigate had reasonably low latency (much lower than HA's) and upon loading the dashboard, first the low-res (substream) version is shown, and then after a few seconds, the high-res stream "kicks-in" seamlessly. 

With frigate-card, I have:

```
        - type: custom:frigate-card
          cameras:
            - camera_entity: camera.doorbell
              live_provider: frigate-jsmpeg
              frigate:
                url: http://192.168.1.x:5000
                client_id: frigate
                camera_name: doorbell
                label: person
          view:
            default: live
          live:
            controls:
              thumbnails:
                mode: right
                media: snapshots
                show_details: false
```

but the behavior is different: the dashboard loads in "low-res" (substream) but it would never pick up the high-res stream like picture-glances would do.

I have tried using "live_provider: ha" but the lag is huge, double the lag I see with picture-glance pointed to the "frigate camera" as above. (8 seconds vs. 3 seconds). "live_provider: frigate-jsmpeg" gives the same lag as picture-glance (3 seconds) but it gets stuck on low resolution mode

I am not sure if this is a misconfiguration, a bug or a missing feature, but I really like the ability of picture-glance to seamlessly go from low-res to high-res after a few seconds, can frigate-card support the same?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
