### ISSUE TITLE
Unable to return to static view

### ISSUE THREAD

**Issue by avvalex** [dermotduffy/frigate-hass-card#903]
Hi, i am new to Frigate, and I'm trying to set up my first cam (after that I will go on with others).
If i start watching the live stream in card there is no way to return to static view. I can pause, even automatically, but i can't find the way to return to static view.
Thanks

**Comment by avvalex** [comment]
I have seen that...
The Frigate menu button: brings the user to the default configured view (view.default), or collapses/expands the menu if the menu.style is hidden .

So, since I am in menu style hidden, Frigate button only expands/collapses menu: how can I return to default view (if, for example, i am in live view mode)?
Thanks

**Comment by dermotduffy** [comment]
You should be able to already do this by adding a custom menu icon to the card that calls the default view:

```yaml
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:test-tube
    title: Default view
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: default
```
