### ISSUE TITLE
Wallpanel Full screen and fitting

### ISSUE THREAD

**Issue by Morphy99** [dermotduffy/frigate-hass-card#909]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
v3.0
**Last working release (if known):**

**Browser and Operating System:**
Silk v106.5.14.5249.208.40
Android 9 AEOHY Build

**Description of problem:**

I'm trying to get an Echo Show 15 to display a Frigate live stream with the "panel view" so it fills the screen. I'm using the Silk browser to display HA as I had constant issues with android webview based browsers ([see here](https://github.com/dermotduffy/frigate-hass-card/issues/902)) not loading the stream. With Silk things are better, however, I'm struggling to get the stream to fit the screen wthout having to scroll. I'm also trying to use the [WallPanel ](https://github.com/j-a-n/lovelace-wallpanel) to hide the elements and put it into full screen. Unfortunately, having event thumbnails below the media seems to result in them overlapping the stream with this full screen view which isn't great. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
This is the card yaml:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front
    live_provider: ha
  - camera_entity: camera.front_door
    live_provider: ha
  - camera_entity: camera.back_garden
    live_provider: ha
  - camera_entity: camera.back_patio
    live_provider: ha
view:
  default: live
  update_force: true
  scan:
    enabled: true
menu:
  buttons:
    frigate_ui:
      enabled: false
live:
  controls:
    thumbnails:
      mode: below
      media: clips
      show_timeline_control: false
    title:
      duration_seconds: 10
```

**Comment by dermotduffy** [comment]
Any chance you can attach a screenshot of what you are seeing, and perhaps a description of what you expect it to look like instead?

**Comment by Morphy99** [comment]
Hi Dermot, yes I'll try and work out how to get a screenshot taken and off it to here. It's almost as bad as using an iPhone... But it looks good on the wall huh 🙂

**Comment by Morphy99** [comment]
So I got some photos as screenshots aren't possible on the echo shows apparently. The issue I was having is getting the video to fit whilst displaying the events underneath. This what I got which fitted fine: 
![normal](https://user-images.githubusercontent.com/5853979/209856569-5e68546e-574d-42c5-b2b2-c99e33a951b4.jpg)
I thought it was great until the browser went full screen:
![fullscreen](https://user-images.githubusercontent.com/5853979/209856861-86900814-c282-4764-aeee-3909b9984c22.jpg)
As you can see the thumbnail carousel overlaps part of the bottom image. This seems to happen no matter what View type I choose, with "Panel" card and I've also tried with the [custom layout](https://github.com/thomasloven/lovelace-layout-card) card.

This is my config:
```
views:
  - theme: Backend-selected
    visible:
      - user: x
      - user: x
    title: home
    type: custom:horizontal-layout
    layout:
      width: 1000
    badges: []
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.front
            live_provider: ha
          - camera_entity: camera.front_door
            live_provider: ha
          - camera_entity: camera.back_garden
            live_provider: ha
          - camera_entity: camera.back_patio
            live_provider: ha
        view:
          default: live
          update_force: true
          scan:
            enabled: true
        menu:
          buttons:
            frigate_ui:
              enabled: false
        live:
          controls:
            thumbnails:
              mode: below
              media: clips
              show_timeline_control: false
            title:
              duration_seconds: 10
          layout:
            fit: contain
          jsmpeg:
            options:
              disableGl: true
        dimensions:
          aspect_ratio_mode: static
          aspect_ratio: '16:9'
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 0
```


I'm not sure if this is an issue with my config or if it's a bug that's fixable. To be honest, I'm not even sure I want to use HA to view the streams anymore as I'm getting lots of the "Error with media stream contents" errors when browsing clips or loading other streams. I only want it for viewing surveillance and it's just not up to it with browsers and HA from what I can tell. I'm kind of leaning towards using Kodi on it now as it plays the streams perfectly. If I had a way of getting the clips info into Kodi with kiosk'd skin it would be perfect as I could use HA to switch streams with some automations.

I'd use the frigate interface if it had better live video but the 5fps limit and no audio makes it a non starter. Also there's no customising of the interface to make things bigger.
