### ISSUE TITLE
Share camera entity as is for WebRTC card and Frigate v0.12

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#915]
The title is self-explanatory, but the thing is, if using Frigate v0.12, the camera entity configured for the card can be shared/used to configure the WebRTC card as is. There is no need to configure an extra camera entity or an RTSP URL just for the WebRTC card.

**Comment by felipecrs** [comment]
Actually, I realized that sharing the camera entity doesn't work. It says "could not find URL" or something like that. What works though, with WebRTC card 3.0, is to share the Frigate camera name as URL. Like:

```yaml
    cameras:
      - camera_entity: camera.video_porteiro
        live_provider: webrtc-card
        webrtc_card:
          url: video_porteiro
      - camera_entity: camera.rua
        live_provider: webrtc-card
        webrtc_card:
          url: rua
      - camera_entity: camera.morro
        live_provider: webrtc-card
        webrtc_card:
          url: morro
      - camera_entity: camera.portao
        live_provider: webrtc-card
        webrtc_card:
          url: portao
```

Which works normally, as long as the WebRTC integration is connected to the go2rtc which is running inside of the Frigate container/add-on.
