### ISSUE TITLE
Activating fullscreen via binary_sensor

### ISSUE THREAD

**Issue by Marfinho** [dermotduffy/frigate-hass-card#918]
**Is your feature request related to a problem? Please describe.**
I use Unifi Protect video streams with this awesome card. One of them is the doorbell. And I'd like to use the binary_sensor of the chime to automatically go to fullscreen with that stream for time x.

**Describe the solution you'd like**
As I´m not completely into the coding behind the card I'm not in the position to describe it in depth. Maybe something to react on binary_sensor? And a time how long Fullscreen should be stay enabled? :) 

**Describe alternatives you've considered**
Digged through a lot of googled stuff but didn't find a suitable solution. If there is already something, please show me :)

**Additional context**

**Comment by dermotduffy** [comment]
The issue with this is that browsers protect the user from random websites activating fullscreen mode. See my [answer here](https://github.com/dermotduffy/frigate-hass-card/issues/237) -- the browser literally will not allow what this issue is asking for. This makes sense -- otherwise random websites could plunge their user into fullscreen Ad experiences ;-)

There may be ways around this involving opening new windows, or changing to subviews in HA -- but the request as written is essentially not feasible AFAIK :-(

**Comment by Marfinho** [comment]
With browser_mod its an ease so far. Or don't go real Fullscreen, just 100% screen width? In a Popup? 

Sorry for not being more helpful, I just try to give my best :D

**Comment by dermotduffy** [comment]
Yeah some trick like 100% width could work, but that's pretty much what subviews do (i.e. the card itself cannot change the space it is given, Home Assistant frontend controls that).

I'm not sure what browser_mod is doing -- does it let you activate fullscreen?

**Comment by felipecrs** [comment]
Maybe it does by using the Fully Kiosk APIs?

**Comment by Marfinho** [comment]
No, Fully Kiosk is not involved.
https://github.com/thomasloven/hass-browser_mod

Maybe I can work from this Integration and just use your Card inside of a Popup. I'll give it a try and let you know.

**Comment by dermotduffy** [comment]
SG @Marfinho . This is a commonly requested feature, so I'd love to feature an FAQ entry if you find a workable way to get this to kind of work.

**Comment by conorlap** [comment]
I've got this working using browser_mod yeah! I setup an automation to trigger the popup when someone is detected or the doorbell is pressed.

**Here's the automation yaml:**

```
alias: >-
  Doorbell Pressed OR Human Detected - Firefox browser full screen video feed
  for 20 seconds
description: ""
trigger:
  - platform: state
    from: "off"
    to: "on"
    entity_id:
      - binary_sensor.frontdoor_person_occupancy
  - platform: state
    entity_id:
      - binary_sensor.front_door_dahua_button_pressed
    to: "on"
condition: []
action:
  - service: browser_mod.popup
    data:
      size: wide
      timeout: 15000
      content:
        type: custom:frigate-card
        aspect_ratio: 55%
        cameras:
          - camera_entity: camera.frontdoor
            live_provider: ha
        menu:
          style: none
        live:
          controls:
            title:
              mode: none
    target:
      device_id:
        - d0e93101edfg44y3yt35y5y45y54y
mode: single


```




I also added my own "fullscreen" button to my frigate-hass-card with the following, it's really useful for a super quick "fullscreen" view:
```
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:fullscreen
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          size: wide
          content:
            type: custom:frigate-card
            aspect_ratio: 55%
            cameras:
              - camera_entity: camera.frontdoor
                live_provider: ha
            menu:
              style: none
            live:
              draggable: false
              controls:
                title:
                  mode: none
```

**Comment by felipecrs** [comment]
Wow, that looks great!

**Comment by dermotduffy** [comment]
Thank you @conorlap for the great example. I've added that to the documentation for now until we come up with a better idea ...

@felipecrs This is related to what I think you're suggesting, using the query parameters to take action: https://github.com/dermotduffy/frigate-hass-card/issues/929 (we still need something to get the browser to open that URL though). If you want to guide the implementation for that feature, chip in on that issue!

**Comment by felipecrs** [comment]
Well, the only idea I have is to use [Fully Kiosk](https://www.home-assistant.io/integrations/fully_kiosk/) with its `fully_kiosk.load_url` service. Something like:

```
service: fully_kiosk.load_url
data:
  url: https://<ha>/lovelace/default_view?myparam=whatever
target:
  device_id: b5005de440d90c862538e61299d8d9f1

```
