### ISSUE TITLE
Frigate camera name autodetection doesn't work for JSMPEG

### ISSUE THREAD

**Issue by alexdelprete** [dermotduffy/frigate-hass-card#92]
Hi, first of all great work on this card, it has all that's needed to display frigate cameras and even more. :)

I had a series of issues configuring it, I worked around most of them but probably I'm missing something, here the macro steps I followed:

1. I didn't have the WebRTC component, I just wanted to display the live view of frigate but it didn't work, I was only seeing a grey rectangle.
2. I installed WebRTC and I configured the camera throught the GUI, selecting the camera.citofono entity, I had an error displayed on the video "RTSP only stream supported" (something like that), but the camera (a doorbell) is RTSP.
3. I read in the doc that I could also use a RTSP URL, but in the GUI I couldn't find it, there was only the listbox with the entity selector:
![image](https://user-images.githubusercontent.com/7027842/135302864-76ac173a-91c2-422f-8f11-1b5e2f2692c4.png)
4. I switched to YAML and replaced the entity: with url: and the RTSP path, then I finally saw the video appearing. :)
5. I wanted to try `frigate-jsmpeg` but in the GUI selector (see above) it didn't appear. I'm using integration 2.1.
![image](https://user-images.githubusercontent.com/7027842/135303187-585f746d-1945-4add-b811-91131c56b62f.png)

So to summarize the issues:

1. live view provider set with frigate doesn't work (grey box)
2. can't find frigate-jsmpeg in live view provider listbox, even if using integration 2.1
3. in webrtc (used as workaround) if I use the entity camera.citofono (created by frigate) webrtc complains about it not being an RTSP stream. Using the RTSP url as workaround means I'm opening a second stream from the camera. I'd prefer to use Frigate as proxy.
4. in webrtc options GUI, you can't set the rtsp url, as described in the documentation, only selection of entity is possible

This is the current config:

```
  - type: custom:frigate-card
    controls: {}
    menu_mode: overlay-bottom
    webrtc:
      url: rtsp://user:XXXXXX@citofono.axel.dom:554/Streaming/Channels/101
      webrtc: true
      mse: false
    autoplay_clip: false
    menu_buttons:
      frigate: false
      clips: true
      live: true
      snapshots: true
      frigate_ui: false
    camera_entity: camera.citofono
    frigate_url: http://hass.axel.dom:5000
    view_default: live
    live_provider: webrtc
```

I think that's everything, if I missed something I'll integrate the post. :)

Thanks again for your great work and the support.

Alessandro
