### ISSUE TITLE
Allow configurable gallery chunk/load size

### ISSUE THREAD

**Issue by tsaG1337** [dermotduffy/frigate-hass-card#921]
I have a Fire Tablet HD10 and it only displays around 15 Events in the Event gallery due to size In addition, it takes a few seconds to load. It would be great to be able to limit the amount of Events that are shown in the Event Gallery. That way, I would limit it to 20 instead of the default 150.

**Comment by Mincka** [comment]
I've also a similar request. I use the following configuration on mobile to display a list of the latest events.
I would like to limit the number of retrieved events in the snapshots view.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.frigate_maison_avant
    frigate:
      label: person
      zone: jardin_avant
    dependencies:
      all_cameras: true
  - camera_entity: camera.frigate_jardin_arriere
  - camera_entity: camera.frigate_jardin_avant
view:
  default: snapshots
event_gallery:
  controls:
    thumbnails:
      show_favorite_control: false
      show_details: true
      show_timeline_control: false
media_viewer:
  controls:
    thumbnails:
      show_details: true
      show_favorite_control: true
      show_timeline_control: true
dimensions:
  aspect_ratio_mode: unconstrained
```

**Comment by dermotduffy** [comment]
Will be in the next build, e.g.

```yaml
performance:
  features:
    media_chunk_size: 10
```
