### ISSUE TITLE
Allow selecting a particular camera from the dashboard query string

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#929]
As suggested by @NickM-27 .

**Comment by dermotduffy** [comment]
[Moving this idea from the other issue]

Well, the only idea I have is to use [Fully Kiosk](https://www.home-assistant.io/integrations/fully_kiosk/) with its `fully_kiosk.load_url` service. Something like:

```yaml
service: fully_kiosk.load_url
data:
  url: https://<ha>/lovelace/default_view?myparam=whatever
target:
  device_id: b5005de440d90c862538e61299d8d9f1

```

_Originally posted by @felipecrs in https://github.com/dermotduffy/frigate-hass-card/issues/918#issuecomment-1446270470_
