### ISSUE TITLE
Card height not matching camera aspect ratio

### ISSUE THREAD

**Issue by baldisos** [dermotduffy/frigate-hass-card#93]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.0.1

**Browser and Operating System:**
Windows/Linux/Android
Firefox/Chromium

**Description of problem:**

My camera has a 4:3 format, the card seems to use 16:9 by standard. This way i'm missing a bit on the lower part of the image, and the actual camera image inside the card is scrollable. I've tried with the aspect_ratio parameters, but that doesn't change anything.

The config used:

```
type: custom:frigate-card
controls:
  nextprev: chevrons
menu_buttons:
  clips: false
webrtc:
  entity: camera.hof
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '4:3'
camera_entity: camera.hof
menu_mode: overlay-bottom
live_provider: frigate

```
