### ISSUE TITLE
Virtual states triggered by buttons per camera

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#934]
**Is your feature request related to a problem? Please describe.**
I want to add a button in my menu bar called "HD". When I click this button, I want to replace WebRTC's card URL with another URL (an URL that points to my camera's HD stream).

However, I also want this button to be colored, so I know whether the HD stream is being used or not.

**Describe the solution you'd like**
Some sort of virtual states that button can toggle on/off. This virtual state is not a HASS entity, but rather just a temporary stored state for the current camera view on the card.

**Describe alternatives you've considered**
Currently I'm adding my cameras HD streams as different cameras, but this UX is not good in my opinion.

https://user-images.githubusercontent.com/29582865/218330134-8c240889-b21d-474b-985a-710690a4f4ae.mp4

A button in the menu bar that I can toggle on/off would be so much cleaner and intuitive.

**Additional context**
Any help would be appreciated. :)

**Comment by dermotduffy** [comment]
Hey @felipecrs , I think maybe this is the same as this: https://github.com/dermotduffy/frigate-hass-card/issues/898 . You're proposing something more generic here, but I think perhaps the real need is getting the UX right for "swapping streams", i.e. the ability to configure multiple cameras that are actually the same camera -- and have an easy way to switch between them. Am I right? 

If yes, would you mind pasting some of your config -- at least including an SD and HD version of the same camera -- so I can think about how I'd do that?

**Comment by felipecrs** [comment]
Right, that's what I wanted. Here's my example:

```yaml
- type: custom:frigate-card
  cameras:
    - camera_entity: camera.video_porteiro
      live_provider: webrtc-card
      webrtc_card:
        url: video_porteiro
    - camera_entity: camera.video_porteiro
      live_provider: webrtc-card
      title: Vídeo Porteiro (HD)
      id: video_porteiro_hd
      webrtc_card:
        url: video_porteiro_hd
```

While in frigate/go2rtc config I have:

```yaml
go2rtc:
  streams:
    video_porteiro:
      - "ffmpeg:rtsp://admin:<pass>@192.168.1.40/cam/realmonitor?channel=1&subtype=0#video=copy#audio=opus#audio=aac"
    video_porteiro_hd:
      - "ffmpeg:rtsp://admin:<pass>@192.168.1.40/cam/realmonitor?channel=1&subtype=1#video=copy"
      - rtsp://127.0.0.1:8554/video_porteiro?audio=opus&audio=aac
```

**Comment by dermotduffy** [comment]
What if we did something like this:

```yaml
- type: custom:frigate-card
  cameras:
    - camera_entity: camera.video_porteiro
      live_provider: webrtc-card
      webrtc_card:
        url: video_porteiro
      id: foo // <--------------- Added
    - camera_entity: camera.video_porteiro
      live_provider: webrtc-card
      title: Vídeo Porteiro (HD)
      id: video_porteiro_hd
      substream_of: foo // <------------- Added (not implemented today)
      webrtc_card:
        url: video_porteiro_hd
```

... with these behaviors:
 - Only the first camera would show up in the camera menu.
 - Only the first camera should show up in the live camera carousel.
 - A new button would appear on the menu for substreams. If there is more than a single substream, that button would open a menu of substreams -- otherwise it would just toggle.

Thoughts?

Questions:
 - For media displaying, would we just never show the substream in the media filtering, or would we want to support being able to choose media from one of the substreams? (i.e. it could have different dependency cameras configured, or different zones/labels). I think this could probably end up being fairly confusing, so perhaps substream cameras are just ignored for media (and any dependency configuration is ignored).
 - For triggers (scan mode), would we want to be able to trigger a specific substream, as distinct from its original camera?
