### ISSUE TITLE
Exclude camera from Clips Gallery card

### ISSUE THREAD

**Issue by jbishop129** [dermotduffy/frigate-hass-card#949]
i’m Running the v4.0 beta 4 Frigate Card HACS addon, and I like having a card that defaults to the Clips Gallery view. I can see recent camera events from all cameras, which is super useful. I want to exclude a specific camera from this view, as it has a lot of activity that is relevant in another context, but not in the at-a-glance context here, it just makes the card messy. I thought just not adding that camera to the list of `cameras: ` in the card would do the trick, but not the case; it still loads Clips from all cameras on that Frigate instance. Is there a way to exclude a specific cameras’ Clips/Events from the Clips Gallery view?

**Comment by dermotduffy** [comment]
Would you mind pasting your config? Thanks!

**Comment by dermotduffy** [comment]
@jbishop129 Would you mind including your config? I don't really understand the issue you are having, in the default config, you should only see clips for the camera that is selected, unless you have camera dependencies manually configured. But then removing cameras would be easy ...

**Comment by jbishop129** [comment]
Here’s my card config. Not sure why it only shows events from the first camera entity

``` yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.garden_south
  - camera_entity: camera.driveway_west
  - camera_entity: camera.hillside_dr_east
  - camera_entity: camera.hillside_dr_north
view:
  default: clips
menu:
  buttons:
    frigate:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    frigate_ui:
      enabled: false
    fullscreen:
      enabled: true
    timeline:
      enabled: false
    media_player:
      enabled: false
event_gallery:
  controls:
    thumbnails:
      show_favorite_control: false
      show_timeline_control: false
      show_details: false
media_viewer:
  controls:
    next_previous:
      style: none 
```
