### ISSUE TITLE
Go2rtc live source not always respecting mute settings

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#959]
**Checklist:**

- [✔️] I updated to the latest version available
- [✔️] I cleared the cache of my browser

**Release with the issue:**
Latest manual build of 4.1.1
**Last working release (if known):**
N/A
**Browser and Operating System:**
Edge - macOS

**Description of problem:**
Go2rtc live source is not always respecting the live view option of "Automatically unmute live cameras' - Never". It works fine when I open my HA dashboard on a fresh tab, but once I navigate to other dashboards and then back to the camera dashboard the camera feed is unmuted (same happens when I leave the HA tab and go back to it). A refresh of the page solves the issue. 

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

```
type: custom:frigate-card
cameras:
  - live_provider: go2rtc
    frigate:
      camera_name: frontdoor
    webrtc_card:
      url: rtsp://192.168.0.22:8554/frontdoor?video=all&audio=all
    camera_entity: camera.frontdoor
view:
  default: live
  camera_select: live
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '4:3'
live:
  controls:
    thumbnails:
      mode: none
      media: clips
    title:
      mode: none
    next_previous:
      style: none
    timeline:
      mode: none
  show_image_during_load: true
  lazy_unload: hidden
  draggable: false
  webrtc_card:
    mode: webrtc
    muted: true
  auto_unmute: never
frigate:
  camera_name: frontdoor
media_viewer:
  controls:
    title:
      mode: none
    thumbnails:
      mode: none
      show_timeline_control: false
    next_previous:
      style: chevrons
  auto_unmute: all
  transition_effect: slide
  auto_mute: hidden
  draggable: false
timeline:
  show_recordings: true
  controls:
    thumbnails:
      mode: none
      show_details: true
      show_favorite_control: true
      show_timeline_control: true
media_gallery:
  controls:
    thumbnails:
      show_details: false
      show_favorite_control: true
      show_timeline_control: false
performance:
  features: {}
```
