### ISSUE TITLE
Reinstate global values for cameras

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#979]
As discussed in: https://github.com/dermotduffy/frigate-hass-card/pull/966

Goals:

* Allow the user to specify default values for camera settings so they don't need to be specified in every camera.
* Ideally, allow a way for camera values to be overridden.

@felipecrs suggested something like:

```
cameras_global:
  live_provider: go2rtc
  go2rtc:
    modes:
      - webrtc
```

... but this would require new camera re-initialization code.
