### ISSUE TITLE
Frigate-hass-card live view loading very slow on Android 

### ISSUE THREAD

**Issue by Klaus062** [dermotduffy/frigate-hass-card#980]
I have created a dashboard with a grid of 3 frigate hass cards showing my outdoor cameras. When switching to this dashboard from another one on my linux desktop, the streams load within 1-2 seconds. On my Android tablet it will take **30-40** seconds. 

Out of interest, I have built a similar grid with picture glance cards and there streams load on the Android Tablet as well within 1-2 seconds. 

I have also tried using 'clips' as default view for the frigate-hass-cards. But here again loading takes 1-2 seconds on the linux desktop and 30-40 seconds on the Android tablet. 

The behaviour on the Android device is the same for running the HA app or using a browser ( tried firefox and chrome)

I would be very happy for any idea what the issue could be.

Here is info regarding the setup:
- Android tablet is a Lenovo P11 with Android 11
- HA is running on i5 NUC
- frigate installed via add on store and added repository 
- frigate hass card installed through HACS
- cameras are defined in go2RTC

Here is the code for the dashboard with frigate hass cards

```
kiosk_mode:
  user_settings:
    - users:
        - panel_user
      kiosk: true
views:
  - title: Video Vorgarten
    theme: backend-selected
    path: null
    icon: mdi:desktop-classic
    type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 6% 47% 47%
      grid-template-rows: 50% 50%
      grid-template-areas: |
        "buttons video1 video2"
        "buttons video3 video4"
      justify-items: stretch
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:button-card
            name: Home
            icon: mdi:home
            color: cyan
            tap_action:
              action: navigate
              navigation_path: /dashboard-tablet
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
        view_layout:
          grid-area: buttons
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.gartentor
        view_layout:
          grid-area: video1
        view:
          default: clips
          timeout_seconds: 60
        menu:
          style: overlay
          buttons:
            cameras:
              enabled: false
            clips:
              enabled: true
            snapshots:
              enabled: false
        live:
          draggable: false
          auto_mute: all
          auto_unmute: never
          controls:
            next_previous:
              style: none
            thumbnails:
              mode: left
              media: clips
            title:
              mode: popup-top-right
          layout:
            fit: contain
        timeline:
          window_seconds: 21600
          media: clips
          controls:
            thumbnails:
              mode: below
        dimensions:
          aspect_ratio_mode: static
          aspect_ratio: '16:9'
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.eingang
        view_layout:
          grid-area: video2
        view:
          default: clips
          timeout_seconds: 60
        menu:
          style: overlay
          buttons:
            cameras:
              enabled: false
            clips:
              enabled: true
            snapshots:
              enabled: false
        live:
          draggable: false
          auto_mute: all
          auto_unmute: never
          controls:
            next_previous:
              style: none
            thumbnails:
              mode: left
              media: clips
            title:
              mode: popup-top-right
          layout:
            fit: contain
        timeline:
          window_seconds: 21600
          media: clips
          controls:
            thumbnails:
              mode: below
        dimensions:
          aspect_ratio_mode: static
          aspect_ratio: '16:9'
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.einfahrt
        view_layout:
          grid-area: video3
        view:
          default: clips
          timeout_seconds: 60
        menu:
          style: overlay
          buttons:
            cameras:
              enabled: false
            clips:
              enabled: true
            snapshots:
              enabled: false
        live:
          draggable: false
          auto_mute: all
          auto_unmute: never
          controls:
            next_previous:
              style: none
            thumbnails:
              mode: left
              media: clips
            title:
              mode: popup-top-right
          layout:
            fit: contain
        timeline:
          window_seconds: 21600
          media: clips
          controls:
            thumbnails:
              mode: below
        dimensions:
          aspect_ratio_mode: static
          aspect_ratio: '16:9'

```

Just in case, same thing with picture glance cards

```
kiosk_mode:
  user_settings:
    - users:
        - panel_user
      kiosk: true
views:
  - title: Video Vorgarten
    theme: backend-selected
    path: null
    icon: mdi:desktop-classic
    type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 6% 47% 47%
      grid-template-rows: 50% 50%
      grid-template-areas: |
        "buttons video1 video2"
        "buttons video3 video4"
      justify-items: stretch
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:button-card
            name: Home
            icon: mdi:home
            color: cyan
            tap_action:
              action: navigate
              navigation_path: /dashboard-tablet
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
          - type: custom:button-card
        view_layout:
          grid-area: buttons
      - camera_view: live
        type: picture-glance
        view_layout:
          grid-area: video1
        entities: []
        camera_image: camera.gartentor
        aspect_ratio: '16:9'
        tap_action:
          action: none
        hold_action:
          action: none
      - camera_view: live
        type: picture-glance
        entities: []
        view_layout:
          grid-area: video2
        camera_image: camera.einfahrt
        aspect_ratio: '16:9'
        tap_action:
          action: none
        hold_action:
          action: none
      - camera_view: live
        type: picture-glance
        view_layout:
          grid-area: video3
        entities: []
        camera_image: camera.eingang
        aspect_ratio: '16:9'
        tap_action:
          action: none
        hold_action:
          action: none

```
Thanks a lot for your help
Klaus
